### PR TITLE
Backport "Fix conda instructions for dev env setup" to v0.20.x

### PR DESCRIPTION
**Pull request by lagru**
## Description

Backports #6781, #6792 and #6806 to v0.20.x.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by mkcor** [comment]
I just noticed that, on current main, `# Install main development and runtime dependencies` is line 337, whereas here it's line 330. I think that, instead of this manual porting (?), we might as well replace v0.20.x's `INSTALL.rst` with main's.

**Comment by lagru** [comment]
I think that difference is largely du to #6770. Would it be safe to include that one as well or would we leave some other context and changes predating #6770 behind?

**Comment by mkcor** [comment]
> I think that difference is largely du to #6770. Would it be safe to include that one as well or would we leave some other context and changes predating #6770 behind?

Ah, ok. It would be safe to include it in the sense that there is no loss of information in #6770 (only fixes to outdated info, moving around of 'constant' info, and merging of duplicate info).

**Comment by lagru** [comment]
@mkcor, FYI: in our last community meeting ([notes](https://github.com/scikit-image/meeting-notes/blob/0fdcc645347deb1ba3980e0ec8092f34a39718d8/2023/2023-03-14_europe_africa_cc.md)) @jarrodmillman suggested to focus a bit more on more frequent releases which would make backports less important. The hope is to avoid the amount of busy work for bug fix releases. 

Of course we can still do them if we really want to be fast about an update. I kind of feel like this qualifies though it's a bit less critical now that Outreachy's application phase has already started.

**Comment by mkcor** [comment]
Hi @lagru,

Thanks for sharing. Btw, I'm really glad to see that an Outreachy applicant participated in the community meeting! :smiley: 

> it's a bit less critical now that Outreachy's application phase has already started

I agree with you and I'm happy to (let you) close this PR. Although I'm not a release expert, I think that backporting shouldn't be done lightly (on a whim). So, unless it *is* critical, let's not do it.

**Pull request closed without merging**
