### PR TITLE
Replace np.bool, np.int, np.float with np.bool_, np.int_, np.float_

### PR DESCRIPTION
**Pull request by jni**
## Description

This should fix CI failures with numpy 1.20rc

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
@scikit-image/core This is ready for review! I don't think I've ever seen so much green! 😍 💚 💚 💚

**Review by alexdesiqueira — APPROVED** [review]
Huge work @jni, looks great :) Thank you!

**Comment by jni** [comment]
Since [some people on the NumPy core team](https://github.com/stefanv) are not aware that NumPy deprecated `np.{bool,float,int}`, here's a link to one of the CI failures + warning soups that motivated this PR. 😂 

https://github.com/scikit-image/scikit-image/runs/1497565948

**Comment by hmaarrfk** [comment]
Did you use a regexp for this?

**Comment by jni** [comment]
@hmaarrfk VSCode global find and replace. I followed each with replacing e.g. `np.bool__` with `np.bool_`, which took care of the existing `np.bool_`s.

**Comment by jni** [comment]
@stefanv informs me that `dtype=float` is perfectly acceptable. Nevertheless, the Python typing fan in me prefers `np.float_` because that is, in fact, a dtype.

**Comment by jni** [comment]
Update: @stefanv's position is actually stronger: he things `dtype=np.{bool,int,float}_` is an antipattern, and we should use `dtype={bool,int,float}`. He has asked @seberg, who is leading NumPy's dtype extension efforts, to confirm this. I'll update the PR accordingly.

**Comment by hmaarrfk** [comment]
I just admit the release notes were not very clear about which one people should use

**Comment by jni** [comment]
Looking green again, finally.

**Comment by emmanuelle** [comment]
Thanks @jni! Merging.

**Comment by seberg** [comment]
Thanks for updating quickly :). Just in case it seems like it.  While I *like* this deprecation (and think cleaning it up in `skimage` is good), it is not actually important for dtypes.
This is just the first release were we can deprecate these confusing names, so if this is creating too much noise downstream or for end-users, I am happy to pull it out.

**Comment by hmaarrfk** [comment]
I have to say, i got into the habbit of doing `np.int` in my own projects, and i'm kinda troubled by the need to go and undo all of this.

Not really sure what the goal is, but yeah, it will be pretty painful to change everybody's habbits.

Is the goal to stop people from doing `from numpy import *`, if so, something should catch that and warn against that.

**Comment by seberg** [comment]
@hmaarrfk the use is OK for `dtype=np.int`, what is a bit troubling is the expectation to get a NumPy scalar for `np.int(1)`. I do think we had issues on this, but while it seems clear that we don't want users to write `np.int`, I am not sure that this particular change is a good use of our "annoy the user base" chip allocation :).

Maybe bring it up on the mailing list?

**Comment by stefanv** [comment]
@jni Interesting side-effect of seach-and-replace :)

```
    if (input_dtype in (bool, bool) or out_dtype in (bool, bool)):
```

**Comment by jni** [comment]
@meeseeksdev backport to v0.18.x

**Comment by jni** [comment]
@seberg well it was very surprising to me when I found out that `np.float is float`. For the longest time I thought that `np.float` was equivalent to "whatever the default float value is on my platform", and considered it best practice to use that instead of plain `float`. 😅 I think that is a common misconception. In my ideal world `np.int` would become `np.int_` and so on. That would use up even more downstream annoyance credits but would get us to a nice place.

**Comment by jni** [comment]
@stefanv that is perfectly cromulent code. =P

**Comment by jni** [comment]
Started a thread on the NumPy mailing list as suggested by @seberg

**Comment by emmanuelle** [comment]
Argh I had overseen that the minimal requirements jobs fail on GHA. @jni is this known / taken care of in another PR?

**Comment by emmanuelle** [comment]
See #5109 for the CI failure.

**Pull request merged**
