### PR TITLE
Simplify benchmarks pinnings

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
Things shouldn't be pinned so hard in the benchmarks. Lets following new software!

cc: @TomAugspurger could this cause any troubles?

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I don't think it's cause any problems.

**Comment by jni** [comment]
My concern is that it will make it harder to detect when a performance regression or improvement is caused by an upstream package change. Could we have one configuration pinned (to current package versions), and one cutting edge? That would make me happy. (Conversely, it'll allow us to *detect* when a regression is due to updates to packages.)

Having said all this, the two major "regressions" we've spotted have been hard/impossible to reproduce on local machines, so I don't know what to think anymore... =\

**Comment by hmaarrfk** [comment]
Yeah I agree

**Comment by hmaarrfk** [comment]
I would just unpin everything and let this "maintain itself". The burden of maintaining version numbers is a pain.

**Comment by hmaarrfk** [comment]
@jni did you want to review this again? I mostly removed the giant comments that we never configured and pointed to the docs, (with the exception to the one thing we aren't supposed to touch).

**Pull request merged**
