### PR TITLE
added ridge-directed-ring-detector + demo notebook

### PR DESCRIPTION
**Pull request by eldad-a**
an implementation of the algorithm in
Sci. Rep. 5, 13584; doi: 10.1038/srep13584 (2015).

EA
 On branch ridge-directed-ring-detector
 Changes to be committed:
    new file:   ridge-directed-ring-detector/demo.ipynb
    new file:   ridge-directed-ring-detector/ridge_directed_ring_detector.pyx

### CODE REVIEW

**Comment by eldad-a** [comment]
This is my first PR -- guess it would need some work -- looking forward to your suggestions.
Cheers, 
Eldad

**Comment by tacaswell** [comment]
If this does not fit into skimage's scope, I think this would fit in https://github.com/soft-matter/trackpy

**Comment by stefanv** [comment]
I encouraged Eldad to make this pull request, after reviewing his paper.  Having looked at several algorithms in the field, I am convinced that this extremely useful.

We'll need to do some work to get this into shape.  Add examples to the gallery, clean up the code, add correct Python wrappers & documentation, etc.  But I think it is well worth the effort!

Thomas, thank you for expressing interest.  Your input would be much appreciated!

**Comment by tacaswell** [comment]
@stefanv Ah, great, sorry for causing trouble. I agree it is useful and want to make sure this code has a home!

**Comment by stefanv** [comment]
@tacaswell Not at all; we are just too happy to have you involved.

**Comment by eldad-a** [comment]
@tacaswell 
@stefanv 

Thank you both for your words of support!
It would be great if this algorithm will be useful for others.

**Comment by stefanv** [comment]
OK, I had a first look.  We need to do a few things here:

- Use the scikit-image build system to build the Cython files (I've sent you a pull request)
- Format the code according to Python PEP8
- Convert the notebook into an example for the gallery
- Add tests
- Remove cv2 and use scikit-image equivalent functions instead

What do you think, Eldad?

**Comment by sciunto** [comment]
@eldad-a What's the status of this PR?

**Comment by alexandrejaguar** [comment]
Hi @eldad-a, we are interested in adding this code to the next major version.
We could add it after answering what Stéfan pointed before.
Do you need any help on that? Thanks!

**Comment by sciunto** [comment]
It's likely that @eldad-a doesn't want to work on this anymore after such a long time. Very interesting feature, but there is quite a lot of work to integrate it in scikit-image. In particular, to reuse build-in fonctions to fit and perform hough transforms.

**Comment by stefanv** [comment]
I spoke to @alexandrejaguar about this, and encouraged him to investigate the contribution.  The work @eldad-a did was of high quality, and I reviewed his manuscript that appeared in Nature Methods.  This is a method that adds unique functionality that does not currently exist in any other library, but the method is well thought through.  I think we would greatly benefit from having it, and so it is worth some extra effort.

@eldad-a may or may not have time to work on this right now, but he has been responsive in the past (he and I have had long email exchanges about the work).

**Comment by eldad-a** [comment]
@alexandrejaguar Thanks for following up and for the interest!
What is the timeline for the next major revision?
I'm happy to contribute and work on the revisions; at the same time, lacking previous experience in collaborative coding, yes, I will need help.

@stefanv Thank you again for the kind words and support!

BTW, Nature Methods requires "_tried-and-tested basic research techniques in the life sciences_", which was beyond the scope of the work at the time (that is, to try and test the technique in a biological research example).

The manuscript can be found at

E. Afik, [Robust and highly performant ring detection algorithm for 3d particle tracking using 2d microscope imaging](http://www.nature.com/articles/srep13584). Sci. Rep. 5, 13584; doi: 10.1038/srep13584 (2015)

**Comment by stefanv** [comment]
Apologies: I mixed up Scientific Reports and Nature Methods—but the effect is the same.

**Comment by stefanv** [comment]
@eldad-a Is this version in sync with the latest in your repo at https://github.com/eldad-a/ridge-directed-ring-detector?

**Comment by eldad-a** [comment]
> Apologies: I mixed up Scientific Reports and Nature Methods—but the effect is the same.

No need to apologize, of course :-)

**Comment by eldad-a** [comment]
> @eldad-a Is this version in sync with the latest in your repo at https://github.com/eldad-a/ridge-directed-ring-detector?

@stefanv Does _this version_ refers to the one in my first PR?
It is almost the same. There are two minor corrections in the code, and some revisions in the Readme.

**Comment by stefanv** [comment]
@eldad-a To make sure I understand correctly: we need to grab those two changes from your ridge-directed-ring-detector repository?

Thanks for chiming in on this; I'm so excited that we're getting the wheels rolling on this awesome feature again.

**Comment by eldad-a** [comment]
@stefanv Yes, I think it is better that the version we'll be working on will the most recent one (it introduces no conceptual changes).

Thanks again for the continuous interest and support, I greatly appreciate it!

**Comment by alexandrejaguar** [comment]
@eldad-a thanks for helping! Could you push these improvements to this pull request?

> Use the scikit-image build system to build the Cython files (I've sent you a pull request)

I think we could start adding the pull request @stefanv sent you before. How's that?

**Comment by stefanv** [comment]
On Thu, 23 May 2019 11:30:37 -0700, Alexandre de Siqueira wrote:
> @eldad-a thanks for helping! Could you push these improvements to this pull request?
> 
> > Use the scikit-image build system to build the Cython files (I've sent you a pull request)
> 
> I think we could start adding the pull request @stefanv sent you before. How's that?

Alex, if Eldad doesn't mind, I think we should just work on his branch and
push the changes up.  This would be the fastest way to move forward.

**Comment by eldad-a** [comment]
> @eldad-a thanks for helping! Could you push these improvements to this pull request?
> 
> > Use the scikit-image build system to build the Cython files (I've sent you a pull request)
> 
> I think we could start adding the pull request @stefanv sent you before. How's that?

@alexandrejaguar I believe this step is done.

**Comment by alexandrejaguar** [comment]
Hey @eldad-a, thank you for your help!

> Could you please direct me what's the best way to do so?

This was solved when you pushed @stefanv PR already, thanks for doing that.

> Additionally, should I update my fork to the current scikit-image one?

This could be good: please use `git pull origin ridge-directed-ring-detector` and let me know if everything was ok.

> Format the code according to Python PEP8
> Remove cv2 and use scikit-image equivalent functions instead

I think now we could address both of these issues at once. What do you think?
Feel free to reach us if you need any help on that, ok? Thanks again!

**Comment by eldad-a** [comment]
@alexandrejaguar wrote:

> This could be good: please use `git pull origin ridge-directed-ring-detector` and let me know if everything was ok.

checked out `ridge-directed-ring-detector`, than ran the command you kindly suggested; did not encounter any issues so far.

Should I sync my fork to the original scikit-image repository?

**Comment by alexandrejaguar** [comment]
@eldad-a wrote: 
> Should I sync my fork to the original scikit-image repository?
> (this hasn't been done since I forked it, Sept 2015...)

Feel free to do that as well (`git pull upstream master`), but I think it wouldn't affect us at this stage.

**Comment by alexandrejaguar** [comment]
Hi @eldad-a, I think you pushed all modifications within `master` on your branch (205a84c)... we don't want that :)

**Comment by eldad-a** [comment]
@alexandrejaguar 
> Hi @eldad-a, I think you pushed all modifications within `master` on your branch ([205a84c](https://github.com/scikit-image/scikit-image/commit/205a84cde8592e00350c2911067d21039aebe925))... we don't want that :)

Oh dear...
Could you kindly instruct me how to correct that?

**Comment by eldad-a** [comment]
@alexandrejaguar 

> Hi @eldad-a, I think you pushed all modifications within `master` on your branch ([205a84c](https://github.com/scikit-image/scikit-image/commit/205a84cde8592e00350c2911067d21039aebe925))... we don't want that :)

Sorry for the misunderstanding; did not realize it was not desired to have my branch updated to `master` of `scikit-image`.

Should I revert?
Could you recommend the easiest way?

Should I run 
`git checkout e0eefe2261b82c30da13d4979a9452cab7b6903b`
followed by a commit and push?

**Comment by alexandrejaguar** [comment]
> Sorry for the misunderstanding; did not realize it was not desired to have my branch updated to `master` of `scikit-image`.
> 
> Should I revert?
> Could you recommend the easiest way?
> 
> Should I run
> `git checkout e0eefe2261b82c30da13d4979a9452cab7b6903b`
> followed by a commit and push?

@eldad-a don't worry, I learned the worst way everything is reversible here. :)
I think you should revert your branch to e0eefe2 (maybe `git revert 5e6ee16..205a84c`), but I would ask first to @nellev or @seberg, the masters of git :)

**Comment by stefanv** [comment]
@eldad-a I don't have permission to push to your branch here; could you please change that setting?  I have done the merge.

Alternatively, you can reset your branch to `stefanv/ridge-directed-ring-detector` where I've pushed these changes.

**Comment by eldad-a** [comment]
> @eldad-a I don't have permission to push to your branch here; could you please change that setting? I have done the merge.
> 
> Alternatively, you can reset your branch to `stefanv/ridge-directed-ring-detector` where I've pushed these changes.

@stefanv I should be able to get back to working on the needed modifications next week;
Till then, I added you as a collaborator.
Hope that's what needed for you to push the merge.

Thanks!

**Comment by stefanv** [comment]
Please note that the data file used in the notebook is missing from the archive.

**Comment by stefanv** [comment]
I've pushed the rebased branch.

**Comment by eldad-a** [comment]
> I've pushed the rebased branch.

@stefanv Thanks!
Do I understand correctly that this resolves me pushing the updates from master to my branch?

If possible, please share the command you used.

**Comment by eldad-a** [comment]
Dear @alexandrejaguar @stefanv ,

I looked at the [(skimage) How to contribute to](https://scikit-image.org/docs/dev/contribute.html) page and followed the [guidelines for conda](https://scikit-image.org/docs/dev/contribute.html#conda), for setting up the build environment.
Running
   ```https://scikit-image.org/docs/dev/contribute.html#conda```
I get an for the use of  Python 2.7:

> ERROR: Python 2.7.15 detected.
>    scikit-image 0.15+ support only Python 3.5 and above.

Tracing back to what caused the switch from my `py36` to `py27`, I found that running:
    ```conda install `for i in requirements/{default,build}.txt; do echo -n " --file $i "; done` ```
leads to the installation of:
     ```python             conda-forge/linux-64::python-2.7.15-h938d71a_1006```    

This happens even if I skip that command and try:
    ```conda install pytest```

Any suggestions on this?

For now I re-created the environment, skipped the lines that switch to `py27` and used
    ```pip install -e . ```

Found that `conda install wheel` will also lead to `py27` as well, 
and so I ended up running
`conda install -c conda-forge wheel`
followed by 
    ```conda install pytest```

**Comment by hmaarrfk** [comment]
:/ I can't seem to recreate on my own computer


```
(base) mark2@xps:~/git/scikit-image$ conda create --name skimage-dev
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/mark2/miniconda3/envs/skimage-dev

Proceed ([y]/n)? 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate skimage-dev
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) mark2@xps:~/git/scikit-image$ conda activate skimage-dev
(skimage-dev) mark2@xps:~/git/scikit-image$ conda install `for i in requirements/{default,build}.txt; do echo -n " --file $i "; done`
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/mark2/miniconda3/envs/skimage-dev

  added / updated specs:
    - cython[version='>=0.25,!=0.28.2,!=0.29.0']
    - imageio[version='>=2.0.1']
    - matplotlib[version='>=2.0.0,!=3.0.0']
    - networkx[version='>=2.0']
    - numpy[version='>=1.13.3,>=1.13.3']
    - pillow[version='>=4.3.0']
    - pywavelets[version='>=0.4.0']
    - scipy[version='>=0.17.0']
    - wheel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gst-plugins-base-1.14.5    |       h0935bb2_0         6.8 MB  conda-forge
    gstreamer-1.14.5           |       h36ae1b5_0         4.5 MB  conda-forge
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         4.0 MB
    ------------------------------------------------------------
                                           Total:        23.4 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.3.9-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.3.9-py37_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  cython             conda-forge/linux-64::cython-0.29.10-py37he1b5a44_0
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  decorator          conda-forge/noarch::decorator-4.4.0-py_0
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-he4413a7_1000
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.58.3-hf63aee3_1001
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_0
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_0
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  imageio            conda-forge/linux-64::imageio-2.5.0-py37_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  kiwisolver         conda-forge/linux-64::kiwisolver-1.1.0-py37hc9558a2_0
  libblas            conda-forge/linux-64::libblas-3.8.0-7_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-7_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  liblapack          conda-forge/linux-64::liblapack-3.8.0-7_openblas
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h57b8799_1003
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.9-h13577e0_0
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  matplotlib         conda-forge/linux-64::matplotlib-3.1.0-py37_1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.1.0-py37hfd891ef_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  networkx           conda-forge/noarch::networkx-2.3-py_0
  numpy              conda-forge/linux-64::numpy-1.16.4-py37h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openblas           conda-forge/linux-64::openblas-0.3.5-h9ac9557_1001
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_1
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pillow             conda-forge/linux-64::pillow-6.0.0-py37he7afcd5_0
  pip                conda-forge/linux-64::pip-19.1.1-py37_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyqt               conda-forge/linux-64::pyqt-5.9.2-py37hcca6a23_0
  python             conda-forge/linux-64::python-3.7.3-h5b0a415_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pywavelets         conda-forge/linux-64::pywavelets-1.0.3-py37hd352d35_1
  qt                 conda-forge/linux-64::qt-5.9.7-h52cfd70_2
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  scipy              conda-forge/linux-64::scipy-1.3.0-py37h921218d_0
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py37_0
  sip                conda-forge/linux-64::sip-4.19.8-py37hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py37_1000
  sqlite             conda-forge/linux-64::sqlite-3.28.0-h8b20d00_0
  tk                 conda-forge/linux-64::tk-8.6.9-hed695b0_1002
  tornado            conda-forge/linux-64::tornado-6.0.2-py37h516909a_0
  wheel              conda-forge/linux-64::wheel-0.33.4-py37_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
  zstd               conda-forge/linux-64::zstd-1.4.0-h3b9ef0a_0


Proceed ([y]/n)? 

```

seems ok on my computer.

**Comment by hmaarrfk** [comment]
do you have any other channels added to your system? is conda up to date for you?

```
(skimage-dev) mark2@xps:~/git/scikit-image$ conda --version
conda 4.6.14
```

```
(skimage-dev) mark2@xps:~/git/scikit-image$ conda config --show channels
channels:
  - conda-forge
  - defaults
```

**Comment by jni** [comment]
I think if your base conda environment is 2.7, your default Python is 2.7. Probably we should add `python=3.7` to the instructions.

**Comment by hmaarrfk** [comment]
That I never knew

**Comment by eldad-a** [comment]
> do you have any other channels added to your system? is conda up to date for you?
> 
> ```
> (skimage-dev) mark2@xps:~/git/scikit-image$ conda --version
> conda 4.6.14
> ```
> 
> ```
> (skimage-dev) mark2@xps:~/git/scikit-image$ conda config --show channels
> channels:
>   - conda-forge
>   - defaults
> ```

Thanks @hmaarrfk , @jni  !
It seems the channels were the issue in my case:

```
:~$ conda config --show channels
channels:
  - https://conda.anaconda.org/auto
...
```
```
:~$ conda --version
conda 4.6.14
```

Apparently the `auto` channel led to the `py27` installation, as `wheel` was found there.

Removing the `auto` channel and following the instructions at  [Build environment setup : conda](https://scikit-image.org/docs/dev/contribute.html#conda) works for the most part.

__I apologize for the false alarm.__

_pytest results in 1 error_

```$ pytest skimage```
results in:
```
================================================= ERRORS =================================================
_________________________________ ERROR at setup of test_imread_http_url _________________________________
file /media/DATA/eldada/Documents/Projects/scikit-image/skimage/io/tests/test_io.py, line 46
  def test_imread_http_url(httpserver):
E       fixture 'httpserver' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/media/DATA/eldada/Documents/Projects/scikit-image/skimage/io/tests/test_io.py:46
============================================ warnings summary ============================================
feature/tests/test_blob.py::test_blob_log
feature/tests/test_blob.py::test_blob_log
  /home/eldada/lib/python/anaconda3/envs/skimage-dev/lib/python3.7/site-packages/numpy/core/function_base.py:277: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
    y = linspace(start, stop, num=num, endpoint=endpoint, axis=axis)

filters/tests/test_ridges.py::test_2d_null_matrix
filters/tests/test_ridges.py::test_3d_null_matrix
  /media/DATA/eldada/Documents/Projects/scikit-image/skimage/filters/ridges.py:216: RuntimeWarning: invalid value encountered in true_divide
    filtered = np.abs(auxiliary) / np.abs(np.max(auxiliary))

filters/tests/test_ridges.py::test_2d_null_matrix
filters/tests/test_ridges.py::test_3d_null_matrix
  /media/DATA/eldada/Documents/Projects/scikit-image/skimage/filters/ridges.py:219: RuntimeWarning: invalid value encountered in greater
    filtered = np.where(filtered > 0, filtered, 0)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================== 5396 passed, 26 skipped, 6 warnings, 1 error in 180.28 seconds =====================
```

**Comment by stefanv** [comment]
@eldad-a I used `git rebase -i` to remove commits I did not want and to replay the rest.  I had to edit a merge conflict once or twice, but overall it went smoothly.

**Comment by eldad-a** [comment]
> Please note that the data file used in the notebook is missing from the archive.

Thanks for the note!
I've added it for now in the same folder as the `demo.ipynb`;

**Comment by sciunto** [comment]
@stefanv Do you have a chance to look at this PR. Would be good to take a decision for the next release.

**Comment by alexdesiqueira** [comment]
Hey @eldad-a, long time no talk :)
Travis is complaining on missing files:
```
Missing from source distribution:

   ./skimage/transform/ridge-directed-ring-detector/unprocessed_fig_46.png
   ./skimage/transform/ridge-directed-ring-detector/demo.ipynb
```
Are these renamed/removed ones?

**Comment by alexdesiqueira** [comment]
Hey everyone,
I could finish this PR if @eldad-a don't mind; cc'ing @scikit-image/core.
Please let me know how to proceed.

**Comment by stefanv** [comment]
That'd be great, thanks Alex.

**Comment by alexdesiqueira** [comment]
I'm trying to push to this branch (`eldad-a:ridge-directed-ring-detector`) without success. Are we allowed to push here?

**Comment by grlee77** [comment]
> I'm trying to push to this branch (eldad-a:ridge-directed-ring-detector) without success. Are we allowed to push here?

Maybe that branch is not set to [allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?  If you can't get it to work, you can make a new PR after creating a new branch from this one. That will still preserve the commit history.

**Comment by alexdesiqueira** [comment]
Seems odd, @grlee77; I see now that @stefanv could push to it [here](https://github.com/scikit-image/scikit-image/pull/1706/commits/4bc19b520307be20c89e617a9b258d0f0a7a6ced).

>  If you can't get it to work, you can make a new PR after creating a new branch from this one.

I'm kinda sure I did that before :sweat_smile: Let me see what I can do tomorrow; I'll do that again if I still have issues.

**Comment by alexdesiqueira** [comment]
I'm still having my PRs denied:
```
> git push eldad-a ridge-directed-ring-detector
To https://github.com/eldad-a/scikit-image/
 ! [remote rejected]     ridge-directed-ring-detector -> ridge-directed-ring-detector (permission denied)
error: failed to push some refs to 'https://github.com/eldad-a/scikit-image/'
> git rev-parse --show-toplevel
```
Not sure what's happening. How would I do this by hand, again?

**Comment by alexdesiqueira** [comment]
Closing due to permission issues. Please refer to #4847, which continues this PR.

**Pull request closed without merging**
