### PR TITLE
add int64 support to `filters.rank_order` and `morphology.reconstruction`

### LINKED ISSUE #6277: Maximum array size for `morphology.reconstruction`?
## Description

When used with large arrays, `morphology.reconstruction` crashes my Python kernel (without any other error - I just see `The kernel for xxx.ipynb appears to have died. It will restart automatically`).

Is there a limit to the size of array this function can handle (beyond the memory limits of the system)? My problem is similar to [this issue](https://github.com/scikit-image/scikit-image/issues/4078), except my array does not contain any NaNs. If I split the array into smaller chunks, everything works as expected, but unfortunately I need to process the whole file in one go. 

I've encountered the same problem with several different datasets, so I don't think it's specific to my data. I also have plenty of memory on my machine: I'm running on Google Cloud and have tried various machines with up to 1 TB of RAM. On these, the kernel crashes when memory usage is less than 1% (as indicated by `top`).

## Way to reproduce

An example array (saved as a `.pkl` file) can be downloaded [here](https://drive.google.com/file/d/1n2GsBPYiLeOdkMnitC_ZI0vsLb4lWcJH/view?usp=sharing) (***warning**: it's about 5 GB*).

The following code runs for 5 to10 minutes, then crashes the kernel:

```python
import pickle
import numpy as np
import skimage.morphology

with open("glomma.pkl", "rb") as f:
    data = pickle.load(f)

assert ~np.isnan(data).any()

# Keep perimeter cells equal to the original values and set all other cells to max
seed = data.copy()
seed[1:-1, 1:-1] = data.max()

filled = skimage.morphology.reconstruction(seed, data, method="erosion")
```

If I use the code below to subset the array into tiles/quadrants, I can process each tile fine (but of course the combined result is not the same as the output for the full array).

```python
# Process just one quadrant
rows, cols = data.shape
data = data[: int(rows / 2), : int(cols / 2)] 
```

Does anyone have any tips, please? I've already split the original image into "coherent" subsets to make each dataset as small as possible. 260 out of 262 subsets are processed OK, but the two largest crash the kernel and I haven't managed to find a workaround yet.

Thank you! :-)

## Version information

```python
3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
Linux-5.4.144+-x86_64-with-glibc2.31
scikit-image version: 0.18.3
numpy version: 1.21.5
```

### PR DESCRIPTION
**Pull request by grlee77**
## Description

closes #6277

This PR resumes work from #6295, using fused types to support both 32 and 64-bit integer types in `morphology.reconstruction` and `filters.rank_order`. This allows extremely large images to be used with these functions.

Additional changes:
- `skimage.filters.rank_order` now uses the minimum required unsigned integer size rather than always using uint32
- to minimize increase in binary size, I only implemented int32 and int64 for the Cython code.
- single precision `seed` now returns single precision output (this function was missed during previous float32 work)
- benchmarks were added

Performance remains approximately the same as before. Memory usage is now a bit less for float32 inputs.

### Pythran version 
In the earlier commits, I tried converting to Pythran, but measured 5-10x slower performance in that case for the larger sizes in the benchmarks. @serge-sans-paille, if you are interested in taking a look see commit d5295bc which has both Cython and pythran versions present (which one is called can be chosen by editing the import at the top of grayreconstruct.py). The pythran code is a bit cleaner (no cdefs required), but it is not obvious to me where the performance difference comes from. 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@grlee77 I think the issue is that pythran cannot prove that array accesses are inbound. I'll investigate that :-)

**Comment by JamesSample** [comment]
This looks fantastic @grlee77 ! 

Thanks for your help with this! Especially for the stuff involving fused types in Cython - it's great to have a version that chooses the most appropriate type automatically.

**Review by rfezzani — APPROVED** [review]
Excellent, thank you @grlee77 :wink:

**Comment by alexdesiqueira** [comment]
Thank you @grlee77 @JamesSample!

**Pull request merged**
