### PR TITLE
Update Travis-CI to xcode 10.1

### PR DESCRIPTION
**Pull request by stefanv**
Let's see if this fixes our test segfault.

### CODE REVIEW

**Comment by stefanv** [comment]
That seems to do the trick!

**Comment by soupault** [comment]
What do you think about moving MacOS builds to Azure?

**Comment by hmaarrfk** [comment]
I guess I missed the segfault. But I'm not sure if you can change the wheel one because of how it is supposed to target older macs too? :/

**Comment by stefanv** [comment]
On Thu, 20 Dec 2018 05:53:08 -0800, Mark Harfouche wrote:
> I guess I missed the segfault. But I'm not sure if you can change the
> wheel one because of how it is supposed to target older macs too? :/

Yes, that was my impression too.

**Comment by hmaarrfk** [comment]
The other issue is that it may be an actual bug, but that we dont see anymore in light of how new compilers are organizing the code

**Comment by hmaarrfk** [comment]
can we downgrade xcode?

**Comment by jni** [comment]
@scikit-image/core can we merge this? We could raise another issue and maybe a PR to revert the change, but I would very much like to have our CI go green again.

**Pull request merged**
