### PR TITLE
Example of see also hyperlinks between gallery examples

### PR DESCRIPTION
**Pull request by emmanuelle**
It would be a nice addition to have see-also-like links between examples of the gallery. Recently I browsed through the statistics of visits of the gallery, and I found out some pages were often visited together (links between those pages would be convenient for users), whereas pages that I would have expected to be visited together were not, maybe because a method was less known than others: suggestions of other pages to visit could also increase the visibility of some pages. 

This PR is a minimal example of how to create links between pages by putting sphinx codes in comment blocks. It works well for html pages. However, it causes problems for the ipython notebook that is created, with the following error

```
<string>:35: (ERROR/3) Unknown interpreted text role "ref"
```

Therefore, I would welcome comments and suggestions for improvements, especially regarding the generation of the ipython notebook.

### CODE REVIEW

**Comment by emmanuelle** [comment]
Another possibility is to have the "see also" links appearing in the sidebar together with "next topic" and "previous topic". I don't know whether they would be as visible, though, and it might be more complicated to implement.

**Comment by emmanuelle** [comment]
Anybody? @scikit-image/core

**Comment by jni** [comment]
@emmanuelle I know nothing at all about linking between notebooks... Did you want this merged anyway or wait for more comments?

**Comment by emmanuelle** [comment]
@jni I'm not in a hurry because the website displays the dev documentation, so it doesn't have to be merged before a release. Let's wait for other comments on links in notebooks.

**Comment by blink1073** [comment]
@emmanuelle, I don't think we should embed the links unless it is the full explicit url, since the notebooks will be downloaded.  I'd vote for a see also tab on the side.

**Comment by sciunto** [comment]
Is it sphinx or sphinx-gallery that generates the notebooks? Maybe this is an issue that can be reported upstream?

**Comment by sciunto** [comment]
The "see also feature" is already used: https://github.com/scikit-image/scikit-image/blob/master/doc/examples/segmentation/plot_thresholding.py#L10

So, I close this PR.

**Comment by sciunto** [comment]
the generation of notebook looks good now. If we check here: https://github.com/scikit-image/scikit-image/blob/master/doc/examples/segmentation/plot_thresholding.py#L10
there is an internal link. In the notebook, it's interpreted as a string... I think we can't do much better. Therefore, I'm closing this issue.

**Pull request closed without merging**
