### PR TITLE
disable Travis-CI builds

### PR DESCRIPTION
**Pull request by grlee77**
We do not have sufficient free credits to run this test matrix on their new billing policy.

We may want to re-enable for non-x86 architectures such as AArch64 going forward

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
Not sure if we want to keep this file around for future use or just rely on the git history for that? I think we may want to enable it again for ARM only going forward and perhaps only in the wheels repo. I think all repos under a single organization share a common pool of credits.

**Comment by emmanuelle** [comment]
I also had the impression that credits are shared within an org, so :+1: for disabling Travis in this repo. I'd be in favor of removing the file altogether and relying on `git history`, but it's not a strong preference so I'm fine with merging the PR. I'm just a bit confused about the CI: it looks like all builds were cancelled.

**Comment by grlee77** [comment]
I manually cancelled them since there was nothing new to test

**Review by emmanuelle — APPROVED** [review]
Thanks @grlee77, approved! Regarding CI, I also opened #5097 yesterday. Maybe we'll have green PRs soon ;-).

**Comment by emmanuelle** [comment]
Oh and there are also the files in `tools/travis` which could be removed. (some of `tools/travis/notes.txt` could be useful for the other CI tools). Can be done in another PR ;-).

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Thank you @grlee77! `--pre` build failures should be fixed in #5103

**Pull request merged**
