### PR TITLE
[New feature] Majority voting filter

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

This PR is related to a feature request in [scipy](https://github.com/scipy/scipy/issues/9873).
Based on the [answer](https://github.com/scipy/scipy/issues/9873#issuecomment-467726092) of @stefanv, I had some explorations.

A first implementation could be:

```python
import numpy as np
from skimage.filters import rank

img = np.random.randint(255, (1024, 1024), dtype=np.uint8)
selem = np.ones((5, 5), dtype=bool)

res = rank.windowed_histogram(img, selem).argmax(axis=-1)
```

This provides good results: I measured 0.97sec average time over 10 runs.

I Tried to improve this using Cython (See my code).

```python
res = rank.majority_filter(img, selem)
```

On the same data, with the same settings, I measured an average time of 0.32 seconds.

I hope that this can be of any help.

## Checklist

- [X] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [X] Unit tests
- [X] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
Your first version, the one-liner, is actually pretty sweet!  But, I would be OK with adding a new rank filter for this.

**Comment by stefanv** [comment]
(Travis-CI failures are unrelated.)

**Comment by jni** [comment]
@rfezzani thanks, very clean!

As a side note:
- we don't actually use the reference result added to the .npz file, as far as I can tell, so maybe we can remove it? (I like the test as it is.)
- I think the kernels should all have docstrings, but since this PR matches the standard of the original file, I'm happy to have it added.

Thanks again!

**Comment by rfezzani** [comment]
Thank you @stefanv and @jni for your feed back. I am really happy if this can help!
Cheers.

**Comment by soupault** [comment]
I suggest to rename this from `majority_filter` to `majority`. Opinions?

**Comment by stefanv** [comment]
Yes, that is a good suggestion.

**Comment by rfezzani** [comment]
yes, `majority` is better indeed.
@jni, the .npz file is still in use, `test_rank_filter` was causing CI failure, that's why I added a reference result for the majority filter.
I also agree that the kernels should have docstrings, it wasn't that obvious to understand the framework of rank filters.

**Comment by soupault** [comment]
See https://github.com/scikit-image/scikit-image/pull/3839

**Pull request merged**
