### PR TITLE
Update scipy requirement to 1.4.1 and use scipy.fft instead of scipy.fftpack

### LINKED ISSUE #5986: EXAMPLES: Change use of `scipy.fftpack` to `scipy.fft`
## Description

Examples like [this band pass](https://scikit-image.org/docs/stable/auto_examples/filters/plot_dog.html) or [this use of windows](https://scikit-image.org/docs/stable/auto_examples/filters/plot_window.html) are using deprecated `scipy.fftpack`. They could use `scipy.fft` module instead. I will kindly make a PR if you consider that is appropiate.

### PR DESCRIPTION
**Pull request by srvanrell**
## Description

- Update requirement of scipy as suggested in isssue #5986.
- Update examples importing fftpack to use fft instead
- Remove _shared.fft workaround that loaded numpy.fft, scipy.fft or scipy.fftpack
- Update imports were necessary to use scipy.fft module

Closes #5986 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks. The test failures here seem to be unrelated (They appear to be an issue with a recent release of `setuptools`)

**Comment by srvanrell** [comment]
@grlee77 The PR looks complete for me but you mentioned in #5986 that there were some calls to astype that are no longer needed. Let me know if there is something more to do or fix. Thank you for your patience with a newbie.

**Comment by grlee77** [comment]
> @grlee77 The PR looks complete for me but you mentioned in #5986 that there were some calls to astype that are no longer needed. Let me know if there is something more to do or fix. Thank you for your patience with a newbie.

Yes, I will take a look at that now and push any changes here.

**Review by grlee77 — APPROVED** [review]
Thanks @srvanrell, this looks good!

**Comment by hmaarrfk** [comment]
Thanks you two!

**Pull request merged**
