### PR TITLE
Functions to create pixel graphs and find central pixels

### PR DESCRIPTION
**Pull request by jni**
## Description

Related but quite distinct from #5273, I've often wanted to select a "central" pixel of an object that represented a "geodesic" center, rather than the centroid/center of mass. I think a pixel neighborhood graph is the most natural way to find such a center.

In this PR I've suggested two new functions in `skimage.graph`:

- `pixel_graph` computes the pixel-pixel neighborhood graph for a given binary image *or* for a grayscale image with a mask. The neighborhood is returned as a compressed sparse matrix together with a list of raveled pixel indices.
- `central_pixel` takes the output of `pixel_graph` and finds the pixel with the smallest sum-of-shortest-path-distances to all other pixels (largest closeness centrality). Note: this is expensive.

Caveats:
- `central_pixel` *assumes* that the graph is connected. If this assumption is violated, it produces garbage. I don't know how much of a problem this is — should we add a check and raise a ValueError?

Still to do:
- [x] tests
- [x] make diagonal distances weighted appropriately
- [x] add anisotropic scaling
- [x] add release notes
- [x] better plot labels in the gallery example
- [x] remove axes in the gallery examples

Questions for core devs:
- thoughts about this API?
- any improvements/suggestions?

Here's the final figure from the gallery example:

retina-pixel-graph

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] Descriptive commit messages (see below)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
I'm just going to quote from [PEP8](https://www.python.org/dev/peps/pep-0008/#indentation) directly because I think PEP8speaks is wrong here:

> Continuation lines should align wrapped elements either vertically using Python's implicit line joining inside parentheses, brackets and braces, or using a hanging indent.  When using a hanging indent the following should be considered; there should be no arguments on the first line and further indentation should be used to clearly distinguish itself as a continuation line.
>
> [...]
>
> `# Add 4 spaces (an extra level of indentation) to distinguish arguments from the rest.`
>
> [...]
>
> The closing brace/bracket/parenthesis on multiline constructs may [...] line up under the first non-whitespace character of the last line of list

**Comment by mkcor** [comment]
> @mkcor thank you for the review! I've updated the PR with your suggestions (bar the one about image vs skeleton)

You're welcome, @jni! I wonder if my latest [comment](https://github.com/scikit-image/scikit-image/pull/5602#discussion_r731597064) might have fallen in the cracks... But now I have a better idea: How about
```
In various image analysis contexts, it is useful to think of the pixels of an
image as a network, and to think of each region (set of connected pixels, with
or without diagonals) as a graph.
```
?

> as well as a comment explaining how the function works, added benchmarks, and tests covering all new lines. The `central_pixel` function is pretty slow, about 10s on the (2x downsampled) benchmark. I went to nx to check if there were any "tricks" to finding closeness centrality quickly but the implementation there is also the brute force approach.

What is nx? Thanks!

**Comment by jni** [comment]
Thanks @mkcor and @stefanv for the repeated reviews and tips! I think I've addressed all of your concerns so far. :crossed_fingers:

**Comment by mkcor** [comment]
> @mkcor you were absolutely right, it _had_ fallen through! Anyway, I've updated it with a third option. In fact images with more than one region can easily be a graph, it just won't be a _connected_ graph.

True! Great, we're getting there... Since the title of the demo is "Pixel graphs," the term 'pixel graph' needs to appear at some point in the body text (preferably in the beginning). How about inserting it right after 'network:'
```
, as a network (or graph),
```
? With or without parentheses? How about *replacing* 'network' with '(pixel) graph?' Oh, I can see this did this very well in the release notes! Then, maybe I would be slightly more hand-holding in the sentences that follows, e.g.:
```
In this example, {thinking of, approaching, considering} a skeleton as a pixel graph,
we find its pixel with maximal *closeness centrality* ...
```
Back to the first sentence, I quite like it now, but I'm not fully convinced with the phrase `, or each region of an image,`: Whether we mean a) "it is useful to think of the pixels of an image or of the pixels of each region of an image" or b) "it is useful to think of the pixels of an image or of each region of an image," I think it's clearer (even though heavier) to keep 'of' right before 'each region.' Also, 'each' is a little unfortunate here... If we mean a), then 'any' or 'a' would be more appropriate; if we mean b) but I guess we don't, then I could imagine something like "it is useful to think of an image as a graph whose vertices are the regions of the image."

@jni you must hate me by now :sweat_smile: but I will add one final comment: I've been pushing for demo titles at the imperative: "Work with pixel graphs," "Approach images as pixel graphs" or, more to the point, "Find the central pixel of an object," "Find the geodesic center of a pixel graph."

**Comment by jni** [comment]
> you must hate me by now :sweat_smile:

I truly do! :joy: But it's a love/hate relationship. :blush: 

> Whether we mean a) "it is useful to think of the pixels of an image or of the pixels of each region of an image" or b) "it is useful to think of the pixels of an image or of each region of an image,"

Indeed it's (a). For (b), we have region adjacency graphs (RAGs) in skimage.future.graph. I'll try to make it clearer.

> the term 'pixel graph' needs to appear at some point in the body text (preferably in the beginning).

Good point! :joy: I'll try to make it clearer.

> I've been pushing for demo titles at the imperative: "Work with pixel graphs," "Approach images as pixel graphs" or, more to the point, "Find the central pixel of an object," "Find the geodesic center of a pixel graph."

How about "Use pixel graphs to find the geodesic center of an object"? (object/region/segment?)

**Comment by jni** [comment]
Thanks @mkcor! I do think this warrants an issue!

Can you remind me how to set a thumbnail? I agree 100% that the last pic should be the thumbnail, hence why I included it in the PR description :smiley:, but I didn't remember (a) that this could be set manually, and (b) how to do it.

I agree with your notes, will try to make a PR to update it.

**Pull request merged**
