### PR TITLE
1477 - Regionprops doesn't check shape equivalence between label_imag…

### PR DESCRIPTION
**Pull request by ajaybhat**
…e and intensity_image

#1477

### CODE REVIEW

**Comment by grlee77** [comment]
Hi @ajaybhat 
looks good to me, but I think this should raise a `ValueError` rather than a `TypeError`

**Comment by ajaybhat** [comment]
> I think this should raise a ValueError rather than a TypeError

**Comment by ajaybhat** [comment]
> I think this should raise a ValueError rather than a TypeError
Okay, I'll change it to ValueError

**Comment by ajaybhat** [comment]
Does it look good to merge now?

**Comment by JDWarner** [comment]
I restarted the Travis 3.4 build, which timed out at 50 minutes. That's usually one of our faster builds, and no others had a problem; I don't know why it happened.

Ignore the AppVeyor failure for now, it has nothing to do with this PR.

**Comment by JDWarner** [comment]
@ajaybhat it's been long enough that one or more underlying files have changed, so this will require a rebase. I believe it is ready to merge once that happens.

**Comment by emmanuelle** [comment]
The code of ``regionprops`` should be modified as well to raise a meaningful error, right?

**Comment by soupault** [comment]
The proposed change has been merged with https://github.com/scikit-image/scikit-image/pull/1777 .
Closing.

**Pull request closed without merging**
