### PR TITLE
Update Travis Script

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@soupault, I added https://github.com/scikit-image/scikit-image/wiki/Github-Access-Token

**Comment by sciunto** [comment]
@blink1073 Is this still necessary? Looks like nobody did the second review. If it is still necessary, could you explain why and rebase please? to make sure it passes with our last modifications.

**Comment by blink1073** [comment]
This token was regenerated using the latest Travis encryption, per their recommendations.

**Comment by sciunto** [comment]
Oh, yes, I remember that! Great. I'll merge as soon as it's validated by travis.

**Pull request merged**
