### PR TITLE
Fix matplotlib + qt 5.12 the same way upstream does it

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
closes: https://github.com/scikit-image/scikit-image/issues/3739
xref: https://github.com/matplotlib/matplotlib/pull/13412

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
There's always something... =P

This doesn't seem to be working (the two failures are identical)...

**Comment by tacaswell** [comment]
@smheidrich figured it out.  You may need to also clear the caches in travis...

**Comment by jni** [comment]
@tacaswell thanks! Ok I've tried deleting recent caches (couldn't do all for some reason), and restarting the failed builds, let's see how we go...

**Comment by hmaarrfk** [comment]
@jni, I still see some caches from PRs. Did you want to "delete all caches". what are the caches actually helping?

**Comment by jni** [comment]
@hmaarrfk I tried "delete all caches" but Travis is unhappy about doing that it seems. I clicked on as many as I could, including all the ones more recent than 24h. Clearly not sufficient. =\

**Comment by smheidrich** [comment]
According to the [docs](https://docs.travis-ci.com/user/caching/), "[i]f a branch does not have its own cache, Travis CI fetches the cache of the repository’s default branch", so it should be enough to just delete the cache for master. If you did that and it still doesn't work, then probably the cache isn't the issue.

**Comment by hmaarrfk** [comment]
I tried to restart one build in isolation. Do you think it is getting the cache from the previous builds in the same PR?

**Comment by hmaarrfk** [comment]
seems like that isn't the issue :/

**Comment by smheidrich** [comment]
I ran a build with more verbose ``pytest`` output, and [what it says](https://travis-ci.org/smheidrich/scikit-image/jobs/492916293#L2765) is:
```
/home/travis/venv/bin/python: relocation error: /home/travis/venv/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference
```
I think this is different from the [error in matplotlib's builds](https://travis-ci.org/matplotlib/matplotlib/jobs/491475297#L2239-L2256), but I'm not sure what to do about it nor why it doesn't appear for matplotlib.

**Comment by tacaswell** [comment]
we bumped to xenial to get py37 iirc

**Comment by smheidrich** [comment]
Hmm you're right, and for the earlier Python versions, switching to xenial didn't help in my tests... in that case, I'm out of ideas.

**Comment by hmaarrfk** [comment]
so we should unpin for 5.12, but keep at 5.10 for anything less than xenial.

That sounds like a plan

**Comment by hmaarrfk** [comment]
@smheidrich it seems xenial helped your tests. You probably got stuck on some xkb bug that we fixed recently (i htink). At least your xenial tests went super far.

**Comment by smheidrich** [comment]
@hmaarrfk One weird thing is: the error message mentioning xcb (if you meant that instead of xkb) is the one that appeared in matplotlib's builds prior to adding ``qtbase5-dev``, except in scikit-image's case it also mentions [``could not connect to display``](https://travis-ci.org/smheidrich/scikit-image/jobs/493015222#L7897). And I guess it comes from a different place in the Python code.

**Comment by hmaarrfk** [comment]
So i think I finally got it, we need both `qtbase5-dev` and the check for ubuntu 16.04.

Ubuntu 14.04 is going to be EOL in April, so I guess we should continue testing on that?
https://wiki.ubuntu.com/Releases

**Comment by jni** [comment]
@scikit-image/core Can someone merge? Let's fix our build matrix!

**Pull request merged**
