### PR TITLE
Add comment in ndi.generic_filter for the use of output, in RAG

### LINKED ISSUE #1843: Add comment clarifying use of strided output array for generic_filter RAG construction
See [here](https://github.com/scikit-image/scikit-image/pull/1826/files#r48343523).

### PR DESCRIPTION
**Pull request by OrkoHunter**
Fixes #1843 

@jni Here you go !

Please comment if you want to add more in the comment.

### CODE REVIEW

**Comment by jni** [comment]
@OrkoHunter Cool, thanks! =) I would like to request a modification: explain *why* this is done: (a) we don't actually care about the output, and (b) without it, a float array of the same shape as the input image is created, which could be expensive.

**Comment by OrkoHunter** [comment]
@jni Modification done !

**Comment by stefanv** [comment]
cost expensive -> expensive in memory consumption?

**Comment by jni** [comment]
Thanks @OrkoHunter! This is timely because I just referred to this line in the numpy mailing list! =)

**Comment by OrkoHunter** [comment]
That's nice :)

**Pull request merged**
