### PR TITLE
improve Euler number example

### PR DESCRIPTION
**Pull request by emmanuelle**
This is a follow-up of #4380 @lagru @jni

### CODE REVIEW

**Review by jni — APPROVED** [review]
🎉

**Comment by jni** [comment]
Awesome, thank you Emma! Feel free to merge when builds pass!

**Review by lagru — APPROVED** [review]
Thanks Emma! Seems like I merged to early. Sorry for that.

**Comment by emmanuelle** [comment]
Thanks @lagru and @jni! Merging.

**Pull request merged**
