### PR TITLE
Fix doctest space

### PR DESCRIPTION
**Pull request by Borda**
## Description
attempt to solve the issue with doctest and new numpy

## References
#2415 and #2935

### CODE REVIEW

**Comment by Borda** [comment]
well, it seems that what is passing in `PIP_FLAGS="--pre"` doe not pass in `WITH_PYAMG=1 MINIMUM_REQUIREMENTS=1 WITH_QT=1`

**Comment by soupault** [comment]
@Borda you have lots of unrelated changes in this PR as well. If you `Enable access for the maintainers`, I could help with this issue.

**Comment by Borda** [comment]
@soupault  I have check the option `Allow edits from maintainers. ` in this PR or do you mean something else?

**Comment by soupault** [comment]
@Borda yes, thanks! I've rebased the branch onto upstream `master`.

However, I'm not able to fix your/origin `master` branch (the granted permissions does not allow this). You'd need to do this by yourself. See https://stackoverflow.com/a/42332860/1759565 for the instructions.

**Comment by Borda** [comment]
I did as the post recommends and I hope that it is correct now...

**Comment by soupault** [comment]
I think the 1st commit (`Merge remote-tracking ...`) is unwanted. Otherwise, should be ok.

**Comment by emmanuelle** [comment]
Thanks for all your hard work @Borda and @soupault 

Did you consider using ``np.set_printoptions(legacy='1.13')`` ? (see for example https://github.com/nilearn/nilearn/pull/1592/files)

**Comment by Borda** [comment]
@soupault I see, so hope that now it is good...
@emmanuelle  I not sure about it but you would need to set `np.set_printoptions(legacy='1.13')` in general (I don't know how) or in the beginning of each test independently, right?

**Comment by soupault** [comment]
@Borda I'm closing this PR as we decided to move on with `np.set_printoptions(legacy='1.13')`. All deprecations related to `numpy=0.14` are to be addressed in https://github.com/scikit-image/scikit-image/pull/2935.

Thank you for your attempt on fixing this, and you are welcome to contribute to the discussion in #2935!

**Pull request closed without merging**
