### PR TITLE
fixed #2551

### LINKED ISSUE #2551: richardson_lucy returns NaN
Hi guys,

I think there is a bug in your Richardson-Lucy implementation:

https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/deconvolution.py
line 389
`relative_blur = image / convolve_method(im_deconv, psf, 'same')`

as soon as  [image] contains 0, more and more NaN will be created and propagated due to convolution.
on my PC (win7, 64bit, anaconda py3.5) the given test case doe not work because of this.

##FIX
add  behind line 389
`relative_blur[np.isnan(relative_blur)] = 0`

Cheers,
Karl

### PR DESCRIPTION
**Pull request by meriki**
## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

### CODE REVIEW

**Comment by soupault** [comment]
@meriki Please, rebase your branch onto `master`. At the moment, it includes a lot of non-relevant changes.

**Comment by meriki** [comment]
Sure. I'll look into it right away.

**Comment by soupault** [comment]
@alexandrejaguar this is meant to address #2551 (see the title).

**Comment by alexandrejaguar** [comment]
@soupault I saw it, but #2512 seems to be forgotten.

**Comment by soupault** [comment]
@alexandrejaguar not really, everyone is just silently waiting for occasional fix of pre-0.13 bugs :).

**Comment by alexandrejaguar** [comment]
@soupault sure :)

**Comment by meriki** [comment]
@soupault I can't seem to remove my earlier commits. Could you please help out with that?

**Comment by jni** [comment]
@meriki it looks like you were working on master. You should always work in a separate branch. (You can see instructions in the [contributing guide](http://scikit-image.org/docs/dev/contribute.html#development-process) as well as Aaron Meurer's [Git workflow guide](http://www.asmeurer.com/git-workflow/).) Now that you've messed up your master branch (by messed up I mean you have commits that are different from our own master), you can clean it as follows:

- git remote add upstream https://github.com/scikit-image/scikit-image

This adds the official scikit-image repository to your git "address book".

- git fetch upstream

This downloads all of the branches from our official repository.

- git branch -m master messed-up-master

This renames your current branch "master" to a branch "messed-up-master"

- git checkout --track upstream/master

This checks out the official master branch into your own master branch.

- git checkout master -b fix-2551

Now you've made a branch specifically for this PR.

- git cherry-pick <commit>

Choose a commit that you want to apply that should go in the PR. `commit` should be the hash of a commit that you want to apply, like
d413bfa57b85e72daf7df2baabe5528f621a1c67
above.

Repeat for other commits that you want to add.

Then,

- git push --set-upstream origin fix-2551

And create a new pull request. In the meantime, I'll close this one because I don't think you can recover it. =P Good luck! =)

**Comment by meriki** [comment]
@jni Thanks a lot for the guidelines. I read up a little too and I understand git a lot better now :D

**Pull request closed without merging**
