### PR TITLE
try to fix ci which is broken because of pyqt5 last version

### PR DESCRIPTION
**Pull request by emmanuelle**
The CI is broken on Travis, probably following the latest release of pyqt5. ~~I noticed that I could only pip install this pyqt5 release using a recent pip so this PR is an attempt to fix the CI.~~ (edit:didn't work, I just excluded the last version)

### CODE REVIEW

**Comment by emmanuelle** [comment]
I don't really understand why the failing test is failing (seems to be a multithreading issue, can't reproduce locally) so I just excluded the last version

**Comment by hmaarrfk** [comment]
the .0 release will almost surely have hiccups with pyqt ;)

**Comment by jni** [comment]
Thanks @emmanuelle!

**Comment by hmaarrfk** [comment]
thanks a bunch!

**Pull request merged**
