### PR TITLE
Fixed NaN issue in threshold_otsu

### LINKED ISSUE #5496: Wrong threshold value in threshold_otsu when passing a precomputed histogram
## Description

When the histogram has bins with zero counts at the beginning, it returns zero as threshold.

## Way to reproduce
```python
import numpy as np
from skimage.filters import threshold_otsu

x = np.array([1, 2])

>>> threshold_otsu(x)
1
>>> threshold_otsu(hist=np.bincount(x))
0
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) [GCC 9.3.0]
Linux-5.8.0-63-generic-x86_64-with-glibc2.31
scikit-image version: 0.19.0.dev0
numpy version: 1.21.1
```

### PR DESCRIPTION
**Pull request by maurosilber**
Closes #5496.

### CODE REVIEW

**Review by grlee77 — APPROVED** [review]
Thanks @maurosilber!

It seems that this PR protects against invalid results in cases where a histogram either starts or ends with a bin whose count is 0.

I don't think you could encounter this issue if the histogram was created using `skimage.exposure.histogram` (which does [have a code path](https://github.com/scikit-image/scikit-image/blob/b7d0209c2b60edfe5ed1b578441c74daab4652d7/skimage/exposure/exposure.py#L129-L131) based on `np.bincount` that uses a `_bincount_histogram` helper to avoid this case)).

That said, this fix is straightforward and seems desirable for robustness with user-provided histograms.

**Comment by maurosilber** [comment]
Yes, reading the codebase, I realized later that I was supposed to use `skimage.exposure.histogram` instead of `np.bincount`.

Given that it is creating an extra intermediate array (the `where=mask`) for all input, maybe it would be better to check if the histogram starts or ends with 0 (assuming negative counts in the histogram make no sense).

**Review by grlee77 — CHANGES_REQUESTED** [review]
There is one test case involving thresholding of Dask arrays that fails since Dask's `cumsum` doesn't support the where keyword argument.
https://github.com/scikit-image/scikit-image/pull/5497/checks?check_run_id=3225209436#step:5:509

If you did a conditional to only call with the where argument when the start/end value is 0 that would resolve that existing test case as well. Addressing this corner case for Dask arrays would require an alternative solution, but I think that can be left out of this PR for simplicity.

**Comment by maurosilber** [comment]
I undid the orirginal commit, instead modifying the `thresholding._validate_image_histogram` function which is called from `thresholding.threshold_*` functions. I'm checking if the histogram starts or ends with 0, and trimming one or both ends in that case. Now, that function produces the same output in both code paths, either if the image or the histogram is supplied.

**Review by grlee77 — APPROVED** [review]
Great, all tests are passing now.

**Review by rfezzani — APPROVED** [review]
Excellent, thank you @maurosilber :tada:

**Pull request merged**
