### PR TITLE
BUG: io: imread in the PIL plugin drops indexed PNG alpha channel.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
When using the PIL plugin to read an indexed PNG file that has
an alpha channel, the alpha channel would be lost.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Strange.  The new test passes on my system (Mac OS X 10.9.5, Python 2.7.10, numpy 1.10.1,  PIL.PILLOW_VERSION 2.9.0).

I don't think the failure of skimage.io.tests.test_pil.test_multi_page_gif is related to this PR.

**Comment by WarrenWeckesser** [comment]
> I don't think the failure of skimage.io.tests.test_pil.test_multi_page_gif is related to this PR.

On second thought, it probably is related.  I'm looking into it.

**Comment by WarrenWeckesser** [comment]
Getting better... AppVeyor tests pass, and python 2.6 on Travis passes.  The Travis python 3 tests are failing because of a warning building the docs that is treated as an error.  I don't know what's going on there.  The failure in python 2.7 is the new test added in this PR, and, well, I don't know what's going on there, either. :)  It works on my (newly updated) system running 2.7 (Mac OS X, python 2.7.10, numpy 1.10.1, PIL.PILLOW_VERSION **3.0.0**).

**Comment by blink1073** [comment]
Hi @WarrenWeckesser, there is a fix for the documentation failure in https://github.com/scikit-image/scikit-image/pull/1800, you'll have to rebase after that it is merged.

**Comment by WarrenWeckesser** [comment]
@blink1073 Thanks.  I'll wait until the fix in https://github.com/scikit-image/scikit-image/pull/1799 is merged too.

**Comment by JDWarner** [comment]
@WarrenWeckesser Should be good to go now!

**Comment by WarrenWeckesser** [comment]
The Python 3 failures on Travis (`AttributeError: 'figure()' is not a Qt property or a signal`) appear to be unrelated to this PR.  The failure with Python 2.7, on the other hand, is the test from this PR, but I haven't been able to reproduce it (and that test passes in Python 2.6 and in AppVeyor).

**Comment by JDWarner** [comment]
Focus on the 2.7 failure, I've raised the 3.x problem as a separate Issue #1802.

**Comment by WarrenWeckesser** [comment]
How can I determine the versions of all the dependencies that are used on TravisCI?  In particular, which version of Pillow gets installed?

**Comment by JDWarner** [comment]
The build will pull the latest release available except on 2.7, where we test with minimum requirements. The minimum requirements used are found in this file: https://github.com/scikit-image/scikit-image/blob/master/DEPENDS.txt

**Comment by WarrenWeckesser** [comment]
Ah, so the 2.7 tests run with Pillow 1.7.8?  I'll see if I can get that version installed.  (Are there any plans to bump up the minimum version to at least 2.0?)

**Comment by JDWarner** [comment]
@WarrenWeckesser That's my understanding. I don't know of any plans to bump the pillow req, but if there is a compelling reason we'd listen to the argument.

**Comment by WarrenWeckesser** [comment]
I can reproduce the failure when I use Pillow 1.7.8.  I suspect this is a bug in the old Pillow; there are several issues and pull requests related to PNG images with alpha channels from back in 2013, but I haven't figured out which one might be the relevant bug (assuming there is one).

Here's what Pillow does with the test file `'foo3x5x4indexed.png'`. The middle row of pixels are all transparent (check with your favorite image viewer).  `a[:, :, 3]` is the alpha channel of the image, so the middle row of `a[:, :, 3]` should be all 0.    With Pillow 1.7.8, the first two bytes in the second row of `a[:, :, 3]` are 255. 

*Pillow 1.7.8:*

```
In [1]: import numpy as np

In [2]: from PIL import Image

In [3]: im = Image.open('foo3x5x4indexed.png')

In [4]: a = np.array(im.convert('RGBA'))

In [5]: a[:, :, 3]
Out[5]: 
array([[255, 255, 255, 255, 255],
       [255, 255,   0,   0,   0],
       [255, 255, 255, 255, 255]], dtype=uint8)
```

*Pillow 2.1.0, 2.9.0 and 3.0.0:*
```
In [1]: import numpy as np

In [2]: from PIL import Image

In [3]: im = Image.open('foo3x5x4indexed.png')

In [4]: a = np.array(im.convert('RGBA'))

In [5]: a[:, :, 3]
Out[5]: 
array([[255, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0],
       [255, 255, 255, 255, 255]], dtype=uint8)
```

**Comment by stefanv** [comment]
Good detective work!  Let's bump up the minimum to 2.1 then.

**Comment by WarrenWeckesser** [comment]
I tried changing the pillow requirement to 2.1.0, but the build on Python 2.7 failed when it couldn't find that version.  I guess my changes weren't enough to allow it to find a version that isn't in the wheels at http://travis-wheels.scikit-image.org/.  There is a wheel for 2.5.1, so just to make sure it works, I increased the pillow requirement to 2.5.1.  But now the Python 2.7 test on Travis fails while building the docs (`WARNING: duplicate citation R31, other instance in /home/travis/build/scikit-image/scikit-image/doc/source/api/skimage.draw.txt`); I'm not sure it ran the test in this PR before then.

**Comment by WarrenWeckesser** [comment]
In Python 2.7 with Pillow 2.5.1, the test in this PR passes.  The most recent commit is a quick work-around to what appears to be a sphinx problem.  Ultimately the Python 2.7 test suite still fails when it tries to install pyamg.

**Comment by matthew-brett** [comment]
I built Pillow 2.1.0 wheels for the travis-wheels URL ...​

**Comment by WarrenWeckesser** [comment]
@matthew-brett Thanks!

With Pillow 2.1.0, plus a couple temporary tweaks to work around some issues not related to this PR, the tests passed on the Travis Python 2.7 build.

**Comment by stefanv** [comment]
It looks like we're ready to merge this.  Warren, can you back out the unrelated changes?

**Comment by WarrenWeckesser** [comment]
Should I leave in the increase of the minimum version of pillow to 2.1.0?

This PR hasn't passed any python 3 tests.  Wouldn't it be better to get all the unrelated issues officially resolved before merging more PRs?  I'm afraid of an ongoing game of whack-a-mole otherwise.

**Comment by stefanv** [comment]
Upping the version is fine. We'll get those other issues sorted first. Hopefully all of this is done before the release sprint on Thu/Fri!  Thanks very much for your help, Warren.

**Comment by WarrenWeckesser** [comment]
I just pushed a rebased version with only the essential changes.  Have a great sprint!

**Comment by WarrenWeckesser** [comment]
Rebased.  All tests now pass.

**Comment by JDWarner** [comment]
Thanks for sticking with this one, @WarrenWeckesser - much appreciated!

**Pull request merged**
