### PR TITLE
MAINT reorganizing CI-related scripts

### PR DESCRIPTION
**Pull request by NelleV**
We are planning to move the build of the documentation to circle-ci for several reasons. This PR just cleans up a bit our current CI-related scripts to prepare for this migration.

I probably broke a bunch of stuff… This is to be able to run travis.

### CODE REVIEW

**Comment by stefanv** [comment]
@NelleV Do you still plan to remove the `travis` prefix as discussed?

**Comment by NelleV** [comment]
Yep.

**Comment by NelleV** [comment]
@stefanv I think this is good. The remaining failing tests on travis is I believe unrelated to this PR.

The circle-ci scripts are in a separate PR, and thus the build doesn't pass either on this PR.

**Comment by stefanv** [comment]
Thank you, @NelleV!

**Pull request merged**
