### PR TITLE
Skeletonize lift gil

### PR DESCRIPTION
**Pull request by constantinpape**
## Description

- compile `skeletonize_3d` with c++ instead of c
- replace python list with std::vector in `skeletonize_3d`
- lift gil where appropriate
- implement benchmark for `skeletonize_3d`

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](https://scikit-image.org/docs/dev/contribute.html)]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This is really cool, did you add a  `with nogil:`? Otherwise, it won't actually release the GIL, just mark functions as `nogil safe`.

**Comment by constantinpape** [comment]
Oh, I see.
No I didn't add the `with nogil` block because in the main loop `img` is being mutated, which is a python object and thus this might cause issues (I think?!).

I see two workarounds:
- making a copy of `img` and returning this + `with nogil` around the main loop
- or just releasing the gil for the relevant functions inside of the loop.

Let me know what you think is more appropriate.

**Comment by hmaarrfk** [comment]
It is a python object? 

It seems to be a memory view `pixel_type[:, :, ::1] img`. Maybe you can remove the `not None` but I think that should be OK.

Can you paste the error message you get if you put everything in a `with nogil` statement.

**Comment by constantinpape** [comment]
@hmaarrfk 
Looks like you are right. I just added `with nogil` around the main loop and this seems to
work without issues: the code compiles and the tests pass.

**Comment by hmaarrfk** [comment]
Awesome! glad to hear. Yeah i think vector is probably the way to go. But
cython doesn't make it easy, glad somebody wanted to work on this one.

**Comment by hmaarrfk** [comment]
Can you paste a result of the benchmarks you took on this thread? I know it might be slow and inconsistent. To make it faster, you can simplify the matrix in  
https://github.com/scikit-image/scikit-image/blob/master/asv.conf.json#L55

You can pick one version of each library, or just leave them blank i.e. `[ ] `

Then the command

```
asv continuous master skeletonize_lift_gil -b Skeletonize3d
```
should give you a nice report.

**Comment by constantinpape** [comment]
@hmaarrfk 
Here are the benchmark results (only for the later versions of cython, numpy and scipy):

```
· Creating environments........................................
· Discovering benchmarks...
·· Uninstalling from conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10.
·· Building b1a3105d for conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10.............................................................
·· Installing b1a3105d into conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10......
· Running 6 total benchmarks (2 commits * 1 environments * 3 benchmarks)
[  0.00%] · For scikit-image commit d8d36fd3 (round 1/2):
[  0.00%] ·· Building for conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10..............................................................
[  0.00%] ·· Benchmarking conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10
[ 25.00%] ··· Running (benchmark_morphology.Skeletonize3d.time_skeletonize_3d--).
[ 25.00%] · For scikit-image commit b1a3105d (round 1/2):
[ 25.00%] ·· Building for conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10.....
[ 25.00%] ·· Benchmarking conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10
[ 50.00%] ··· Running (benchmark_morphology.Skeletonize3d.time_skeletonize_3d--).
[ 50.00%] · For scikit-image commit b1a3105d (round 2/2):
[ 50.00%] ·· Benchmarking conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10
[ 58.33%] ··· benchmark_morphology.Skeletonize3d.peakmem_reference                                                                                                                                                                                                                                                       73.4M
[ 66.67%] ··· benchmark_morphology.Skeletonize3d.peakmem_skeletonize_3d                                                                                                                                                                                                                                                    74M
[ 75.00%] ··· benchmark_morphology.Skeletonize3d.time_skeletonize_3d                                                                                                                                                                                                                                                 103±0.9ms
[ 75.00%] · For scikit-image commit d8d36fd3 (round 2/2):
[ 75.00%] ·· Building for conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10...
[ 75.00%] ·· Benchmarking conda-py3.6-cython0.28-matplotlib2.2-numpy1.14-scipy1.1-six1.10
[ 83.33%] ··· benchmark_morphology.Skeletonize3d.peakmem_reference                                                                                                                                                                                                                                                       73.4M
[ 91.67%] ··· benchmark_morphology.Skeletonize3d.peakmem_skeletonize_3d                                                                                                                                                                                                                                                  81.1M
[100.00%] ··· benchmark_morphology.Skeletonize3d.time_skeletonize_3d                                                                                                                                                                                                                                                 115±0.3ms
       before           after         ratio
     [d8d36fd3]       [b1a3105d]
-       115±0.3ms        103±0.9ms     0.89  benchmark_morphology.Skeletonize3d.time_skeletonize_3d

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```

**Comment by hmaarrfk** [comment]
nice, C++ lists are faster than python ones!

**Comment by jni** [comment]
@hmaarrfk 

> nice, C++ lists are faster than python ones!

I'm shocked. Shocked! Well, not that shocked.

**Comment by hmaarrfk** [comment]
I was looking at the automatic benchmarks and it seems that this PR might have actually made things much slower on the benchmarked configurations.

http://pandas.pydata.org/speed/scikit-image/#benchmark_morphology.Skeletonize3d.time_skeletonize_3d?cython=0.28&numpy=1.14&scipy=1.1

Maybe newer cython/numpy is better?

**Comment by stefanv** [comment]
Interesting; how does it happen that newer benchmarking code gets run on older versions?

**Comment by hmaarrfk** [comment]
you can run newer benchmarks on older versions with asv. @jni and other configured it a while back.

**Comment by jni** [comment]
Wow. Well spotted @hmaarrfk and, whichever way this ends up being resolved: asv ftw!

I might try to compare pre-and-post benchmarks on my own machine to see if we can come up with a likely culprit (versions, compiler, processor, @constantinpape was lying... =P)

**Pull request merged**
