### PR TITLE
Blacklist pillow 7.1.0, see #4548

### PR DESCRIPTION
**Pull request by sciunto**
## Description

See #4548

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hugovk** [comment]
```
../../venv/lib/python3.7/site-packages/PIL/PngImagePlugin.py:748: in seek
    self._seek(f)
../../venv/lib/python3.7/site-packages/PIL/PngImagePlugin.py:791: in _seek
    cid, pos, length = self.png.read()
E   AttributeError: 'NoneType' object has no attribute 'read'
```

This next error is https://github.com/python-pillow/Pillow/issues/4518, which has a PR https://github.com/python-pillow/Pillow/issues/4518.

Would you be able to do a test build with the branch from https://github.com/python-pillow/Pillow/issues/4518, so we can see a) it fixes this, and b) there's no other regressions?

Thank you!

**Comment by hmaarrfk** [comment]
can you out the link to the issue in the list of dependencies?

**Comment by sciunto** [comment]
Good idea. It's done, And I did it retrospectively for imread I blacklisted last week.

**Comment by sciunto** [comment]
Oops, I did it incorrectly I'm fixing it.

**Comment by emmanuelle** [comment]
In order to fix rapidly the CI, mayve @sciunto you can pin to versions < 7.0 and try in another PR to use the Pillow branch mentioned by @hugovk?

**Comment by hmaarrfk** [comment]
just also blacklist 7.1.1

**Comment by hugovk** [comment]
Yep, `pillow>=4.3.0,!=7.1.0,!=7.1.1` should do it.

**Pull request merged**
