### PR TITLE
Fix computation of the correlation in register.phase_cross_correlation

### LINKED ISSUE #5459: Phase cross correlation is not a phase cross correlation
https://github.com/scikit-image/scikit-image/blob/2bbfce4786102a3a9e85839a52303e858346a08e/skimage/registration/_phase_cross_correlation.py#L118-L288

For this function to compute the phase cross correlation the ```image_product``` should be divided by ```np.abs(image_product)``` line 220. Also the ```overlap_ratio``` is not used (so it doesn't actually work as intended) and thus very confusing.

The phase cross correlation is explained here in detail: https://en.wikipedia.org/wiki/Phase_correlation

### LINKED ISSUE #5460: Phase cross correlation : uncorrect shift in some conditions
Hello,

Here is a simple case that illustrates problems that I meet in a more complicated one.
In some "conditions" (?), the calculated shift is not correct.
In the pseudo 1D example below, I play with 2 parameters:
**length** : which is the length of my trench of my 'profile'
**shift** : which is the shift applied between the 2 'profiles'

with length=20, the calculated shifts are correct in the both cases
with length=10, the calculated shift is not correct in the case of shift=20.

**length** = 10 / **shift** = 15 : **OK**
image

**length** = 10 / **shift** = 20 : **NOK**
image

What the reason of this ?
Thanks

Patrick

```
import numpy as np
import matplotlib.pyplot as plt

from skimage.registration import phase_cross_correlation as cross_correl
from skimage.transform import EuclideanTransform, warp


def test(length, shift):
    img = np.ones((2, 100, 10))
    img[0, 0:40, :] = 0.5
    img[0, 50:50 + length, :] = 0.5
    img[1, 0:40 + shift, :] = 0.5
    img[1, 50 + shift:50 + length + shift, :] = 0.5

    shift_calc = cross_correl(img[0], img[1],
                              upsample_factor=1,
                              overlap_ratio=0.3)[0]

    tform = EuclideanTransform(translation=[-shift_calc[1], -shift_calc[0]])
    img_reg = warp(img[1], tform, mode='edge')

    plt.figure(figsize=(8, 6))
    plt.title(f"target : {shift} / calcul : {-shift_calc[0]}")
    plt.plot(img[0, :, 0], 'b-', label='ref')
    plt.plot(img[1, :, 0], 'k--', label='mov', zorder=10)
    plt.plot(img_reg[:, 0], 'r-', label='reg')
    plt.legend()

# TESTS OK
test(length=20, shift=15)
test(length=20, shift=20)
plt.show()

# TESTS NOT OK
test(length=10, shift=15)
test(length=10, shift=20)    # UNCORRECT CALCULATED SHIFT
plt.show()
```

### PR DESCRIPTION
**Pull request by grlee77**
## Description
closes #5459, closes #5460

#5459 pointed out the need to divide by the magnitude before taking the ifftn of `image_product`. See the two images in my first comment in that issue for a visualization of the difference doing this makes in practice.

I also added epsilon to avoid any potential NaN values due to divide by zero.

@JulesScholler, I added you as a co-author in the first commit. Let me know if you do not want to be listed and I will remove it.

### TODO
- [ ] add test case (perhaps adapt the failing example from #5460 which seems to work after this change, but not before)

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by JulesScholler** [comment]
@grlee77 thanks for adding me as co-author!

**Review by rfezzani — APPROVED** [review]
Thank you @grlee77 :tada:

**Comment by grlee77** [comment]
I have marked this as WIP again, because I came across some more discussion of this in the docs to a function in [DIPlib](https://diplib.org/diplib-docs/analysis.html#dip-FindShift-dip-Image-CL-dip-Image-CL-dip-String-CL-dip-dfloat--dip-UnsignedArray-) where they provide three normalization options. 

What we had prior to this PR is equivalent to `"don't normalize"` in DIPlib, while what is implemented in this PR is called `"phase"` normalization there. There is also a third option there called `"normalize"` where the squared magnitude of the first image is used in the denominator. 

From the DIPlib docs regarding difference between "phase" vs "normalize"

>These two approaches are identical if the only difference between in1 and in2 is a shift, except that "normalize" is computationally cheaper than "phase". If the images are otherwise not identical, then the "phase" method might be the better choice. If there exist strong differences, the non-normalized method can be the best option.


Since it sounds like which is the better option can be scenario dependent, I think we should perhaps add a keyword-only argument with the default set to `normalization=None` for backwards compatibility.

**Comment by rfezzani** [comment]
Good finding @grlee77, I :+1: the addition of the `normalization` parameter.

**Comment by grlee77** [comment]
The only question I have remaining here is if perhaps we should default to `None` for backwards compatibility and start a deprecation cycle for changing the default to `"phase"` in a future release? Given that the older normalization is also used in the literature, I don't know that we can consider this purely a bug fix.

**Comment by alexdesiqueira** [comment]
Thanks @grlee77! I like this one. Are we ready to merge it?

**Comment by grlee77** [comment]
> Thanks @grlee77! I like this one. Are we ready to merge it?

What did you think about introducing a deprecation cycle first as suggested in the prior comment? If we consider it a bug fix it is ready as-is.

**Comment by alexdesiqueira** [comment]
Seeing #5459 and #5460, I'd consider this as a bug fix @grlee77. Thank you! Merging.

**Comment by alexdesiqueira** [comment]
Thank you @JulesScholler as well! Great catch!

**Comment by petsuter** [comment]
Could it be this broke the RMS error return value? #7078

**Pull request merged**
