### PR TITLE
Fix error in contribs.py

### PR DESCRIPTION
**Pull request by hugovk**
## Description

Add a missing `)` to fix a `SyntaxError`.

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Gallery example in `./doc/examples` (new features only)
- [n/a] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [n/a] Unit tests

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by soupault** [comment]
Thanks!

**Comment by jni** [comment]
@soupault why does this need backporting? Actually the script doesn't work at all for point releases because it works on dates, not branches.

**Comment by hugovk** [comment]
There's no syntax error in v0.14:
```
[hugo:/tmp/scikit-image] v0.14.x ± pyflakes doc/release/contribs.py
[hugo:/tmp/scikit-image] v0.14.x ±
```

Master pre-merge:
```
⌂75% [hugo:/tmp/scikit-image] master ± pyflakes doc/release/contribs.py
doc/release/contribs.py:94:11: invalid syntax
    reviews = request(url)
          ^
⌂75% [hugo:/tmp/scikit-image] master 1 ±
```

**Comment by jni** [comment]
Right. I think the earlier changes to this script didn't even make it to v0.14.x. =) I'm gonna go ahead and remove the tags.

**Comment by hmaarrfk** [comment]
@jni this script works for point release if you still need it 

https://github.com/scikit-image/scikit-image/pull/3405

Shameless plug

**Comment by jni** [comment]
@hmaarrfk 🎉 That's excellent, thank you! Will totally use it.

**Pull request merged**
