### PR TITLE
Avoid travis failture regarding scikit.lookfor

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Workaround until #3475 is fixed.

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](https://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by sciunto** [comment]
Regarding 1.: you said that it failed with "0.28.2". I chose to disregard all subversions from 0.28.x.

2. hum, yes, but I'm not on the way to do it shortly.

**Comment by hmaarrfk** [comment]
AFAIK, cython 0.27 is incompatible with python 3.7

**Comment by sciunto** [comment]
But the test suite passes with python 3.7. It's all we need for this temporary patch.

**Comment by hmaarrfk** [comment]
Right, but I have a feeling it is only 0.28.2 that was buggy. 


See https://github.com/scikit-image/scikit-image/pull/3455
that passed with `0.28.5`
https://travis-ci.org/scikit-image/scikit-image/jobs/438951025#L2581

Worth a try with `!=0.29.0`

**Comment by hmaarrfk** [comment]
This is awesome! thanks for looking it to this. It seems that both 0.28.2 and 0.29.0 were buggy! luck is just not on @jni's side 😆

**Comment by jni** [comment]
Note that, except for a stalled build (which I just restarted), `!=0.29.0` actually passed:

https://travis-ci.org/scikit-image/scikit-image/builds/442325025

ditto for AppVeyor:

https://ci.appveyor.com/project/scikit-image/scikit-image/builds/19558108

**Pull request merged**
