### PR TITLE
remove unused dtype argument in IO plugins

### PR DESCRIPTION
**Pull request by sciunto**
## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
My fear here is that some user uses the dtype argument, and we pass it along, and drop it. but by doing this, they get some error instead of silently ignoring their request.

https://github.com/scikit-image/scikit-image/blob/87830b081516b93dcb2e4a883483b4d895232066/skimage/io/_io.py#L57

This might need a deprecation cycle....

**Comment by hmaarrfk** [comment]
Maybe something like 

```patch
diff --git a/skimage/io/_io.py b/skimage/io/_io.py
index f0b60fb75..fcd8a0103 100644
--- a/skimage/io/_io.py
+++ b/skimage/io/_io.py
@@ -58,6 +58,13 @@ def imread(fname, as_gray=False, plugin=None, flatten=None,
         if fname.lower().endswith(('.tiff', '.tif')):
             plugin = 'tifffile'
 
+    if 'dtype' in plugin_args:
+        warn('The dtype argument was always silently ignored. It will be '
+             'removed from scikit-image version 0.17. To avoid this '
+             'warning, do not specify it in your function call.',
+             UserWarning, stacklevel=2)
+        plugin_args.pop('dtype')
+
     with file_or_url_context(fname) as fname:
         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
```

**Comment by sciunto** [comment]
You are right. The deprecation cycle sounds reasonable here. At least, I'll keep this PR so that we can point to it in the TODO list to avoid reinventing the wheel that day.

**Comment by hmaarrfk** [comment]
I doubt anybody is going in and digging into the io modules. Aren't they all supposed to be using the "common interface" we provide?

The 3 lines of code I added enable those that use the common interface we provide to get a nice warning. For those that are using internal functions, well they did so at their own peril.

**Pull request closed without merging**
