### PR TITLE
Include Plausible analytics from Scientific Python in our HTML docs

### PR DESCRIPTION
**Pull request by lagru**
## Description

Scientific Python offered us to use their plausible instance for our website analytics. [Plausible](https://plausible.io) self-describes as

> No cookies and fully compliant with GDPR, CCPA and PECR

and should hopefully gain us some insights into our users in a privacy-friendly manner.

Documentation for the inclusion in our theme can be found here: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/analytics.html

I am not yet sure how and who will be able to access the reports at https://views.scientific-python.org but @stefanv would know more.

After adding this we could also think about adding it to our main page and possibly shoehorn into our old HTML docs. Not sure if the latter is worth it though. I am mainly interested in which part of our documentation get accessed most or least.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
...
```

### CODE REVIEW

**Comment by mkcor** [comment]
Good idea, @lagru! My understanding is that {we'll get analytics for / our HTML docs consist in} everything under https://scikit-image.org/ except for the landing page itself and the [Community page](https://scikit-image.org/community_guidelines.html). Correct?

Not sure it's worth collecting analytics for the old HTML docs (i.e., before #6714).

I've edited your PR description to include a release note.

**Review by mkcor — APPROVED** [review]

**Comment by lagru** [comment]
Correct, this only includes in HTML pages that are build by Sphinx.

> I've edited your PR description to include a release note.

I intentionally left that section empty so that changelist will fall back to the PR title, which I find expressive enough in this case. Just in case you were not aware of this behavior.

**Comment by mkcor** [comment]
> Correct, this only includes in HTML pages that are build by Sphinx.

Thanks. It's probably enough (at least for a start).

> I intentionally left that section empty so that changelist will fall back to the PR title. Just in case you were not aware of this behavior.

Oh! That explains all these empty fields... I wasn't aware of this (sensible) default behaviour, indeed. I just removed my addition (got confused with the multiple "```" though, hope I didn't break anything for the parser!). Thanks for telling me.

**Review by soupault — APPROVED** [review]
This kind of analytics looks very promising to me, as long as it is safe for the users. Let us try and see whether we can learn anything actionable.

**Review by jarrodmillman — APPROVED** [review]
LGTM. @stefanv may need to update some things on the scientific python end, if he hasn't already.

**Comment by stefanv** [comment]
I've added @lagru as administrator on our portal, and he is able to add anyone else on the team who might be interested.

**Comment by lagru** [comment]
@mkcor and me have access to the plausible instance now. Let us know if you would like to have access as well.

**Pull request merged**
