### PR TITLE
Do not try and upgrade other large dependencies on pip install

### PR DESCRIPTION
**Pull request by blink1073**
Installing or upgrading scikit-image should not try to upgrade libraries with large external dependencies.
Scipy takes the same stance with numpy.

### CODE REVIEW

**Comment by blink1073** [comment]
We have seen this problem when someone tries `pip install -U scikit-image` and scipy starts to try and upgrade itself.

**Comment by matthew-brett** [comment]
Not disagreeing, but it is a worry that a scikit image source install will have different behavior from a wheel install in this respect?  Or that it will behave differently from other packages?

**Comment by blink1073** [comment]
This is addressing a shortcoming in `pip install -U`, where it will recursively upgrade all dependencies even if the minimum version is satisfied.  While unexpected, I think that is an *okay* behavior for packages that are python-only, but given the fact that wheels are broken and not allowed on PyPI for linux, it is not tractable for `scipy` and friends.

**Comment by JDWarner** [comment]
IMO `pip` shouldn't do this in any case. It hinders reproducibility. When trying to recreate a specific stack, e.g., from a manuscript, unasked-for and unnecessary upgrades happening elsewhere is borderline broken behavior. Only necessary upgrades should be triggered.

**Comment by stefanv** [comment]
It is terrible default behaviour indeed.  I know this may not be maximally consistent, but I think it's a move in the right direction.

**Comment by matthew-brett** [comment]
Sorry to be the questioner here, and I think this probably is a good idea - but the question is whether we are likely to get people confused by different behavior in apparently similar circumstances.   I can certainly see the argument that the confusion is a lot less worrying than the astonishment and annoyance that pip causes while unnecessarily trying to upgrade scipy from source on Linux.

**Comment by stefanv** [comment]
Alternative question: how, otherwise, can you upgrade scikit-image
without touching scipy?

**Comment by JDWarner** [comment]
* conda (maybe, some builds are linked above their true requirements but often possible)
* checkout, clean, and build the package inplace with the repo on your PYTHONPATH

I honestly don't know any other ways.

**Comment by rgommers** [comment]
@stefanv you have to know the magic pip command: ``pip install -U --no-deps scikit-image``.

There's a reason that this gets a load of +1's: https://github.com/pypa/pip/issues/59

**Comment by JDWarner** [comment]
@rgommers while technically `--no-deps` satisfies @stefanv's question (without touching scipy), this remains a poor solution. No new dependencies get installed, and dependencies with version bumps aren't minimally upgraded. 

The pip docs recommend

``` bash
pip install --upgrade --no-deps packagename
pip install packagename
```

which addresses new dependencies in the second line, but will not upgrade existing ones to the next required version (e.g., when we recently bumped Cython from 0.17 to 0.21). Also - ridiculously cumbersome!

(pypa/pip#59 is the real solution, no idea how this behavior wasn't fixed years ago)

**Comment by rgommers** [comment]
@JDWarner thanks for the correction. Fully agree that the situation is a bit ridiculous.

**Comment by stefanv** [comment]
I'm merging this for now: it seems like the choice is between a bad and a terrible one.

**Comment by blink1073** [comment]
Yesss! The best kind of PR....

**Pull request merged**
