### PR TITLE
[MRG+1] Add community guidelines to doc navigation

### PR DESCRIPTION
**Pull request by stefanv**
Closes https://github.com/scikit-image/scikit-image-web/issues/38

### CODE REVIEW

**Comment by ahojnnes** [comment]
This is going to break the navigation, just like on the webpage...

**Comment by stefanv** [comment]
It doesn't break anything, it just renders it on the next line.  I'll move the search box down.

**Comment by ahojnnes** [comment]
Well, I guess, that's a matter of how you define "break". It surely breaks the layout/design.

**Comment by stefanv** [comment]
Done.

**Comment by ahojnnes** [comment]
LGTM, thanks!

**Comment by soupault** [comment]
Very nice! Thanks @stefanv!

**Pull request merged**
