### PR TITLE
MNT: multiprocessing should always be avaible since we depend on python >2.7

### PR DESCRIPTION
**Pull request by hmaarrfk**
## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
MINIMUM_REQUIREMENTS build is failing due to https://github.com/scikit-image/scikit-image/pull/3432

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.14.x

**Comment by jni** [comment]
@hmaarrfk not a huge deal, but my feeling is that backporting "code cleanup" PRs like this one is unnecessary.

**Comment by hmaarrfk** [comment]
yeah, totally agree!

**Pull request merged**
