### PR TITLE
Fix some remaining TODO items

### PR DESCRIPTION
**Pull request by ahojnnes**

### CODE REVIEW

**Comment by jni** [comment]
@ahojnnes Thanks! Some nice API cleanups coming good! =)

**Comment by stefanv** [comment]
@jni What happened to the 2x :+1: policy :)

**Comment by OrkoHunter** [comment]
@stefanv This was bugging me too ! If a core team member has sent a PR, that means he's already +1 to it. So, the next core dev is the second thumbs up guy. But, I guess you are eliminating the PR author from the right to give thumbs up. ;)

**Comment by stefanv** [comment]
@OrkoHunter Yes, in this case the PR is pretty straightforward and I was just teasing Juan, but I think the second assessment of "at least two reviewers" is what we'll be going for.

**Comment by jni** [comment]
@stefanv slipped my mind! I agree that I should have just :+1:d it. I wish github offered real support for such policies...

**Comment by stefanv** [comment]
:+1:  And... https://github.com/dear-github/dear-github

**Comment by stefanv** [comment]
@carreau and @matthew-brett are interested in extending Homu to support just this kind of thing.

**Comment by vighneshbirodkar** [comment]
For the +1s, can't someone create a website that will offer +1 badges ?

**Comment by Carreau** [comment]
> For the +1s, can't someone create a website that will offer +1 badges ?

Install https://www.zenhub.io/ extension, and you get a +1 button people can click that show the count. 

> @carreau and @matthew-brett are interested in extending Homu to support just this kind of thing.

Yes, if you fork Homu, I'm interested, in particular the jupyter team have some local scrip to backport a PR from one branch to another and migrate issues from one repo to another. 

I'd like to be able to `@homu migrate-to foo/bar`, or `@homu backport-to 4.2`.

**Pull request merged**
