### PR TITLE
specify python version used by mybinder.org for gallery demos

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This is an attempt to address #6136 by getting binder to use Python 3.9 rather than its default choice of 3.7 (we recently dropped Python 3.7 on the `main` dev branch).

Adding `runtime.txt` is based on the following docs: 
https://mybinder.readthedocs.io/en/latest/config_files.html#runtime-txt-specifying-runtimes
and the location in `.binder` is mentioned here:
https://mybinder.readthedocs.io/en/latest/config_files.html#configuration-files

not sure how to test this other than just merging this PR and seeing if it works?

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by hmaarrfk — APPROVED** [review]

**Comment by hmaarrfk** [comment]
i would just merge. setting up binder on your own fork seems tedious.

**Comment by hmaarrfk** [comment]
this should also be backpoeted.

**Comment by grlee77** [comment]
Okay, it is working now for the dev docs. I just tried running [this demo](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_log_gamma.html#sphx-glr-auto-examples-color-exposure-plot-log-gamma-py)) and it works. On the initial run it took a while to generate wheels, etc. before launching, but on repeated launch it was faster.

> this should also be backpoeted.

We could, but I'm not sure it is necessary? We still support Python 3.7 for v0.19.x

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.19.x

**Pull request merged**
