### PR TITLE
Practical guide to reading video files

### PR DESCRIPTION
**Pull request by danielballan**
Here is a start on the documentation requested by @stefanv in #850.

It needs better links, both external and to other sections of the documentation within scikit-image. I made no attempt to get the sphinx right yet. This is just a draft.

Also, this is opinionated, but I attempt to show each project's strengths and shortcomings. As discussed in #850, I do not believe an optimal solution exists yet. Once this is ready to merge I will solicit the input of the creators of various projects I mention. I hope they will feel that I give each project a fair, if brief, treatment here.

Is this on the right track?

### CODE REVIEW

**Comment by groakat** [comment]
I have worked a lot with video in the last months and I would have some suggestions. 

- working with video is tricky (codecs are a real mess) and *nothing* should be assumed to be working correctly. Everything needs to be tested, if possible with a video in which each frame is identifiable. A way to get such a video is with the following bash script:

::

    #!/bin/bash
    
    # Use imagemagick to generate an image sequence containing numbers 0..999
    for i in $(seq -f "%05g" 0 999)
    do
            convert -size 51x18 -pointsize 16 -font /usr/share/fonts/truetype/freefont/FreeMono.ttf label:$i $i.png
    done

    # Use ffmpeg to create a video from the image sequence:
    ffmpeg -y -f image2 -r 30 -i "%05d.png" -r 30 test.avi 

- Problems I noticed in particular are:
    - frame accurate seek
    - missing frames at the beginning or end of the video stream

I dont know how openCV deals with this issues now, but some time ago the seek in particular was unreliable. Test it before using it!

A good ffmpeg wrapper I found and used for some time is `ffvideo` (https://bitbucket.org/zakhar/ffvideo/). Even this is a good wrapper it had some issues with accurate seek, reading the first or last frames (depending on the codec), and performance within threads. I forked it and reimplemented the decoding part following the ffmpeg tutorial. I would highly appreciate if people would test my version and improve/use it. The author of the original version seems to have abandoned his project. I am happy to manage further bugfixing if needed and try again to send him a pull request once I am  sure my version does not break something I have overlooked.

You can find my fork on https://bitbucket.org/groakat/ffvideo . I will also put it up on `conda` together with the `ffmpeg` dependencies win64, osx and linux in the next couple of days. Especially for unexperienced users, installing ffmpeg and sorts can be quite painful. With `conda` the installation becomes really easy.

**Comment by danielballan** [comment]
Great! I sunk a couple days into working on a cross-platform FFmpeg conda package, with eyes toward making PyAV conda-installable on all platforms as well, but I haven't got it all working yet. I'd be really pleased to test your conda packages and to help spread the word.

**Comment by danielballan** [comment]
@groakat Have you pushed your cross-platform FFmpeg conda recipe anywhere public?

**Comment by stefanv** [comment]
Any update on this?

**Comment by danielballan** [comment]
Good news: I built and uploaded conda packages of PyAV, the package with Cython bindings to FFmpeg. On OSX and Linux, we now have a conda-installable way to read and write video files. Windows support [has been demonstrated](https://github.com/mikeboers/PyAV/pull/84) and conda packages for Windows might not be far off.

Packages for OSX and 64-bit Linux (py27, py33, py34) are on [my binstar](https://binstar.org/danielballan/pyav). The recipes are in conda/conda-recipes#289. Thanks @tacaswell for helping me finish this long-running packaging nightmare. :- )

I will update our remarks about PyAV in this PR in the next day or two.

**Comment by stefanv** [comment]
Thanks for the update, and for your work on that packages!  Have you tried imageio at all?

http://imageio.github.io/

**Comment by danielballan** [comment]
Yes. Like MoviePy, matplotlib, and several others, it invokes FFmpeg through a subprocess and reads data over a pipe. I found that approach to be unstable for large files, and implementing random access is difficult. I think PyAV's approach is generally better -- with the big caveat that it's much harder to install because it has to link against FFmpeg's libraries. Maybe once we have Windows conda packages, ImageIO can support both the MoviePy way and the PyAV way.

**Comment by matthew-brett** [comment]
I put OSX binary wheels for PyAV up on http://wheels.scipy.org for those of us using vanilla Pythons such as Python.org Python, system Python, homebrew, macports:

Example install command:

```
pip install -f http://wheels.scipy.org av
```

Me installing into a virtualenv:

```
$ mkvirtualenv av-test
New python executable in av-test/bin/python
Installing setuptools, pip...done.
(av-test)$ pip install -f http://wheels.scipy.org av
Collecting av
  This repository located at wheels.scipy.org is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host wheels.scipy.org'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Downloading http://wheels.scipy.org/av-0.2.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (6.7MB)
    100% |████████████████████████████████| 6.7MB 1.3MB/s 
Installing collected packages: av
Successfully installed av-0.2.2
(av-test)$ python -c 'import av'
(av-test)$
```

**Comment by danielballan** [comment]
@matthew-brett Neat! I have never used wheels -- I went straight from pip to conda -- so I have an ignorant question: does the wheel include FFmpeg? Can it?

**Comment by matthew-brett** [comment]
Yes, the wheel includes ffmpeg.  Here's the repo that does the build:

https://github.com/MacPython/PyAV-wheels

It works the same way as the matplotlib wheel builds - the repo builds the library dependencies that OSX does not have by default, then uses the [delocate](https://pypi.python.org/pypi/delocate/0.3.0) utility to copy the required libraries into the package directory tree, and relink them.

I don't use conda myself because it seems unwise to make conda / Anaconda the only standard way of installing on OSX, but luckily for me, pip and virtualenvs are a pleasure to use on OSX now, because all the packages I install regularly have wheels.

**Comment by matthew-brett** [comment]
I opened an issue for the automated wheel building on PyAV : https://github.com/mikeboers/PyAV/issues/89

**Comment by danielballan** [comment]
Thanks for explaining. This is great! The more working solutions, the better!

**Comment by stefanv** [comment]
Matthew, this is excellent. Is there any progress on a delocate for Linux?

**Comment by stefanv** [comment]
Daniel, are we about ready to merge here?

**Comment by matthew-brett** [comment]
No, no progress on a delocate for Linux I'm afraid.

I get so busy...

If someone would like to help, I will try and carve out more time.

**Comment by danielballan** [comment]
@stefanv I just pushed an update with more details and new links to build recipes and benchmarks. I also included brief installation instructions for each package, since packaging difficult are a major consideration here.

**Comment by danielballan** [comment]
With one more review, this should be ready to go.

**Comment by stefanv** [comment]
Thanks @danielballan, this looks great.  Some failures in building the docs, but as soon as those are fixed we can merge.

**Comment by danielballan** [comment]
Travis is happy. Appveyor looks like it's failing on an unrelated issue with scipy.

**Comment by stefanv** [comment]
Thank you very much for this excellent guide @danielballan; merged in 448230def636258a8be242c56536623dc34b2c37

**Comment by soupault** [comment]
@stefanv see https://travis-ci.org/scikit-image/scikit-image/jobs/211736423:
```
Warning, treated as error:
/home/travis/build/scikit-image/scikit-image/doc/source/user_guide.rst:4: WARNING: toctree contains reference to nonexisting document u'user_guide/video'
make[1]: *** [html] Error 1
make[1]: Leaving directory `/home/travis/build/scikit-image/scikit-image/doc'
make: *** [html] Error 2
```

**Comment by soupault** [comment]
^ Should be fixed with https://github.com/scikit-image/scikit-image/commit/c1d53202b5d7d655c89fd918bd4b285b60ab318a.

**Comment by danielballan** [comment]
Thanks for the fixup, @soupault.

**Comment by soupault** [comment]
@danielballan not at all.
By the way, I've recently come across http://www.scikit-video.org/stable/ . Maybe we should add it also.

**Comment by sciunto** [comment]
+1. It's extremely valuable to have a page summarizing the shooting range of the different libraries.

**Pull request closed without merging**
