### PR TITLE
Delay matplotlib import in skimage/future/manual_segmentation.py

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
## Description
Bugfix for missing matplotlib import error in `skimage.future.manual_segmentation.py`.

Currently if you try to run the docstring examples from the `manual_polygon_segmentaion` or `manual_lasso_segmentation` functions, this error is produced (also verified independently by @jni):
```
File '...\scikit-image\skimage\future\manual_segmentation.py", line 92, in manual_polygon_segmentation
    undo_button = matplotlib.widgets.Button(undo_pos, u'\u27F2')
NameError: name 'matplotlib' is not defined
```

It seems that as part of the larger effort to remove matplotlib as a dependency (https://github.com/scikit-image/scikit-image/pull/3129), the line `import matplotlib` inadvertently got dropped in PR https://github.com/scikit-image/scikit-image/pull/3533, commit https://github.com/scikit-image/scikit-image/commit/fb81456bf527f93ec0ad7a968b02de6eba0ad8cb. It's necessary for the undo buttons, but flew under the radar because pytest skips these docstring examples.

@hmaarrfk 
Mark, is this the right place to add that line back in, or should it go next to the `import matplotlib.pyplot as plt` lines inside the manual segmentation functions? You've spent a lot more time thinking about how to handle this.

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](https://scikit-image.org/docs/dev/contribute.html)]

## References
PR https://github.com/scikit-image/scikit-image/pull/3533, commit https://github.com/scikit-image/scikit-image/commit/fb81456bf527f93ec0ad7a968b02de6eba0ad8cb

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
btw I think this is the right place for this import. `import matplotlib` does not set the backend, which I believe was the whole problem that #3533 was trying to solve.

**Comment by hmaarrfk** [comment]
sorry for the delay, many PRs were comming through and I didn't have a chance to see it.


I think jni is right that this doesn't set the backend.

https://github.com/scikit-image/scikit-image/pull/3129 needs a good push forward.

**Comment by hmaarrfk** [comment]
honestly, can we place this inside the function that needs it.

I'm not sure there is enough bandwidth to completely remove matplotlib as a dependency, but at least delaying importing can allow downstream developer to "not install matplotlib" and scikit-image would still work (but the tests would fail).

**Comment by GenevieveBuckley** [comment]
@hmaarrfk - do I understand correctly, you would like to delay importing all the matplotlib imports currently at the top of the manual_segmentation.py file?

```
import matplotlib
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
```

**Comment by hmaarrfk** [comment]
yeah, that is effectively the last change needed to move away from a hard dependency on matplotlib.

at that point matplotlib would only be a "testing" dependency (and for polyclip).

but please just take this as a suggestion. my main gripe with matplotlib is more that I don't want it in my ci tests.

**Comment by jni** [comment]
Woot! @scikit-image/core still waiting for another review...

**Comment by GenevieveBuckley** [comment]
Thanks @soupault - I've updated with the change you suggest.

**Pull request merged**
