### PR TITLE
MNT: Convert links using http to https

### PR DESCRIPTION
**Pull request by hmaarrfk**
Harden some known links with https

I had a check a few of the ones in later commits.

I got bored so there are still ~50 links with http that could be converted to https today.

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by emmanuelle** [comment]
Hi @hmaarrfk could you please explain the interest of using https for these links? Thanks!

**Comment by hmaarrfk** [comment]
Generally http allows the links too the intercepted.

Webpages will typically redirect you to the "secure" page, but that is only after you've made an insecure connection, which almost defeats the purpose.

Google will actually start labelling pages as insecure soon if they dont use https

**Comment by hmaarrfk** [comment]
Here goes nothing

@meeseeksdev backport to v0.14.x

**Comment by hmaarrfk** [comment]
Yeah... this PR is too big to get backported. No hope. I'm generally not worried, but it is good practice to migrate to https, so this PR going into 0.15 is good enough for me.

**Pull request merged**
