### PR TITLE
3D test for register_translation, as required by TODO.txt

### PR DESCRIPTION
**Pull request by emmanuelle**
The 3D phantom data was added a while ago as ``data.binary_blobs``

### CODE REVIEW

**Comment by jni** [comment]
:+1: from me!

**Comment by emmanuelle** [comment]
Thanks @jni! We still need one :-)

**Comment by jni** [comment]
@stefanv @ahojnnes @JDWarner somebody merge this already! =D

**Comment by JDWarner** [comment]
LGTM, thanks @emmanuelle!

**Pull request merged**
