### PR TITLE
Remove fancy language from 0.15 release notes

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
didn't this already get released?

**Comment by stefanv** [comment]
It did get tagged and released, but the website + tweet points here.

**Comment by matthew-brett** [comment]
Then again : https://www.joelonsoftware.com/2005/07/25/hitting-the-high-notes/ - see the Winamp section.

**Comment by stefanv** [comment]
Yes, like I told Juan in an offline discussion, I'm not against humor or informal announcements, but getting it right is hard. The failure mode of humor is not great, so in the face of that risk, I tend to err on the safe side.

**Comment by jni** [comment]
@matthew-brett 

> see the Winamp section

Wait, did you just call @stefanv an AOL Time Warner Corporate Weeniehead? 😂

**Comment by matthew-brett** [comment]
Oops - busted! :)

**Comment by stefanv** [comment]
pointy haired boss

**Comment by stefanv** [comment]
youre-welcome-now-get-back-to-work

**Pull request merged**
