### PR TITLE
Fix compilation error in XCode 12

### LINKED ISSUE #5051: pip install error: implicit declaration of function 'unwrap2D' is invalid in C99
## Description
I'm getting an installation error on MacOS using pip

## Way to reproduce
```python
pip install scikit-image
```

## Version information
```python
# Paste the output of the following python commands
3.9.0 (default, Oct 27 2020, 14:15:17) 
[Clang 12.0.0 (clang-1200.0.32.21)]
macOS-10.15.7-x86_64-i386-64bit
numpy version: 1.19.4
```

skimage/restoration/_unwrap_2d.c:2285:9: error: implicit declaration of function 'unwrap2D' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

See the attached log file the for the full dump:
[scikit_install_log.txt](https://github.com/scikit-image/scikit-image/files/5492160/scikit_install_log.txt)

### PR DESCRIPTION
**Pull request by jni**
## Description

Closes #5051 

@david-a-joy thank you for the fix! Could you check that this branch compiles as-is?

Does anyone have suggestions for how we can test this? Is there a flag we can pass to our older compilers to make them error out on the missing declarations?

At any rate even without a test I think we should merge this, since we have seen many people hitting this issue.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by hmaarrfk — APPROVED** [review]

**Comment by jni** [comment]
The `--pre` failures are addressed in #5103

**Comment by david-a-joy** [comment]
Oops, looks like we also need to include the new headers in the relevant cython files:
 
"_unwrap_2d.pyx":
> cdef extern from "unwrap_2d_ljmu.h":
>      void unwrap2D(double* wrapped_image,
>                    double* unwrapped_image,
>                    unsigned char* input_mask,

"_unwrap_3d.pyx":
> cdef extern from "unwrap_3d_ljmu.h":
>    void unwrap3D(double* wrapped_volume,
>                  double* unwrapped_volume,
>                  unsigned char* input_mask,

With that, everything compiles successfully on cython 0.29.21 and cython 3.0a6 (Mac OS Catalina, Python 3.9.0, clang 12.0.0). I get what I think are unrelated test failures ([errors_cython0-29.txt](https://github.com/scikit-image/scikit-image/files/5647643/errors_cython0-29.txt)), but everything in the restoration module passes.

---

As far as testing, both clang and gcc should take "-std=c99" flag that should reproduce the failure (no idea about msvc, a quick google suggests maybe not?). I tried to naively add that switch to extra_compile_args in "setup.py" but it breaks when compiling stuff with clang++ so I think something fancier is needed.

**Comment by jni** [comment]
Thanks @david-a-joy! For some reason I'm having trouble getting my local compilation working for unrelated reasons, so I haven't been able to test it out. 😬

**Comment by emmanuelle** [comment]
@david-a-joy any idea of why the compilation fails on all jobs?

**Comment by david-a-joy** [comment]
I think the cdefs got added to the wrong files? They go in the Cython "_unwrap_2d.pyx" and "_unwrap_3d.pyx" files not in the C "unwrap_2d_ljmu.c" and "unwrap_3d_ljmu.c" files...

**Comment by emmanuelle** [comment]
Thanks @david-a-joy ! So should the cdefs replace the existing blocks like

```python
cdef extern from *:
    void unwrap2D(double* wrapped_image,
                  double* unwrapped_image,
                  unsigned char* input_mask,
                  int image_width, int image_height,
                  int wrap_around_x, int wrap_around_y,
                  char use_seed, unsigned int seed) nogil
```

or should they be added to the file, leaving the existing ones?

**Comment by david-a-joy** [comment]
They should replace them. The old line 

> cdef extern from *:

means that the functions are assumed to be defined in a header already included elsewhere (say if there was a "skimage.h" that had the headers for all c functions used by scikit-image). We don't have that, so cython needs to be pointed to the header files explicitly, i.e:

> cdef extern from "unwrap_2d_ljmu.h":

I don't know what happens if you try to do two cdef extern blocks that define the same function, but my guess is that it will make cython mad.

**Comment by emmanuelle** [comment]
Thanks a lot for your help @david-a-joy ! I'm trying to get this PR to the finish line while Australia sleeps, so that Juan can concentrate on other things for the release :-).

**Comment by jni** [comment]
Awesome, thanks @emmanuelle for picking up the slack! If anyone else from @scikit-image/core could merge this (failure is what @emmanuelle fixed in #5109), it would be much appreciated! 🙏

**Comment by grlee77** [comment]
Looks good. Thanks!

**Pull request merged**
