### PR TITLE
Updated Documentation of adapt_rgb.py

### PR DESCRIPTION
**Pull request by Ganesh2409**
## Description

Updated Documentation of adapt_rgb.py by adding more information in docstring

Fixes:#7270

* I have added the "image" parameter as an array and highlighted the additional arguments (*args, **kwargs) that can be passed to the underlying image filter function into Docstring

* The docstring now explains that if the image is RGB-like, the apply_to_rgb function is used to apply the filter. Otherwise, the image filter is applied directly.

### CODE REVIEW

**Comment by lagru** [comment]
@Ganesh2409, welcome and thanks for giving this a shot! Could you take a look at the indent level of the added docstrings. They are tripping up the tests..

**Comment by Ganesh2409** [comment]
Thanks for ur suggestion ....! I am new to open source contribution please guide me through this ...... :)

**Comment by Ganesh2409** [comment]
* Actually I encountered the indentation error u have specified still my checks have been failing 
* 
` def decorator(image_filter):
        """
    Decorator to adapt an image filter function for both RGB-like and non-RGB-like images.

    Parameters
    ----------
    image_filter : function
        Function that filters an image.

    Returns
    -------
    image_filter_adapted : function
    """
        @functools.wraps(image_filter)
        def image_filter_adapted(image, *args, **kwargs):
            """Adapted image filter function to handle both RGB-like and non-RGB-like images.

            Parameters
            ----------
            image : array
                Input image. The format should be checked using the `is_rgb_like` function.

            *args, **kwargs : additional arguments
                Additional arguments to be passed to the underlying image filter function.

            Returns
            -------
            filtered_image : array
                Filtered image obtained by applying the image filter function.
                """
            if is_rgb_like(image):
                return apply_to_rgb(image_filter, image, *args, **kwargs)
            else:
                return image_filter(image, *args, **kwargs)

        return image_filter_adapted

    return decorator`

**Comment by lagru** [comment]
In cases like this its often useful to take a look at other parts of the library and see how docstrings are formatted there. I've edited your comment above so that the docstring should be formatted accordingly. 

Also please have a look at our [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html). I noticed that you created your PR from your `main` branch. That can lead to future problems (see [Don’t Start Pull Requests from Your Main Branch](https://hynek.me/articles/pull-requests-branch/)) so it's best to use feature branches. 

However in this case, feel welcome to reopen this PR and give it a shot. ;)

**Comment by Ganesh2409** [comment]
@lagru  i need ur assistance sir please .. :) 
Screenshot 2023-12-24 204924

**Pull request closed without merging**
