### PR TITLE
Make all of the pip installs quiet to fit in 10000 lines

### PR DESCRIPTION
**Pull request by blink1073**
This way we do not have to view the raw log.

### CODE REVIEW

**Comment by jni** [comment]
D'oh! Still over. (At least on 3.4.) Thanks for this — a much needed goal. Happy to merge this now or do you want to keep hacking at the problem on this branch?

**Comment by blink1073** [comment]
Fixed!  This is good to go.

**Comment by jni** [comment]
Woooowwwwww! Thanks @blink1073!

**Comment by stefanv** [comment]
I wonder if something like this would help: https://github.com/stefanv/scikit-image/blob/drone/tools/drone_script.sh#L12

**Pull request merged**
