### PR TITLE
Handle Sphinx 1.3 API change

### PR DESCRIPTION
**Pull request by blink1073**
Sphinx changed `cfg.source_suffix` to be a list in version 1.3.
We were using it as a string. 
First, I tried just changing `cfg.source_suffix` to a string if it was a list, but that affected other parts of the build.  Instead, we create a new `cfg.source_suffix_str` and use that, so we can support all versions of Sphinx.

### CODE REVIEW

**Comment by blink1073** [comment]
@jni, you may just want to take these two lines and add them to #1416.

**Comment by jni** [comment]
@blink1073 when and if this passes and gets merged (=P), I'll rebase... I like to keep PRs small and self-contained...

**Comment by blink1073** [comment]
Why sphinx why?!?!?

**Comment by tacaswell** [comment]
mpl is also having issues.  We have pinned to 1.2.3 for now...

cc @jenshnielsen

**Comment by blink1073** [comment]
@scikit-image/core, someone please merge this as it is holding up all open PRs.

**Comment by JDWarner** [comment]
Travis is happy, AppVeyor is still queued 4 hours later. I realize it's a free service and resources are limited, but that kind of delay is borderline unusable.

Thanks for the fix @blink1073 - I'm merging this. If Windows ends up having a problem we can deal with that separately.

**Pull request merged**
