### PR TITLE
BUG: make resize with order=0 more robust to floating-point rounding

### PR DESCRIPTION
**Pull request by grlee77**
## Description

As reported in gh-2629, which neighbor is judged to be nearest is currently dependent on
whether numpy was built with MKL or OpenBLAS.  By shifting coordinates by ~100 times machine
epsilon when order=0, this inconsistency can be avoided.  

The amount of shift was determined empirically as one which gives the same result across MKL and OpenBLAS numpy builds (as tested in parallel conda environments).

I'm not sure there is a good way to properly test this fix across BLAS builds, but I did add a test verifying that for the specific example of gh-2629, the transform gives the same result for both the 2D and n-dimensional code paths.

### CODE REVIEW

**Comment by grlee77** [comment]
not sure what is causing the Travis failures.  they don't seem related to this PR.  e.g.
```
/home/travis/build/scikit-image/scikit-image/doc/examples/features_detection/plot_orb.py failed to execute correctly:

**Comment by soupault** [comment]
Seems acceptable to me.

@mcquin Could you verify this fix?

**Comment by mcquin** [comment]
I don't have access to those computers until next week. I'll verify first
thing on Monday.

**Comment by ahojnnes** [comment]
Have you tested this for larger images as well? Something with several thousand pixels and/or larger scaling factors.

**Comment by grlee77** [comment]
>> Have you tested this for larger images as well? Something with several thousand pixels and/or larger scaling factors.

Not yet, but I will try it.  Trying to account for these type of cases are why I had bumped up the offset to a much larger value than the minimum required for the specific example raised in #2629 in my second commit.

**Comment by ahojnnes** [comment]
Since this is a rather critical fix that seems brittle wrt. the dimensions of the image, I suggest to do further experiments here regarding different image sizes?

**Comment by mcquin** [comment]
Hey @grlee77, with this change I get [this result](https://cloud.githubusercontent.com/assets/4721755/25248776/80115744-25dd-11e7-9d67-e62a1e10c4ea.png) on OS X and Ubuntu 16.04.

**Comment by grlee77** [comment]
please do not merge yet.  Despite the apparent consistency with this toy example, in initial testing with larger sizes and scale factors I do not seem to always get identical results.

**Comment by grlee77** [comment]
in the toy example
---------------------
Python 2.7, This patch gives consistent results across two different numpy builds.  There are a total of two unique results over two numpy builds and two branches of scikit-image.
master, numpy (defaults) : result 1
master, numpy (conda-forge) : result 2
this PR, numpy (defaults) : result 2
this PR, numpy (conda-forge) : result 2
It is also the case that this result (arbitrarily labeled "result 2" here) exactly matches one of the results from the master branch.

In a larger example  
----------------------
randomized labels generated as:
```python
sz = (32, 16384)
labels = np.random.rand(*sz)*4
labels = labels.astype(np.int)
```
results of resizing are saved out to `.npy` files, the numpy build or skimage branch is changed and then comparison to the previously saved results is done by loading the previously output from the other build.

master, numpy (defaults) : result 1
master, numpy (conda-forge) : result 2
this PR, numpy (defaults) : result 3
this PR, numpy (conda-forge) : result 3

So, with this PR, the result becomes consistent across numpy builds, however, unlike for the toy example **the result for this branch is not identical to the result from the master branch** for either numpy build.  I suppose if the current behavior in master is considered a bug due to susceptibility to rounding error then this is not a problem in terms of backwards compatibliity.  

consistency across numpy builds was also verified for other extreme reshape cases such as (32, 32) reshaped to (32, 100001), etc.

**Comment by grlee77** [comment]
@ahojnnes
This patch seems to improve consistency even for larger test cases, but as discussed in the comment above, may result in slightly different output than current master for some inputs.

Note that the coordinate shifts are only applied when `order == 0`, so this will not cause in change in behaviour for the default (`order=1`) interpolation.

**Comment by jni** [comment]
Hi @grlee77 et al!

Although I very much appreciate the effort that's gone into this PR and all the testing in #2629, I most agree with @mcquin's comment [here](https://github.com/scikit-image/scikit-image/issues/2629#issuecomment-296209703):

> I wonder if it is scikit-image's responsibility to adjust for these machine-level differences.

The proposed solution, in particular, can be qualified only as a hack, and not something I'm particularly keen to add to skimage. (I don't mean this disrespectfully btw — we all use hacks. But the standard for adding to skimage should be higher.) If we *do* decide that we need a solution, I would aim for something that looks at the underlying linear algebra problem being solved (is it a matrix inversion?), and what the solutions are to improve *that algorithm's* numerical stability.

**Comment by grlee77** [comment]
>> The proposed solution, in particular, can be qualified only as a hack
Agreed.  Unfortunately, I don't have the time/motivation to dig deeply into this edge case further at the moment.  I understand if others do not wish to merge it as is.

**Comment by dvolgyes** [comment]
If the decision is not to merge, then maybe it is time to close the PR, isn't it?

**Comment by grlee77** [comment]
This was not a very robust solution, so I have closed this PR

**Comment by stefanv** [comment]
Thanks, Greg, I'm sorry we could not figure out a cleaner way out—tricky!

**Pull request closed without merging**
