### PR TITLE
Added bresenham-based supercover line algorithm as a argument to line() with default option set to false

### PR DESCRIPTION
**Pull request by amccaugh**
Verified the supercover algorithm works correctly and updated the examples given in line()

### CODE REVIEW

**Comment by soupault** [comment]
@amccaugh please, use `r, c` instead of `y, x`.

**Comment by amccaugh** [comment]
@soupault Sure thing -- but where exactly?  I'm followed the style of line() and line_aa() pretty closely, both of which use x and y in their arguments as well as their internal code

**Comment by soupault** [comment]
@amccaugh basically, everywhere (https://github.com/scikit-image/scikit-image/issues/1602) :). I'm addressing this for other functions in https://github.com/scikit-image/scikit-image/pull/2321.

**Comment by amccaugh** [comment]
@soupault Sounds good--also, does it make sense for me to add the supercover argument (=False by default) to the function polygon_perimeter?  This is where it would come in most handy for algorithms which require finding all grid traversals like in a [fill tool](http://www.klayout.de/doc/manual/tiling.html)

**Comment by amccaugh** [comment]
@soupault Made the requested x->c and y->r conversions

**Comment by soupault** [comment]
@amccaugh Hi! #2321 is finally out. Could you rebase this onto `master` so we can give it a final dash? Feel free to ask any help if you need it.
Regarding the content of this PR, I'd like to see also some tests (see `tests/test_draw.py`, it has a lot of good examples), and would ask you to work a little on the """marketing""" aspect of your work (i.e. demonstrate the feature in one of our gallery examples. http://scikit-image.org/docs/dev/auto_examples/edges/plot_shapes.html is probably the best candidate).

**Pull request closed without merging**
