### PR TITLE
Texture synthesis and Structural inpainting using Exemplar based approach

### PR DESCRIPTION
**Pull request by chintak**
Implementation of Criminisi et al. algorithm. Great results for both textural synthesis as well as structural case. `plot_inpaint_criminisi.py` shows the real effectiveness of the algorithm. 

Profiling results: 2500 pixels in 10.4 sec.

Things to be done:
1. Cythonise `_inpaint_criminisi` function

@emmanuelle @sciunto @stefanv review please!

### CODE REVIEW

**Comment by glemaitre** [comment]
If still interested by this feature I moved it inside the `filters` module.

**Comment by soupault** [comment]
@chintak Hello! Would you like to finalize this or I can go ahead?

**Comment by chintak** [comment]
Yes you can.

Best
Chintak




On Thu, Jun 23, 2016 at 12:27 AM +0530, "Egor Panfilov" <notifications@github.com> wrote:












@chintak Hello! Would you like to finalize this or I can go ahead?

**Comment by soupault** [comment]
Couldn't make this work, btw.

**Pull request closed without merging**
