### PR TITLE
Remove .meeseeksdev.yml, Mark is a core-dev.

### PR DESCRIPTION
**Pull request by sciunto**
## Description

@hmaarrfk No need for this file anymore, right?

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
What made the builds fail?

**Comment by sciunto** [comment]
looks random. I restarted the three that failed, 1 passed and 2 failed again. Restarted those again...

**Comment by soupault** [comment]
Should update also https://github.com/scikit-image/scikit-image/blob/869d044a7421fc654a3e77d6934d889ef7e6e8e9/tools/check_sdist.py#L31 .

**Comment by sciunto** [comment]
well spotted @soupault

**Comment by hmaarrfk** [comment]
i think it is unrelated. I'm just sad to see them fail again....

**Comment by sciunto** [comment]
yep

**Pull request merged**
