### PR TITLE
Add python 3.10 test runs on GitHub Actions and Appveyor

### PR DESCRIPTION
**Pull request by grlee77**
## Description

Adding test cases for Python 3.10 on CI. NumPy, SciPy and PyWavelets should have Python 3.10 wheels now, so let's see how this goes.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
It looks like we need to remove the call to `bdist_wininst` here since that command was [deprecated in Python 3.8 and removed in Python 3.10](https://discuss.python.org/t/remove-bdist-wininst-command/6434):
https://github.com/scikit-image/scikit-image/blob/9fea28b7d5708152e0b96dea2f3635fa2fe6d4a0/.appveyor.yml#L46

**Comment by grlee77** [comment]
@rfezzani, the following error occurred in the stitching demo, but I don't think it usually happens. I have seen multiple other recent builds pass, but I think this has also occurred in at least one other recent PR:

https://github.com/scikit-image/scikit-image/runs/4158420675?check_suite_focus=true#step:6:1580
```
Warning, treated as error:
/Users/runner/work/scikit-image/scikit-image/doc/examples/registration/plot_stitching.py failed to execute correctly: Traceback (most recent call last):
  File "/Users/runner/work/scikit-image/scikit-image/doc/examples/registration/plot_stitching.py", line 113, in <module>
    for dst in matching_corners]
  File "/Users/runner/work/scikit-image/scikit-image/doc/examples/registration/plot_stitching.py", line 113, in <listcomp>
    for dst in matching_corners]
AttributeError: 'NoneType' object has no attribute 'params'

```

**Comment by grlee77** [comment]
I think these will all pass now that we pinned sphinx. let me trigger CI again to be sure

**Comment by hmaarrfk** [comment]
Sorry, can you try to rebase. I might have created conflicts with pyproject.toml

**Comment by grlee77** [comment]
> Sorry, can you try to rebase. I might have created conflicts with pyproject.toml

no problem it is just the one line with Cython requirements. I will use the setting for that from the other PR. All linux CI passes now and Appveyor passed last time around, so I will go ahead and fix the conflict and merge here.

**Comment by grlee77** [comment]
I guess we still need an approval to merge. I think it should be fine to merge now, but I am fine if you want to wait until CI completes again.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Awwwweeeesome, thank you both!!! 🎉

**Pull request merged**
