### PR TITLE
reworded paragraph on order of iteration

### PR DESCRIPTION
**Pull request by anufern**
## Description
rewording as requested as in #2695 

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by stefanv** [comment]
I'm glad you caught this one!  I think this is a vast improvement; but can we explain it even better?  This seems like a great opportunity to educate, with an example.

**Comment by anufern** [comment]
I agree how about a diagram of a c contiguous array with an arrow to show which way the iteration should occur
 "along the last/rightmost dimension in the innermost loop of the computation."

**Comment by jni** [comment]
Yes, a diagram is sorely needed here. I would also add that scikit-image uses c-ordering *because it follows NumPy defaults*.

**Comment by dpshelio** [comment]
@anufern - I'll help you to do that diagram this week, and we can also include @jni comment about NumPy.

**Comment by jni** [comment]
@anufern I'm closing this in favour of #3127. We would still welcome a diagram to clarify these concepts!

**Pull request closed without merging**
