### PR TITLE
Azure CI caching fix (v2)

### PR DESCRIPTION
**Pull request by grlee77**
## Description

When trying to remove the unneccessary indentations in #5343, I made a mistake that caused Azure to quit running on PRs. This PR should fix this.

I also added `skimage/data/_registry.py` as a file the cache key as is already done for the CircleCI cache (see #5350)

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
since this PR only touches the Azure yml file, I stopped the other CI runs.

**Comment by grlee77** [comment]
This time I caught the Azure gallery build job while it was stuck and it was just sitting for > 30 minutes at the following test:
```
+ 'C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe' -W ignore:Matplotlib:UserWarning doc/examples/applications/plot_3d_interaction.py
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
```

@mkcor, this was one of the recent examples using Plotly, so I wonder if this is somehow related? I have restarted that job to see if it happens repeatedly

**Comment by grlee77** [comment]
If anyone from @scikit-image/core has a change to approve and merge this it will get Azure running on CI again. Currently due to the indentation error fixed in the first commit here, the CI is not running at all on new PRs or new commits to existing PRs.

The only CI failures here are just the non-Azure jobs I manually stopped.

I had to skip one specific gallery example that was persistently getting stuck and will open a new issue about addressing that.

**Review by mkcor — APPROVED** [review]

**Comment by mkcor** [comment]
> This time I caught the Azure gallery build job while it was stuck and it was just sitting for > 30 minutes at the following test:
> 
> ```
> + 'C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe' -W ignore:Matplotlib:UserWarning doc/examples/applications/plot_3d_interaction.py
> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
> ```
> 
> @mkcor, this was one of the recent examples using Plotly, so I wonder if this is somehow related? I have restarted that job to see if it happens repeatedly

@grlee77 oops... When building the docs locally, I noticed that this example would use up all my CPU. I should have raised a flag in this respect. :pray:

**Pull request merged**
