### PR TITLE
Update Getting Started documentation

### PR DESCRIPTION
**Pull request by MattTheCuber**
## Description
Fixed a few broken function calls and syntax issues.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
Updated Getting Started documentation.
```

### CODE REVIEW

**Review by soupault — APPROVED** [review]
Thanks!

**Comment by MattTheCuber** [comment]
Does anyone know why `2` is skipped?

chrome_vnDq9Tdumy

**Comment by soupault** [comment]
> Does anyone know why `2` is skipped?

Nice catch. Seems it is under Section 1 🙂 -  https://scikit-image.org/docs/stable/user_guide/install.html#installing-scikit-image-for-contributors .

**Comment by MattTheCuber** [comment]
> > Does anyone know why `2` is skipped?
> 
> Nice catch. Seems it is under Section 1 🙂 -  https://scikit-image.org/docs/stable/user_guide/install.html#installing-scikit-image-for-contributors .

Should 2 be moved into `install.rst` or changed to 1.1?

**Comment by MattTheCuber** [comment]
Additionally, 12.4 demonstrate `ski.lookfor('eigenvector')` but that returns `Nothing found.`. Not sure if that is the intended example, maybe the function got renamed? If you let me know of a better example I can add that to this PR.

**Comment by mkcor** [comment]
> Additionally, 12.4 demonstrates `ski.lookfor('eigenvector')`, but that returns `Nothing found.`. Not sure if that is the intended example, maybe the function got renamed? If you let me know of a better example I can add that to this PR.

Thanks for reporting, @MattTheCuber. If this was intended, I don't think it's a good example. I would suggest replacing it with `ski.lookfor('eigen')` (which returns several API functions). I'm not aware of a past `eigenvector` function; along these lines, the names changes I'm aware are mentioned in https://github.com/scikit-image/scikit-image/pull/6162#issue-1094782782.

**Comment by soupault** [comment]
>What should be done with this, should 2 be moved to a separate file or something?

My suggestion would be that we keep it as a section and add to the table of contents under `2. Installing scikit-image [contributors]`, while renaming Section 1 to `1. Installing scikit-image [users]`.

It also bothers me a little that we have `skimage` in Section 12, but "scikit-image" and "NumPy" up in the list. It reads well, but is somewhat inconsistent.

>ski.lookfor('eigenvector')

I think `ski.lookfor('eigenvalue')` would be just fine.

**Comment by MattTheCuber** [comment]
> > What should be done with this, should 2 be moved to a separate file or something?
> 
> My suggestion would be that we keep it as a section and add to the table of contents under `2. Installing scikit-image [contributors]`, while renaming Section 1 to `1. Installing scikit-image [users]`.
> 
> It also bothers me a little that we have `skimage` in Section 12, but "scikit-image" and "NumPy" up in the list. It reads well, but is somewhat inconsistent.
> 
> > ski.lookfor('eigenvector')
> 
> I think `ski.lookfor('eigenvalue')` would be just fine.

I am not very well versed in RST and don't want to setup an environment to test this. Can you provide me with what exactly needs to be added to `index.rst`?

**Review by mkcor — APPROVED** [review]

**Comment by mkcor** [comment]
I'm happy to merge this, since it makes a self-contained, objective improvement. Thank you, @MattTheCuber! I hope that this first contribution of yours won't be your last one... :smiley: 

> I am not very well versed in RST and don't want to setup an environment to test this. Can you provide me with what exactly needs to be added to index.rst?

I suggest we leave this to another, subsequent PR.

**Comment by soupault** [comment]
>I am not very well versed in RST and don't want to setup an environment to test this. Can you provide me with what exactly needs to be added to index.rst?

No worries, we will address that issue separately. @MattTheCuber thank you for the contribution!

**Pull request merged**
