### PR TITLE
Drop old dependencies per SPEC 0

### PR DESCRIPTION
**Pull request by jarrodmillman**
## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
...
```

### CODE REVIEW

**Review by lagru — APPROVED** [review]
Thanks!

**Comment by stefanv** [comment]
@lagru Did you notice that CI was red on that one?

**Comment by lagru** [comment]
Yes, I've been seeing this [error for the pre-job](https://github.com/scikit-image/scikit-image/actions/runs/7454674839/job/20282434449#step:5:639) in other PRs as well and was reasonably sure that this PR didn't introduce it. Haven't yet looked into whats triggering it... 

For future reference, should I have held of one the merge regardless in this case?

**Comment by stefanv** [comment]
Ah, no, just want to make sure it gets looked at; I will also investigate. Merging this to main caused that branch to now fail.

**Comment by lagru** [comment]
I can reproduce the error locally for Python 3.12. Pytest 8.0.0rc1 (as opposed to 7.4.4) seems to trigger it.

**Comment by lagru** [comment]
I think it's because starting with 8.0.0rc1 pytest now re-emits warnings it didn't match. Previously these were silently consumed. :/ Search for \#9288 in https://docs.pytest.org/en/latest/changelog.html. So it's not a new warning, it's that we are seeing it now.

**Pull request merged**
