### PR TITLE
remove structure_tensor_eigvals and change default structure_tensor order

### PR DESCRIPTION
**Pull request by grlee77**
This PR completes two scheduled deprecations:

1.) removal of `structure_tensor_eigvals` (it was replaced by `structure_tensor_eigenvalues`).
2.) order='rc' is the default for `structure_tensor`

One inconsistency I noticed while working on this is that we still have a `hessian_matrix_eigvals` which we might consider also renaming to `hessian_tensor_eigenvalues` for consistency!

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by mkcor — COMMENTED** [review]
Please also edit docstring in `skimage/feature/corner.py` to remove "optional" (line 70) and update "NOTE: 'xy' value only applies to 2D. Higher dimensions always use 'rc' order."

**Comment by grlee77** [comment]
> Please also edit docstring in skimage/feature/corner.py to remove "optional" (line 70) and update "NOTE: 'xy' value only applies to 2D. Higher dimensions always use 'rc' order."

Thanks, I updated the NOTE, but it is still an optional kwarg

**Comment by mkcor** [comment]
> but it is still an optional kwarg

Oh, right, sorry!

> Thanks, I updated the NOTE,

Could it be that you haven't pushed?

**Comment by grlee77** [comment]
> Could it be that you haven't pushed?

yep. it is there now

**Review by mkcor — APPROVED** [review]

**Review by rfezzani — APPROVED** [review]
Excellent, thank you @grlee77 :wink:

**Pull request merged**
