### PR TITLE
Accelerate gamma_adjust for uint8 images

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

This PR proposes a LUT based approach for gamma correction of uint8 images. It allows for considerable speedup:

### Master branch

```python
In [1]: from skimage.exposure import adjust_gamma                                                       

In [2]: img = np.ones((1024, 1024, 3), dtype='uint8')                                                   

In [3]: %timeit adjust_gamma(img)                                                                       
10.7 ms ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### Current branch

```python
In [1]: from skimage.exposure import adjust_gamma                                                       

In [2]: img = np.ones((1024, 1024, 3), dtype='uint8')                                                   

In [3]: %timeit adjust_gamma(img)                                   
6.87 ms ± 9.45 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by sciunto** [comment]
Nice! I think it would be too much work to add a benchmark for this function: https://github.com/scikit-image/scikit-image/blob/master/benchmarks/benchmark_exposure.py

**Review by emmanuelle — APPROVED** [review]
Really cool! The performance gain was even bigger on my machine (15 vs 8.5 ms so factor of 1.76), and I also tested with an array of random uint and observed the same gain. A benchmark could be nice indeed, but we ca also merge the PR as it is.

**Review by jni — APPROVED** [review]
I'm also ok with merging as is but would also like a benchmark.

One comment about the code is it'd be better to write:

```python
if dtype is np.uint8:
    out = ...
else:
    _assert_non_negative(image)
    scale = ...
    out = ...
return out
```

It's one of NASA's rules for bug-free code to have only one return statement per function. I'm happy to stray from this when the returns are close to each other and well structured (`if ...: return something; else: return something_else`). Here, though, there's a return high up in the function and then the function continues...

But, I'm nitpicking, if you get a chance, I'd appreciate the changes, otherwise, we'll merge before release. =)

**Comment by emmanuelle** [comment]
There seems to be something wrong with Travis, but it's not specific to this PR, it also happens on recent commits in other PRs.

**Comment by emmanuelle** [comment]
> There seems to be something wrong with Travis, but it's not specific to this PR, it also happens on recent commits in other PRs.

There has been a release of dask on Friday, maybe this is why? It's probably related to one of the optional deps since only those builds are failing.

**Comment by emmanuelle** [comment]
In #4973 I try to fix the CI problem, let's see if it works.

**Comment by jni** [comment]
Awesome, thanks @emmanuelle! Since this is otherwise ready, I suggest we merge?

**Comment by emmanuelle** [comment]
Sure, merging! Thanks @rfezzani .

**Pull request merged**
