### PR TITLE
forbid latest version of pyqt

### PR DESCRIPTION
**Pull request by emmanuelle**
Travis builds are failing with optional deps, this is an attempt to fix this.

### CODE REVIEW

**Comment by jni** [comment]
@emmanuelle can you add `pytest-faulthandler` to the test dependencies? It will tell you which test segfaulted/aborted.

**Comment by emmanuelle** [comment]
@jni done! Travis build is passing now :-). (and the circleCI failure is not related)

**Comment by jni** [comment]
Awesome! So this is ready to merge then?

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
I think the answer is yes, I'm just gonna go for it! :blush:

**Comment by emmanuelle** [comment]
@jni yes, as far as I'm concerned!

**Pull request merged**
