### PR TITLE
Adding stages to travis CI

### LINKED ISSUE #4242: Speeding up CI
@bsipocz made a [PR to NumPy](https://github.com/numpy/numpy/pull/14703/files) to run a set of tests on *one worker* to catch early failures, before launching the full parallel suite.  This is a great way to save cores, since PRs are likely to fail quite often.

### PR DESCRIPTION
**Pull request by bsipocz**
To close #4242 

I only had access to the travis logs from the past 3 days. Based on that very limited stat it seems that job no7 was failing most often, so I put that into the initial stage.

### CODE REVIEW

**Comment by bsipocz** [comment]
failure is a red herring

**Comment by hmaarrfk** [comment]
Can we do a standard 3.7 build instead of the --pre one?

**Comment by hmaarrfk** [comment]
That one fails most often, but it is rarely the contributor's fault.

**Comment by bsipocz** [comment]
> Can we do a standard 3.7 build instead of the --pre one?

surely, it was just the one that failed the most often (well, failed 2 times, so it's not significant).

**Comment by hmaarrfk** [comment]
Right, but most of the time we are trying to help contributor's write good tests, not necessarily patch up code due to changes upstream

**Comment by bsipocz** [comment]
But then would you merge PRs with a legitly failing CI, or would patch up that given PR (or open a separate one and rebase said PR) before merging?

**Comment by hmaarrfk** [comment]
I mostly want to point the contributor to a legitimate failure of theirs, rather than a maintenance failure that we need time to fix.

In certain cases, we do merge with failing CIs. Especially with --pre failures

**Comment by hmaarrfk** [comment]
Many contributor's are new to ensuring backward compatibility, and writing tests, that process takes time to teach. 

We aren't trying to teach them about prereleases necessarily.

**Comment by hmaarrfk** [comment]
@stefanv friendly ping!

**Comment by stefanv** [comment]
Thanks, @bsipocz!

**Comment by bsipocz** [comment]
oh, sorry not getting back to this, was on my list.

**Comment by stefanv** [comment]
I hope you are happy with the state of the merged PR; feel free to let us know if there's anything else that needs attending.

Thanks again!

**Pull request merged**
