### PR TITLE
STY: Fix formatting and use tight_layout in doc examples.

### PR DESCRIPTION
**Pull request by JDWarner**
Attempts to address #1774 and #1775.

Some lines may need to be reverted if the automatic `tight_layout()` is a step backward.

I attempted to enforce 80 char line limits wherever possible; many of the shared axes calls did not respect this. There are likely other instances beyond the scope of this PR (which was aimed specifically at the above Issues).

### CODE REVIEW

**Comment by emmanuelle** [comment]
@JDWarner could you please rebase now that #1810 has been merged?

**Comment by JDWarner** [comment]
@emmanuelle Rebased!

**Comment by JDWarner** [comment]
@emmanuelle @blink1073 it baffles me why I suddenly am getting duplicate reference Sphinx errors. I didn't change any references in this PR.

**Comment by blink1073** [comment]
I'm debugging now https://travis-ci.org/blink1073/scikit-image/builds/98625458

**Comment by blink1073** [comment]
And it did not reproduce...I'll restart both builds.

**Comment by blink1073** [comment]
Ahhh, this could be related to our sphinx caching:
https://github.com/scikit-image/scikit-image/blob/master/tools/travis_script.sh#L12

**Comment by JDWarner** [comment]
Thanks @blink1073!

**Comment by emmanuelle** [comment]
Thanks, merging !

**Comment by soupault** [comment]
Great!
Does this fully close https://github.com/scikit-image/scikit-image/issues/1775 ?

**Pull request merged**
