### PR TITLE
Travis CI: The sudo: tag is deprcated in Travis

### PR DESCRIPTION
**Pull request by cclauss**
## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Is sudo always true now?

**Comment by hmaarrfk** [comment]
Yeah. It will always be true

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

**Comment by cclauss** [comment]
These changes do not effect runtime behavior (only test time) so backporting should not change much.

**Comment by sciunto** [comment]
thank you @cclauss !

**Pull request merged**
