### PR TITLE
DOC: fix env variable GH_TOCKEN

### PR DESCRIPTION
**Pull request by sciunto**
Is it the solution?

### CODE REVIEW

**Comment by sciunto** [comment]
ping @stefanv @blink1073

**Comment by blink1073** [comment]
Here we go....

**Comment by sciunto** [comment]
not yet...

```
remote: Anonymous access to scikit-image/docs.git denied.

fatal: Authentication failed for 'https://@github.com/scikit-image/docs.git/'
```

**Comment by blink1073** [comment]
Aaaargh....

**Pull request merged**
