### PR TITLE
Move cython pinning forward

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
Cython 0.29.13 is necessary for Python 3.8 support

If this pinning is good enough for scipy, it is good enough for us!
https://github.com/scipy/scipy/blob/master/pyproject.toml#L5

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by emmanuelle** [comment]
Just a naive question BTW: why do we need to bump the dep here, wouldn't pip install automatically a cython version compatible with Python 3.8 if the version of Python used is 3.8?

**Comment by hmaarrfk** [comment]
that is if we stop shipping C files. That seems like  harder decision ;)

**Comment by hmaarrfk** [comment]
and harder to ensure that the new build process goes well.

**Comment by jni** [comment]
@emmanuelle imho we should aim for the generated C code to match in all Python versions. I think it's probably a good idea to be on the bleeding edge with Cython, as they are making performance improvements all the time, and it also frees us to use more modern constructs like their [pure Python mode](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html).

I'll let this sit for a bit longer in case @stefanv or others want to comment. Thanks @hmaarrfk!

**Comment by stefanv** [comment]
This is the simplest solution for now.  In the longer term, I agree that we should stop shipping C files in the source bundle.

**Comment by emmanuelle** [comment]
Thanks everyone for the explanations, merging!

**Pull request merged**
