### PR TITLE
Fixing Cythonized version of HOG

### LINKED ISSUE #1648: plot_hog.py results in strangely-looking figure in the gallery
Compare http://scikit-image.org/docs/dev/_images/plot_hog_1.png and http://scikit-image.org/docs/0.11.x/_images/plot_hog_1.png

I don't think the example changed, so it must be inside the hog functions or in one of the functions called by this function.

### PR DESCRIPTION
**Pull request by ivoflipse**
This tries to fix #1648 

I moved range_rows_start/stop and range_colums_start/stop to hog_histograms, since they are the same for each iteration of cell_hog.

I also divided the total by the size of the cell to normalize the result in cell_hog, which seems to somewhat replicate the uniform filter from the original implementation and make the results more similar. However, the result is still not entirely the same though, subtracting the result from the old implementation from the new implementation I get the following result: 
image

I believe the difference is due to the fact that the old implementation first masked the magnitudes of the gradients, then filtered the result and subsampled from that array. Whereas the new implementation only calculates the values for the subsampled points, leading to small differences.

image

Is this a problem or are the results sufficiently similar?

### CODE REVIEW

**Comment by ivoflipse** [comment]
The built might fail, because I had to apply the same changes as in #1782 to get my code working, though that may just be a Windows thing.

**Comment by JDWarner** [comment]
For the difference image, what are the actual maximum/minimum values in the array? If they're sufficiently small what we're seeing could be precision error.

**Comment by ivoflipse** [comment]
@JDWarner the min and max of the difference image are: -0.264, 0.264. Which are the same as the maximum of the individual images. After closer inspection it seems the two results are somewhat misaligned:

image

The differences become much smaller if I shift the old image 8 pixels in both directions. This seems to indicate a difference in the subsampling strategy.

The min/max difference is 0.093, -0.050 after the shift. Here's an image of the difference both scaled to the same max values:
image

**Comment by Korijn** [comment]
Perhaps is it also interesting to add a unit test to check expected output? I was surprised to see that no such unit test is currently in the suite.

Also, I think we should consider integrating #1646 into this PR. I think they have a valid point.

**Comment by ivoflipse** [comment]
@Korijn pointed out to me that the 8 pixel difference was caused by an incorrect change made to the visualize part of the hog function in _hog.py. Reverting it seems to make the difference basically rounding errors, since the minimum and maximum values are: (3.253e-08, -3.893e-08).

image

**Comment by ivoflipse** [comment]
Somehow I managed to mess up my commit and revert a whole bunch of changes, sorry for the confusion!

**Comment by Korijn** [comment]
A change made in #595, to be precise, where `y * cy + cy // 2` was optimized by moving `cr2 = cy + cy` outside of the loop and substituting `y * cr2 // 2`, which (according to math operator precedence rules) is not equivalent and thus incorrect.

**Comment by Korijn** [comment]
I've added a unit test to check for correct output to prevent any future regressions, and I've added a parameter to address #1646. Default behaviour has not changed, so no worries for current users of the function.

**Comment by ivoflipse** [comment]
@stefanv anything else that needs to happen to get this PR merged? The Travis error seems unrelated to our PR

**Comment by stefanv** [comment]
@ivoflipse Great works, thanks very much--we'll include this in the next release, due any time now.  Could I ask you to please rebase this on master so that we don't have all the branch merges on the PR?

**Comment by Korijn** [comment]
Looks like some things went wrong with merging upstream there... give us a moment to fix it...

**Comment by Korijn** [comment]
I have no idea how to undo the commits @ivoflipse pushed, `git revert -m {parent} {id}` seems to do nothing. I'll create a new PR...

**Comment by Korijn** [comment]
There, I think it should be good now.

**Comment by emmanuelle** [comment]
Looks good to me, merging.

**Comment by stefanv** [comment]
Perfect, thanks for this!

**Pull request merged**
