### PR TITLE
Pin to latest meson-python

### PR DESCRIPTION
**Pull request by stefanv**
See https://meson-python.readthedocs.io/en/latest/changelog.html

In particular, https://github.com/mesonbuild/meson-python/commit/8824bc2191445e22345e4dcbe75f49634cafbca2

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Hmm, as a matter of curiosity, why force using a PyPI installed version of Ninja if meson-python detects that there's already a suitable version of Ninja available?

**Comment by stefanv** [comment]
Sorry, I don't follow. We have to ensure that Ninja is present on the system, now that meson no longer pulls it in as a dependency (that's the issue we ran into, that meson would not work without ninja already present).

**Comment by eli-schwartz** [comment]
The purpose of the meson-python change was that meson-python would still add an additional get_requires_for_build_wheel ensuring that `pip install scikit-image` would install ninja as a build requirement... but only if meson-python could not find a `/usr/bin/ninja` installed via apt or rpm or something.

This is important for Linux distros particularly, as they already have ninja installed beforehand as a C++ program, and also install all the python dependencies before running `python -m build --no-isolation`, and don't want it to either fail because not all build dependencies are installed, or attempt to download additional copies from the internet in a managed build.

If you are actually getting failed builds with meson-python 0.11.0 and no ninja getting installed at all, then something is very wrong as that should absolutely not be happening.

**Comment by stefanv** [comment]
Unfortunately, we don't always build via pip, and then you see:

```
ERROR: Could not detect Ninja v1.8.2 or newer
```

**Comment by eli-schwartz** [comment]
... oh, you're building with `pip install --no-build-isolation` which doesn't install dependencies at *all* (it totally ignores what is specified in pyproject.toml) and you manually install from `requirements/build.txt`.

So IMO the solution is simple enough, in this PR you added ninja to both pyproject.toml and requirements/build.txt but you only actually need it for the latter. :)

**Pull request merged**
