### PR TITLE
RANSAC: don't pick duplicate samples

### LINKED ISSUE #3886: ransac selects duplicate data points in random sample
## Description
I don't know if this behavior is intentional, but to me it seems a bit odd.
When the ransac-method selects the random sample to fit the model, it can select the same data point multiple times.

## Way to reproduce
```python
import numpy as np
from skimage.measure import ransac

np.random.seed(seed=0)

data = np.arange(10)

class Model(object):

    """Dummy model"""

    def estimate(self, data):
        if np.unique(data).size != data.size:
            print("Duplicate points: ", data)
        return True

    def residuals(self, data):
        return 1.0

ransac(data, Model, min_samples=3, residual_threshold=0.0, max_trials=10)
```
Which results in
```python
('Duplicate points: ', array([8, 8, 1]))
('Duplicate points: ', array([6, 7, 7]))
('Duplicate points: ', array([9, 8, 9]))
```

## Version information
```python
# Paste the output of the following python commands
2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]
Linux-4.9.0-8-amd64-x86_64-with-debian-9.4
scikit-image version: 0.14.2
numpy version: 1.16.0
```

### PR DESCRIPTION
**Pull request by johanjeppsson**
## Description

Make sure that the data samples that are drawn in the RANSAC method don't contain duplicates
Closes #3886

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Whoa, what is this WIP voodo!

**Comment by johanjeppsson** [comment]
> Whoa, what is this WIP voodo!

I'm a newbie at this, so I wanted check that I didn't miss anything before I submitted the PR for real. :-)

**Comment by hmaarrfk** [comment]
No this PR is excellent as far as I'm concerned! 

As a self described "newbie", were you able to install the library in development mode on your own computer?

**Comment by johanjeppsson** [comment]
> No this PR is excellent as far as I'm concerned!
> 
> As a self described "newbie", were you able to install the library in development mode on your own computer?

No, I actually ran in to trouble there. I followed the guide [here](https://scikit-image.org/docs/dev/contribute.html), and set up a conda environment. The dependencies install fine, but when I try to install scikit-image from source locally, I get an error when _shared/geometry.c is being complied:

>pip install -e . --no-deps

>...

>error: Command "gcc -pthread -shared -B /home/johan/anaconda2/envs/skimage-dev/compiler_compat -L/home/johan/anaconda2/envs/skimage-dev/lib -Wl,-rpath=/home/johan/anaconda2/envs/skimage-dev/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o -o skimage/_shared/geometry.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1
>    ----------------------------------------
> ERROR: Command "/home/johan/anaconda2/envs/skimage-dev/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/johan/scikit-image/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/johan/scikit-image/

**Comment by hmaarrfk** [comment]
Hey thanks! That is great feedback. Can you please upload more of the error message? Do you have gcc installed?

**Comment by hmaarrfk** [comment]
FYI, I wouldn't worry about the tests failing. It seems unrelated to your PR. 
xref: https://github.com/luispedro/imread/issues/35

**Comment by johanjeppsson** [comment]
> FYI, I wouldn't worry about the tests failing. It seems unrelated to your PR.
Yes, I thought so as well :)

> Hey thanks! That is great feedback. Can you please upload more of the error message? Do you have gcc installed?

Sure! I've got gcc installed. I updated it just in case, but I still get the same error. I attached the full error message [here](https://github.com/scikit-image/scikit-image/files/3170400/err.txt)

I also tried to run the failing gcc command manually:

> gcc -pthread -shared -B /home/johan/anaconda2/envs/skimage-dev/compiler_compat -L/home/johan/anaconda2/envs/skimage-dev/lib -Wl,-rpath=/home/johan/anaconda2/envs/skimage-dev/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o -o skimage/_shared/geometry.cpython-37m-x86_64-linux-gnu.so

>/home/johan/anaconda2/envs/skimage-dev/compiler_compat/ld: build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o: unable to initialize decompress status for section .debug_info
>/home/johan/anaconda2/envs/skimage-dev/compiler_compat/ld: build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o: unable to initialize decompress status for section .debug_info
>/home/johan/anaconda2/envs/skimage-dev/compiler_compat/ld: build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o: unable to initialize decompress status for section .debug_info
>/home/johan/anaconda2/envs/skimage-dev/compiler_compat/ld: build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o: unable to initialize decompress status for section .debug_info
build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o: file not recognized: file format not recognized

I don't know if that's helpful or not.

**Comment by hmaarrfk** [comment]
>     test.o: file not recognized: file format not recognized

This kinda indicates that you might have a incompatibility between your compiler and your installed version of python.

can you provide the output of
```
python --version
gcc --version
python -c 'import struct;print( 8 * struct.calcsize("P"))'
python -c "import platform; print(platform.architecture())"
python -c "import sys; print(sys.version)"
```

**Comment by johanjeppsson** [comment]
> > ```
> > test.o: file not recognized: file format not recognized
> > ```
> 
> This kinda indicates that you might have a incompatibility between your compiler and your installed version of python.
> 
> can you provide the output of
> 
> ```
> python --version
> gcc --version
> python -c 'import struct;print( 8 * struct.calcsize("P"))'
> python -c "import platform; print(platform.architecture())"
> python -c "import sys; print(sys.version)"
> ```

Sure!

```
> python --version
Python 3.7.3
> gcc --version
gcc (GCC) 8.3.0
>python -c 'import struct;print( 8 * struct.calcsize("P"))'
64
>python -c "import platform; print(platform.architecture())"
('64bit', 'ELF')
>python -c "import sys; print(sys.version)"
[GCC 7.3.0]
```
Is the discrepancy between "gcc (GCC) 8.3.0" and "[GCC 7.3.0]" a problem?

**Comment by hmaarrfk** [comment]
Not too sure. I think it is should be OK to use a newer compiler with older compilers. What distro are you on?

I'm surprised you are on such a new distry but running Anaconda2 ;) I guess that is the advantage of having Anaconda

Can you run 
```
which python
```

**Comment by hmaarrfk** [comment]
Try the command
```
git clean -xfd
```
this will remove any unversioned file. so watch out.

Then try to follow the commands you found in the link you posted.

**Comment by jni** [comment]
Thanks @johanjeppsson! A very neat PR! I hope you get your compilation issues sorted!

**Comment by jni** [comment]
(As @hmaarrfk hinted in his last message, often it is useful to clean up your entire repo of cache files etc and then try again.)

(Side note: it's nice to use gist.github.com or pastebin.com to share big text files, as they then render in the browser.)

**Comment by jni** [comment]
And the cleanup might help: what is `test.c`? I don't think it's a file that should exist in our repo...

**Comment by hmaarrfk** [comment]
Yeah seems like a very old file that used to be in our repo. I kinda remeber seeing it in mine too

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.15.x

**Comment by johanjeppsson** [comment]
I gave it another shot today, and got the development installation to work using venv instead of conda. Maybe there is something wrong with my anaconda installation?

Anyway, thanks for all the help!

**Pull request merged**
