### PR TITLE
Added function for interpreting and expanding multidimensional parameters.

### PR DESCRIPTION
**Pull request by kne42**
## Description
Will be used in future pull requests for backwards-compatibility and standardized-parameter interpretation for properties of multidimensional functions.

Is additionally used in `filters._gaussian`, `segmentation.slic_superpixels`, and `measure._moments`.

    Provides an expected/standardized output of the parameter as
    an ndarray the size of times. Primarily used in n-dimensional
    image processing.
    
    An argument that is not what NumPy considers to be array-like
    will be repeated the number of times specified. Otherwise,
    the default value will be appended to the argument until
    it reaches a size equivalent to that of the number of times
    specified.
    
    All values of ``None`` within the argument will be replaced with
    the default value.
    
    Parameters
    ----------
    arg : any
        The argument to interpret and standardize.
    times : int
        The number of elements in the output matrix.
    arg_name : str, optional
        Name of the argument in the original function.
    default : any, optional (default: 0)
        The value to default to when None is provided.
    dtype: data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    
    Returns
    -------
    expanded_arg : array, shape (``times``,)
        The standardized output of the argument.
    filled : int
        The number of arguments that have been filled in.

## Examples
```py
>>> expand_arg(None, 3)
(array([ 0.,  0.,  0.]), 3)

>>> expand_arg((None, 0, None, 42), 5, default=180)
(array([ 180.,    0.,  180.,   42.,  180.]), 1)

>>> expand_arg((2.6,  2.3), 2, dtype=int)
(array([2, 2]), 0)
```

## References
Will be used in #2739 

## Checklist
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by kne42** [comment]
@jni @soupault This PR is now ready for review.

**Comment by jni** [comment]
To be honest, I'm 👎 on this function. *Mostly*, array broadcasting can handle the use cases for this function. For example, the use in `moments_central_coords` is actually totally unnecessary: see https://github.com/scikit-image/scikit-image/pull/3023/files. In the case of `sigma`/`multichannel`, using the function saves a single line of code or *zero* lines of code, while actually hiding intent, which (to me) makes the code more confusing to read.

I'll let others weigh in also. CC @scikit-image/core

**Comment by soupault** [comment]
I'd agree with @jni: adding an extra layer of abstraction here is not really neccessary, and it negatively affects the readibility of the code.
Instead of this, I'd suggest to converge on a codestyle for handling such cases (I can see that they appear quite often), so that we do not check for `if not isinstance(sigma, coll.Iterable)` in one place and `if type(center) not in [tuple, list, np.ndarray]` in another. As an option, by pre-casting the parameter to ndarray, and then checking what is needed in a unified way.

**Comment by kne42** [comment]
Closed as unnecessary. Discussion may be continued in #3286.

**Pull request closed without merging**
