### PR TITLE
Remove logo (moved to branding repo)

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by JDWarner** [comment]
Where is the branding repo?

Will a successful build of the docs now require cloning that repo, building the logo, locating it or copying it into place, and then continuing with Sphinx?

**Comment by stefanv** [comment]
Oh dear, I scanned for dependencies; did I miss one?  The other repo is at

https://github.com/scikit-image/skimage-branding

**Comment by blink1073** [comment]
Seems reasonable to me!

**Comment by tacaswell** [comment]
Why are you splitting the branding out?

**Comment by stefanv** [comment]
Mainly to keep things modular.  We have a repo for tutorials, one for demos, one for the library itself, one for the webpage, and it seemed like branding would be a good next candidate.  The repo will probably see quite a few binary files passing through, and I don't want to dirty the skimage source repo with that history.

**Pull request merged**
