### PR TITLE
Encrypt token for target repo

### PR DESCRIPTION
**Pull request by blink1073**
I had encrypted the token against this repo, instead of `scikit-image/docs`...

@stefanv, @sciunto

### CODE REVIEW

**Comment by sciunto** [comment]
@blink1073 That's also the idea I came :) However, if it works, it's not natural to me.

**Comment by sciunto** [comment]
I don't see why it should be the token of the source repo, not the destination. It would mean I can push to any repository like that, excepted if I need to belong to the organisation, but then, what's the point? I miss something.

**Comment by blink1073** [comment]
Well, there was also the problem that I had forgotten to add `GH_TOKEN=` to the `travis encrypt` incantation...

**Comment by sciunto** [comment]
I couldn't guess that :)

So it means that if the secure is wrong, GH_TOKEN is empty.

**Comment by blink1073** [comment]
Something like that :wink:

**Comment by stefanv** [comment]
Please document this procedure when you're done. I shudder to think what
would happen if you decided to defect to OpenCV.

**Pull request merged**
