### PR TITLE
Fix  skimage.test() to run the unittests

### LINKED ISSUE #3151: skimage.test does not execute the unit test
## Description

`skimage.test` does not run the unit tests.  

```
~$ python -c "import skimage; print(skimage.__version__); skimage.test()"
0.14.0
====================================================================== test session starts ======================================================================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/jhelmus, inifile:

================================================================= no tests ran in 0.00 seconds ==================================================================
ERROR: file not found: skimage
```

<details><summary>Environment Details</summary>

```
$ conda info

     active environment : sktest
    active env location : /home/jhelmus/anaconda3/envs/sktest
            shell level : 1
       user config file : /home/jhelmus/.condarc
 populated config files : /home/jhelmus/.condarc
          conda version : 4.5.4
    conda-build version : 3.9.1
         python version : 3.6.4.final.0
       base environment : /home/jhelmus/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/jhelmus/anaconda3/pkgs
                          /home/jhelmus/.conda/pkgs
       envs directories : /home/jhelmus/anaconda3/envs
                          /home/jhelmus/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-41-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
$ conda create -n sktest python=3.6 pip
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/anaconda3/envs/sktest

  added / updated specs: 
    - pip
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0            defaults
    certifi:         2018.4.16-py36_0        defaults
    libedit:         3.1.20170329-h6b74fdf_2 defaults
    libffi:          3.2.1-hd88cf55_4        defaults
    libgcc-ng:       7.2.0-hdf63c60_3        defaults
    libstdcxx-ng:    7.2.0-hdf63c60_3        defaults
    ncurses:         6.1-hf484d3e_0          defaults
    openssl:         1.0.2o-h20670df_0       defaults
    pip:             10.0.1-py36_0           defaults
    python:          3.6.5-hc3d631a_2        defaults
    readline:        7.0-ha6073c6_4          defaults
    setuptools:      39.2.0-py36_0           defaults
    sqlite:          3.23.1-he433501_0       defaults
    tk:              8.6.7-hc745277_3        defaults
    wheel:           0.31.1-py36_0           defaults
    xz:              5.2.4-h14c3975_4        defaults
    zlib:            1.2.11-ha838bed_2       defaults

Proceed ([y]/n)? y
...
$ pip install scikit-image
Collecting scikit-image
  Using cached https://files.pythonhosted.org/packages/34/79/cefff573a53ca3fb4c390739d19541b95f371e24d2990aed4cd8837971f0/scikit_image-0.14.0-cp36-cp36m-manylinux1_x86_64.whl
...
Successfully installed PyWavelets-0.5.2 cloudpickle-0.5.3 cycler-0.10.0 dask-0.17.5 decorator-4.3.0 kiwisolver-1.0.1 matplotlib-2.2.2 networkx-2.1 numpy-1.14.3 pillow-5.1.0 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.4 scikit-image-0.14.0 scipy-1.1.0 six-1.11.0 toolz-0.9.0
$ pip install pytest
Collecting pytest
  Using cached https://files.pythonhosted.org/packages/d3/75/e79b66c9fe6166a90004bb8fb02bab06213c3348e93f3be41d7eaf625554/pytest-3.6.1-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest)
...
Successfully installed atomicwrites-1.1.5 attrs-18.1.0 more-itertools-4.2.0 pluggy-0.6.0 py-1.5.3 pytest-3.6.1
```

</details>

## Way to reproduce

- [x] Code example
- [ ] Relevant images (if any)
- [x] Operating system and version
- [x] Python version
- [x] scikit-image version (run `skimage.__version__`)

This has been observed on conda-forge, see conda-forge/scikit-image-feedstock#23

### PR DESCRIPTION
**Pull request by jjhelmus**
Pass the path to the package directory to pytest.main in the test function.

closes #3151

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jjhelmus** [comment]
This change follows the logic in the [`pandas.test` function](https://github.com/pandas-dev/pandas/blob/v0.23.0/pandas/util/_tester.py#L20)

**Comment by hmaarrfk** [comment]
Isn't `--pyargs` the more correct way to do this.

I always feel like introspection is a bad idea.

**Comment by jjhelmus** [comment]
> Isn't --pyargs the more correct way to do this.

Yes, `args = ['--pyargs', 'skimage']` will also work. I don't have a preference either way.

**Comment by soupault** [comment]
Thanks @jjhelmus !

**Comment by hmaarrfk** [comment]
@scikit-image/core  backport?

I know PR 3164 obviates this for 0.15.dev0, but it probably makes sense to backport this one to 0.14 as not to break the API?

**Comment by stefanv** [comment]
@meeseeksdev backport to v0.14.x

**Pull request merged**
