### PR TITLE
DOC: activate favicon in config + fix doc push

### PR DESCRIPTION
**Pull request by sciunto**
@stefanv looks like it needs to be activated.

### CODE REVIEW

**Comment by blink1073** [comment]
It looks like we also have to remove the check for `TRAVIS_PULL_REQUEST`, because we never actually commit directly to master.
https://github.com/scikit-image/scikit-image/blob/master/tools/deploy_docs.sh#L2

**Comment by sciunto** [comment]
@blink1073 I think you're right based on the description of this page:http://docs.travis-ci.com/user/pull-requests/
Should I also patch this file in this PR?

**Comment by blink1073** [comment]
Yes, please do.

**Comment by sciunto** [comment]
done. :)

**Comment by blink1073** [comment]
Great, thanks, let's wait for Travis just in case.

**Comment by blink1073** [comment]
:fingers crossed:

**Comment by sciunto** [comment]
OK. Final test, the favicon should appear once https://travis-ci.org/scikit-image/scikit-image/builds/80832648 is done.

**Comment by blink1073** [comment]
I wish we could get the 3.4 build to go first...

**Comment by blink1073** [comment]
well, actually, we could reorder them in the yaml file.

**Comment by stefanv** [comment]
We're moving into the next century!

**Comment by sciunto** [comment]
@stefanv @blink1073 Is it me or the doc is not pushed?

**Pull request merged**
