### PR TITLE
remove skimage.viewer

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This PR removes `skimage.viewer` as previously scheduled for v0.20

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by rfezzani — APPROVED** [review]
:tada: Excellent! Thank you @grlee77

**Review by mkcor — APPROVED** [review]
Feels great! :sweat_smile:

**Comment by Erotemic** [comment]
Hope this is released soon! This module is breaking my package on install because I don't have a qt binding!

**Comment by grlee77** [comment]
@Erotemic:  can you open an issue with more details on the error message you are seeing? I am curious if there is a smaller change for the v0.19.x branch that could mitigate the issue you are seeing. It will likely be a few months until there is a new release from the main branch, but we probably will release a v0.19.2 fairly soon.

**Comment by Erotemic** [comment]
I'll post the traceback here:

```
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/bin/python -m pip install --upgrade pip' command.
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py:127: UserWarning: Viewer requires Qt
  return _bootstrap._gcd_import(name[level:], package, level)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 116, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 108, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 88, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 48, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 40, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 20, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/smart_kwcoco_demodata.py", line 7, in <module>
    from watch.cli import coco_align_geotiffs
  File "/home/local/KHQ/jon.crall/code/watch/watch/cli/coco_align_geotiffs.py", line 66, in <module>
    import kwimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/__init__.py", line 65, in <module>
    from .im_stack import (stack_images, stack_images_grid,)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/im_stack.py", line 8, in <module>
    import skimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/__init__.py", line 98, in <module>
    __getattr__, __lazy_dir__, _ = lazy.attach(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 77, in attach
    __getattr__(attr)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/__init__.py", line 9, in <module>
    from .viewers import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/__init__.py", line 1, in <module>
    from .core import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/core.py", line 14, in <module>
    from ..plugins.base import Plugin
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/__init__.py", line 3, in <module>
    from .color_histogram import ColorHistogram
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/color_histogram.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2230, in <module>
    switch_backend(rcParams["backend"])
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qt5agg.py", line 5, in <module>
    from .backend_qtagg import (
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py:127: UserWarning: Viewer requires Qt
  return _bootstrap._gcd_import(name[level:], package, level)
Traceback (most recent call last):
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 116, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 108, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 88, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 48, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 40, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 20, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/smart_kwcoco_demodata.py", line 7, in <module>
    from watch.cli import coco_align_geotiffs
  File "/home/local/KHQ/jon.crall/code/watch/watch/cli/coco_align_geotiffs.py", line 66, in <module>
    import kwimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/__init__.py", line 65, in <module>
    from .im_stack import (stack_images, stack_images_grid,)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/im_stack.py", line 8, in <module>
    import skimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/__init__.py", line 98, in <module>
    __getattr__, __lazy_dir__, _ = lazy.attach(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 77, in attach
    __getattr__(attr)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/__init__.py", line 9, in <module>
    from .viewers import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/__init__.py", line 1, in <module>
    from .core import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/core.py", line 14, in <module>
    from ..plugins.base import Plugin
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/__init__.py", line 3, in <module>
    from .color_histogram import ColorHistogram
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/color_histogram.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2230, in <module>
    switch_backend(rcParams["backend"])
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qt5agg.py", line 5, in <module>
    from .backend_qtagg import (
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py:127: UserWarning: Viewer requires Qt
  return _bootstrap._gcd_import(name[level:], package, level)
Traceback (most recent call last):
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 116, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 108, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/__init__.py", line 88, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 48, in <module>
    __getattr__ = lazy_import(
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 40, in lazy_import
    __getattr__(name)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/__init__.py", line 20, in __getattr__
    attr = importlib.import_module(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/code/watch/watch/demo/smart_kwcoco_demodata.py", line 7, in <module>
    from watch.cli import coco_align_geotiffs
  File "/home/local/KHQ/jon.crall/code/watch/watch/cli/coco_align_geotiffs.py", line 66, in <module>
    import kwimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/__init__.py", line 65, in <module>
    from .im_stack import (stack_images, stack_images_grid,)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/kwimage/im_stack.py", line 8, in <module>
    import skimage
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/__init__.py", line 98, in <module>
    __getattr__, __lazy_dir__, _ = lazy.attach(
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 77, in attach
    __getattr__(attr)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/__init__.py", line 9, in <module>
    from .viewers import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/__init__.py", line 1, in <module>
    from .core import ImageViewer, CollectionViewer
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/viewers/core.py", line 14, in <module>
    from ..plugins.base import Plugin
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/__init__.py", line 3, in <module>
    from .color_histogram import ColorHistogram
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/skimage/viewer/plugins/color_histogram.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2230, in <module>
    switch_backend(rcParams["backend"])
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qt5agg.py", line 5, in <module>
    from .backend_qtagg import (
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/home/local/KHQ/jon.crall/.pyenv/versions/3.9.9/envs/pyenv3.9.9/lib/python3.9/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

If I get time to build a MWE I'll make an issue, but I don't want to make a fuss if I can't reproduce it (and I don't have time ATM to do a deep dive into this, ensuring I install PyQt5 beforehand is an effective enough workaround). The problem seems to be an early import of pyplot, which is weird because it looks like skimage shouldn't be importing that eagerly, and I'm not requesting it. I'm just importing skimage and skimage.transform (inside [kwimage.im_stack](https://github.com/Kitware/kwimage/blob/master/kwimage/im_stack.py#L8)).

**Pull request merged**
