### PR TITLE
Improve import time

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
This delays almost all imports from the critical import path of scikit image.

Now, on a "good" install, only numpy is imported, all other libraries are now lazy imported and only used when the user needs them in their code.

This decreases the total import time from 0.7 s to 0.13 s. Most of this is due to importing numpy.
Before:
image

After:
image

Ref: #4038

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
Is this really worth it? We're bound to just do it again.

**Comment by hmaarrfk** [comment]
Thats fine, and I'll gladly make the PR to get it back to this level again. We do all the effort to keep the namespace clean, but we import much of scipy to create optional datasets for examples. It really does take too long to import scikit-image and I am basically having to drop it as one of my dependencies due to that.

I can work on adding a benchmark if that helps.

**Comment by jni** [comment]
Thanks @hmaarrfk! I support this work, and think we should definitely not be so lackadaisical about this sort of stuff. See also #3397.

With regards to @stefanv's point that you will be forever maintaining this, perhaps adding a benchmark for imports would be a good idea?

My main concern is about how unpythonic this all is (PEP8 puts all imports at the top, which I like), and it makes me wonder whether we can do better by fiddling with `skimage/__init__.py` instead.

**Comment by jni** [comment]
(but note that I still might be in favour of merging this as-is, just need to think about it a bit more!)

**Comment by hmaarrfk** [comment]
i totally understand the desire not to have random imports everywhere. Unfortunately, certain things like `platform` take a non-negligeable amount of time to import.

I think you had an issue where we talked about the craziness in the dependencies.

I'm trying to write a benchmark for this, but it isn't as easy as I thought ;)

**Comment by hmaarrfk** [comment]
some of the other ones are: importing dask array for a convenience tutorial function.

That is fine, but that increases the import time of scikit-image by about 200 ms, which is non negligeable. This will happen when people download distributions such as anaconda, and find `scikit-image` as a result of combined packages being installed at once.

In terms of cost to benefit analysis, I think this is well worth it at this point to keep the package light, especially for the `img_as_*` functions, which are pretty core to any analysis.

Here are some results:

master
```
[100.00%] ··· ============== ===========
               package_name
              -------------- -----------
                  numpy       126±0.9ms
                 skimage       498±2ms
              ============== ===========
```

this branch:

```
[ 75.00%] ··· ============== =========
               package_name
              -------------- ---------
                  numpy       126±1ms
                 skimage      128±1ms
              ============== =========
```

```

       before           after         ratio
     [cba1798f]       [3e5f1a08]
     <master>         <improve_import_time~1>
-        579±90ms         389±30ms     0.67  benchmark_import_time.ImportSuite.time_import('skimage.feature') [mark-xps/conda-py3.7-cython-numpy1.16-scipy]
-         597±8ms         363±20ms     0.61  benchmark_import_time.ImportSuite.time_import('skimage.feature') [mark-xps/conda-py3.7-cython-numpy1.15-scipy]
-        564±20ms         326±20ms     0.58  benchmark_import_time.ImportSuite.time_import('skimage.morphology') [mark-xps/conda-py3.7-cython-numpy1.15-scipy]
-        586±70ms         324±10ms     0.55  benchmark_import_time.ImportSuite.time_import('skimage.morphology') [mark-xps/conda-py3.7-cython-numpy1.16-scipy]
-        509±20ms          162±7ms     0.32  benchmark_import_time.ImportSuite.time_import('skimage.color') [mark-xps/conda-py3.7-cython-numpy1.15-scipy]
-        580±40ms          166±3ms     0.29  benchmark_import_time.ImportSuite.time_import('skimage.color') [mark-xps/conda-py3.7-cython-numpy1.16-scipy]
-         570±4ms          131±5ms     0.23  benchmark_import_time.ImportSuite.time_import('skimage') [mark-xps/conda-py3.7-cython-numpy1.16-scipy]
-         606±5ms          132±2ms     0.22  benchmark_import_time.ImportSuite.time_import('skimage') [mark-xps/conda-py3.7-cython-numpy1.15-scipy]

```

**Comment by hmaarrfk** [comment]
Numpy seems to have their own benchmarks, though they don't display quite nicely.
https://pv.github.io/numpy-bench/#bench_import.Import.time_fft

Finally, i don't think their numbers are quite accurate, if it really does take 1 second to start up numpy, that is REALLY slow.

**Comment by hmaarrfk** [comment]
@jni, i wish I knew how to use `Popen`, then we could try `preloading` certain parts of the python standard library and running only the relevant import statement in the benchmark. but as is now, the benchmark shows that we are basically limited by importing numpy, which is fine since this is a `numpy` first library.

**Comment by hmaarrfk** [comment]
https://snarky.ca/lazy-importing-in-python-3-7/

**Comment by stefanv** [comment]
I didn't realize we were up to 0.5s already—that is quite painful.  Pity about the style, but I don't see an easy way around it, other than messing with hacks like lazy import (https://pypi.org/project/lazy-import/).

**Comment by stefanv** [comment]
And, yes, this is a great usage of benchmarks!

**Comment by sciunto** [comment]
I (re?)discovered tuna, thanks for this @hmaarrfk

**Pull request merged**
