### PR TITLE
Added README to binary (wheel) distribution

### PR DESCRIPTION
**Pull request by jasmcaus**
Added the README.md file to the binary wheel distribution

### CODE REVIEW

**Review by hmaarrfk — APPROVED** [review]

**Review by jni — APPROVED** [review]
LGTM, thank you!

**Comment by jni** [comment]
I'm just going to let this sit another day to give more devs a chance to weigh in, but I don't anticipate that it will be controversial.

**Review by hmaarrfk — CHANGES_REQUESTED** [review]
Can you provide us with some documentation that states that this is the currest best practice to include this kind of long description?

**Comment by hmaarrfk** [comment]
It just seems like there are a bunch of non-standard keys.

https://github.com/pypa/setuptools/blob/master/setup.cfg#L23
https://stackoverflow.com/questions/60084128/does-description-file-in-setup-cfg-section-metadata-have-any-effect

**Comment by hmaarrfk** [comment]
Maybe we want to focus on https://github.com/scikit-image/scikit-image/pull/5015 instead?

**Comment by jasmcaus** [comment]
This PR is addressed in #5015. Closing this now.

**Comment by jni** [comment]
> I don't anticipate that it will be controversial.

Never make a prediction, especially about the future. =P

**Pull request closed without merging**
