### PR TITLE
MAINT: Remove unused imports

### PR DESCRIPTION
**Pull request by alessiamarcolini**
## Description

This PR removes unused imports in multiple modules.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks for this. It seems that some examples assumed that numpy was imported. It might be better to simply import numpy in the examples to keep it explicit.

I like being able to copy and paste from documentation when I first learn about a library. It makes it much easier to focus on the new aspects, rather than the same old "missing import" statements.

**Review by hmaarrfk — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Thanks!

**Comment by alessiamarcolini** [comment]
Hi @hmaarrfk can I ask you to label this PR with `hacktoberfest-accepted`? 🙏🏼

**Comment by rfezzani** [comment]
Excellent, thank you @alessiamarcolini for this!
`skimage` is not (yet) in the Hacktoberfest, but it could be interesting to participate. What @scikit-image/core dear members think?

**Comment by alexdesiqueira** [comment]
@alessiamarcolini thank you for this! @rfezzani I added the tag; I'll assume it won't hurt :slightly_smiling_face: Please feel free to remove it if it does, though.

**Comment by rfezzani** [comment]
Excellent @alexdesiqueira, I just didn't want to take the decision alone :slightly_smiling_face: 
Thank you @alessiamarcolini :wink:

**Comment by rfezzani** [comment]
@scikit-image/core I registered skimage to the Hacktoberfest by adding the `hacktoberfest` topics to the repository as required. I hope it's fine for you all.

**Pull request merged**
