### PR TITLE
Downgrade Xcode to 9.4 on master

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

This is the default version from travis which seems to be used by the wheel builder.

Should be merged in conjunction with https://github.com/scikit-image/scikit-image/pull/3724

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
What is the reason for downgrading?  Why not upgrade all builds to 10.4?

**Comment by hmaarrfk** [comment]
The wheel builder uses 9.4.1 https://github.com/scikit-image/scikit-image-wheels/blob/master/.travis.yml#L77 as it is left empty.

**Comment by hmaarrfk** [comment]
I think.

**Comment by stefanv** [comment]
Right, but why not just upgrade both?

**Comment by hmaarrfk** [comment]
That works too. I'm just mostly worried about the multibuild blackmagic voodo that I don't know how to use.

This is a more familar change to me.

**Comment by hmaarrfk** [comment]
The bonus is that Xcode 9.4 is used by conda-forge
https://github.com/conda-forge/staged-recipes/blob/master/.travis.yml#L8

And keeping up with that is probably a good enough reason for me

**Comment by stefanv** [comment]
That's fine with me, but then it should be documented in the developer tech 
manual
What manual you ask. Yes, the one we should create to document updating the 
website, eg.

**Comment by stefanv** [comment]
No, certainly not!

**Pull request merged**
