### PR TITLE
Add howto on testing to "Contribute"

### PR DESCRIPTION
**Pull request by id-gue**
## Description
I added a short description about testing with nose in the Contribute-text.

### CODE REVIEW

**Comment by soupault** [comment]
@id-gue We'll be transitioning to `pytest` shorty (see https://github.com/scikit-image/scikit-image/pull/2468), right after 0.13 is released. For now, it is better for us not to accept any changes which will complicate the transition.
Thanks for your work, however, I'm closing this PR due to aforementioned reasons. We'd be glad to see you contributing more though :).

**Comment by infraredgirl** [comment]
Right now there is no mention of how to run unit tests in the docs. This is problematic especially for new contributors - they will want to set up their development environment and run unit tests, and the documentation doesn't tell them how to do that. Therefore, I think this patch is an improvement and it would be good to merge it. The relevant part of the docs would of course be fixed as part of the transition to pytest - it surely does not further complicate the transition to make a simple docs change?

**Comment by soupault** [comment]
@infraredgirl I'm not saying that the proposed changes are useless in any sense. The reason is the following: if you look at #2468 closely you will see how much work has already been done, but that PR has to be also __rebased__ (which is quite tricky due to the modifications we made to enable Py3.6 support) and __reviewed__. And for these processes to pass quicker I would strongly prefer not to put any additional doc/code in the way. Keeping this PR opened is also not the best idea as rebasing on `pytest`-powered branch might cause significant troubles for @id-gue.
One more thing to give you the right perception: we've 3 minor bugs to close before we release 0.14. The PR with migration to `pytest` is №1 candidate for the merge after the release. Most likely, is a matter of 2-3 weeks. You are very welcome to come back to this issue after.

**Comment by stefanv** [comment]
@soupault There's probably no harm in merging this until we're done with the pytest transition?

**Comment by stefanv** [comment]
We can even make it generic:

```
import skimage
skimage.test()
```

**Comment by id-gue** [comment]
That’s great! We will try to du the next PR on the weekend. :)

Have a nice evening!

**Comment by sciunto** [comment]
@soupault (a side comment jsut for you, we have two mrg+2 PR for which we (I... I admit) said that we will merge before the integration of pytest, because it took a lot of time to make those two PR ready (partially our fault) and the contributors did a lot of work. End of the side comment :) )

**Comment by sciunto** [comment]
Otherwise, I support @soupault decision. Much easier this way for all of us

**Comment by stefanv** [comment]
@soupault @sciunto Can we all agree to merge this PR if the language is changed to something like:

```Testing your installation of scikit-image

You can execute the scikit-image test suite with the following command:

python -c 'import skimage; skimage.test()'
```
?

**Comment by sciunto** [comment]
Yes, good point. And we can add more later on, with pytest integrated.

**Comment by soupault** [comment]
@stefanv Actually, this confuses me even more (see https://github.com/scikit-image/scikit-image/pull/2468#issuecomment-274283452).

Regarding the PR: in different Linux-based distributions the command to run `nosetests` could be different. For example, in Archlinux `nosetests` calls Python 3 version of `nosetests`, and `nosetests2` Python 2 one. I guess, if we agree to move forward it is necessary to address this point as well.

**Comment by soupault** [comment]
@id-gue @infraredgirl Dears, we have just switched to `pytest`. Now it is time to revisit your proposal. Would you be interested to continue the work here?

**Comment by grlee77** [comment]
This would be useful to have.  See for instance, recent questions on how to do testing in #1425 where it is specifically asked how to run only a subset of the tests for a given package or file.

Related to another question in #1425, do we have docs anywhere on how to setup a dedicated development environment via either virtualenv and/or conda environments?

**Comment by soupault** [comment]
@grlee77 I assume we could go forward by submitting a new PR and closing this one. The bad thing is that I still don't completely understand how to run the tests via py.test :).

As for the second part of your question, I remember only the statement from @jni - https://github.com/scikit-image/scikit-image/pull/2567#issuecomment-293820580 .

**Comment by soupault** [comment]
/all I've figured out the convenient way to run the tests via `pytest`, and updated the wiki page with the new instructions (see https://github.com/scikit-image/scikit-image/wiki/Testing-in-32-bit-environment, Step 4). If anyone would be interested in submitting a PR, that'd be great.

**Comment by stefanv** [comment]
It should be as simple as: `PYTHONPATH=. pytest skimage`

**Comment by soupault** [comment]
@stefanv nice, thanks! I've updated the wiki with your solution.

**Comment by soupault** [comment]
Closed in advance of https://github.com/scikit-image/scikit-image/pull/2751.

**Pull request closed without merging**
