### PR TITLE
Use SciPy to create Euler rotation matrices

### PR DESCRIPTION
**Pull request by michaelbratsch**
## Description

This pull-request replaces the computation of the 3D rotation matrix in
https://github.com/scikit-image/scikit-image/blob/fe57b47ba46e9e11c626b97a8a24cd4d2c41fba1/skimage/transform/_geometric.py#L1228
by SciPy's `Rotation.from_euler` as been suggested in https://github.com/scikit-image/scikit-image/pull/7479#discussion_r1722816838. 

The function definition of `_euler_rotation_matrix` itself has still been kept to make sure that the sequence of the axes definition is always the same for `SimilarityTransform` and `EuclideanTransform`.  Due to that reason also the optional parameter `axes` has been removed.

## Release note

```release-note
Use `Rotation.from_euler` to compute 3D rotation matrix
```

### CODE REVIEW

**Comment by pamitabh** [comment]
Please see post here: https://discuss.scientific-python.org/t/defining-coordinate-reference-system-for-scikit-image/1394. 

Present EuclideanTransform just uses the scipy's CRS which is not consistent with skimage's present convention. We should choose a CRS which is consistent with rotation etc, modules.

**Comment by michaelbratsch** [comment]
> Present EuclideanTransform just uses the scipy's CRS which is not consistent with skimage's present convention.

Which skimage's present convention do you mean? Maybe I am missing it in the discussion of https://discuss.scientific-python.org/t/defining-coordinate-reference-system-for-scikit-image/1394.

> We should choose a CRS which is consistent with rotation etc, modules.

I fully agree. But this is something that should come with skimage2 and not this pull-request. Otherwise user need to adapt their existing source code using the `EuclideanTransform` or `SimilarityTransform`.

**Comment by stefanv** [comment]
I think this change is fine for now. @jni, are you able to cast an eye?

We will still be overhauling the rotations for skimage v2, towards consistent right-handed axes, which will need some careful review.

**Review by lagru — APPROVED** [review]
Looks good. Can be merged if the CI is green. Thank you @michaelbratsch!

**Review by stefanv — APPROVED** [review]

**Comment by lagru** [comment]
Thanks @michaelbratsch!

**Pull request merged**
