### PR TITLE
[just testing] Mac segfaulter

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
cc: @jni

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jni so you can see that the segfault is totally not caused by scikit-image.

**Comment by jni** [comment]
@hmaarrfk can you add a commit to increase the Cython version?

**Comment by hmaarrfk** [comment]
@jni I had already run the scikit-image test suite with the updated cython version in the other PR. I think these builds are easier to follow for scipy though. I could maybe rip out more of our infrastructure.

**Comment by hmaarrfk** [comment]
This is being discussed upstream

**Comment by hmaarrfk** [comment]
https://github.com/scipy/scipy/issues/9751

**Pull request closed without merging**
