### PR TITLE
multichannel to channel_axis (5 of 6): restoration

### PR DESCRIPTION
**Pull request by grlee77**
follows #5287. Implements `channel_axis` for the restoration module

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by alexdesiqueira** [comment]
Hey @grlee77, could you check [4c06e3c](https://github.com/scikit-image/scikit-image/pull/5288/commits/4c06e3cf71cff6e7360d98ee697e7f0e82ab0e3f) and see if I fixed the conflicts as you needed? Thanks!

**Comment by alexdesiqueira** [comment]
Otherwise, LGTM :slightly_smiling_face:

**Review by alexdesiqueira — APPROVED** [review]

**Comment by alexdesiqueira** [comment]
Nope, I broke everything :cry: Sorry! Could you undo 4c06e3c and fix the conflicts?

**Comment by grlee77** [comment]
> Nope, I broke everything cry Sorry! Could you undo 4c06e3c and fix the conflicts?

No worries, the inpainting file was modified in two other recently merged PRs as well, so that became a bit more tricky. It should be ready now if CI passes

**Comment by alexdesiqueira** [comment]
Thank you Greg! @jni wanna check and merge? :slightly_smiling_face:

**Review by jni — APPROVED** [review]

**Pull request merged**
