### PR TITLE
Fixes to apply_parallel for functions working with multichannel data

### LINKED ISSUE #4900: IndexError with util.apply_parallel (RGB images)
I don't really understand the origin of this error. I could only reproduce with RGB images, not with 2D arrays. Does `apply_parallel` only work for 2D images?

## Way to reproduce
```python
from skimage import util, segmentation, data
img = data.astronaut()
_ = util.apply_parallel(segmentation.slic, img, chunks=None)
```

Output
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-63f67e7b9ccd> in <module>
----> 1 _ = util.apply_parallel(segmentation.slic, img, chunks=None)

~/code/scikit-image/skimage/util/apply_parallel.py in apply_parallel(function, array, chunks, depth, mode, extra_arguments, extra_keywords, compute)
    143     res = darr.map_overlap(wrapped_func, depth, boundary=mode)
    144     if compute:
--> 145         res = res.compute()
    146 
    147     return res

~/.local/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/.local/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    443 
    444     results = schedule(dsk, keys, **kwargs)
--> 445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    446 
    447 

~/.local/lib/python3.7/site-packages/dask/base.py in <listcomp>(.0)
    443 
    444     results = schedule(dsk, keys, **kwargs)
--> 445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    446 
    447 

~/.local/lib/python3.7/site-packages/dask/array/core.py in finalize(results)
    984     while isinstance(results2, (tuple, list)):
    985         if len(results2) > 1:
--> 986             return concatenate3(results)
    987         else:
    988             results2 = results2[0]

~/.local/lib/python3.7/site-packages/dask/array/core.py in concatenate3(arrays)
   4383     if not ndim:
   4384         return arrays
-> 4385     chunks = chunks_from_arrays(arrays)
   4386     shape = tuple(map(sum, chunks))
   4387 

~/.local/lib/python3.7/site-packages/dask/array/core.py in chunks_from_arrays(arrays)
   4152 
   4153     while isinstance(arrays, (list, tuple)):
-> 4154         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4155         arrays = arrays[0]
   4156         dim += 1

~/.local/lib/python3.7/site-packages/dask/array/core.py in <listcomp>(.0)
   4152 
   4153     while isinstance(arrays, (list, tuple)):
-> 4154         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4155         arrays = arrays[0]
   4156         dim += 1

IndexError: tuple index out of range
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0]
Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
scikit-image version: 0.18.dev0
numpy version: 1.16.4
```

### PR DESCRIPTION
**Pull request by grlee77**
## Description

closes #4900

The `multichannel` argument helps give sensible default chunks and expands scalar `depth` arguments appropriately for multichannel data.

A concrete example where the `dtype` argument is needed for this to pass was added as a test case. There is an explanation of the reason it is needed in https://github.com/scikit-image/scikit-image/issues/4900#issuecomment-675647296.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
One subtlety: specifying `dtype` does **not** guarantee the specific output dtype that will be returned by `apply_parallel`. For floating point inputs, the dtype of the output seems to match precision of the input and not that of the specified `dtype` argument. 

The following example demonstrates via direct use of map_blocks that the output dtype is determined via a combination of the input data-type and the `dtype` argument to `map_blocks`.

```Python
import numpy as np
import dask.array as da
for dtype_in, dtype_map_blocks in [
    (np.uint8, np.float32),
    (np.uint16, np.float32),
    (np.uint32, np.float32),
    (np.float32, np.float16),
    (np.float32, np.float32),
    (np.float32, np.float64),
    (np.float64, np.float16),
    (np.float64, np.float32),
    (np.float64, np.float64)
]:
    x = da.from_array(np.arange(64, dtype=dtype_in))

    out = da.map_blocks(np.sqrt, x, chunks=(8,), dtype=dtype_map_blocks).compute()
    print(f"dtype_in={np.dtype(dtype_in).name}, "
          f"dtype_map_blocks={np.dtype(dtype_map_blocks).name} -> "
          f"dtype_out={out.dtype.name}")
```

```
dtype_in=uint8, dtype_map_blocks=float32 -> dtype_out=float16
dtype_in=uint16, dtype_map_blocks=float32 -> dtype_out=float32
dtype_in=uint32, dtype_map_blocks=float32 -> dtype_out=float64
dtype_in=float32, dtype_map_blocks=float16 -> dtype_out=float32
dtype_in=float32, dtype_map_blocks=float32 -> dtype_out=float32
dtype_in=float32, dtype_map_blocks=float64 -> dtype_out=float32
dtype_in=float64, dtype_map_blocks=float16 -> dtype_out=float64
dtype_in=float64, dtype_map_blocks=float32 -> dtype_out=float64
dtype_in=float64, dtype_map_blocks=float64 -> dtype_out=float64
```

**Comment by emmanuelle** [comment]
> One subtlety: specifying `dtype` does **not** guarantee the specific output dtype that will be returned by `apply_parallel`. For floating point inputs, the dtype of the output seems to match precision of the input and not that of the specified `dtype` argument.

Should the docstring be modified to suggest that this parameter is here to help dask, but is by no means a guarantee of the output dtype?

**Review by emmanuelle — APPROVED** [review]
Thanks @grlee77 ! I just left a small comment. 

Your PR also reminds me that we should incorporate the doc on `apply_parallel` of #4214 and #3386 but this is independent of this PR!

**Comment by emmanuelle** [comment]
> One subtlety: specifying `dtype` does **not** guarantee the specific output dtype that will be returned by `apply_parallel`. For floating point inputs, the dtype of the output seems to match precision of the input and not that of the specified `dtype` argument.

Should the docstring be modified to suggest that this parameter is here to help dask, but is by no means a guarantee of the output dtype?

**Comment by sciunto** [comment]
thank you @grlee77 !

**Pull request merged**
