### PR TITLE
Backport PR #5243: Rename `master` to `main` throughout

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

Hopefully with this we can build aarch64 wheels.

Backport of #5243

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
@hmaarrfk should we worry about the minreq failures? They are all [like this one](https://github.com/scikit-image/scikit-image/pull/5295/checks?check_run_id=2215182803#step:5:239):

```
/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/scipy/linalg/blas.py:196: in <module>
    from scipy.linalg import _fblas
E   ImportError: numpy.core.multiarray failed to import
------------------------------- Captured stderr --------------------------------
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

At any rate I'll approve and let you use your best judgment here. Thank you. :pray:

**Review by jni — APPROVED** [review]

**Comment by hmaarrfk** [comment]
I guess we should also backport the min req PR.

Let's try to use mrmeseeks for that one too after this gets merged.

**Comment by hmaarrfk** [comment]
https://github.com/scikit-image/scikit-image/pull/5295/checks?check_run_id=2215182803#step:4:78

numpy is let loose in this line.

not sure why.

C_API_VERSION 0xe is 1.20 https://github.com/numpy/numpy/blob/main/numpy/core/setup_common.py#L45

**Comment by hmaarrfk** [comment]
https://github.com/scikit-image/scikit-image/pull/5296

**Comment by hmaarrfk** [comment]
@jni see: https://github.com/scikit-image/scikit-image/pull/5298

**Review by jni — APPROVED** [review]

**Pull request merged**
