### PR TITLE
Add skimage.future package

### PR DESCRIPTION
**Pull request by jni**
Addresses #1350.

The RAG functionality has been moved under to a `future.graph` subpackage, and the package docstring indicates that the API here may change at any time. The only thing left is to decide raise a warning within `skimage/future/__init__.py`. @stefanv @blink1073 ?

### CODE REVIEW

**Comment by jni** [comment]
... Another thing left, fix Travis. =P I must admit I had no idea what I was doing with the setup.py files, and was working only through imitation, so please go over those with a fine-toothed comb!

**Comment by stefanv** [comment]
Why should it raise a warning, @jni?

**Comment by stefanv** [comment]
I would import ``graph`` into ``future``, so that you can write:

```from skimage import future```

and then

```future.graph.xyz(...)```

**Comment by jni** [comment]
@stefanv just to let people know that the API could change under their noses — similar to a deprecation warning. I'm happy to leave it to the docstring, though; in fact, I prefer it.

As to importing graph, again, no issues, but I think `from skimage.future import graph` reads nicer. But it's a matter of preference and we should let the users decide. Updating now!

**Comment by stefanv** [comment]
Ready?

**Comment by jni** [comment]
Yes, I don't have anything else to add to this! =)

**Comment by blink1073** [comment]
Boom.

**Comment by stefanv** [comment]
:+1:

**Pull request merged**
