### PR TITLE
added link to imagesc forum in example pages

### LINKED ISSUE #4488: Add a link to forum at the bottom of gallery examples
In order to increase participation to the Image.sc forum, we could add a footer in example pages saying "We hope that this example was useful. If you have question unanswered by our documentation, you can ask them on the Image.sc forum...".

I wonder what the best technical solution for this would be; either defining an html template for gallery pages (I think we're using the same for all pages of the website at the moment?), or at the rst level (I'm just not sure this can be done without hacking sphinx-gallery). Thoughts?

### PR DESCRIPTION
**Pull request by emmanuelle**
Closes #4488 

I hope that the doc artifact build will work, but otherwise here is a screenshot of how it looks like. The idea is to let more people know that there is a forum where they can ask questions.

image

### CODE REVIEW

**Review by sciunto — APPROVED** [review]
nice

**Review by rfezzani — APPROVED** [review]
Excellent! Thank you @emmanuelle :wink:

**Comment by emmanuelle** [comment]
Thank you @sciunto and @rfezzani ! @jni up to you to decide whether you want this in 0.18 for the stable doc.

**Comment by jni** [comment]
@meeseeksdev backport to v0.18.x

**Comment by jni** [comment]
@emmanuelle there is my answer! 😃

**Pull request merged**
