### PR TITLE
MAINT+DOC update RELEASE.txt

### PR DESCRIPTION
**Pull request by NelleV**
## Description

This is an update of the RELEASE.txt following the release of 0.16.

Marking this as draft. Will finish updating the document *after* we finish the 0.16 release.

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
@NelleV is this ready to merge? Apparently you need to mark it as ready. This is a cool new feature btw!

**Comment by NelleV** [comment]
Nope, it's not ready yet. I need to go back to some of the pain points and clean up the document

**Comment by emmanuelle** [comment]
Happy New Year @NelleV ! Any chance to update this one soon? Thanks :-).

**Comment by sciunto** [comment]
@emmanuelle @NelleV Perhaps this PR can be checked during the next release preparation?

**Comment by emmanuelle** [comment]
@NelleV can we merge this PR? It will still be possible to amend the release instructions later on :-).

**Pull request merged**
