### PR TITLE
Enable packagers to disable failures on warnings.

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
The `SKIMAGE_TEST_STRICT_WARNINGS` now enables packagers to avoid failures due to warnings. This often happens when warnings pop up due to newer versions of dependencies.

I added a few tests for this functionality too.

As somebody who maintains the conda-forge package, I would like this backported to both 0.15 and 0.14.

I couldn't find where the `expected_warnings` context manager was tested, so I created new tests that test this added functionality.

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@scikit-image/core this also opens up the possibility to rip out much the warning based logic, and simply be strict about catching warnings on bleeding edge. 

We also need to document this, If this new feature request is accepted, I would have to document how to use it somewhere.

**Comment by sciunto** [comment]
as you said... :D :D

**Comment by jni** [comment]
@hmaarrfk I'm +1 on this idea with some documentation... Dunno where that best would fit though... The testing section of the contributing guide?

**Comment by sciunto** [comment]
I did some packaging for archlinux, and as a packager, I always missed a file like COPYING, AUTHORS, TODO, CHANGELOG... named PACKAGERS, where I could find what I need (or where I can find it).

**Comment by hmaarrfk** [comment]
I think it best goes in the Installing section. That is where I go to see things like dependencies and test procedures anyway.

**Comment by jni** [comment]
@sciunto I like your suggestion but I think it belongs within a bigger refactor of our contributing/release documentation, so let's leave it for a later PR.

Thanks @hmaarrfk, the new paragraph is (imho) just right. =)

**Comment by sciunto** [comment]
Sure!

**Comment by sciunto** [comment]
Nice PR, thanks @hmaarrfk

**Comment by soupault** [comment]
@meeseeksdev backport to v0.14.x

**Comment by soupault** [comment]
@meeseeksdev backport to v0.15.x

**Pull request merged**
