### PR TITLE
Restrict sphinx builds to a single process.  Remove vendored numpydoc.

### PR DESCRIPTION
**Pull request by stefanv**
Reference relabeling breaks when building docs in parallel.  Restrict to a single process.

Also removes the vendored version of numpydoc and depends on the published package.

### CODE REVIEW

**Comment by jni** [comment]
Workaround for #2237 . @sciunto can you test this on your machine?

**Comment by jni** [comment]
👍 !

**Comment by JDWarner** [comment]
LGTM.

**Comment by soupault** [comment]
Nice! Do we have a reproducible case somewhere?

**Comment by stefanv** [comment]
Something weird with the OSX build, but seems unrelated to this PR.

**Pull request merged**
