### PR TITLE
Solving white space + fixing previous mistake

### PR DESCRIPTION
**Pull request by alexandrejaguar**
Solving white space + fixing mistake on `plot_local_otsu.py`.
Please check if this is ok.
Thank you very much!

### CODE REVIEW

**Comment by stefanv** [comment]
Please rebase this PR, removing all merges, and compress all changes into one patch.

**Comment by alexandrejaguar** [comment]
I think this is ok already. Could someone check it when possible? Thanks!

**Comment by soupault** [comment]
Looks fine.

**Comment by stefanv** [comment]
Thanks, @alexandrejaguar !

**Comment by alexandrejaguar** [comment]
Thanks @soupault and @stefanv! Going to the next ones.

**Pull request merged**
