### PR TITLE
Try with a token encrypted in this repo

### PR DESCRIPTION
**Pull request by blink1073**
@stefanv @sciunto 

Whack - a - mole...

### CODE REVIEW

**Comment by blink1073** [comment]
:tada: :beers:

**Comment by blink1073** [comment]
Still no favicon though...

**Comment by blink1073** [comment]
Ah, this one has it: http://scikit-image.org/docs/dev/

**Comment by sciunto** [comment]
Linkchecker is happier :) https://linkchecker.sciunto.org/scikit-image.org-docs_dev

Thanks @blink1073

**Comment by stefanv** [comment]
BIG WIN!

**Pull request merged**
