### PR TITLE
Faster Unit Tests

### PR DESCRIPTION
**Pull request by jjhelmus**
Speed up various tests in the test suite by using smaller test images.

### CODE REVIEW

**Comment by jjhelmus** [comment]
For reference, I'm using [nose-timer](https://pypi.python.org/pypi/nose-timer) to profile the timing of the unit tests.  As of commit 661b8e the top 20 tests in term of run time on my machine were:

```
nosetests --with-timer --timer-top-n 20
...
skimage.io.tests.test_multi_image.TestMultiImage.test_getitem: 3.2813s
skimage.restoration.tests.test_restoration.test_unsupervised_wiener: 3.0921s
skimage.filters.rank.tests.test_rank.test_entropy: 2.2910s
skimage.io.tests.test_multi_image.TestMultiImage.test_concatenate: 2.1498s
skimage.feature.tests.test_censure.test_keypoints_censure_moon_image_star: 1.9726s
skimage.transform.tests.test_radon_transform.test_radon_iradon('cubic', 'shepp-logan'): 1.6627s
skimage.feature.tests.test_blob.test_blob_log: 1.4323s
skimage.filters.rank.tests.test_rank.test_compare_8bit_unsigned_vs_signed: 1.3723s
skimage.filters.rank.tests.test_rank.test_compare_8bit_vs_16bit: 1.3387s
skimage.segmentation.tests.test_random_walker.test_spacing_1: 1.2652s
skimage.feature.tests.test_censure.test_keypoints_censure_moon_image_octagon: 1.1049s
skimage.transform.tests.test_radon_transform.test_iradon_sart: 1.0691s
skimage.restoration.tests.test_denoise.test_nl_means_denoising_3d: 1.0381s
skimage.io.tests.test_pil.test_all_color: 0.8926s
skimage.graph.tests.test_heap.test_heap: 0.7830s
skimage.segmentation.tests.test_random_walker.test_multispectral_3d: 0.5528s
skimage.morphology.tests.test_watershed.TestWatershed.test_watershed09: 0.5276s
skimage.segmentation.tests.test_felzenszwalb.test_minsize: 0.5207s
skimage.feature.tests.test_blob.test_blob_doh: 0.5067s
skimage.feature.tests.test_orb.test_keypoints_orb_desired_no_of_keypoints: 0.4416s
----------------------------------------------------------------------
Ran 1342 tests in 57.874s

OK (SKIP=47)
```

**Comment by jjhelmus** [comment]
The `no_time_for_that.gif` file in not longer used in any of the unit tests, should it be removed?

**Comment by stefanv** [comment]
That should be fine; we can always resurrect it later if needed.

**Comment by blink1073** [comment]
Excellent, thanks @jjhelmus!

**Pull request merged**
