### PR TITLE
Dynamic Time Warping

### PR DESCRIPTION
**Pull request by marcdk**
DTW implementation according to:
1) http://mirlab.org/jang/books/dcpr/dpDtw.asp?title=8-4%20Dynamic%20Time%20Warping
2) http://en.wikipedia.org/wiki/Dynamic_time_warping

Issues:
Type-2 results differ from 2)

Todos:
Implementing start boundary condition still outstanding
Correctness test outstanding

### CODE REVIEW

**Comment by soupault** [comment]
Is this really within the confines of `skimage`?

**Comment by stefanv** [comment]
Yes, very commonly used for finding matches in paths etc.

**Comment by sciunto** [comment]
xref: https://github.com/scipy/scipy/issues/7638

**Comment by alexdesiqueira** [comment]
This became [a full package](https://pypi.org/project/dtw-python/), as the xref @sciunto pointed shows. Maybe we could show how to use the package in our context? My two BRL cents would be aimed to close this PR.
@scikit-image/core thoughts? I'll wait a little bit before closing it, feel free to manifest any interest.

**Comment by sciunto** [comment]
and eventually reopen an issue to request an example on this feature.

**Comment by alexdesiqueira** [comment]
Closed; please refer to the previous comments. Feel free to reopen if necessary.

**Comment by stefanv** [comment]
@alexdesiqueira Do you mind adding a note to the `route_through_array` and `shortest_path` docstrings to point users to this package?

**Comment by alexdesiqueira** [comment]
@stefanv I'm thinking we could reopen the issue and have our small version of `dtw`... what do you think?

**Comment by stefanv** [comment]
@alexdesiqueira Did you change your mind about referring people to the `dtw-python` package?

**Comment by alexdesiqueira** [comment]
@stefanv yeah, ... too much?

**Pull request closed without merging**
