### PR TITLE
Fix matplotlib errors in test suite

### LINKED ISSUE #1802: Viewer errors in test suite under Python 3.x
These appear related to qt5 or the Matplotlib qt5 backend, but only appear in Python 3.x. [See here](https://travis-ci.org/scikit-image/scikit-image/jobs/95082214).

Basic form of the error: 

``` python
  File "/home/travis/build/scikit-image/scikit-image/skimage/viewer/viewers/core.py", line 120, in __init__
    self.fig, self.ax = figimage(image)
  File "/home/travis/build/scikit-image/scikit-image/skimage/viewer/utils/core.py", line 188, in figimage
    fig, ax = new_plot(figsize=figsize, dpi=dpi)
  File "/home/travis/build/scikit-image/scikit-image/skimage/viewer/utils/core.py", line 156, in new_plot
    canvas = new_canvas(**fig_kw)
  File "/home/travis/build/scikit-image/scikit-image/skimage/viewer/utils/core.py", line 136, in new_canvas
    canvas = FigureCanvas(figure)
  File "/home/travis/build/scikit-image/scikit-image/skimage/viewer/utils/core.py", line 116, in __init__
    FigureCanvasQTAgg.__init__(self, self.fig)
  File "/home/travis/venv/lib/python3.4/site-packages/matplotlib/backends/backend_qt5agg.py", line 216, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/travis/venv/lib/python3.4/site-packages/matplotlib/backends/backend_qt5agg.py", line 65, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/travis/venv/lib/python3.4/site-packages/matplotlib/backends/backend_qt5.py", line 239, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
AttributeError: 'figure()' is not a Qt property or a signal
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1802.

Changing from `Agg` -> `Qt4Agg` addresses the original issue, but there is still one test failure.

### CODE REVIEW

**Comment by blink1073** [comment]
I commented out the failing issue, it passes locally but not on Travis.  I don't think it should hold up a release.   I added #1814 for tracking.

**Comment by blink1073** [comment]
This is ready to go, the only failing test is the known `pyamg` failure.

**Comment by stefanv** [comment]
@blink1073 This issue is back on: https://travis-ci.org/stefanv/scikit-image/jobs/122989361

Do you have any advice?

**Comment by blink1073** [comment]
This only happened on that one build?

**Comment by stefanv** [comment]
Yes, I tweaked some bash test and it went away, sorry about the noise.

**Comment by blink1073** [comment]
More gremlins!

**Pull request merged**
