### PR TITLE
DOC: Restore custom sphinx-gallery CSS style settings

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This restores stylistic changes to the sphinx gallery (primarily related to the appearance of the download buttons) that were inadvertently removed in #2666.  Rather than going back to a local copy of `sphinx-gallery`, the `custom.css` file is used to override settings specific to `sphinx-gallery`.

See also discussion in #2666

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
There is currently an unrelated documentation error related to a duplicate citation in a skeletonize example:
https://travis-ci.org/scikit-image/scikit-image/jobs/257033392#L4005-L4007

**Comment by stefanv** [comment]
Yes, it seems not to be a problem on Python 3 + latest Sphinx, so I'm just suppressing docs builds on 2.x for now.

**Comment by soupault** [comment]
I've almost zero expertise in CSS, but let's if it works, and undo if it doesn't. :)

**Comment by soupault** [comment]
Confirmed, everything is good. @grlee77 thanks for the fix!

**Comment by grlee77** [comment]
Great!  Just for future reference, these CSS modifications were mostly copied over from the previous modifications to gallery.css made in #2585 with minor tweaks made to work with the current version of sphinx-gallery.

**Pull request merged**
