### PR TITLE
Handling IO objects with tifffile

### PR DESCRIPTION
**Pull request by jwittenbach**
Addresses #2045 -- allows `tifffile.imsave` and `tifffile.imread` to take IO objects (`File` or `BytesIO`) as targets for output.

First PR to this codebase, so happy for any and all feedback =)

### CODE REVIEW

**Comment by jni** [comment]
Um... You appear to have nuked our README. =P

On another topic, I'm wondering whether this belongs in the upstream project? I don't know where TiffFile "canonically" lives, but the copy in skimage/external is just that, a copy to prevent a dependency, right? CC @blink1073 

Other than that, a clean PR, thank you! One suggestion would be to change the arg name from filename to file.

**Comment by blink1073** [comment]
My concern is that this file and (and my repo) is intended to be a mirror of http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html.  Christoph has the domain knowledge and makes the pertinent updates, I am essentially hosting a mirror.

**Comment by jni** [comment]
@cgohlke would you accept this PR, and if so, where and how should @jwittenbach submit it?

**Comment by cgohlke** [comment]
OK, I'll add that functionality. It's a little more complicated that this PR. You might want to keep the tests; I don't test on non-Windows.

**Comment by jwittenbach** [comment]
Didn't realize this was just a copy of another package to avoid the dependency; thanks for trying to figure out where to put the change. Let me know if there's anything further I should do to get this functionality implemented.

**Comment by JDWarner** [comment]
@jwittenbach, that's why we pinged @cgohlke - he is the author of tifffile. When he says he'll add it, that means it's happening!

**Comment by jwittenbach** [comment]
I noticed that @cgohlke updated the version at http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html to include this functionality -- many thanks! I have now updated the version of `tifffile.py` on this branch to match (with minor edits for testing).

**Comment by blink1073** [comment]
@jwittenbach, do you mind also incorporating the latest http://www.lfd.uci.edu/~gohlke/code/tifffile.c.html as well?

**Comment by jwittenbach** [comment]
@blink1073 Sure thing. Just pushed the commit with the change.

**Comment by soupault** [comment]
@jwittenbach Please, add the summary to https://github.com/scikit-image/scikit-image/blob/master/doc/source/api_changes.txt .
Otherwise :+1: .

**Comment by stefanv** [comment]
This only needs to go into the api docs if it is a backward incompatible
change.

**Comment by jwittenbach** [comment]
@stefanv I think the only API change is a name change on non-keyword arguments and extending the scope of the type of objects that said arguments can handle. My guess would be that that is backwards compatible. Either way, just let me know where I need to document changes and I'll hop to it.

**Comment by stefanv** [comment]
It sounds to me like no additional documentation is needed then.

**Comment by jwittenbach** [comment]
Should I still add a mention in the file that @soupault pointed to or is that unnecessary?

**Comment by soupault** [comment]
@jwittenbach no, nevermind.

**Comment by stefanv** [comment]
@jwittenbach This looks good to me.  Would you mind cleaning up the commits a bit?  There should be two: a) update tifffile to latest version and b) Update skimage tests.  I'm happy to help if it's unclear how to do that.

**Comment by soupault** [comment]
@stefanv it is possible to squash commits and modify commit message with GitHub web-UI now. The prompt appears on `Merge pull request` click.

**Comment by jwittenbach** [comment]
@stefanv sure thing -- something I should know how to do, so I'll give it a shot!

**Comment by stefanv** [comment]
@soupault You should follow my wars on this feature on Twitter :)

**Comment by jwittenbach** [comment]
@stefanv That was a fun and educational dive into rebasing :) Hopefully this is what you had in mind.

**Comment by stefanv** [comment]
@jwittenbach I'm glad :)  Thanks--this looks great.

**Pull request merged**
