### PR TITLE
Enable pytest skipping at module level

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

Closes https://github.com/scikit-image/scikit-image/issues/5511

Thank you @olebole  for so clearly finding the problem.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by grlee77 — APPROVED** [review]
Thanks @hmaarrfk. I was unaware of this option, but it looks like it should resolve the issue.

**Comment by hmaarrfk** [comment]
I can attest that I use this option sometimes.

**Comment by olebole** [comment]
Thank you! I can confirm that this solves the problem.

**Comment by hmaarrfk** [comment]
Thanks for testing it.

**Pull request merged**
