### PR TITLE
On Travis-CI, test with Python 3.6 against the latest NumPy nightly

### PR DESCRIPTION
**Pull request by stefanv**
From a tip by @matthew-brett on the NumPy list

### CODE REVIEW

**Comment by jni** [comment]
> despite that this will occasionally cause lots of failing builds

:joy: 

https://api.travis-ci.org/v3/job/392361657/log.txt

Question: are boolean arrays deprecated??? Or is the nightly build broken??? Also, what's with all the `[1m ... [0m`?

**Comment by soupault** [comment]
@jni it is a syntax for colors in Bash`ian. :)

**Comment by stefanv** [comment]
Ah, good, we already caught something :)

**Comment by jni** [comment]
@stefanv do we still want this in?

**Comment by hmaarrfk** [comment]
xref: https://github.com/scikit-image/scikit-image/pull/3729

I think this should just be closed. this infrastructure stuff goes stale quickly.

**Comment by emmanuelle** [comment]
Let's close this one given the above discussion and what was done in #3729. Stéfan if you have second thoughts you can of course re-open it.

**Pull request closed without merging**
