### PR TITLE
MAINT: fixes #1652

### LINKED ISSUE #1652: Temporary file from file_or_url_context is not removed on error
In case error occured in file_or_url_context (source: https://github.com/scikit-image/scikit-image/blob/master/skimage/io/util.py#L23) on `u = urlopen(resource_name)` or `f.write(u.read())` (lines https://github.com/scikit-image/scikit-image/blob/master/skimage/io/util.py#L28-L29) temporary file created with `tempfile.NamedTemporaryFile(delete=False, suffix=ext)` will not be removed.

### PR DESCRIPTION
**Pull request by sciunto**
#1652

### CODE REVIEW

**Comment by JDWarner** [comment]
:+1: pending tests.

**Comment by sciunto** [comment]
@stefanv OK, now I remember why I didn't implement your solution last time.

If i do this,
```
        try:
            f = tempfile.NamedTemporaryFile(delete=False, suffix=ext)
            u = urlopen(resource_name)
            f.write(u.read())
            f.close()
            yield f.name
```
I ensure that the file is close before I yield, ie the file is written.

**Comment by sciunto** [comment]
Here, I try to combine the two ideas.

**Comment by sciunto** [comment]
I think it's good. I put a comment to reflect that point.

**Comment by JDWarner** [comment]
:+1:, Coveralls is not being helpful.

**Pull request merged**
