### PR TITLE
Use Travis-CI's xvfb service, instead of firing it up manually

### PR DESCRIPTION
**Pull request by stefanv**
Backport of patch made on the v0.14.x branch: https://github.com/scikit-image/scikit-image/commit/5751e4ead9fdc16a89c84b8a372339c49c73af27

### CODE REVIEW

**Comment by jni** [comment]
@stefanv hmmm, sadly this seems to have made things worse...

**Comment by stefanv** [comment]
@jni You think these failures are related? I'll restart the build to be sure.

**Comment by hmaarrfk** [comment]
I'm sorry Stephan, I'm requesting to revert the change https://github.com/scikit-image/scikit-image/commit/5751e4ead9fdc16a89c84b8a372339c49c73af27 
in https://github.com/scikit-image/scikit-image/pull/3695

It is killing the 0.14.x builds with similar errors.

I don't know how to use travis's XVFB service, but maybe have a look at the `DISPLAY` (set in the before install script) variable as well as setting it is related to xvfb.

**Comment by soupault** [comment]
Superseded by #3709

**Pull request closed without merging**
