### PR TITLE
Generalised existing CLAHE implementation to support n dimensions

### LINKED ISSUE #2219: equalize_adapthist leaves artefacts when image size is not a multiple of tile size
Python 3.5.2/Arch Linux/skimage 0.12.3

equalize_adapthist leaves "artefacts" when a dimension of the image is not a multiple of the kernel size:

```
from matplotlib import pyplot as plt
import numpy as np
from skimage.exposure import equalize_adapthist
img = (np.add.outer(np.sin(np.arange(126)), np.arange(128))
       + np.random.randint(3, size=(126, 128))).astype(int)
fig, axs = plt.subplots(1, 2)
axs[0].imshow(img, cmap="gray", interpolation="none")
axs[1].imshow(equalize_adapthist(img), cmap="gray", interpolation="none")
plt.show()
```

adapthist
See the line at the top and the strip at the bottom of the second image.

Possibly related to #757?

### PR DESCRIPTION
**Pull request by m-albert**
## Description
CLAHE (https://en.wikipedia.org/wiki/Adaptive_histogram_equalization) is well defined for n dimensions and I extended the existing implementation in a straight forward manner.

  - only change in main function equalize_adapthist: handling of default argument
  - changed: _clahe and interpolate naturally extended to nd
  - unchanged: functions clip_histogram and map_histogram

First (and only) tests I performed:
- using the new equalize_adapthist on a 2d np.uint16 image yields the same result as the old equalize_adapthist
- new equalize_adapthist yields sensible results in 3d

## Checklist
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests

## References
- the unwanted artefact reported in #2219 is still present (EDIT: fixes #2219)

## For reviewers
- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
@quakberto very cool! Could you add a test that shows this in 3D? Even just checking input against a reference output is useful (to avoid regressions in the future.)

Also, please review your changes to docstrings in terms of whitespace/blank lines, as they violate the NumPy docstring conventions.

Thanks!

**Comment by m-albert** [comment]
Hi, sorry for coming back to this only now. I still think it would be great to have CLAHE for 3d and higher in scikit-image :)

> Could you add a test that shows this in 3D? Even just checking input against a reference output is useful (to avoid regressions in the future.)

As you suggested, I added a simple test consisting of two parts:
1) check that the dimensions are kept in 2d and 3d
2) check that a plane of the result of a stack of 2d images is similar to the result of the 2d image

Here's a visual comparison (vmin=0, vmax=1 for all images):
image

> Also, please review your changes to docstrings in terms of whitespace/blank lines, as they violate the NumPy docstring conventions.

Corrected this, somehow some newlines had disappeared in my first commit.

Two more notes:
1) I saw that in the meantime, #4015 fixed the nan issue. This should be independent from this pull request, right?

2) I realised that `equalize_adapthist` is decorated by `@adapt_rgb(hsv_value)` to handle color images. In the [documentation](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_adapt_rgb.html) it says that `adapt_rgb` is "not recommended for functions that support 3D volumes". So with the current implementation input images with dimension 3 or higher could not be interpreted as color images and 3d images will only be interpreted as such if `img.shape[-1]>4`. Which would be the right way of handling n-dimensional color images in `scikit-image`? At the same time, I doubt that many users would want to work with high dimensional color images or 3d grayscale images with very few columns.

Thanks for any comments and let me know what I can improve :)

**Comment by m-albert** [comment]
After adding the proposed fixes to #2219 one of the CLAHE tests fails:
`test_adapthist_grayscale`
> >       assert_almost_equal(peak_snr(img, adapted), 102.078, 3)
> E       AssertionError:
> E       Arrays are not almost equal to 3 decimals
> E        ACTUAL: 100.15823498443757
> E        DESIRED: 102.078

In principle, the existing 2D tests should see these changes:

- artefacts are taken out
- different effective tile sizes. Before, the tile sizes could be different from the ones indicated in `kernel_size`, because of this code:
https://github.com/scikit-image/scikit-image/blob/2ffd9c823838a7975d1e16601cd724be530c31fa/skimage/exposure/_adapthist.py#L119-L123
the new tile sizes should be equal to the `kernel_size` because the image shape is padded

How to deal with the existing tests?

On another note, one thing that might make sense to add is logic to incorporate the `multichannel` argument and `convert2lab`.

**Comment by rfezzani** [comment]
Hello @m-albert, `equalize_adapthist` border artifacts have been solved in #4349 without image padding, but the nD support that you address in this PR is still a must!
Do you have by any chance some time to fix this here? Thank you ;-)

**Comment by m-albert** [comment]
Hi @rfezzani, great that you fixed the border artefacts and thanks for pinging me :)

Do you think it makes sense to continue working with my extension of the existing 2D CLAHE code into nD or directly adapt @anntzer's [code](https://github.com/anntzer/clahe) which is very elegant and seems to show less artefacts?

I'd be happy to work on getting any of the two incorporated into scikit-image.

**Comment by rfezzani** [comment]
Thank you @m-albert for your enthusiasm ;-)
I think that the actual implementation should be kept as a base line / fast implementation.
@anntzer version should be then implemented in a separate PR.

**Comment by m-albert** [comment]
@rfezzani That makes sense.

Great, would you then recommend rebasing this (rather old) pull request?

**Comment by rfezzani** [comment]
> Great, would you then recommend rebasing this (rather old) pull request?

This is up to you ;-) I f you feel more comfortable opening a new PR, just refer to this one and close it.

**Comment by RealPolitiX** [comment]
We (@VincentStimper,@RealPolitiX) have recently implemented an n-dimensional CLAHE algorithm in tensorflow without constraints for the kernel size using padding.
https://github.com/VincentStimper/mclahe

**Comment by rfezzani** [comment]
Wow! @VincentStimper and @RealPolitiX, the demonstrated examples [gh-mclahe](https://github.com/VincentStimper/mclahe) are really beautiful :clap:
It is not planed to add tensorflow as a dependency for skimage, and I refer to this https://github.com/scikit-image/scikit-image/issues/4478#issuecomment-590190956 concerning the possible integration of `mclahe` in skimage ;-)

**Comment by VincentStimper** [comment]
Thanks! 
Since I'm going to rewrite `mclahe` soon anyway, I could also do a pure numpy implementation if this makes the integration easier.

**Comment by pattonw** [comment]
Hey, I'm also interested in using mclahe. Are there any updates on this topic and is there anything I can do to help?

**Comment by VincentStimper** [comment]
I've finished the NumPy only implementation of MCLAHE (not using Tensorflow), see the numpy branch in my repository
https://github.com/VincentStimper/mclahe/tree/numpy
We could integrate it in skimage now.

**Comment by m-albert** [comment]
> This is up to you ;-) I f you feel more comfortable opening a new PR, just refer to this one and close it.

Was working on this lately and opened a new pull request https://github.com/scikit-image/scikit-image/pull/4598 with my changes embedded into the current master.

**Comment by m-albert** [comment]
Closing this PR in favor of (merged) https://github.com/scikit-image/scikit-image/pull/4598.

**Pull request closed without merging**
