### PR TITLE
[DOC] add favicon

### PR DESCRIPTION
**Pull request by sciunto**
I think this will fix a bunch of errors in this check-up: https://linkchecker.sciunto.org/scikit-image.org-docs_stable

### CODE REVIEW

**Comment by stefanv** [comment]
What do you think: is it best to use the scipy favicon, or our own logo?

**Comment by sciunto** [comment]
I used the favicon from scikit-image-web but you raise a good point. The new beautiful logo can be used too. I made a quick patch here to generate a favicon: https://github.com/scikit-image/skimage-branding/pull/2

If it looks ok for you @stefanv then, I can update the favicon elsewhere.

**Comment by emmanuelle** [comment]
It'd be so cool to have our own favicon!

**Comment by stefanv** [comment]
Neat!  I merged the other PR, and will merge this as soon as updated.

**Comment by sciunto** [comment]
@stefanv Cool. This PR is updated.

**Comment by emmanuelle** [comment]
Thanks @sciunto !

**Pull request merged**
