### PR TITLE
Also document submodules, and ignore private modules `_*`

### PR DESCRIPTION
**Pull request by stefanv**
This allows `skimage.future` to be included in the API guide.

### CODE REVIEW

**Comment by soupault** [comment]
Travis fails on Py3.4 with docs:
```
Warning, treated as error:
/home/travis/build/scikit-image/scikit-image/doc/source/api/skimage.data.rst:8: (WARNING/2) autodoc: failed to import module 'skimage.data.np'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'skimage.data.np'
make[1]: *** [html] Error 1
make[1]: Leaving directory `/home/travis/build/scikit-image/scikit-image/doc'
make: *** [html] Error 2
```

**Comment by stefanv** [comment]
@jni 0.13.1 does not build without this patch.

**Comment by jni** [comment]
@stefanv what do you mean? the docs? or the .future docs?

**Comment by jni** [comment]
Also, do you suggest I patch and release 0.13.2, or overwrite the tag? I favour the former.

**Comment by stefanv** [comment]
Without that patch, I could not get a clean docs build working.  So I guess we're in for 0.13.2.

**Comment by jni** [comment]
@stefanv that's fine, I'll backport my watershed speedup too, I think people might appreciate that. =) I might have a whack at getting Travis to build stable release docs too, when a new tag is uploaded... Tips on how to do this are appreciated!

**Comment by stefanv** [comment]
See https://github.com/scikit-image/scikit-image/blob/master/tools/travis/deploy_docs.sh

**Pull request merged**
