### PR TITLE
Add builds for aarch64

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

Updating builds for aarch64: https://github.com/scikit-image/scikit-image-wheels/pull/47

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
I cancelled the Travis job for now. Can you disable Travis temporarily in this PR while testing other things? I thought we needed Travis for the AArch64 builds, but all the ones in the job I just canceled were AMD64.

**Comment by hmaarrfk** [comment]
I'm not too sure how ghactions works. I just figured i would try to follow a pattern.

@jni where did you see the artifact outputs. 

Am i expecting artifacts from this build?

**Comment by jni** [comment]
@hmaarrfk the wheel building actions are triggered on:

```yaml
on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
      - cibuildwheel
    tags:
      - v*
```

and not on PRs. So, you should make PRs that change the wheel building to by creating a `cibuildwheel` branch. I just did this with your branch. Build happening [here](https://github.com/scikit-image/scikit-image/actions/runs/401997255).

There is a lot of contributing documentation to be updated about all this. We haven't done it yet because we've done all this in quite a rush...

**Comment by jni** [comment]
Hmm, @hmaarrfk what is the aarch suffix? Are the aarch wheels here? Or is there an upload missing maybe?

Screen Shot 2020-12-05 at 5 41 48 pm

**Comment by grlee77** [comment]
The wheels should end with a name like: `manylinux2014_aarch64.whl`
For example, the following were created by merging scikit-image/scikit-image-wheels#47: https://anaconda.org/scipy-wheels-nightly/scikit-image/files

I don't think it is possible to build the wheels for ARM via GitHub Actions (although perhaps it is possible via qemu emulation or something like that). We can do ARM builds on Travis at `scikit-image-wheels`, but now our credits have expired again. We can either request more credits again or build them after we get 10,000 credits again at the end of the month. Now that Travis is disabled on the main repo we shouldn't run out too fast.

We can potentially move these Travis-based ARM builds to this repo and use cibuildwheel for those as well if we want to keep all wheel builds in one place.

**Comment by jni** [comment]
> We can potentially move these Travis-based ARM builds to this repo and use cibuildwheel for those as well if we want to keep all wheel builds in one place.

I think this is a good choice. I also wonder whether qemu might keep things simpler (all wheels upload to one place). Medium term I'd like our tags to directly push the wheels to PyPI, as we do in napari.

**Comment by janaknat** [comment]
@hmaarrfk @jni I've got a PR(https://github.com/scikit-image/scikit-image/pull/5197) to use Github Actions and cibuildwheel to build the aarch64 wheels. cibuildwheel support non-native architecture builds from v1.8.0 onwards. See https://cibuildwheel.readthedocs.io/en/stable/options/#archs for more information.

**Comment by grlee77** [comment]
closing as outdated (#5197 add aarch64 wheels)

**Pull request closed without merging**
