### PR TITLE
Update Matplotib Plugin Docstring and Create Test Module Setup Function

### PR DESCRIPTION
**Pull request by blink1073**
Completes #1300.

### CODE REVIEW

**Comment by jni** [comment]
@stefanv shouldn't you wait for Travis before merging shit? ;)

**Comment by jni** [comment]
@blink1073 I mean "shit" in the sense of "stuff" LOL

**Comment by blink1073** [comment]
That's why he's our *fearless* leader.

**Comment by jni** [comment]
Oh well. At least we don't have a badge on the README anymore... =P

**Comment by stefanv** [comment]
I don't expect anything less than perfection from the core team, of course...

**Pull request merged**
