### PR TITLE
Migrate to networkx 2.x

### PR DESCRIPTION
**Pull request by jarrodmillman**
## Description

This should complete the migration from networkx 1.x to 2.x:
https://networkx.github.io/documentation/latest/release/migration_guide_from_1.x_to_2.0.html

In 2.4, we deleted several deprecated features:
https://networkx.github.io/documentation/latest/release/release_2.4.html

According to your `requirements/default.txt` file, you currently require `networkx>=2.0`, which should be fine as the new interface was introduced in 2.0.

See #4235.

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Do we want to backport this to 0.16.1?

**Comment by jarrodmillman** [comment]
I would.  You've required nx>2.0 since at least 0.15.  So these changes shouldn't create any problems.  I plan to release networkx 2.4 in about a week, so without this patch 0.16.x will fail the current version of networkx at that point.

**Comment by jni** [comment]
0.16.2, 0.16.1 is already tagged (there was a snafu with the 0.16.0 tag). But yes!

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.16.x

**Comment by hmaarrfk** [comment]
I guess we shouldn't backport to 0.14.x since the primary use is 2.7 now that we will have 0.16.1 out soon.

(There are a few bugs fixed in 0.14 that have not been fixed in 0.15)

**Comment by jni** [comment]
@hmaarrfk I agree, not much point adding to 0.14, but we *should* probably backport to 0.15, as I expect there will still be quite a few of those out there "in the wild".

**Comment by jni** [comment]
@meesseeksdev backport to v0.15.x

**Pull request merged**
