### PR TITLE
Complete deprecation of `plot_matches`

### PR DESCRIPTION
**Pull request by lagru**
## Description

`plot_matches` was deprecated by us in https://github.com/scikit-image/scikit-image/pull/7255 in favor of `plot_matched_features`. We forgot to update the gallery and `__init__.py` accordingly.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpydoc/blob/main/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

For maintainers and optionally contributors, please refer to the [instructions](https://scikit-image.org/docs/stable/development/contribute.html#documenting-changes) on how to document this PR for the release notes.

```release-note
...
```

### CODE REVIEW

**Review by mkcor — APPROVED** [review]
Oh, thanks for catching this, @lagru! :pray:

**Comment by mkcor** [comment]
Minor detail: I think this PR is about maintenance rather than bug fix...

**Comment by lagru** [comment]
I'd consider it a bug because we tell users in a deprecation message to use `plot_matched_features` which can't actually be imported from `skimage.feature`. That's broken API. 

I actually realize, that this PR also needs to keep the old `plot_matches` around during the deprecation cycle. Let me fix that right now.

**Comment by mkcor** [comment]
Oh, you're right.

> I actually realize, that this PR also needs to keep the old `plot_matches` around during the deprecation cycle. Otherwise we'll just break users.

Right *bis*. Btw, should we remove it 'right before' or 'right after' we release 0.25?

**Comment by lagru** [comment]
The deprecaction message says `removed_version="0.25"`, after releasing 0.24 and before releasing 0.25. :sweat_smile: Ha, so we can just remove it now since I don't anticipate us making a minor 0.24.x release. :see_no_evil:

**Review by stefanv — APPROVED** [review]

**Comment by lagru** [comment]
Since two maintainers -- Stéfan and me -- have looked at the recent version I'm going ahead and merge now.

**Comment by mkcor** [comment]
Yes, sorry for not being super reactive these days! I meant to get back to it and re-approve with the latest changes, but when I saw the 5 CI failures, although I suspected they would be unrelated to this PR, it made me pause, thinking "I'll take a slightly closer look!"

**Comment by mkcor** [comment]
PS: Oh, ok! Reading #7491 now. Thank you, @lagru! :pray:

**Pull request merged**
