### PR TITLE
style: be explicit when stacking arrays

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This PR relies on calling `np.stack` explicitly rather than relying on implicit stacking of lists of arrays via `np.array`. I think this "explicit is better than implicit" approach is preferable from a readability standpoint. 

There should be no change in existing behavior, it is purely a style/maintenance PR. That said, there will be a change in the contiguity of the returned type in at least one place. In `adapt_rgb.py` the current code

```Python
    return np.moveaxis(np.array(c_new), 0, -1)
```
returns an F-ordered array while the updated code

```Python
    return np.stack(c_new, axis=-1)
```
returns a C-ordered array. I don't think we typically guarantee a specific contiguity for the returned arrays, but it is something to consider.

This issue was inspired by discovering that passing lists of arrays to `array()`, or `tranpose()` does not work in CuPy. So, in addition to style/readability benefits, it may also ease potentially supporting other array module backends in the future.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
These were only the instances I came across when working on GPU conversions for  `cupyimg`. Let me do a quick grep of the codebase to see if there are any other obvious instances in functions I didn't consider there.

**Comment by grlee77** [comment]
In revisiting this, implicit stacking of a list of arrays (even if they are NumPy arrays!) along axis 0 when calling 
`cupy.array` does work with recent CuPy (master) + NumPy (1.18.5). I don't think that was previously the case.

So, some of these changes are no longer strictly needed for that purpose.  I still don't think it hurts to be explicit in using `stack` instead, though.

**Comment by alexdesiqueira** [comment]
@grlee77 thanks Greg!

**Comment by jni** [comment]
Very lovely, thanks @grlee77!

**Pull request merged**
