### PR TITLE
pypi: explicitly exclude Python 3.1, 3.2, and 3.3

### PR DESCRIPTION
**Pull request by stefanv**
See also: https://github.com/scikit-image/scikit-image/issues/3713

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Are you going to rebuild 3.4?

**Comment by stefanv** [comment]
Cannot rebuild 3.4 without a working Matplotlib, since *that* is not yet an optional dependency.  @matthew-brett uses [this script](https://github.com/matthew-brett/manylinux-builds/blob/master/build_matplotlibs.sh) to build Matplotlib.  We only need one version that works on every platform.

**Comment by hmaarrfk** [comment]
you could skip the tests no?

Matplotlib isn't necessary to build.

In either case, if you wanted matplotlib to be an optional dependency, I can put the final 30 mins of work to clean it up, but since it touches the build system, it is hard to keep the PR in a mergable state.

**Comment by stefanv** [comment]
Thinking about it more: these wheels would not be installable unless we made Matplotlib fully optional.

**Comment by hmaarrfk** [comment]
The work is already done for making matplotlib optional. We can add a switch that would fall back on the poolygon clip algorithm from AGG if matplotlib is installed

**Comment by stefanv** [comment]
I think this is probably exactly what Matplotlib uses: https://github.com/stefanv/supreme/blob/master/supreme/ext/polygon.c#L121

**Comment by hmaarrfk** [comment]
Ok, I suggested it, on the PR, but I don't think the implementation detail
is what is holding up that PR.
That implementation detail could also be fixed in a separate issue.

**Comment by hmaarrfk** [comment]
Isn't matplotlib available on pypi for 3.4???
https://pypi.org/project/matplotlib/2.2.3/#files

**Comment by stefanv** [comment]
On Mon, 04 Feb 2019 17:53:10 -0800, Mark Harfouche wrote:
> Isn't matplotlib available on pypi for 3.4???
> https://pypi.org/project/matplotlib/2.2.3/#files

Looks like they are; I was thinking of 32-bit.

Should check why those 0.14.x builders never built our 3.4 wheels,
then.

Something like this:
https://travis-ci.org/scikit-image/scikit-image-wheels/builds/481253099

**Comment by hmaarrfk** [comment]
thats the dask array dependency, that I think I just fixed.

I think the easiest solution there is just to release 0.14.3

https://github.com/scikit-image/scikit-image/blob/v0.14.x/requirements/optional.txt#L13

**Comment by hmaarrfk** [comment]
It also seems that some where missing matplotlib. that can be for 0.14.4 ;)

**Comment by stefanv** [comment]
Agreed, 0.14.3 should be easy enough.

**Pull request merged**
