### PR TITLE
Docstring

### PR DESCRIPTION
**Pull request by sciunto**
Counter-side of #2140 + a small addition in a docstring.

### CODE REVIEW

**Comment by soupault** [comment]
`..:math:` is not being rendered, anyway: http://scikit-image.org/docs/dev/api/skimage.transform.html?highlight=polynomialtransform#skimage.transform.PolynomialTransform .
:+1:

**Comment by stefanv** [comment]
​It wouldn't, because the syntax is `.. math::`.

**Comment by sciunto** [comment]
@stefanv : @ahojnnes raised the point that latex is difficult to read in #2140

**Comment by stefanv** [comment]
I agree with him; I was only mentioning that the ``.. math::`` directive
will render fine (but mis-spelling the directive of course won't).

**Pull request merged**
