### PR TITLE
Silence PyData theme warning about new default for "navigation_with_keys"

### PR DESCRIPTION
**Pull request by lagru**
## Description

Hopefully addresses our [failing Windows CI](https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=10593&view=logs&j=feb0b66f-d63c-5533-bf34-a72e08b12053&t=26b7b1f7-60f2-5676-21d5-45b533330524). The new default (`False`) apparently has the nice benefit of improving keyboard navigation (see https://github.com/pydata/pydata-sphinx-theme/issues/1492).

With PyData theme v0.14.2 [a warning is raised](https://github.com/pydata/pydata-sphinx-theme/blob/fe02751fa10a9487d38d65e817cb007d6d413d2f/src/pydata_sphinx_theme/__init__.py#L53-L63) about a changing default config option. As it is treated as an error by our Windows CI mute it by setting it explicitly to the new default.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
Stop HTML documentation from intercepting left and right-arrow keys
to improve keyboard accessibility.
```

### CODE REVIEW

**Review by soupault — APPROVED** [review]
The CI is happy. 👍🏻

**Comment by mkcor** [comment]
Hi @lagru, I'm confused because (today) I'm getting this warning when I build the docs:
```bash
[...]
myst v2.0.0: [...]
The default value for `navigation_with_keys` will change to `False` in the next release.
If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the
`html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has
negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
building [mo]: targets for 0 po files that are out of date
[...]
```
I checked locally and I'm indeed running pydata-sphinx-theme >= 0.15.0
```
$ python
>>> import pydata_sphinx_theme
>>> pydata_sphinx_theme.__version__
'0.15.2'
```

PS: Noticing that we are ready to support multiple languages (translations) when reading "po files..." :wink:

**Comment by mkcor** [comment]
I'll update the other docs dependencies...

**Comment by lagru** [comment]
@mkcor I can't reproduce your warning. Let's check in person.

**Comment by stefanv** [comment]
I don't see any warnings on current `main`, with upgraded `sphinx`, `myst`, `myst-parser`, `pydata-sphinx-theme`, and `pygments`.

**Comment by mkcor** [comment]
Oh, there we go!

Did:
```bash
$ pip install myst-parser==4.0.0  # somehow -U wouldn't upgrade, although I had version 2.0.0
$ pip install myst==1.0.4
$ pip install -U pydata-sphinx-theme  # which upgraded to version 0.15.4
```

The "navigation_with_keys" warning is gone and I could see the "pygments-*" warnings before syncing up `main`.

Thank you, both! :pray:

**Comment by stefanv** [comment]
@mkcor https://github.com/scikit-image/scikit-image/pull/7511

**Pull request merged**
