### PR TITLE
Document the multichannel->channel_axis transition in the release notes

### PR DESCRIPTION
**Pull request by grlee77**
## Description

I put the most detail under the API section, but there were also deprecation and new feature components.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by mkcor — APPROVED** [review]
Wonderful! I appreciate your writing style, @grlee77: It is very clear.

**Comment by mkcor** [comment]
By the way, I wonder if we should turn
https://github.com/scikit-image/scikit-image/blob/dad624b0f1063d653a1d7e7beba080312cfd59b6/skimage/color/colorconv.py#L746
into
```py
def rgb2gray(rgb, channel_axis=-1)
```
'simply' adding a call to `np.moveaxis` at the beginning of the function... :thinking:

**Comment by grlee77** [comment]
> def rgb2gray(rgb, channel_axis=-1)

Good point. The prior PRs deprecated `multichannel`, replacing it with `channel_axis`. However, we probably want to also add a new `channel_axis` PR to any functions that always assumed a color image for input and thus did not have a `multichannel` argument previously. This would include many functions in `skimage.color`, but I'm not sure if there are also others outside of that package?

**Comment by rfezzani** [comment]
> By the way, I wonder if we should turn
> 
> https://github.com/scikit-image/scikit-image/blob/dad624b0f1063d653a1d7e7beba080312cfd59b6/skimage/color/colorconv.py#L746
> 
> into
> 
> ```python
> def rgb2gray(rgb, channel_axis=-1)
> ```
> 
> 'simply' adding a call to `np.moveaxis` at the beginning of the function... thinking

It's funny, I though about that when reviewing your PR @mkcor #5420 ([here](https://github.com/scikit-image/scikit-image/pull/5420/files#diff-86a281d5e54219571aa714be839b3d6d1044d45918761c000cbd8ecd153d2590R56)) :smile:

**Comment by mkcor** [comment]
> It's funny, I though about that when reviewing your PR @mkcor #5420 (here) :smile:

@rfezzani I know!! :wink:

**Comment by mkcor** [comment]
> [...] but I'm not sure if there are also others outside of that package?

I don't know right off the bat. I'll open an issue so we can keep track.

By the way, this PR is a documentation one, so I guess I can go ahead and merge without a second approval.

**Pull request merged**
