### PR TITLE
ENH: `make clean` now removes compiled .c and .pyd files.

### PR DESCRIPTION
**Pull request by JDWarner**
As reported by @grlee77 as a sidenote in #1583, `make clean` previously did not remove all compiled files.

Now the `clean` target removes Cythonized `.c` files as well as `.pyd` files, which are the Windows equivalent of `.so`, for those using Cygwin or similar to have `Makefile` support on Windows.

### CODE REVIEW

**Comment by grlee77** [comment]
see my comment in #1583 about not accidentally removing other .c files in the codebase not generated by cython
e.g.
``restoration/unwrap_2d_ljmu.c``
``restoration/unwrap_3d_ljmu.c``

I guess a .c file should only be removed if there is a matching .pyx file

**Comment by JDWarner** [comment]
@grlee77 You're right, time for some RegEx-fu.

**Comment by JDWarner** [comment]
@grlee77 I think this handles it.

**Comment by grlee77** [comment]
this works for me.  thanks @JDWarner

**Pull request merged**
