### PR TITLE
Various updates to the ASV benchmarks

### PR DESCRIPTION
**Pull request by TomAugspurger**
## Description

A few fixups for the ASV benchmarks:

1. ASV expects a `__init__.py` in the benchmarks dir
2. For `mem_` tests, the object has to be returned
3. Added the generated `.asv` directory to the `.gitignore` 

## Checklist

- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks!

**Comment by jni** [comment]
@TomAugspurger ah, but I don't think we care very much about the result. So there is no way to measure the *internal* memory used by a function?

**Comment by stefanv** [comment]
Right, good point.

**Comment by TomAugspurger** [comment]
I wonder, is
https://github.com/airspeed-velocity/asv/blob/master/docs/source/writing_benchmarks.rst#peak-memory
what we want?

**Comment by jni** [comment]
@TomAugspurger yes that is exactly the right thing! =) Mesohappy.

**Pull request merged**
