### PR TITLE
Backport PR #4219 on branch v0.14.x (FIX + MAINT installation of cask on travis (OSX))

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #4219: FIX + MAINT installation of cask on travis (OSX)

### CODE REVIEW

**Comment by jni** [comment]
@hmaarrfk given that Jan 1 2020 is fast approaching, I don't know that we'll make another 0.14 release. Let's leave this open until that date in case we do need to come back and fix the branch. =)

**Comment by hmaarrfk** [comment]
I guess there is also an issue with the Linux builds due to a change in how Travis chose the default images.

**Comment by jni** [comment]
@soupault I agree, I just presumed that we would want to get the CI passing before merging, and that might take effort, and it's effort that might be better spent elsewhere. =)

**Comment by hmaarrfk** [comment]
@jni this passes the apple builds. Lets just merge this one line while we find the correct backports for the other builds.

**Comment by jni** [comment]
Okely. =)

**Pull request merged**
