### PR TITLE
Fix doctests and restore doctesting on CI

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This PR fixes doctest failures that were observed locally. ~I need to still debug on CI to see why the failures weren't showing up there.~

The underlying issue is that the TEST_ARGS environment variable was being set during the **Build package** build step, but the tests are run during a separate **"Run tests"** build step. This was a problem because the environment variables apparently get reset between steps. Moving the definition of TEST_ARGS to the test runner script resolved the issue.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
The change in bc15198 was sufficient to get the doctests running again. When I tried reverting the fixes in b6d5732, the expected failure was observed on the GHA jobs.

**Comment by grlee77** [comment]
This branch is based off of #5503 since that PR changed and fixed the broken doctest for `blob_dog`. This can be rebased and the debug history cleaned up after that one is merged.

**Comment by grlee77** [comment]
Is anyone from @scikit-image/core available to do a quick review here?

The actual fix is the small change in https://github.com/scikit-image/scikit-image/pull/5505/commits/e0407ac3e6cd7d61dfdd760ffb278d85c2a7e550 (the environment variable does not persist across sections on GitHubActions, so the doctests had not been getting run ever since we switched away from TravisCI!)

The other individual commits are fixes to doctests that had become broken over the last several months or changes to avoid warnings.

**Review by alexdesiqueira — APPROVED** [review]
Looks great! Thanks @grlee77!

**Pull request merged**
