### PR TITLE
TEST - DO NOT MERGE remove lily

### PR DESCRIPTION
**Pull request by sciunto**
## Description

A test for #4958 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
```

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx\cmd\build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx\application.py", line 278, in __init__
    self._init_builder()
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx\application.py", line 334, in _init_builder
    self.events.emit('builder-inited')
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx\events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx_gallery\gen_gallery.py", line 434, in generate_gallery_rst
    seen_backrefs)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx_gallery\gen_rst.py", line 362, in generate_dir_rst
    fname, target_dir, src_dir, gallery_conf, seen_backrefs)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx_gallery\gen_rst.py", line 847, in generate_file_rst
    gallery_conf)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx_gallery\gen_rst.py", line 976, in save_rst_example
    gallery_conf)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\sphinx_gallery\binder.py", line 112, in gen_binder_rst
    binder_logo_path = os.path.relpath(binder_logo, gallery_conf['src_dir'])
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py", line 584, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:
```

**Comment by sciunto** [comment]
oh, wait. Isn't is related to this recent change in sphinx-gallery? https://github.com/sphinx-gallery/sphinx-gallery/issues/735

**Comment by sciunto** [comment]
they released a version 3 days ago... Ping @larsoner @lucyleeow

**Comment by lucyleeow** [comment]
Yes, the error is a line I changed recently. I did have a bad feeling about it - my bad, I'll look into it.

**Comment by sciunto** [comment]
thanks for commenting so quickly @lucyleeow :)

**Pull request closed without merging**
