### PR TITLE
Fix networkx for v0.14.x and python 2

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
Sigh, networkx needs to release things in non-zip format.

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
Probably something @jarrodmillman would like to know about.

**Comment by jni** [comment]
@hmaarrfk can you point to the issue that this is addressing?

**Comment by hmaarrfk** [comment]
i think it is just the `--pre` build in 2.7 that fails due to some strangeness in packages dropping 2.7 this year.

**Comment by jarrodmillman** [comment]
NetworkX dropped support for Python 2 (we did it 8 days after you guys).  I am not sure what issue you are running into with the zip format.  Can you be a little more specific about what problem that is causing?

**Comment by hmaarrfk** [comment]
I don't think it is networkx in particular, or the zip format (though networkx is the first package I encountared that ships via zip)

For example, see this build that is failing with a strange error message
https://travis-ci.org/scikit-image/scikit-image/jobs/526723143#L973

Note that it passes the `--pre` flag to pip during the builds. I think it might be time to drop the `--pre` flag, but the `--pre` flag allows us to anticipate breakage with new versions of numpy/scipy

**Comment by jarrodmillman** [comment]
I just deleted `2.3rc1` and `2.3rc2` from PyPI.  I added 
```
python_requires='>=3.5'
```
in https://github.com/networkx/networkx/commit/dca6362a2bde91a4b228d9f7a58d69b146a2614f
after `2.3rc2`, but before `2.3rc3`.  So now if you are running Python 2.7 and type
```
$ pip install --pre networkx
```
it should still install `2.2`.  Would you mind rerunning the Travis job to see if the problem is resolved?  You shouldn't need to remove the `--pre` flag or add anything to your requirements file.

**Comment by stefanv** [comment]
Thanks, Jarrod!

**Comment by hmaarrfk** [comment]
@jarrodmillman thanks a bunch !!! this really simplifies our pinnings and our tests are now able to get back to green without too many hacks! I never knew you could actually supply pip packages via zip formats. so many things!

**Pull request closed without merging**
