### PR TITLE
FIX: Correct typo in local version of tifffile _replace_by

### PR DESCRIPTION
**Pull request by JDWarner**
Should fix the error reported in #1548. Also added a minor point to our local __version__ for this file.

### CODE REVIEW

**Comment by stefanv** [comment]
Does this 0.3.4 correspond exactly to the one on Christoph's webpage?

**Comment by JDWarner** [comment]
From what I can find, it looks like the tifffile package on PyPi is maintained by our very own @blink1073 - that's where the __version__ number came from. The current version is 0.4, and it's undergone a few improvements from the original at Christoph's site - including changes to the `_replace_by` decorator. 

This issue remains in the PyPi source, but I'm about to submit a fix to blink1073/tifffile including this fix.

**Comment by JDWarner** [comment]
As of this commit, `tifffile_local.py` will be exactly identical to `tifffile.py` on PyPi once blink1073/tifffile#6 is merged and version 0.4.1 pushed up.

**Comment by JDWarner** [comment]
I lied, turns out they can't be exactly identical. tifffile isn't a package, it's a module, so `from . import` doesn't work.

They are as close as possible while retaining our relative import conventions, differing in exactly one line where `_tifffile` is imported.

**Comment by blink1073** [comment]
Thanks @JDWarner, the typo was actually from my version of the `tifffile` package.  I just release a new on on PyPI with the fix.

**Comment by blink1073** [comment]
...and catching up I see you already knew that.  Beat you to it.  :smile:

**Comment by JDWarner** [comment]
@blink1073 I do think we still need this merged into the main repo, as it's a separate local version here rather than depending on the PyPi version.

Unless you want to transition to making the PyPi version a dependency...? Even if so, we should patch this here and then have that discussion.

**Comment by blink1073** [comment]
Oh, agreed, forgot to merge!

**Pull request merged**
