### PR TITLE
Adding new default values to functions on doc/examples/segmentation/plot_ncut

### PR DESCRIPTION
**Pull request by alexdesiqueira**
## Description

Small fix. Solves unexpected behavior on the [normalized cut example](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_ncut.html#sphx-glr-auto-examples-segmentation-plot-ncut-py).

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks @alexdesiqueira ! I'm going to merge this one as soon as Travis is happy. I still don't understand why the example looks good on master but not on 0.17.x...

**Comment by emmanuelle** [comment]
Well in fact the example looks better after your fix than on the dev doc.

**Comment by alexdesiqueira** [comment]
@emmanuelle I based myself on the warnings we received:

```
FutureWarning: skimage.measure.label's indexing starts from 0. In future version it will start from 1. (...)
FutureWarning: The new recommended value for bg_label is 0. (...)
```

Maybe some of the variables were impaired on the process, and now that they have the "better" defaults things are okay? :)

**Comment by emmanuelle** [comment]
@meeseeksdev backport to v0.17.x

**Pull request merged**
