### PR TITLE
Allow viewer plot plugin to have tools

### PR DESCRIPTION
**Pull request by blink1073**
We added a tool manager to the viewer, but the plot plugin needs to have its own tool manager.  This affected the color_histogram plot plugin.

https://groups.google.com/forum/#!topic/scikit-image/f8E7xJaQ0_s

### CODE REVIEW

**Comment by tacaswell** [comment]
You folks know about https://github.com/matplotlib/matplotlib/blob/master/doc/users/whats_new/toolmanager.rst ?

**Comment by blink1073** [comment]
Looks like the *right* way to do it, eventually.

**Comment by tacaswell** [comment]
Eventually is going to be an awesome time! :wink:

**Comment by blink1073** [comment]
@stefanv, this is addressing a demonstrated bug and is ready to merge in my opinion.

**Comment by JDWarner** [comment]
Agreed, looks great from my perspective!

**Pull request merged**
