### PR TITLE
Added catch for zero image in threshold_li

### PR DESCRIPTION
**Pull request by jmetz**
Fix for #2337 - pending decision on how/whether to handle.

### CODE REVIEW

**Comment by jmetz** [comment]
**Note** an alternative to returning zero could be to raise a more sensible Exception, which is what `threshold_otsu` does for example.

**Comment by soupault** [comment]
@jmetz thanks for reporting this issue!
I don't think that your current fix is the right one: user can pass any image with any single intensity value and get the same results (i.e. `np.full((100, 100), 5, dtype=np.uint8`).
Regarding the handling of such cases, I'd be fine with an Exception.

**Comment by sciunto** [comment]
Why not `max_iter` like in threshold_minimum? I raised the fact that such loop could cause issues during the review and we adopted this solution.

**Comment by jmetz** [comment]
I don't understand what you're suggesting @sciunto - could you elaborate? 
@soupault - thanks for pointing that out; I've updated the PR to check for differing values or raise an exception.

**Comment by jni** [comment]
@jmetz this is the right fix imho, but it needs a corresponding test.

**Comment by jmetz** [comment]
@jni - thanks for the reminder - just added in a simple test - look ok?

**Pull request merged**
