### PR TITLE
Nogil

### PR DESCRIPTION
**Pull request by ahojnnes**

### CODE REVIEW

**Comment by JDWarner** [comment]
@ahojnnes Looks great so far, let know when ready to merge.

**Comment by jni** [comment]
This is tremendously exciting...!

**Comment by mrocklin** [comment]
Hooray for releasing the GIL.  Curious have errors come up?  We often rely on the GIL without realizing it.

When this is complete I would personally love to see a public writeup on the experience of releasing the GIL within scikit-image.  I think that the community should do this more broadly; scikit-image could lead a bit here.

**Comment by ahojnnes** [comment]
Assuming that all tests pass, I am through with "nogilling" all Cython code.

@mrocklin I think, it was pretty straightforward. It is very helpful to use `cython -a ...` to figure which code actually accesses Python objects (usually only the yellow lines). Going through the code once again also helped to replace some Python code with pure C code.

**Comment by stefanv** [comment]
Stellar work!  Doesn't look like NAN is recognized under Windows :/  Also, perhaps good to rebase on master.

**Comment by ahojnnes** [comment]
Thanks Stefan. This should hopefully do the trick.

**Comment by stefanv** [comment]
This is a major step forward--thanks @ahojnnes !

**Comment by mrocklin** [comment]
Hey look, momentum https://github.com/pydata/pandas/pull/10199

**Comment by jreback** [comment]
I DID ruthlessly steal your ``test_parallel`` (open-source, gotta luv it!)

**Comment by ahojnnes** [comment]
No problem, go ahead and copy as much as you want ;-) I am glad it gets reused and look forward to feedback or ideas how to improve the testing.

**Pull request merged**
