### PR TITLE
Add helper functions img_as_float32 and img_as_float64

### PR DESCRIPTION
**Pull request by silverneko**
## Description
The `img_as_float` converts images to `float64` (double precision). However sometimes it can be helpful if we store images in `float32` (single precision) regarding memory consumption and bandwidth.
This PR adds two helper functions `img_as_float32` and `img_as_float64` to skimage.util.dtype, and change `img_as_float` to an alias to `img_as_float64`.

Changes:
- Add `img_as_float32`: Converts image to `float32`
- Add `img_as_float64`: Converts image to `float64`
- Change `img_as_float` to an alias to `img_as_float64`

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by stefanv** [comment]
Yup, that seems like a perfectly legitimate addition. Thanks!

**Comment by stefanv** [comment]
W.r.t. naming convention, perhaps we should have `img_as_single` and `img_as_double`, and alias `img_as_float` to `img_as_double`; what do you think?  (I compared, e.g., to `img_as_ubyte`.)

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/1234

**Comment by jni** [comment]
Thanks @silverneko!

**Pull request merged**
