### PR TITLE
 Missing cval parameter in threshold_local

### LINKED ISSUE #3230: Missing cval parameter in threshold_local
## Description
Maybe I am missing something, but I cannot set the `cval` parameter when using mode `constant` with `threshold_local`.

`TypeError: threshold_local() got an unexpected keyword argument 'cval'`

## Way to reproduce
Tried with both v0.13.1 and v0.14.0. It is missing also from the API documentation of 0.15dev so I am not sure if it got fixed yet (if a bug at all) and it does not appear in the source code either.

Thanks! :)

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Fixes #3230

 I guess we need a unittest for that...

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
it closes issue #3230 

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
@sciunto 

> I guess we need a unittest for that...

Yes, that would be ideal... =) A simple filter with `mode='constant'` and cval being a value higher than 0 (maybe 1.0) would probably be sufficient. You can use a tiny image for this.

**Comment by sciunto** [comment]
@jni test added :)

**Comment by jni** [comment]
Yep: https://github.com/sphinx-doc/sphinx/issues/5361

**Comment by jni** [comment]
I've reset the Travis cache in case that fixes it, as semi-suggested by the issue in Sphinx. I'm also submitting a PR so that Sphinx 1.7.8 is avoided in future builds.

**Comment by jni** [comment]
Hooray, green! =)

**Pull request merged**
