### PR TITLE
Use imageio v3 API

### PR DESCRIPTION
**Pull request by stefanv**
In response to
https://discuss.scientific-python.org/t/full-support-for-4-channel-images-in-imsave/651/9

Thanks for the prod, @FirefoxMetzger

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
I had a quick look at CI and it looks like the tests that break call `imsave`. This was an alias for `imwrite`, which we dropped in v3 to make the API cleaner.

Instead of `imwrite`, `imsave`, `mimwrite`, `mimsave`, `volwrite`, and `volsave` you now just have `imwrite` (much simpler mental model). They all do the same thing on different inputs or are aliases of each other, and we can differentiate which behavior the user wants by simply inspecting the input.

**Comment by stefanv** [comment]
Paletted read is still broken:

```
    def test_imageio_palette():
        img = imread(fetch('data/palette_color.png'))
>       assert img.ndim == 3
E       assert 2 == 3
E        +  where 2 = array([[191, 108,  72, 194,  73,  65,  79, 130, 216, 131],\n       [ 90,  96, 104,  92,  29, 172,  51,  29, 102, 119],\n...  22,  95, 171, 220,  87, 109,  61, 205,  24],\n       [ 77, 102,  32,  55, 190, 132,  50,  26, 172, 156]], dtype=uint8).ndim
```

**Comment by stefanv** [comment]
Matplotlib reads this image correctly; PIL does too, but you need to handle `im.mode == 'P'` correctly:

```
im = PIL.Image.open('skimage/data/palette_color.png')
A = np.array(im)
pal = np.array(im.getpalette()).reshape(-1, 3)
return pal[np.array(im)]
```

@FirefoxMetzger would you consider this to be a bug?

**Comment by FirefoxMetzger** [comment]
Interesting image @stefanv . Would we be allowed to adopt it in our own test suite?

Currently, we have a warning/note for this behavior in the pillow plugin's read function:

```
Notes
-----
If you open a GIF - or any other format using color pallets - you may
wish to manually set the `mode` parameter. Otherwise, the numbers in
the returned image will refer to the entries in the color pallet, which
is discarded during conversion to ndarray.
```

and you can have ImageIO reconstruct it for you by asking for a result in RGB:

```python
img = iio.imread("palette_color.png", mode="RGB")
img.shape  # (10, 10, 3)
```

That said, we have changed the behavior for GIF a while ago, i.e., you get a reconstructed image (RGB/A depending on the palette) instead of palette indices. This came after listening to a frequent stream of feedback asking if GIF was broken/buggy. I think we could extend this behavior to other paletted formats including PNG since you, too, are asking if the behavior for palette PNG is a bug 😄.

**Comment by FirefoxMetzger** [comment]
> @FirefoxMetzger would you consider this to be a bug?

@stefanv This will be fixed by https://github.com/imageio/imageio/pull/955 . That PR is ready except for a regression test; would I be allowed to add https://github.com/scikit-image/scikit-image/raw/main/skimage/data/palette_color.png to our test suite (and distribute it alongside the suite), or should I look into generating my own palette PNG image?

**Comment by FirefoxMetzger** [comment]
The other failure is that ImageIO sometimes returns a read-only ndarray that is a view into a PIL buffer instead of making a copy of the data. This is a performance optimization done internally by PIL; however, it seems to break some of the filters here which assume that the image is writable.

Does `skimage.io.imread` expect to produced result to be writable? If so, we could discuss adding a flag along the lines of `force_writable=True`, which will make a copy of the image before returning it if the result turns out to be read-only. This obviously has a negative impact on performance and memory requirements (especially if we are forced to copy large images), but if this is behavior that users rely on then ImageIO can (optionally) allow this, and you can set that flag internally.

**Comment by stefanv** [comment]
@FirefoxMetzger Yes, indeed, I think the idea is that you get a standard ndarray back that you can manipulate however you wish; so that `force_writable` or similar flag (maybe `copy=True` or `view=False`) would be helpful!

**Comment by stefanv** [comment]
> > @FirefoxMetzger would you consider this to be a bug?
> 
> @stefanv This will be fixed by [imageio/imageio#955](https://github.com/imageio/imageio/pull/955) . That PR is ready except for a regression test; would I be allowed to add https://github.com/scikit-image/scikit-image/raw/main/skimage/data/palette_color.png to our test suite (and distribute it alongside the suite), or should I look into generating my own palette PNG image?

You can go ahead and use that image.

**Comment by stefanv** [comment]
The changes I pushed should work around the read-only behavior. I should probably test for that explicitly (I don't know which images show this behavior), but I know it's being tested for implicitly in the test suite.

**Comment by stefanv** [comment]
This failure I don't understand. On my local machine, `imageio` correctly returns a 2D image. Under which circumstances would it return a 3D image?

```
    def test_eagle():
        """ Test that "eagle" image can be loaded. """
        # Fetching the data through the testing module will
        # cause the test to skip if pooch isn't installed.
        fetch('data/eagle.png')
        eagle = data.eagle()
>       assert_equal(eagle.ndim, 2)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 3
E        DESIRED: 2
```

**Comment by stefanv** [comment]
@FirefoxMetzger This seems like a genuine bug in imageio:

```
In [1]: from imageio.v3 import imread

In [2]: imread('/tmp/eagle.png').shape
Out[2]: (2019, 1826, 3)
```

[Eagle image](https://gitlab.com/scikit-image/data/-/blob/master/eagle.png)

**Comment by lagru** [comment]
Cross-referencing https://github.com/scikit-image/scikit-image/issues/6908 here. I haven't investigated yet. Would this PR address #6908?

**Comment by FirefoxMetzger** [comment]
> Cross-referencing https://github.com/scikit-image/scikit-image/issues/6908 here. I haven't investigated yet. Would this PR address https://github.com/scikit-image/scikit-image/issues/6908?

@lagru Yes, because v2.28 only affects the `imageio.v2` namespace. `imageio.v3` works just like before. 

There are still some discussion points in this PR though that need resolution before it can be merged. In particular, we need to decide how to deal with RGB paletted images that store "grey as RGB", i.e., the entire palette consists of gray values encoded as RGB. The old ImageIO had an explicit (and slow) check for this and did RGB->gray conversion if needed; however, we currently don't do this, because the image was explicitly stored as RGB which is probably intentional so you get things back as stored, which means as RGB.

**Comment by stefanv** [comment]
I suspect the new imageio behavior is more correct, and we should fix our eagle data file instead.

**Comment by lagru** [comment]
See https://gitlab.com/scikit-image/data/-/merge_requests/22. Once that's merged we can update the registry entry for `eagle.png` here. The we don't have to worry about that image anymore regardless how imageio decides to proceed with cases such as this. Also saves a few MiB of download (2.2 to 1.4 MiB).

**Comment by FirefoxMetzger** [comment]
Awesome @lagru once that is merged all the CI failures here should resolve themself (at least as far as I can see).

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
@lagru Merged on gitlab; do you mind updating the data repo? You are welcome to push to this PR what you need to.

**Comment by stefanv** [comment]
Thanks! Should be good to go on green.

**Comment by stefanv** [comment]
@FirefoxMetzger We're almost good to go, but with latest imageio we have `no_time_for_that_tiny.gif` be RGB, whereas it used to be RGBA.

Imagemagick tells me:

```
$ identify -format '%[channels] ' skimage/data/no_time_for_that_tiny.gif
srgb srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba srgba
```

Any idea what the correct output here should be?

**Comment by lagru** [comment]
`srgb srgba srgba ...` makes it seem a bit like only the first frame is lacking an alpha channel? Did imageio perhaps fill in this channel previously while it is now dropping the alpha channel for all other frames (it seems like this locally).

**Comment by stefanv** [comment]
I've re-introduced the <2.28 pin, since we do not have time to figure out this latest change in behavior before the release.

**Comment by FirefoxMetzger** [comment]
Yes, I noticed this as well last week. Unfortunately, I didn't yet find the time to think through the important scenarios and decide the correct behavior. I started a new job last week and getting set up didn’t leave much free time.

The short version: You already identified that the first plane of this GIF is RGB and all others are RGBA. This is likely due to the writer taking advantage of one of GIF's more obscure compression features, which is commonly "misused" to create transparent GIFs. In a nutshell returning RGB is the _technically_ correct thing to do (read: it strictly follows the GIF standard), but it may be more user friendly to return RGBA instead (read: strictly following GIF might be surprising here).

---

(sorry that the below response turned out so long. It's again one of those edge cases that doesn't have a clear default and depends on "what the average user expects". My hope with this lengthy explanation is that it gives you enough context to give me feedback on what skimage's "average user" would expect.)


The longer version: A GIF palette can’t store RGBA; it's always RGB. Instead, one _may_ set a byte (a `unit8`) in the frame’s metadata to flag an index as "transparent". If set, it means “if you encounter this index in the index array, don’t look it up in the color palette and instead _reuse the value of the previous pixel_”. If there is no previous pixel (first frame or disposal set to “restore background”) then we default to the GIFs chosen background color, and if that too is not set, the reader gets to choose the color (aka we have undefined behavior). In practice, readers have converged to understand this lack of background color to mean “the background has `alpha=0`”. This is nothing a GIF can represent explicitly (aka its non-standard), but it’s so popular and well supported that this behavior is nowadays ubiquitous.

The obligatory piece of trivia: The original intent of this _transparency flag_ was to allow better compression (smaller per-frame palettes) and to circumvent the 256-color limitation. If we can reuse 2+ colors from the previous frame, we can choose 1+ new colors for the current frame and create a 257+ color image (255 new colors, and 2+ reused/old). It's an ingenious idea, but not many writers ever took advantage of it because it means a lot of GIF-specific custom logic when creating a frame-level palette. Instead people found a loophole in the definition of this feature (the implicit background color), which eventually became RGBA support in GIF.

This brings us back to the ultimate question of: What is the expected behavior of a reader for this particular image? Since, for this image, the first frame is RGB (not RGB + transparency flag) we can always trace the final value to a valid RGB color and avoid the “undefined behavior/transparent pixel hack” territory. Also, for each index, users expect a fully decoded frame. This means that - by default - for `index=5` they want the full frame, not only those pixels which are new/changed and transparent everywhere else. At the moment, this translates to “return an RGB, since we will never have a pixel with `alpha != 255`”, but I am happy to change this and append an effectively empty alpha channel if that is more intuitive.

**Comment by lagru** [comment]
@FirefoxMetzger, no worries and thank you so much for taking the time to give a detailed answer anyway! It's very much appreciated. Hope can settle nicely into the new job. :)

Regarding `no_time_for_that_tiny.gif` (I am finding the name very ironic right now :joy:) and what to do from scikit-image's side: If find it also noteworthy that we already have a test case that actually expects the last dimension to have the size 3 (as opposed to the [failing test expecting 4](https://github.com/scikit-image/scikit-image/actions/runs/4929830157/jobs/8809971303#step:5:542)) :smile:  https://github.com/scikit-image/scikit-image/blob/e8a92e348382782c26cde44e4bf8bb96981ae94e/skimage/io/tests/test_pil.py#L265-L267

I don't think our tests actually care for the properties of this GIF that we are currently discussing as long as the shape can be asserted. In this context I think we are free to just update the unit test and / or the file. Do you know a quick way to generate a similar file without the ambiguous first channel? I don't think the content actually matters to our tests...

I'm not sure which behavior imageio should aim for but I find it noteworthy that PIL has been returning only 3 channels for this GIF for some time.

**Comment by FirefoxMetzger** [comment]
> Regarding no_time_for_that_tiny.gif (I am finding the name very ironic right now 😂) [...] we already have a test case that actually expects the last dimension to have the size 3 (as opposed to the [failing test expecting 4](https://github.com/scikit-image/scikit-image/actions/runs/4929830157/jobs/8809971303#step:5:542))

RIP ⚰️ 🤣 

> Do you know a quick way to generate a similar file without the ambiguous first channel?

If you want the same pixels, loading the image in the mode you want (RGB/RGBA) and saving it again should do the trick.

```python
# if you want to have RGB consistently
img = iio.imread("no_time_for_that_tiny.gif", mode="RBG")

# if you want to have RGBA consistently
img = iio.imread("no_time_for_that_tiny.gif", mode="RBG")

iio.imwrite("new_test_file.gif", img)
```

If you don't care about the actual pixel values, you can also opt to generate a GIF in memory:

```
desired_shape = (24, 25, 14, 3)
img = np.random.randint(0, 255, desired_shape, dtype=np.uint8)
# img = np.full(desired_shape, 42, dtype=np.uint8)
buffer = iio.imwrite("<bytes>", img, extension=".gif")

result = iio.imread(buffer)
assert result.shape == desired_shape
```

**Pull request merged**
