### PR TITLE
Fixed typo in hog() method keyword argument visualise

### PR DESCRIPTION
**Pull request by DrGFreeman**
## Description
Fixed typo in `plot_hog.py` example. In the example, the call to `hog()` method uses `visualize` keyword argument which raises a type error (see issue #2812). The correct keyword argument is changed to `visualise` as per the [method documentation](http://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.hog).

Note to reviewers; this is my first contribution to the project. Please indicate if I also need to update the .ipynb file for the example.

Thank you!

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

Checklist items not verified and assumed to be OK (simple typo correction).

## References
Closing issue #2812.

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by soupault** [comment]
Closing as invalid (see https://github.com/scikit-image/scikit-image/issues/2812#issuecomment-332724141). Please, reopen if disagree.

**Comment by stefanv** [comment]
@DrGFreeman FWIW, I really appreciate you coming here and trying to make a patch, unlike so many others who never go to the trouble.  I hope we'll be seeing more contributions from you!

**Comment by DrGFreeman** [comment]
Thank you @stefanv! I must admit this is a bit intimidating for a "hobbyist" user like me.

For some reason when browsing the gallery on http://scikit-image.org/ I got to the example for version 0.14 example but the method documentation for 0.13 which appeared to me as a discrepancy between the two. I'll be more careful about checking the version of documentation I use next time!

I am still unsure why there is no deprecation warning when running 0.13.1 about `visualise` changing to `visualize` in 0.14? This means that code using `hog()` developed under 0.13 will not run on 0.14?

Regards,

**Comment by stefanv** [comment]
We understand your confusion! We have made a PR to make the website and 
documentation more consistent.

**Comment by soupault** [comment]
@DrGFreeman 

>I am still unsure why there is no deprecation warning when running 0.13.1 about visualise changing to visualize in 0.14?

Well, we can't forecast the changes :). The change has been made in 0.14dev, and we'll keep backward compatibility for 2 releases (our typical policy), till 0.16.

>This means that code using hog() developed under 0.13 will not run on 0.14?

It will work. See https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_hog.py#L184-L187 .

**Pull request closed without merging**
