### PR TITLE
Replace words with racial connotations

### PR DESCRIPTION
**Pull request by sciunto**
## Description

After the recommendations made in https://github.com/scipy/scipy/issues/12446#issuecomment-651770734 and a recent comment by @grlee77 

@scikit-image/core We have the word in release notes. Can I modify them?

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks @sciunto. I think it's ok to modify release notes as long as it does not change the overall meaning.

**Comment by sciunto** [comment]
done.

**Comment by alexdesiqueira** [comment]
This is great! Thanks @sciunto!

**Comment by hmaarrfk** [comment]
Awesome!

**Pull request merged**
