### PR TITLE
Call it what it is: pip and conda

### PR DESCRIPTION
**Pull request by stefanv**
/cc @lagru

### CODE REVIEW

**Review by mkcor — APPROVED** [review]
Ha!

**Review by hmaarrfk — APPROVED** [review]

**Comment by hmaarrfk** [comment]
https://xkcd.com/1987/

**Review by jarrodmillman — APPROVED** [review]

**Comment by mkcor** [comment]
I'll let @lagru merge :wink:

**Comment by lagru** [comment]
This is great! :smile: And I guess very well reviewed.

**Pull request merged**
