### PR TITLE
Handle pip-only dependencies when using conda.

### PR DESCRIPTION
**Pull request by mkcor**
## Description

Sorry for shipping these in dribs and drabs! This should be backported in the wake of #6781 and #6792: @lagru could you please update #6803 with this last fix?

With this PR, the conda instructions run successfully. So at least nothing is broken, even though it's not perfect (until we address #6794).

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Comment by hmaarrfk** [comment]
can we release devpy and meson-python on conda-forge instead? would that resolve the same problem? 

the usage of devpy directly from github kinda scares me as long term practice

**Comment by stefanv** [comment]
Fine with me, if someone wants to take it on.

**Comment by lagru** [comment]
Thanks @mkcor. I'll include it in #6803.

**Comment by hmaarrfk** [comment]
i'm happy to help release them.

**Pull request merged**
