### PR TITLE
Fix random_walker regression

### LINKED ISSUE #4770: segmentation.random_walker error, masking problem
## Description
The method segmentation.random_walker produces an error when passing labels with negative values. The code below worked with the `segmentation/random_walker.py` file from commit d61625b3950ffa9ee3d59e91295b49357be03b27. It produces an error starting from commit 8f76f0fb48908ba2ca92816d3611bba5cd09b998 (the next one modifying the file). I am attaching below the arrays used for the image and the labels in calling the random_walker method.
[image.txt](https://github.com/scikit-image/scikit-image/files/4720149/image.txt)
[labels.txt](https://github.com/scikit-image/scikit-image/files/4720150/labels.txt)

## Way to reproduce
The error can be reproduced using the following code:
```
import numpy as np
from skimage import segmentation

labels = np.loadtxt('labels.txt')
img = np.loadtxt('image.txt')

labeled_image = segmentation.random_walker(img, labels, mode='bf', beta=130., return_full_prob=False)
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.8.2 (default, Apr 23 2020, 14:32:57) 
[GCC 8.3.0]
Linux-4.15.0-101-generic-x86_64-with-glibc2.2.5
scikit-image version: 0.18.dev0
numpy version: 1.18.4
```

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

Fix #4770.

Regression was introduced in https://github.com/scikit-image/scikit-image/commit/8f76f0fb48908ba2ca92816d3611bba5cd09b998.

This PR
- fixes `random_walker` segmentation when labels contains isolated area
- adds `test_isolated_area`

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by sciunto** [comment]
@scikit-image/core We need a second review on this bugfix (easy to read).

**Comment by stefanv** [comment]
If the test failures are unrelated, go ahead and merge.

**Comment by sciunto** [comment]
They are. i'm merging. Thanks @stefanv

**Comment by sciunto** [comment]
@meeseeksdev backport to v0.17.x

**Comment by rfezzani** [comment]
:tada: Thank you @sciunto ;)

**Pull request merged**
