### PR TITLE
Remove lena image from test suite

### PR DESCRIPTION
**Pull request by stefanv**
Results from the morphology module were compared against output from the
corresponding MATLAB functions, as applied to the lena test image.  This image
does not conform to the Debian Free Software Guidelines and had to be removed.
The output is now tested against results generated with the current version of
scikit-image (0.12.0), which is known to be correct due to the comparison
described above.

### CODE REVIEW

**Comment by soupault** [comment]
xref #1865

**Comment by soupault** [comment]
Looks good to me.

Regarding the errors:
* `format` in Python 2.6 should use indices: http://stackoverflow.com/a/10054232/1759565 .
* `skimage/io/collection.py#146` has `lena` in Example section of the docsting;

Extra finding:
* functions in `skimage/feature/tests/test_match.py` should be renamed (lena -> astronaut).

**Comment by stefanv** [comment]
Thanks for the review, Egor.  I've made the necessary updates.
​

**Comment by JDWarner** [comment]
LGTM, merging.

**Comment by JDWarner** [comment]
And Lena is finally gone!

**Comment by soupault** [comment]
Right before IWD :grimacing: .

**Pull request merged**
