### PR TITLE
Adding missing copyrights to LICENSE.txt, formatting according to SPDX identifiers

### PR DESCRIPTION
**Pull request by alexdesiqueira**
## Description
Adding missing copyright info, according to discussion in #544 and Debian's [python3-skimage (0.18.3-3)](http://deb.debian.org/debian/pool/main/s/skimage/skimage_0.18.3-3.debian.tar.xz) `copyright` file. Licenses now are formatted according to [SPDX](https://spdx.org/licenses/) identifiers.

Solves #544.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by stefanv** [comment]
Also remove remaining license snippets from other files.

**Review by grlee77 — APPROVED** [review]
This looks good. One possible change is to have only the scikit-image BSD-3 license in `LICENSE.txt` and move the rest into `LICENSES_bundled.txt`. At least that is what SciPy and NumPy do
https://github.com/scipy/scipy. One positive effect of splitting it that way is that the GitHub UI will autodetect the license type from LICENSE.txt which it can't currently do with everything listed in one file.

**Review by lagru — COMMENTED** [review]
I like this more "standardized" / machinefriendly approach to handle licenses. But see below...

**Comment by alexdesiqueira** [comment]
Hey @lagru, 
> I like this more "standardized" / machinefriendly approach to handle licenses. But see below...

the whole idea was to centralize the licenses in one file! :sweat_smile:

**Comment by alexdesiqueira** [comment]
> I'm happy to centralize the license information but would like to retain module level documentation which you removed as well.

@lagru the idea was precisely to _not_ have module licenses anymore :sweat_smile: Please check discussion in #544.

**Comment by stefanv** [comment]
> > I'm happy to centralize the license information but would like to retain module level documentation which you removed as well.
> 
> @lagru the idea was precisely to _not_ have module licenses anymore 😅 Please check discussion in #544.

Right, but what @lagru is asking for is to retain module-level doctrines (not copyright).

**Comment by alexdesiqueira** [comment]
You're right @stefanv,

> (...) but would like to retain module level documentation which you removed as well.

@lagru I apologize, I misread your comment. I understood that you wanted the licenses in `LICENSE` and in the individual files as well, instead of only in `LICENSE`. I'll solve that today.

**Comment by lagru** [comment]
@alexdesiqueira, no worries! :sweat_smile:

**Comment by alexdesiqueira** [comment]
I guess that's it :)

**Review by lagru — CHANGES_REQUESTED** [review]
I'm sorry to delay this further but I think some license information inside the library code is still included in the libraries source. E.g. `grep --ignore-case "copyright" $(git ls-files skimage/)` returns (edited)
```
skimage/_shared/version_requirements.py:    Copyright (C) 2013  The IPython Development Team
skimage/_shared/version_requirements.py:    Original Copyright (C) 2009-2011 Pierre Raybaut
skimage/exposure/_adapthist.py:The Graphics Gems code is copyright-protected.  In other words, you cannot
skimage/morphology/_grayreconstruct.pyx:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/morphology/_grayreconstruct.pyx:Copyright (c) 2009-2011 Broad Institute
skimage/morphology/_skeletonize_cy.pyx:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/morphology/_skeletonize_cy.pyx:Copyright (c) 2009-2011 Broad Institute
skimage/morphology/grayreconstruct.py:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/morphology/grayreconstruct.py:Copyright (c) 2009-2011 Broad Institute
skimage/morphology/tests/test_reconstruction.py:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/morphology/tests/test_reconstruction.py:Copyright (c) 2009-2011 Broad Institute
skimage/segmentation/_expand_labels.py:Copyright (c) 2020 Broad Institute
skimage/segmentation/_watershed.py:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/segmentation/_watershed.py:Copyright (c) 2009-2011 Broad Institute
skimage/segmentation/heap_general.pxi:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/segmentation/heap_general.pxi:Copyright (c) 2009-2011 Broad Institute
skimage/segmentation/heap_watershed.pxi:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/segmentation/heap_watershed.pxi:Copyright (c) 2009-2011 Broad Institute
skimage/segmentation/tests/test_watershed.py:Copyright (c) 2003-2009 Massachusetts Institute of Technology
skimage/segmentation/tests/test_watershed.py:Copyright (c) 2009-2011 Broad Institute
skimage/segmentation/tests/test_watershed.py:# Copyright (C) 2003-2005 Peter J. Verveer
skimage/segmentation/tests/test_watershed.py:# 1. Redistributions of source code must retain the above copyright
skimage/segmentation/tests/test_watershed.py:#    copyright notice, this list of conditions and the following
```

**Review by lagru — APPROVED** [review]
Approving this despite my previous comment as removing the snippets from the library files is not the main focus and aim of this PR. It's totally fine if we do it later. @alexdesiqueira feel free to either remove the remaining duplicate copyright and license stuff or merge and I will do it later. :wink:

**Comment by alexdesiqueira** [comment]
:sweat_smile: geez. Don't worry @lagru, I'll do it here.

**Comment by alexdesiqueira** [comment]
Alright @lagru, I think this one is done. I won't poke the licenses on `data`, since some of those files live in another repo.

**Review by lagru — APPROVED** [review]
Looks good. I'm a little confused whether it's correct to add "Peter J. Verveer" as a copyright holder to a lot of the CellProfiler stuff (originally only listed in [test_watershed.py](https://github.com/scikit-image/scikit-image/pull/6419/files#diff-35b98022076af3de5633285e968480800bacefcb9581ee730c297a6bcda55afe) but now also for [other files](https://github.com/scikit-image/scikit-image/pull/6419/files#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7R9-R18)). However, I think the other way round would be more problematic.

We should also keep in mind that this increases our maintenance burden (2 places to sync and so on). Perhaps another checkbox for our PR template?

I'm merging this. Thanks @alexdesiqueira for the patience!

**Comment by alexdesiqueira** [comment]
> Looks good. I'm a little confused whether it's correct to add "Peter J. Verveer" as a copyright holder to a lot of the CellProfiler stuff (originally only listed in [test_watershed.py](https://github.com/scikit-image/scikit-image/pull/6419/files#diff-35b98022076af3de5633285e968480800bacefcb9581ee730c297a6bcda55afe) but now also for [other files](https://github.com/scikit-image/scikit-image/pull/6419/files#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7R9-R18)). However, I think the other way round would be more problematic.

@lagru I think this definition came from the Debian package. We should check if that's the case, if there's doubt.

**Pull request merged**
