### PR TITLE
Fix sphinx layout to make the search engine working for latest sphinx versions

### LINKED ISSUE #4647: Update blocked versions for sphinx in requirement.txt
## Description

See #4644 and #4616 
We recently blacklisted all sphinx recent versions. We need to monitor the new releases and set correctly the backlisted version once sphinx has fixed the issue.

Cc @emmanuelle 

## State of the art:

* Online version: `sphinx>=1.8,<=2.4.4` (afaik, 2.4.4 is used). **Working well**.
https://scikit-image.org/docs/dev/search.html?q=canny&check_keywords=yes&area=default
also true on artifacts: https://1636-2014929-gh.circle-artifacts.com/0/doc/build/html/search.html?q=canny&check_keywords=yes&area=default

* For `sphinx>=1.8` Not working, **hanging forever**. Latest sphinx version.
https://1637-2014929-gh.circle-artifacts.com/0/doc/build/html/search.html?q=canny&check_keywords=yes&area=default

Is it somehow related to https://github.com/sphinx-doc/sphinx/pull/7192?

### PR DESCRIPTION
**Pull request by sciunto**
## Description
closes #4647 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by sciunto** [comment]
It's searching forever, same behavior on artifact and locally...

**Comment by sciunto** [comment]
@scikit-image/core I got some help from sphinx's community and the search engine is working again (tested locally). Please check and review.

**Review by grlee77 — APPROVED** [review]
Thanks for fixing this @sciunto! It is working on the artifact for me as well

**Comment by alexdesiqueira** [comment]
Thank you @sciunto !

**Pull request merged**
