### PR TITLE
Update testdoc

### PR DESCRIPTION
**Pull request by jarrodmillman**
## Description

While working on PR #2766, I needed to run the tests and doctests on my local machine to investigate the problem.  I had trouble finding the contributor file because it wasn't where I expected it to be and my default search commands don't search inside hidden directories (i.e., directories starting with a dot).

This PR makes it easier to find the contributor guidelines if you are working at the command line.  Github looks for this file in repository's root anyway, so there's no advantage for it to be in the ``.github`` directory.  For more information, see:  https://help.github.com/articles/setting-guidelines-for-repository-contributors/

The PR also adds instructions for running doctests.

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by soupault** [comment]
For reference, the rationale for moving CONTRIBUTING.txt to another location - https://github.com/scikit-image/scikit-image/issues/1949

**Comment by stefanv** [comment]
Yes, we can't move CONTRIBUTING.txt, otherwise GitHub won't render it.

**Comment by jarrodmillman** [comment]
GitHub will render it.  At the top of https://help.github.com/articles/setting-guidelines-for-repository-contributors/ it states:  "To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file."

It then gives three examples of how it works:
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/rails/rails/blob/master/CONTRIBUTING.md
- https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

They all use the ``.md`` extensions, but according to the instructions:
"Contributing guidelines filenames are not case sensitive, and can have an extension such as .md or .txt."

So the only reason I can find in the previous discussion for moving this file is "We should also move CONTRIBUTING.txt into that directory, decluttering the root. It's always been less than ideal having CONTRIBUTORS.txt and CONTRIBUTING.txt right next to each other."  I am not sure what the problem with having "CONTRIBUTORS.txt and CONTRIBUTING.txt right next to each other", but I doesn't seem to be a major issue from my perspective.  I suppose someone might accidentally open the wrong file with a text editor, but I suspect that would be a minor inconvenience unless you have a text editor that takes a long time to open a file.  However, having the file inside a hidden directory meant I struggled more than once to find this file.  The first time you had to tell me in person.  The second time I ended up searching for it on google after all the ways I search from the commandline failed.  First I tried ``ls``, then I used ``grep``, and finally I tried ``grin``.  All three tools don't search inside of dot directories by default.

**Comment by stefanv** [comment]
Aha, good to know!  Thanks.

**Comment by soupault** [comment]
>First I tried ls, then I used grep, and finally I tried grin. All three tools don't search inside of dot directories by default.
Good point!
I let @JDWarner to make the final decision as an author of this change.

**Comment by jarrodmillman** [comment]
If having CONTRIBUTORS.txt and CONTRIBUTING.txt right next to each other is the concern, you could move CONTRIBUTORS.txt to somwhere in ``doc``.  When I contribute to a project I rarely need to look at a project's contributors, but I often need to know how to contribute.  This is particularly true when I am new to a project or when I am shifting between several projects in a day.

If you want to declutter the root directory, you could move the following files:
1. ``TASKS.txt`` could be included directly in ``doc/source/contribute.rst``.  The name ``TASKS`` doesn't seem to match the content and looking at it from the commandline doesn't seem to be very helpful for a new contributor.
2. ``TODO.txt`` could be moved to ``doc/release/``.  It looks like it would be more relevant to an experienced developer or release manager anyway, so it isn't clear it needs to have so much visibility.
3. ``DEPENDS.txt`` could be included directly in ``doc/source/install.rst``.  When I set up a development environment, I usually expect that the ``requirements.txt`` or ``pip install`` should handle dependencies for me.
4. ``RELEASE.txt`` could be moved to ``doc/release/``.  I suspect that only a few people will need to look at this file.  And those people should probably be familiar with where to find things in the repo.
5. Change ``requirements.docs.txt`` and ``requirements.optional.txt`` to ``requirements/docs.txt`` and ``requirements/optional.txt``.  I would expect to find requirements files in a directory named requirements, so I don't think this would add confusion.  You could also add a ``requirements/README.md`` explaining what the various requirement files contain, if you wish.
6. ``appveyor.yml`` could become ``.appveyor.yml`` so it doesn't show up with ``ls``.  This is the type of things I would expect to be hidden and shouldn't be necessary for new contributors to find from the commandline.
7. Remove ``bento.info`` and content in related files.  I think it is a dead project (correct me if I am wrong).  NumPy stopped supporting it a couple of years ago:  https://github.com/numpy/numpy/pull/6268

If any of that seems reasonable, I am happy to make a PR.

**Comment by jarrodmillman** [comment]
I created a PR to remove bento support (#2776) so any discussion about it should take place there.

**Comment by JDWarner** [comment]
I approve.

**Comment by soupault** [comment]
@jarrodmillman use https://github.com/scikit-image/scikit-image/issues/2777 for further discussions on the different points from your list.

**Pull request merged**
