### PR TITLE
[WIP] Remove use of lena in TestMorphology

### LINKED ISSUE #1865: Tests in skimage/morphology/tests/test_grey.py use lena
To remove the lena image (#1855) some tests have to be rewritten to use a different image.
The following tests in ``skimage/morphology/tests/test_grey.py`` use lena

* All tests in class TestMorphology

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #1865 

The tests in this class seem to be using outputs generated by matlab. I couldn't find any documentation on how were they generated at first place.
The original files were added in [this commit](https://github.com/scikit-image/scikit-image/commit/f7f294ccf1d4ec26e84f9628a992e6cf1b6cd2eb), but I can't find any useful message in it either.

DO NOT merge this. I need help here.

### CODE REVIEW

**Comment by JDWarner** [comment]
I think we're going to have to bite the bullet and create a new test suite here. I can't find additional history for these either, and I do not like to rely on Matlab-generated results. Binary morphology can be robustly tested with smaller, hand-verified examples (and with a bit more effort, so can grayscale morphology). That would be my preference over "use the function, save & reference its output" type testing.

**Comment by stefanv** [comment]
I'm afraid Josh is right.
​

**Comment by soupault** [comment]
I second @JDWarner . Could be a really nice clean-up.

**Comment by soupault** [comment]
I've thought about this topic once again...
I'd suggest to completely remove generic tests on morphology.
As it is mentioned in https://github.com/scikit-image/scikit-image/issues/1917 , in `skimage` we almost directly use corresponding `scipy` functions. This way one should expect that these functions are already being tested in `scipy` package (see https://github.com/scipy/scipy/blob/master/scipy/ndimage/tests/test_ndimage.py#L3011).
I think we should leave only `skimage`-specific tests and tests related to default behaviour.

**Comment by stefanv** [comment]
If we expose an API, it is our responsibility to make sure that that API does the right thing.  So, we have to test.

**Comment by JDWarner** [comment]
We still have to cover our wrappers and API. Testing isn't optional, but we could borrow tests from SciPy.

**Comment by soupault** [comment]
I see... Thanks for the replies!

**Comment by soupault** [comment]
Hi guys! Just trying to kick-off the process... 
Could we split 'lena'-removal and tests' refactoring into separate issues? I bet the former is a stopper for 0.12, while the latter could be performed even after the release.

**Comment by stefanv** [comment]
Closed in favor of https://github.com/scikit-image/scikit-image/pull/1985

**Pull request closed without merging**
