### PR TITLE
Fix invalid normalization of 2nd deriviative of Gaussian kernel

### PR DESCRIPTION
**Pull request by ahojnnes**

### CODE REVIEW

**Comment by JDWarner** [comment]
Yikes, NaN's everywhere!

**Comment by ahojnnes** [comment]
The problem that I see here (I don't have time to fix it). The filter kernel that is generated is not correct for small kernel sizes, since the formula does not apply for small discretization.

**Comment by Gregosh** [comment]
There is probably a mistake with the gaussian kernels, in the hessian matrix. Still in the module feature -> corner.py lines 159 - 166 

For example, have a look at this example:
>>> I = np.arange(0,4,1).reshape(2,2).astype('float')
>>> Hxx, Hxy, Hyy = skimage.feature.hessian_matrix(I)
>>> Hxx
array([[  47.25260038,  109.83208425],
       [  77.90636735,  140.48585121]])
>>> Hxy
array([[  2.42708710e+16,  -1.61805806e+16],
       [ -8.09029032e+15,   0.00000000e+00]])
>>> Hyy
array([[  23.62630019,   38.95318367],
       [ 148.78526792,  164.1121514 ]])

The values for Hxy derivative are huge. Especially compared to the derivatives of Hxx an Hyy.
I have the proper normalization of the kernel kxy (line 165) thanks @ahojnnes 

In the file probably these equations were used, for example:
http://campar.in.tum.de/Chair/HaukeHeibelGaussianDerivatives

and there is a simple code for calculation of masks:
http://campar.in.tum.de/twiki/pub/Chair/HaukeHeibelGaussianDerivatives/gaussian2d.m

Unfortunately, I can't find any bug at this moment and I don't have matlab for doing comparison of these values. But I feel that the diference in values between one directional derivatives and mixed derivatives is too big.

Maybe you have any idea, or am I wrong in my thinking?

**Comment by ahojnnes** [comment]
@Gregosh Did you delete your last comment?

**Comment by emmanuelle** [comment]
@ahojnnes what is the plan for this PR? It is marked for 0.12, any chance to solve the remaining problems and merge it soon?

**Comment by emmanuelle** [comment]
@ahojnnes @JDWarner what should we do for small kernel sizes, then? Raise an exception if the size is too small, or apply a different formula?

**Comment by ahojnnes** [comment]
@emmanuelle Sorry for the late reply. I don't really have time to fix this. For now, I would raise an exception for small kernel sizes.

**Comment by Gregosh** [comment]
I think that the problem is with incorrect kernel calculation at all.

As a reference, I could give a link:
http://campar.in.tum.de/Chair/HaukeHeibelGaussianDerivatives
There are also Matlab codes for kernel calculations, which are easy to read and port to Python.

In my opinion the way in which the gaussian kernel is calculated is more proper in these files.
Especially, the normalization of gaussian kernel is not done by sum of its values but by value of sigma, as in these examples. The two ways for solution is no normalize the gasussian kernel, or normalize by multiplication of kernels values by sigma.

And I can propose to cut very small values of kernel by the trick:
 gauss_kernel[gauss_kernel <
               np.finfo(gauss_kernel.dtype).eps*gauss_kernel.max()] = 0
So, the values smaller than eps, aren't taken for consideration. I think, that is good approach.

Unfortunatelly, I don't know yet how to write patch but maybe I will to learn and propose a fix for calculation of this kernel.

**Comment by emmanuelle** [comment]
@Gregosh thank you for your insights on this issue.

Instructions for contributing a pull request are found on http://scikit-image.org/docs/stable/contribute.html
You can also fetch @ahojnnes 's branch and submit a pull request to his branch, or start a new pull request.

If you encounter difficulties, you can ask for help on the gitter chatroom https://gitter.im/scikit-image/scikit-image

Thanks!

**Comment by ahojnnes** [comment]
That would be great. Thanks!

**Comment by stefanv** [comment]
@Gregosh Would you mind either looking at the code, or writing a bit of code to calculate kernels?  We would be more than happy to help you integrate your code into scikit-image.  If you can think of some good test cases along the way, that would be even better.

**Comment by ahojnnes** [comment]
Closing in favor of https://github.com/scikit-image/scikit-image/pull/1888

**Pull request closed without merging**
