### PR TITLE
Enable use of `rescale_intensity` with dask array

### PR DESCRIPTION
**Pull request by ericpre**
## Description

Avoid calling `np.asarray` to enable use of `skimage.exposure.rescale_intensity` with dask array:

```python
import dask.array as da
import numpy as np
from skimage.exposure import rescale_intensity


image = da.array([51, 102, 153], dtype=np.uint8)
a = rescale_intensity(image)
a.compute()
```

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by jni** [comment]
Thanks @ericpre! Would you like to add a test that ensures that we maintain dask compatibility for this function in the future? You can find an example in `test_exposure` already:

https://github.com/scikit-image/scikit-image/blob/707f1c5530f8e3a7706c7808d823ce2e9250af62/skimage/exposure/tests/test_exposure.py#L889

You can copy that pattern so that the test doesn't fail if dask is not installed.

**Comment by ericpre** [comment]
Done! :)

**Review by jni — APPROVED** [review]

**Comment by ericpre** [comment]
Thinking about it more, I am wondering if it would be worth to test more systematically against dask using the following approach?

```python
import functools

import dask.array as da
import numpy as np
from numpy.testing import assert_array_almost_equal

from skimage import exposure


def daskify(func, **kwargs):
    @functools.wraps(func)
    def daskify_func(self, *args, **kwds):
        for k in self.__dict__.keys():
            if not k.startswith('__'):
                v = getattr(self, k)
                if isinstance(v, np.ndarray):
                    v = da.from_array(v)
                    setattr(self, k, v)
        self.__dict__.update(kwargs)
        return func(self, *args, **kwds)
    return daskify_func


def DaskifyTestClass(*args, **kwargs):
    def daskify_test(original_class):
        class_keys_list = [k for k in original_class.__dict__.keys()]
        for thing in class_keys_list:
            if thing.startswith('test'):
                if not thing.startswith('test_dask'):
                    newname = 'test_dask' + thing[4:]
                    if newname not in class_keys_list:
                        newfunc = daskify(getattr(original_class, thing),
                                          **kwargs)
                        newfunc.__name__ = newname
                        setattr(original_class, newname, newfunc)

        return original_class
    if len(args):
        return daskify_test(*args)
    else:
        return daskify_test


@DaskifyTestClass
class TestRescale:

    def setup_method(self):
        # the numpy array that will be converted to dask have to be here
        self.image = np.array([51, 102, 153], dtype=np.uint8)

    def test_rescale(self):
        image = self.image
        out = exposure.rescale_intensity(image)
        assert out.dtype == np.uint8
        assert_array_almost_equal(out, [0, 127, 255])
        assert type(image) is type(out)
```

This is adapted from https://github.com/hyperspy/hyperspy/blob/e5023adc8e695750825ffe36ebe174886c6273bd/hyperspy/decorators.py#L46 and has the advantage to be easy to use (write test as class test and add decorator) and to create new test automatically with the numpy arrays defined in `setup_method` converted to a dask array.

In the pytest output, it is easy to identify the tests using numpy or dask array:
```
================================================ test session starts ================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /opt/miniforge/envs/skimage-dev/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/eric/Dev/scikit-image
plugins: cov-4.0.0, localserver-0.0.0
collected 2 items                                                                                                   
untitled1.py::TestRescale::test_rescale PASSED                                                                [ 50%]
untitled1.py::TestRescale::test_dask_rescale PASSED                                                           [100%]
================================================= 2 passed in 0.45s =================================================
```

I didn't expect that scikit-image would test against dask array but it does make sense to do it more systematically for the functions which are dask friendly!

**Review by lagru — CHANGES_REQUESTED** [review]

**Comment by lagru** [comment]
> I am wondering if it would be worth to test more systematically against dask using the following approach?

That doesn't seem like a bad idea. Though, we'd probably wouldn't structure this as a unittest but rather with pytest. Perhaps with a [parametrized fixture](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#parametrizing-fixtures)?

```python
import pytest

@pytest.fixture(params=["numpy.array", "dask.array"])
def numpy_or_dask_array(request):
    if request.param == "dask.Array":
        pytest.importorskip('dask', reason="dask python library is not installed")
        import dask.array as da
        return da.array
    else:
        return np.array


def test_simple(numpy_or_dask_array):
    image = numpy_or_dask_array([51, 102, 153], dtype=np.uint8)
    out = exposure.rescale_intensity(image)
    assert isinstance(out, type(image))
    assert out.dtype == np.uint8
    assert_array_almost_equal(out, [0, 127, 255])
```

**Comment by jni** [comment]
Well spotted re tests @lagru 😅

The systematic approach is a cool idea but I suggest getting this PR in first then improving things in a subsequent PR. PR scope creep is a great way to ensure improvements never make it in 😂

**Comment by lagru** [comment]
> I suggest getting this PR in first then improving things in a subsequent PR

Totally. Never meant to suggest otherwise!

**Comment by ericpre** [comment]
Thanks @jni and @lagru for the review.

@lagru, the approach you suggested with the pytest fixture is much more simple, I may come back to this in a future PR! :)

**Pull request merged**
