### PR TITLE
Only iterate over available region properties

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jni** [comment]
@stefanv Python 2.6 is [unhappy](https://travis-ci.org/scikit-image/scikit-image/jobs/89552375#L2957) with dict comprehension.

I thought I heard some rumblings about dropping 2.6 support (Legacy Legacy Python, or LLPy, hereafter). How is that going?

**Comment by stefanv** [comment]
We'll eventually do it, when there's compelling reason.  But this one was easy enough to fix.

**Comment by jni** [comment]
@stefanv looks like you're sprinting early! =)

**Comment by stefanv** [comment]
Just warming up ;)

**Pull request merged**
