### PR TITLE
Test on OSX

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by soupault** [comment]
There are some issues with the support of Python in Travis Mac.
Should try:
https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-171736610
https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855

**Comment by stefanv** [comment]
@blink1073 @scikit-image/core Look!  OSX testing :D

**Comment by blink1073** [comment]
Ironic that Appveyor failed (albiet due to an unrelated problem).  Nice!

**Comment by blink1073** [comment]
Ready to merge?  :+1: from me.

**Comment by jni** [comment]
Why did the coverage fail?

**Comment by JDWarner** [comment]
@jni from the error message returned by codecov, it appears that if _any_ CI builds fail it may decline to report coverage.

**Comment by JDWarner** [comment]
As a tangentially related point, I'm still annoyed that only @stefanv can restart AppVeyor builds. They should allow any project managers to do this, like Travis. The current state slows down development and places an unfair burden on @stefanv.

**Comment by stefanv** [comment]
You should now have permission to restart, Josh.  Anyone else who wants to,
send me your GitHub email address.

**Comment by JDWarner** [comment]
I think the problem is that it's listed as @blink1073's project, so the overall project credentials aren't what it uses. Link to above AppVeyor build reads: https://ci.appveyor.com/project/blink1073/scikit-image-qbl76/build/1.0.1355

**Comment by stefanv** [comment]
Ah, I see, so I can't rebuild either.  @blink1073, could you give us the
correct roles?

**Comment by blink1073** [comment]
I added the core team to my account as Administrators, all of you should be able to restart builds now.

**Comment by JDWarner** [comment]
Glad we got that figured out!

**Comment by stefanv** [comment]
Josh, can you rebuild now?  I still don't see a button.
​

**Comment by blink1073** [comment]
@stefanv, it could be that you need to create an account for the organization and we point the builds there.

**Comment by blink1073** [comment]
I tried but it would not let me create one for scikit-image.

**Comment by stefanv** [comment]
I can create one, but it looks like it sits under my name?

https://ci.appveyor.com/project/stefanv/scikit-image-1w3sk/settings

**Comment by blink1073** [comment]
Ha, well shoot.

**Comment by blink1073** [comment]
I have access to restart builds there.

**Comment by blink1073** [comment]
It honestly looks like we're ping pong taking control whenever one of us merges a PR.  This is a really poor UX.

**Comment by JDWarner** [comment]
Yup, when I tried it made it under my name.

@stefanv is there an actual @scikit-image account or is it just the organization? If so, might have to actually log in as that top-level user.

**Comment by stefanv** [comment]
No, their recommendation is to rename your personal account to the org
name. But that doesn't fix the permission problem!

**Comment by soupault** [comment]
@blink1073 I still don't have that option for _my_ PR.

Regarding PR: everything looks good and safe, although I'm not really an OSX user. so couldn't verify in details.

**Comment by blink1073** [comment]
Agreed, merging.

**Pull request merged**
