### PR TITLE
Fix inclusion of `random.js` in HTML output

### PR DESCRIPTION
**Pull request by lagru**
## Description

This script was removed in #6933 even though it is still in use on our front page (see https://github.com/scikit-image/skimage-web/pull/85)! Therefore revert this particular change of #6933.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by lagru** [comment]
Hmm, `random.js` is actually missing from the artifacts generated by [CircleCI](https://app.circleci.com/pipelines/github/scikit-image/scikit-image/5661/workflows/2e0978e6-211c-4562-b1fa-c4c3253760c2/jobs/5710/artifacts). Though, it seems that has also been the case pre https://github.com/scikit-image/scikit-image/pull/6933. If it's a bug then it existed previously. I'll investigate tomorrow...

**Comment by lagru** [comment]
Wayback machine indicates that this broke between [2020-07-27](http://web.archive.org/web/20200727054800/http://scikit-image.org) and [2020-08-15](http://web.archive.org/web/20200815074104/https://scikit-image.org/), though I can't find anything that looks like the cause in the commit history. @stefanv do you remember how the generated `_static/random.js` was supposed to be included in the corresponding folder in `build/html`?

Anyway I think I know why it isn't included. `random.js` is only created after sphinx is done https://github.com/scikit-image/scikit-image/blob/84bd0825cd3fdfc51dabcdbdeb0b8070051b1279/doc/Makefile#L49-L53

There is nothing copying it to `build/html/_static` until sphinx is invoked again which doesn't happen in our build job.

**Comment by lagru** [comment]
Okay, it's included now (see [artifacts](https://app.circleci.com/pipelines/github/scikit-image/scikit-image/5670/workflows/343eacb2-92f3-4fc3-b30c-120ff8ab2fd5/jobs/5719/artifacts)).

**Comment by jarrodmillman** [comment]
view-source:https://scikit-image.org/docs/dev/_static/random.js

It looks like it is still there, so I think there must be another reason that the random galleries aren't appearing on the main page.

**Pull request merged**
