### PR TITLE
Update up/download artifact version

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Review by lagru — APPROVED** [review]
Should we test this first on a `maintenance/` prefixed branch in our main repo?

**Comment by mkcor** [comment]
> Should we test this first on a `maintenance/` prefixed branch in our main repo?

Are you asking because of the matrix variables (as opposed to the 'simple' version updates, which would be similar to changes in #7368)?

**Comment by lagru** [comment]
No just as a precaution. Though, thinking about it, this will run soon enough through our regular nightly wheel builder.

**Comment by stefanv** [comment]
Good idea; see https://github.com/scikit-image/scikit-image/tree/maintenance/test-7545

**Comment by stefanv** [comment]
The 3.13t wheel build failed, but I don't think it's related: https://github.com/scikit-image/scikit-image/actions/runs/10907804013/job/30272333784

**Review by mkcor — APPROVED** [review]

**Pull request merged**
