### PR TITLE
Fixing order of elements in docstrings of skimage/color/colorconv

### PR DESCRIPTION
**Pull request by alexdesiqueira**
## Description
Some docstrings had elements with order different than given on numpydoc. Some small changes on text as well.

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by alexdesiqueira** [comment]
Travis complaining: `FAILED scikit-image/skimage/filters/rank/tests/test_rank.py::TestRank::test_rank_filter[windowed_histogram]`... :thinking: any ideas @scikit-image/core?

**Comment by alexdesiqueira** [comment]
AppVeyor compaining:
```
___________________ test_hog_output_correctness_l2hys_norm ____________________
    def test_hog_output_correctness_l2hys_norm():
        img = color.rgb2gray(data.astronaut())
>       correct_output = np.load(fetch('data/astronaut_GRAY_hog_L2-Hys.npy'))
(...)
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 503 Server Error: Backend unavailable,
connection timeout for url: https://raw.githubusercontent.com/scikit-image/scikit-image/master/skimage/data/astronaut_GRAY_hog_L2-Hys.npy
```
```

**Comment by rfezzani** [comment]
@alexdesiqueira, I restarted the CI, it's all green now ;-)

**Comment by sciunto** [comment]
Thanks!

**Pull request merged**
