### PR TITLE
Hardcode the inputs to test_ssim_grad

### PR DESCRIPTION
**Pull request by hmaarrfk**
This would randomly fail mostly when I run `pytest -n 4` to speed up the tests on 4 threads.

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by emmanuelle** [comment]
I just installed ``pytest-xdist``, speeding up tests is pretty cool :-). I also get a failure here with ``n=4``. Instead of hardcoding, why don't you use a random number generator with a fixed seed (like in test_slic.py for example, test_color_2d)? Fixing the seed solves the problem on my machine.

**Comment by hmaarrfk** [comment]
@emmanuelle even smarter

**Comment by jni** [comment]
@hmaarrfk thanks again! =)

**Comment by hmaarrfk** [comment]
Thanks @jni

**Comment by hmaarrfk** [comment]
Thanks for reviewing @emmanuelle

**Comment by hmaarrfk** [comment]
FYI, we need to find a solution for the tiffile doctest before you can run doctests in parallel too.

Those tests require a temporary file to be present which is created in the "first doc test".

I'm kinda in favour of helping tiffile package a wheel, then we can (optionally) depend on tiffile and not version it.

**Pull request merged**
