### PR TITLE
Deprecate qt and skivi plugins in skimage.io

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Ready for reviews.

Solves part of the overall deprecation of skivi. The viewer module is the other part, but I prefer to split in different PR.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by rfezzani — APPROVED** [review]
Excellent! Thank you @sciunto ;)

**Comment by hmaarrfk** [comment]
It doesn't even seem like this is tested anywhere.

**Comment by jni** [comment]
I'm late to the party but I love this. Thanks @sciunto! =D

**Comment by sciunto** [comment]
:)

**Pull request merged**
