### PR TITLE
Use --pre flag for Travis pip installs.

### PR DESCRIPTION
**Pull request by stefanv**
This way we can help NumPy and others test their pre-releases.

### CODE REVIEW

**Comment by jni** [comment]
Do we really want to do this for all PRs?

Idea: keep this PR around and simply rebase whenever numpy release a beta. Instant testing!

**Comment by soupault** [comment]
@jni

**Comment by stefanv** [comment]
We want to know whenever we break betas of any packages, so what's the harm in including it in all PRs?

**Comment by jni** [comment]
@stefanv we also want to make sure we work with existing releases, right?

**Comment by stefanv** [comment]
Yes, which is what we will get *until* a package releases a pre-release. We
could also set one of the Python versions to test without it?

**Comment by jni** [comment]
@stefanv a variation of this latter choice is what I would be most comfortable with. One test with minimal, one test with pre-release, remaining tests with with latest. Numpy prereleases can go for weeks, and I don't want to be in a position of having failing Travis builds because of a broken pre-release.

I suggest we make Python 3.5 test with pre.

**Comment by matthew-brett** [comment]
In case it's interesting - here's our version of the same thing : https://github.com/nipy/nibabel/pull/423

**Comment by stefanv** [comment]
Fiiinaaaalllyyyyyy

**Comment by blink1073** [comment]
LGTM

**Comment by JDWarner** [comment]
LGTM too, and I like the renamed variables. Easier to track the flow than by Python version.

**Pull request merged**
