### PR TITLE
Fix the order of return values for `hessian_matrix`

### LINKED ISSUE #5230: Wrong order in hessian_matrix?
## Description

In `hessian_matrix`, when `order='rc'`, the elements are supposed to be returned as `(Hrr, Hrc, Hcc)`. But if I'm understanding the code correctly, it instead returns `(Hcc, Hrc, Hrr)`:
```python
    gradients = np.gradient(gaussian_filtered)
    axes = range(image.ndim)

    if order == 'rc':  # I think this line is wrong -- should be if order == 'xy'
        axes = reversed(axes)

    H_elems = [np.gradient(gradients[ax0], axis=ax1)
               for ax0, ax1 in combinations_with_replacement(axes, 2)]
```

Note that when `order == 'rc'`, then
```python
axes = reversed(range(2))
combinations = list(combinations_with_replacement(axes, 2))
combinations
```
which yeilds `[(1, 1), (1, 0), (0, 0)]`, putting columns first instead of rows.

Am I correct that this isn't the intended behavior?

### PR DESCRIPTION
**Pull request by grlee77**
closes #5230

This fixes the reported bug where 'xy' order was returned when 'rc' was requested and vice-versa. The change here also matrix `hessian_matrix` order consistent with `structure_tensor` which has the same conventions.

A second inconsistency is that `structure_tensor` only allows use of mode='xy' for 2D images and otherwise raises an error, while `hessian_matrix` did not have this restriction. I have changed the `hessian_matrix` behavior here for consistency.

Fortunately, the presence of this bug did not effect the use cases of this function in higher order functions within scikit-image (e.g. `blob_doh` and various ridge filters like `sato`, `meijering`, `frangi`). The eigenvalues used by the ridge filters, for example, are the same whether or not the axes are reversed.

### CODE REVIEW

**Review by lagru — APPROVED** [review]
A few nitpicks and maybe we can make a test more specific but otherwise good to go. Thanks @grlee77!

**Comment by stefanv** [comment]
@lagru Want to make the minor adjustment to the test and merge this?

**Comment by lagru** [comment]
Okay, I'll take your https://github.com/scikit-image/scikit-image/pull/6624#issuecomment-1386594808 as an approval.

**Comment by lagru** [comment]
Thanks @grlee77 and @stefanv!

**Pull request merged**
