### PR TITLE
Fix equalize_adapthist border artifacts

### LINKED ISSUE #4160: equalize_adapthist produces image with artifact
## Description

equalize_adapthist produces images that look like they aren't fully processed

Input
https://drive.google.com/file/d/1EWWAEzM_bXzm6_CwmG17BPnGYJUcjFBX/view
Output
https://drive.google.com/file/d/1Qr8BJl2OYgjCcMZw6a3tNbJ_rpB2JBhc/view

I cannot upload tifs on the github so, I put them on the my Gdrive.

## Way to reproduce

import tifffile as tif
import skimage.exposure as ex

input_img = 'path_to_img'
out_img = 'path_to_img'

img = tif.imread(input_img)
corrected = ex.equalize_adapthist(img, 11, 0.3, 256)
eq = skimage.img_as_ubyte(corrected)
tif.imwrite(out_img, eq)

## Version information

3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.15.0
numpy version: 1.16.4

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

Closes #4160.

The artifacts comes from round-off errors in `map_array` shape computation in `_clahe` function ([here](https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/_adapthist.py#L119)).

Here is the result using the example of @VasylVaskivskyi in #4160:

adapt_hist_1

and prettier with `clip_lim=0.1`

adapt_hist_2

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Is there some kind of test one can add?

**Comment by emmanuelle** [comment]
@rfezzani I second @hmaarrfk's suggestion to add a test here, in order to check that the whole image is processed. Can you think of a tail which would fail with the current master and pass with your improvement? Thank you for the PR!

**Comment by rfezzani** [comment]
Sorry for the delay, I finally managed to find a reasonable test. I hope you like it.

**Comment by rfezzani** [comment]
Thank you @jni.

**Comment by rfezzani** [comment]
@jni and @sciunto , I have a couple of suggestions for refactoring/optimizing this `_adapthist` module, should I include them in this PR or does it deserve an other one?

**Comment by sciunto** [comment]
I usually prefer short PRs to review :)

**Comment by emmanuelle** [comment]
merging, thanks!

**Pull request merged**
