### PR TITLE
include all md files in manifest.in

### PR DESCRIPTION
**Pull request by sciunto**
## Description
I'm trying to rationalize this file.

The CODE_OF_CONDUCT.md must be included imo.

### CODE REVIEW

**Comment by sciunto** [comment]
It is used for the sdist (at least, afaik).

**Comment by emmanuelle** [comment]
an easy PR to approve and merge @scikit-image/core

**Comment by alexdesiqueira** [comment]
> The CODE_OF_CONDUCT.md must be included imo.
+1 @sciunto. Thank you!

**Comment by stefanv** [comment]
What is the point of having this in the source distribution? README is in there, because that is where pypi description came from. LICENSE for obvious reasons. The others? This is not where users or developers will find them. It's not a big deal either way, including a few more won't hurt.

**Comment by alexdesiqueira** [comment]
I would say that it's good having this kind of info easily available "offline" — but hey, what's offline anyway :slightly_smiling_face:

**Comment by sciunto** [comment]
yes, get all relevant files versioned outside git.

**Pull request merged**
