### PR TITLE
Perform todo tasks for 0.17!

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Some tasks were not performed. oops. Cc @emmanuelle 

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by emmanuelle** [comment]
oops indeed :-)

**Comment by emmanuelle** [comment]
I checked that the TODO was mentioned in the release notes and it is!

**Comment by hmaarrfk** [comment]
are we deciding to backport these? No opinion, just a question

**Comment by emmanuelle** [comment]
I think so, although it's a bit delicate. We said we would make these changes so not making them is a bug (sorry for this). And most people haven't upgraded yet so they won't notice. Thoughts?

**Comment by emmanuelle** [comment]
The other solution is to release 0.18 in a month :-).

**Comment by hmaarrfk** [comment]
Cool, Well ill let the release manager of 0.17.2 decide ;)

**Comment by emmanuelle** [comment]
Still interested in knowing other opinions before calling Mr meeseeksdev. But I guess the reason why @sciunto made quickly this PR is so that it could be in 0.17.2.

**Comment by sciunto** [comment]
IMO, I would backport.

**Comment by sciunto** [comment]
@meeseeksdev backport to v0.17.x

**Comment by sciunto** [comment]
It's also to open the debate in #4698 :)

**Comment by jni** [comment]
Hi everyone, I missed this PR, thank you all for handling it. One note I would add to this (and I'll make an issue and try to make a PR as soon as I get a chance) is that I would replace the `..deprecated` sections with `..versionchanged` sections, rather than delete them altogether. I think they are very useful for people getting errors in their code to quickly figure out what happened without reading several lots of release notes.

**Comment by sciunto** [comment]
good point.

**Pull request merged**
