### PR TITLE
Build tool: Pass tests that don't raise floating point exceptions on arm with soft-fp

### PR DESCRIPTION
**Pull request by hmaarrfk**
Issue #3335

Ready if this passes tests.

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@olebole can you try to build with this: [diff](https://patch-diff.githubusercontent.com/raw/scikit-image/scikit-image/pull/3337.diff) 
[patch](https://patch-diff.githubusercontent.com/raw/scikit-image/scikit-image/pull/3337.patch)

I don't know which you need.
I only disabled the check for 1 warning. If you still fail on the other warning, I'll disable it too.

**Comment by olebole** [comment]
I will test it on the weekend (will take some time, since the CPU is quite slow).
However,  I am not sure about this; at least the error message in #3335 means that _both_ warnings are not there.
What speaks against making both optional by adding `r'|\A\Z'`? Are you sure that you want to take it an error if they (on other archs) do not appear? You are later checking the result for correctness anyway.

**Comment by hmaarrfk** [comment]
@odebeir Can you just tell me what the warnings are when you run this code: should be much faster.
```python
import numpy as np
def shape_index():
    l2 = np.array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0., -1.,  0.],
       [ 0.,  0., -2.,  0.,  0.],
       [ 0., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])
    l1 = np.array([[ 0.,  0.,  2.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 2.,  0., -2.,  0.,  2.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  2.,  0.,  0.]])
    return (2.0 / np.pi) * np.arctan((l2 + l1) / (l2 - l1))
print(shape_index())
```
I would also like the output of the print statement.

@jni it fails on windows!!

**Comment by hmaarrfk** [comment]
@odebeir the patchc now simply makes the warning optional.
I don't like optional warnings without explanations, but with the comment pointing to the issue, I think it is fine.

**Comment by olebole** [comment]
It works after some trivial fixes -- the line should be
```
with expected_warnings([r'divide by zero|\A\Z', r'invalid value|\A\Z']):
```
I now however get another error:
```
________________________________ test_spacing_1 ________________________________

    def test_spacing_1():
        [...]
        # Test with `spacing` kwarg
        # First, anisotropic along Y
        with expected_warnings(['"cg" mode' + '|' + SCIPY_EXPECTED]):
            labels_aniso = random_walker(data_aniso, labels_aniso, mode='cg',
>                                        spacing=(1., 2., 1.))

../debian/tmp/usr/lib/python2.7/dist-packages/skimage/segmentation/tests/test_random_walker.py:
263: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/contextlib.py:24: in __exit__
    self.gen.next()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

matching = ['"cg" mode|numpy.linalg.matrix_rank|\\A\\Z']

    @contextmanager
    def expected_warnings(matching):
        """[...]"""
        with all_warnings() as w:
            # enter context
            yield w
            # exited user context, check the recorded warnings
            remaining = [m for m in matching if '\A\Z' not in m.split('|')]
            for warn in w:
                found = False
                for match in matching:
                    if re.search(match, str(warn.message)) is not None:
                        found = True
                        if match in remaining:
                            remaining.remove(match)
                if not found:
>                   raise ValueError('Unexpected warning: %s' % str(warn.message))
E                   ValueError: Unexpected warning: overflow encountered in long_scalars
```
I can open a new issue for this -- shall I?

**Comment by hmaarrfk** [comment]
The others were pretty safe to ignore. I wonder if this is a real bug.

**Comment by hmaarrfk** [comment]
Gah thanks!

**Comment by jni** [comment]
@meeseeksdev backport to v0.14.x

**Comment by jni** [comment]
@hmaarrfk thanks for this fix! =)

**Pull request merged**
