### PR TITLE
run face classification gallery example with a single thread

### PR DESCRIPTION
**Pull request by grlee77**
## Description

The example modified in this PR takes >5 minutes in local testing with the Dask `'threads'` scheduler. Changing to `'single-threaded'` resulted in completion in 46 seconds.

The intention of the PR is to reduce the time required for generating the gallery on CI and hopefully reduce the number of Azure timeouts we have been seeing recently.

If this also works well on CI, should we just remove use of Dask from the example? It seems like it complicates things unnecessarily if we can't actually benefit from multiple workers for this task.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
On CI, it did not seem to make a big difference. Maybe this is because Azure was already limiting the jobs to a single core? (I see 80 s for the full feature set computation in this PR vs 87 s in a previous PR I looked at.

For some reason, Azure will not show me the log in the cases where a timeout occurred ([example with timeout during gallery generation](https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=5669&view=logs&jobId=5e84a1d3-1354-51e2-40cf-26996967c2ef)), but I would like to know at what point it gets stuck in the times when it fails. In that failure case timeout occurred 30 minutes into the gallery generation, but in some other jobs that have succeeded in the past, it finishes in <13 minutes.

**Comment by grlee77** [comment]
For f72a3cf:
Python3.8 gallery testing completed in 11:44
Python3.7 gallery testing timed out at 55 minutes, but I couldn't see the log to see where this occasional hang occurs.

Now trying to split up the doc/gallery builds and add timeout on individual tasks to see if that helps get logs in case of failure.

**Comment by grlee77** [comment]
I have now moved some CI-related changes discussed above to #5343. This PR now only contains the minimal change to the example script.

**Review by jni — APPROVED** [review]
I'm happy with this but at the same time it looks like it's masking a deeper GIL issue... Perhaps we should create an issue about this?

**Comment by alexdesiqueira** [comment]
Thank you Greg!

**Pull request merged**
