### PR TITLE
Set astropy minimum requirement to 1.2 to help the CIs.

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description
Not too sure astropy was ever installed successfully.

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@scikit-image/core fun fun, the pip quiet flag also fails silently ;)

https://travis-ci.org/scikit-image/scikit-image/jobs/497867990#L2071

**Comment by stefanv** [comment]
Feel free to pick one and move on.  I think we only use this to test our fits plugin.

**Comment by hmaarrfk** [comment]
I was able to use astropy 1.0 to import pyfits. astropy 0.4 didn't install on my system (being very descriptive here). 

Astropy 1.2 has wheels python 2.7 and 3.5, so I think that is the best thing to do for our CIs and backport.

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.14.x

**Pull request merged**
