### PR TITLE
Bounding Box crop module issue 5428

### PR DESCRIPTION
**Pull request by ArpithaRaviSeetala**
Bounding Box crop module issue #5428
A newfile module - crop_bounding_box.py added. This file contains two
methods. One, to locate the users downloads folder and create the
Cropped folder if necessary. Two, a method to crop parts of the image
in the bounding box. All the cropped images are then saved in the folder
created in the download_path() method.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by ArpithaRaviSeetala** [comment]
Hello everyone, I am new to this platform. Can anybody help me why the "continuous-integration" checks don't pass even after I reverted the changes back to the state when all the checks have passed successfully. Can anybody help me with what happens in a "continuous integration" check.

**Comment by grlee77** [comment]
> Can anybody help me with what happens in a "continuous integration" check.

In this case, I wouldn't worry about it. The failure I see here is a timeout on Azure that has been annoying me for some time. Something occasionally stalls during the example gallery build, but I have so far been unable to diagnose a root cause. If I restart it, it may pass.

**Comment by ArpithaRaviSeetala** [comment]
> 
> 
> > Can anybody help me with what happens in a "continuous integration" check.
> 
> In this case, I wouldn't worry about it. The failure I see here is a timeout on Azure that has been annoying me for some time. Something occasionally stalls during the example gallery build, but I have so far been unable to diagnose a root cause. If I restart it, it may pass.

Thanks a lot for the clarification. Please do let me know in-case I can do something to re-run the checks from my end.

**Comment by grlee77** [comment]
Thank you for making the PR @ArpithaRaviSeetala, but I see that this implementation is OpenCV-based. That may be good from a performance perspective, but will limit it to the 2D case only (n-dimensional support was part of the request in #5428 and something we make an effort to support where possible)

The bigger issue is that OpenCV is not one of our required dependencies for scikit-image, so cannot be used as the basis for this function. We could debate about having an optional, fast code path using OpenCV for users who have it installed, but there would still need a fallback implementation for users without OpenCV.

**Comment by ArpithaRaviSeetala** [comment]
> 
> 
> Thank you for making the PR @ArpithaRaviSeetala, but I see that this implementation is OpenCV-based. That may be good from a performance perspective, but will limit it to the 2D case only (n-dimensional support was part of the request in #5428 and something we make an effort to support where possible)
> 
> The bigger issue is that OpenCV is not one of our required dependencies for scikit-image, so cannot be used as the basis for this function. We could debate about having an optional, fast code path using OpenCV for users who have it installed, but there would still need a fallback implementation for users without OpenCV.

Thanks a lot for the feedback @grlee77 . I will look into the points mentioned and try to come up with another approach which also includes solution for the n-dimensional case.

**Comment by grlee77** [comment]
Thank you for opening the PR @ArpithaRaviSeetala, but I am going to close this since there is now another PR for this feature that has an nD implementation (#5499). Feel free to review/comment on that one or work on another feature.

**Comment by ArpithaRaviSeetala** [comment]
> 
> 
> Thank you for opening the PR @ArpithaRaviSeetala, but I am going to close this since there is now another PR for this feature that has an nD implementation (#5499). Feel free to review/comment on that one or work on another feature.

Okay @grlee77 . Sure. Thank you very much.

**Pull request closed without merging**
