### PR TITLE
Fixed variable names to accord with r, c naming convention

### PR DESCRIPTION
**Pull request by michaelpacer**
Addresses https://github.com/scikit-image/scikit-image/issues/1595

### CODE REVIEW

**Comment by sciunto** [comment]
@michaelaye Did you check that r designates the row and c the column in the unittests?

**Comment by michaelaye** [comment]
You meant to address @michaelpacer I guess? :)

**Comment by michaelpacer** [comment]
All it was was changing the variable names from the y's to row and x's to column and when i tested it manually (not using the tests directory), that seemed to create the correct changes. To be honest I don't know how to test what you're asking with the unit tests, but once travis builds that should be automatically checked, yes?

**Comment by JDWarner** [comment]
Just to make sure we're all talking the same language... for a 2D NumPy array:

row-col

**Comment by sciunto** [comment]
The idea is just to check that shapes drawn off-centered on an image satisfies the definition that Josh recalled. I believe it would be good to check all this file and I also have on my todo list to check the transforms (Hough...). I know that these functions have been written and reviewed at a time when the convention was not explicitly defined.

**Comment by emmanuelle** [comment]
Do we want ``(r, c)`` or ``(row, col)``? 1-letter variable names should be avoided I think. http://scikit-image.org/docs/stable/user_guide/numpy_images.html#coordinate-conventions mentions the two possibilities (`r` or `row`).

**Comment by ahojnnes** [comment]
I am fine with single letter names for index variables.

**Comment by emmanuelle** [comment]
@scikit-image/core I have the impression that Travis errors don't have anything to do with this PR. Should we merge it anyway?

**Comment by blink1073** [comment]
Yep, merging and opened #1835.

**Pull request merged**
