### PR TITLE
Speed up inner loop of GLCM

### LINKED ISSUE #3377: Performance improvement for `scikit-image/skimage/feature/_texture.pyx`
## Description
When calculating GLCM using the _glcm_loop, the offset pixel calculation can be optimized slightly.
In lines 68-69 the pixel offset value is calculated per each element, those offset values are constant and require both the calculation of a trigonometric function and casting to a different variable type.
By calculating the rowOffset and columnOffset ouside of the loop those executions need only happen once.
                        row = r + <int>round(sin(angle) * distance)
                        col = c + <int>round(cos(angle) * distance)

Some further optimization can be done by using the offset size(s) to reduce the number of iterations by changing the range of the for loops in lines 63 and 64.
In my opinion it would be wiser to change the convention from distance and angle to  rowOffset and columnOffset, but that does not conform with the standard notations.

### PR DESCRIPTION
**Pull request by jni**
## Description
As suggested by @abTest-123 in #3377, pulling some computations and comparisons outside of the inner loop of the gray level co-occurrence matrix results in a significant speedup. In my machine, the included benchmark runs in 9.6ms with the new code, vs 14.7ms on master!

## Checklist
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] ~~[Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)~~
- [x] ~~Gallery example in `./doc/examples` (new features only)~~
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] ~~Unit tests~~

## References
Closes #3377 

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
By the way, while developing this I learned about the command `asv dev`, which is super useful: it runs the specified benchmarks in the current environment. (Rather than doing the full build matrix.)

**Comment by jni** [comment]
Just fyi, I think the remaining PEP8 issues should be ignored, as the angles list is more readable this way.

**Comment by hmaarrfk** [comment]
Does it make sense to have a separate PR for the benchmark to have this speed up visible in the history?

**Comment by jni** [comment]
I'm working on a solution for this problem. I don't want to have to break every PR into two, though, so we'll punt on this until that's in place. It's possible to build a history retroactively, so we can do that periodically.

**Comment by hmaarrfk** [comment]
Nice. I didn’t know we could build a history retroactively. That makes things much easier.

**Comment by jni** [comment]
What the... Anyone know what is going on here?

https://travis-ci.org/scikit-image/scikit-image/jobs/421352873#L5050

Pytest 3.7.3 was released yesterday, which is very suspicious.

**Comment by jni** [comment]
... Yup: https://github.com/pytest-dev/pytest/issues/3888

Options: downgrade/pin pytest, or wait for the fix.

**Comment by hmaarrfk** [comment]
Can you exclude versions in the requirements file?

**Comment by jni** [comment]
Looks like it!

```
 $ cat excl-requirements.txt 
numpy!=1.15.1

 $ pip install -r excl-requirements.txt 
Collecting numpy!=1.15.1 (from -r excl-requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.2 requires cython, which is not installed.
distributed 1.22.0 requires msgpack, which is not installed.
Installing collected packages: numpy
  Found existing installation: numpy 1.15.1
    Uninstalling numpy-1.15.1:
      Successfully uninstalled numpy-1.15.1
Successfully installed numpy-1.15.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

PR incoming!

**Comment by jni** [comment]
Actually I just appended it to this one to avoid a rebase. Hopefully it gets merged quickly... ;)

**Comment by jni** [comment]
*sigh* now what the hell is wrong with appveyor? This "morning project" is getting out of hand. LOL

**Comment by hmaarrfk** [comment]
It found matplotlib 3!!!

**Comment by hmaarrfk** [comment]
xref: PR #3222 <- only pull in --pre on one single Windows Build.
xref: https://github.com/scikit-image/scikit-image/issues/3228#issuecomment-400823864 <- allowing --pre failures

**Comment by soupault** [comment]
>It found matplotlib 3!!!

Awesome news! Need to buy some matplotlib shares :smiley:.

**Comment by abTest-123** [comment]
Not sure why - but it seems that the [pyx file](https://github.com/scikit-image/scikit-image/blob/da11c23ed9c2b5db146ffb96b5d05e4cf5206307/skimage/feature/_texture.pyx) hasn't updated. Not sure why/how to see the updated version?

**Comment by soupault** [comment]
@abTest-123 you were looking at the old version (see `blob/...` in your URL). The latest is here - https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_texture.pyx .

**Pull request merged**
