### PR TITLE
declare script deploy_doc in travis

### PR DESCRIPTION
**Pull request by sciunto**

### CODE REVIEW

**Comment by sciunto** [comment]
@blink1073 I tried to follow https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

I think it's necessary to declare the script, so that the script has access to the env variable. Not sure though.

**Comment by sciunto** [comment]
No that should not be correct.

**Comment by blink1073** [comment]
Here's a working version: https://github.com/jupyter/jupyter-js-services/blob/master/.travis.yml

**Comment by sciunto** [comment]
Ok, so I'm wrong...

**Comment by blink1073** [comment]
Yeah I am really stumped here...

**Comment by sciunto** [comment]
If the token is incorrect, wouldn't we have the same result (noting in the GH_TOKEN variable)?

**Comment by blink1073** [comment]
The token worked from my command line, unencrypted.  I generated the encrypted one the same way as the one linked above.

**Comment by blink1073** [comment]
ohhhhhh, I know what to do.

**Pull request closed without merging**
