### PR TITLE
hog block normalization fix

### PR DESCRIPTION
**Pull request by PuppySaturation**
Was reviewing and comparing with my own HoG implementation, noticed that the normalization was done wrong. I fixed it assuming an L-2 normalization.

### CODE REVIEW

**Comment by stefanv** [comment]
@scikit-image/core Can anyone who uses HoG's verify this fix?

**Comment by emmanuelle** [comment]
@stefanv it seems indeed right to use the L2 norm of ``block`` for normalization, and it would be consistent with the formula of http://en.wikipedia.org/wiki/Histogram_of_oriented_gradients (paragraph block normalization). +1 for merging.

**Comment by stefanv** [comment]
@PuppySaturation Thanks very much for this fix; could you please add a test, then I will merge.

**Comment by PuppySaturation** [comment]
Gave the test some though, didn't come up with anything that would be useful.

**Comment by PuppySaturation** [comment]
Gave the test some though, didn't come up with anything that would be useful. The current test for HoG don't seem to cover general value accuracy, so I'm not sure quite how to go about this.
Should I hardcode come known values into the test and check the results? If I check the norm of the result by recalculating it, I don't see that as being very useful. 

Given that is it such a small fix, if there was no test before, how does it warrant one now?

**Comment by JDWarner** [comment]
@PuppySaturation - Generally speaking, if the tests are bad at actually evaluating the function _feel completely free_ to improve them. Trivial tests are easy to write, but aren't good long-term.

I'm completely fine with hardcoded values, if there is a known valid example available or if one can hand-calculate the expected results. This type of test is very powerful, even if seemingly rather simple. Note that for this type of test, `np.testing.assert_allclose` is better than checking exact equality as future alternative implementations may well have slightly different, but effectively equal floating point results.

**Comment by PuppySaturation** [comment]
Yet for a complex operation such as HoG the only practical way of obtaining the values of a non-trivial transformation is to run the algorithm. That would mean they are in affect testing whether the implementation fits itself. This might be useful to some extent, but It would also mean that the tests themselves would have to be subject to bug fixes of the algorithm. Which would make future corrections complicated.

If my change were from:
`normalised_blocks[y,x,:] = normalize(block,'L1') `
to:
`normalised_blocks[y,x,:] = normalize(block,'L2') `

and the function normalize was properly tested, would HoG still needed a new test?

**Comment by JDWarner** [comment]
Yes, that would work. Ideally we would have an independently verified result to compare against, though.

**Comment by soupault** [comment]
I suppose, that's not the easiest thing to get for a HoG descriptior.

**Comment by soupault** [comment]
@JDWarner Ok, well, a comparison had been added in https://github.com/scikit-image/scikit-image/commit/c095daa2346c34bbd0ec628d1b52368301343402#diff-f7fbb052903c8ca5aab7b798019b73b3R23 .

**Comment by stefanv** [comment]
Perhaps @sdsingh has some thoughts, since he was looking at comparing with the Matlab results.

**Comment by PuppySaturation** [comment]
Thank you @soupault for picking this up. I completely forgot about it.

**Comment by sdsingh** [comment]
I tried comparing to Matlab results--the comparison is in #2011, and is not particularly encouraging. However, perhaps it will be fixed after this bug fix. Feel free to use tests from #2011 if they are useful.

**Comment by soupault** [comment]
Superseded by #2040.

**Pull request closed without merging**
