### PR TITLE
Clarify header pointing to notes for latest version released.

### LINKED ISSUE #6496: Dev docs show previous stable release notes
## Description

While working on #6495, I noticed that when I view https://scikit-image.org/docs/dev/release_notes.html, it says "Docs for 0.20.0.dev0" in the side bar on the left, but the text in `release_notes.html` is for the previous stable release v0.19.3.

Is this intentional?

I was half-expecting the dev docs to display the current work-in-progress of the dev "release notes". But I also acknowledge that this would be somewhat strange...

### PR DESCRIPTION
**Pull request by mkcor**
## Description

Minor / docs (one core dev approval is enough)
Related to #6496

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Review by lagru — APPROVED** [review]
Thanks @mkcor, this is an improvement so merging. But I don't think it fixes #6496 which I understand to be about the incongruence between "0.20.0.dev0" in the sidebar and "We’re happy to announce the release of scikit-image v0.19.3!" in the first line after the modified heading.

**Comment by lagru** [comment]
@mkcor I just noticed that you used a branch on our main repo, was that intentional?

**Comment by mkcor** [comment]
> @mkcor I just noticed that you used a branch on our main repo, was that intentional?

No, it wasn't. My bad. I didn't pay attention to this when editing from the GitHub interface.

> But I don't think it fixes https://github.com/scikit-image/scikit-image/issues/6496

Right, that's why I wrote "related to" (not "fixes" or "closes").

**Comment by lagru** [comment]
No worries. But look at the edit, you wrote "closes". :grin:

**Comment by mkcor** [comment]
> No worries. But look at the edit, you wrote "closes". :grin:

Oh, you edited! :laughing: Sorry, I didn't (try to) remember.  It's my first time using GitHub's version control for comments; I had never noticed this was available just like any other history; thanks for drawing my attention to it! :pray:

**Pull request merged**
