### PR TITLE
Specify 2D images in denoise bilateral docstring

### PR DESCRIPTION
**Pull request by jni**
Addresses #1840

### CODE REVIEW

**Comment by emmanuelle** [comment]
thanks Juan. Could you also add a warning when the image is 3-D and im.shape[-1] > 3?

**Comment by emmanuelle** [comment]
Since your change is already an improvement, I can also merge this PR first if you don't have time right now for the warning.

**Comment by JDWarner** [comment]
What happens for RGBA (M, N, 4) images or other combinations of color channels?

**Comment by jni** [comment]
@emmanuelle I don't think I have time right now. New warnings imply new tests. Did this cos it was late and stumbled across the easy issue in my feed. =)

@JDWarner I don't know, but based on the associated issue, I assume it denoises the alpha channel.

**Comment by emmanuelle** [comment]
@JDWarner as Juan says, every channel is filtered separately.

**Comment by emmanuelle** [comment]
@jni OK, merging and I'll leave issue #1840 open for warning + test

**Pull request merged**
