### PR TITLE
Handling of Contours for Moments

### PR DESCRIPTION
**Pull request by kne42**
## Description
In its current form, the moments module does not support the generation of moments from a contour (array of points). This pull request overloads `moments_central` in the .pyx source code to handle all arrays of the shape (N, 2) and perform contour-specific moment generation for them.

## Notes
* Please guide me through compiling with cython lol, I'm bad.
* I generated the new documentation. If it is not necessary, just ask and I will revert that commit.

## Checklist
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
Closes issue #2682.
1. [Johannes Kilian. Simple Image Analysis By Moments. Durham 
           University, version 0.2, Durham, 2001.](http://breckon.eu/toby/teaching/dip/opencv/SimpleImageAnalysisbyMoments.pdf)

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by emmanuelle** [comment]
Hi @kne42 ! Why would you want to compute the moments for a contour? Wouldn't it be to transform the contour into a binary array (with ``im[rr, cc] = 1``), and then to compute its moments?

**Comment by kne42** [comment]
I considered that @emmanuelle; the reason why I implemented the method raw was for optimization. After creating two equivalent images, `image = np.zeros((20, 20), dtype=np.double; image[13:17, 13:17] = 1` and `contour = np.array([[r, c] for r in range(13, 17) for c in range(13, 17)], dtype=np.double)` the cython function `moments_central` as implemented in the pull request saw a speed up from ~14 µs to ~8 µs with regards to the image and the contour implementations, respectively. This is not even taking into account the amount of time it would take to convert the contour to an image.

It does however, slow down the processing speed by ~1.5 µs compared to the original implementations when normal images are passed in due to depth checking. I could of course sacrifice the elegance of overloading and create two separate functions: one for contours and one for images.

Regardless, this change is a significant boost in performance for extrapolating the moments of a countour, especially since it is common practice to find the contours of an image, then iterate over that list, which would multiply this efficiency.

**Comment by kne42** [comment]
I would also like to note that this performance improvement is the direct result of iterating over a list of contours directly versus iterating over a 2D array.

The percentage boost with the contour converted to the smallest possible array containing the contour's points can be computed as follows: `len(range(min(contour), max(contour))) * len(range(min(contour[:, 1]), max(contour[:, 1]))) / len(contour)`

**Comment by stefanv** [comment]
This seems reasonable; we should think a bit about API (I don't like overriding existing methods to "magically" change behavior on shape; what if you have a 2x2 image, e.g.).  Let's add a new method to implement your suggested behavior.

You asked for help with Cython: any specific question?  Once you've installed skimage with `pip install -e .`, you can just run `python setup.py build_ext -i` each time after you modify .pyx files, and you should be set.

**Comment by kne42** [comment]
Okay, thanks! I'll work on it when I get back home or you can get someone from the sprint to work on it and merge with my branch.

**Comment by kne42** [comment]
@pep8speaks pep8ify

**Comment by kne42** [comment]
@OrkoHunter I think it's glitchy. It took 5 hours to complete and when it did, the PR didn't correct all of the issues the bot pointed out in the first place, and out of its 3 commits, there was only 1 change (?).

**Comment by OrkoHunter** [comment]
@kne42 Yep I agree with you. I found this while looking for failed requests to the server. I re-tried the payload and it made an irrelevant PR.
I have created an issue https://github.com/OrkoHunter/pep8speaks/issues/54 for this. I'll get back to this as soon as I reach back home (travelling from SciPy). :)f

**Comment by stefanv** [comment]
@kne42 The `flake8` tool is perfect for local corrections

**Comment by jni** [comment]
@kne42 Sorry that I'm late to comment on this, but it seems to clash a little with #2603. I'm hoping that we can piggyback this change onto that one and instead of adding some more 2D-specific Cython code...

**Comment by kne42** [comment]
Closing this pull request as a new implementation of the base `moments_central` has been merged. Will follow up with a new PR that is n-dimensional contour compatible.

**Pull request closed without merging**
