### PR TITLE
Simplified code in _euler_rotation

### PR DESCRIPTION
**Pull request by evbernardes**
## Description
Slightly simplified the code from `_euler_rotation` from `Transform/_geometric`.

Does not change much, but this version is a bit shorter and, arguably, a bit easier to understand.

## Checklist
Nothing new was implemented.

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks for taking a look @evbernardes! We really appreciate your eyes on this part of the code :pray:

The reason we use the matrix formulation is because that is the way it is most often presented in papers. Do you think we can preserve the linear algebra expression, while simplifying the axis handling?

**Comment by evbernardes** [comment]
> Thanks for taking a look @evbernardes! 

It's my pleasure :)

> The reason we use the matrix formulation is because that is the way it is most often presented in papers. Do you think we can preserve the linear algebra expression, while simplifying the axis handling?

I didn't really modify much of the code in this PR! I just implemented a little simplification, and it should give the same result. This is also why I didn't implement any new tests, since this should pass any test that also passed before.

The original one had this comment:
```python
# 0 -> (1, 2); 1 -> (0, 2); 2 -> (0, 1).
```
This is basically what I do with these lines:
```python
i = (axis + 2) % 3
j = (axis - 2) % 3
```
For example, if `axis = 2`, then `i = 1` and `j = 0`, which is equivalent to what was done already!

**Comment by stefanv** [comment]
I was specifically thinking of:

```python
    i = axis
    s = (-1)**i * np.sin(angle)
    c = np.cos(angle)
    R2 = np.array([[c, -s],
                   [s,  c]])
    Ri = np.eye(3)
```

That `R2` is very well known from transformation literature.

**Comment by evbernardes** [comment]
Right, I see what you mean! If you prefer to leave the matrix `R2` explicitly expressed, then I think the original implementation is pretty good already!

**Comment by stefanv** [comment]
OK, so maybe we'll leave it like that for now. But I *really* appreciate you taking a look! I am concerned about correctness in that PR I tagged you on, since none of us know our way around Euler rotations that well.

**Comment by evbernardes** [comment]
> But I _really_ appreciate you taking a look! I am concerned about correctness in that PR I tagged you on, since none of us know our way around Euler rotations that well.

Feel free to pinpoint me any things you'd like me to check in particular! 

I made some comments on things I think might come from misunderstandings… but then, I might just be missing some definitions specific to that application!

**Comment by stefanv** [comment]
Awesome, thanks again!

**Pull request closed without merging**
