### PR TITLE
Use relative imports in skimage files

### PR DESCRIPTION
**Pull request by ahojnnes**

### CODE REVIEW

**Comment by stefanv** [comment]
@blink1073 Do you have an easy way to test for the lowest working version?

**Comment by jjhelmus** [comment]
I tried a number of different version of Cython to see what version work.  

The results were as follows:

| Cython version | Errors |
| ------------------- | --------- |
| 0.19.2 |  10 |
| 0.20 | 10 |
| 0.20.1 | 10 |
| 0.20.2 | 10 |
| 0.21 | 0 |
| 0.21.1 | 0 |
| 0.21.2 | 0 |

It looks like Cython >= 0.21 is required.  I gave up trying to find where this fix was introduced into Cython.

For testing, on a Mac (10.9) running Anaconda's Python 2.7, latest Numpy, etc I used the commands:

```
conda remove cython
conda install cython=0.20.1
git clean -dfx
python setup.py build_ext -i
nosetests
python -c "import Cython; print Cython.__version__"
```

**Comment by blink1073** [comment]
Thanks @jjhelmus, that's exactly what I was going to do.  I say `0.21` all the way.  @ahojnnes, you'll have to edit `requirements.txt` and `DEPENDS.txt` to reflect the change.

**Comment by ahojnnes** [comment]
Let's hope that Travis is happy :-)

**Comment by ahojnnes** [comment]
Rebased.

**Comment by blink1073** [comment]
Quick, press the button @JDWarner!

**Comment by blink1073** [comment]
Times up, I'm going for it...

**Comment by stefanv** [comment]
:+1:

**Comment by JDWarner** [comment]
Sorry for the delay, I missed this one but it looks great.

**Pull request merged**
