### PR TITLE
graph cut for image segmentation

### PR DESCRIPTION
**Pull request by weilinear**
This is an early pull request for image segmentation using graph cut. I adopt code  `spectral_embedding` and `discretize` from scikit-learn with and remove those unused features within the code. I add an example to `plot_segmentations` based on the result from `slic`:
lena

The function calculates the affinity matrix as in `random_walker_segmentation` and then apply the graph cuts algorithms to get the pixel-wise discrete labels. Also, it can take pre-segmentation to accelerate the process. Image that with more than 1000 pixels wll suffer from the svd on large laplacian matrix. It currently supports `callable` function, numpy `ndarray` and some predefined methods(currently only `slic`) as a preprocessing method.

It may take some time to clean the codes and repair some trivial mistakes before review. Just send the pull request to make sure it is in the correct direction :)

PS: Actually I am not sure whether I can use code from `scikit-learn`? @amueller

### CODE REVIEW

**Comment by souravsingh** [comment]
Is the PR still being worked? If not, I can pick from where the work was left and attempt to finish up.

**Comment by Borda** [comment]
btw, what about using this segmentation? https://github.com/Borda/pyImSegm

**Comment by soupault** [comment]
@Borda great work! How fast is your code?

**Comment by Borda** [comment]
depends on several parameters/aspects, such as how many features you want to compute, what is the size of superpixels, etc., but in general it is manes of seconds...

**Comment by soupault** [comment]
@Borda could you, please, elaborate on what you have in mind? I see that your repo implements, so to say, a framework for segmentation. Are you suggesting to consider your implementation or Graph Cut, or something more?

**Comment by Borda** [comment]
@soupault I am not sure if I should suggest anything, I was giving an example that there are also some other graph-cut based segmentation... I think that using super-pixels features is quite useful and make the segmentation more robust and running graph-cut on large images is impossible to compare to running it on an image of the same size decomposed into super-pixels... The graph-cut is standard, and computed features are simple or what should I elaborate?

**Comment by alexdesiqueira** [comment]
Hi @souravsingh @Borda are any of you still interested in bringing this to life again? :)

**Comment by Borda** [comment]
it looks quite old... @alexdesiqueira do you mean to finish this PR or what I proposed makes Graph-Cut on superpixels? I could do the superpixel version, just need to find python graph-cut running on all OS, because [pyGCO](https://github.com/Borda/pyGCO) is now compiled only for Linux... I was considering https://github.com/Borda/pyImSegm/issues/21

**Comment by alexdesiqueira** [comment]
Hey @Borda,
I checked your issue ([Borda#21](https://github.com/Borda/pyImSegm/issues/21)) and it seems a nice algorithm! The papers where it is based ([[1](https://ieeexplore.ieee.org/document/937505), [2](https://link.springer.com/article/10.1007/s11263-006-7934-5)] and others) seem relevant, so I'm in favor of having it here.
@scikit-image/core are we in favor of closing this PR and @Borda opening a new one on graph-cut on superpixels?

**Comment by jni** [comment]
@alexdesiqueira @Borda the superpixel version exists in `skimage.future.graph`. We definitely need to pull that out of there... 🤦‍♂

**Comment by jni** [comment]
See https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_ncut.html#sphx-glr-auto-examples-segmentation-plot-ncut-py

**Comment by Borda** [comment]
@jni so it means that there is no need for another superpixel - graphCut, right?

**Comment by jni** [comment]
That's my reading of the situation, yes... This PR actually predates `skimage.future`, but, as many do, it got stuck in limbo while that was added. =\

**Comment by alexdesiqueira** [comment]
I see two ways we could proceed here:
1. Maybe it's time to discuss putting the `graph_cut` algorithms (normalized, threshold, n cut) at `skimage.graph`, changing API, all the stuff you would like to do, @jni. @Borda would you like to take care of that?
2. I checked the papers, and it seems that the algorithms differ (the one @Borda suggesting being "newer"). Since we have some cut algorithms already, I wouldn't mind us having another algorithm inside (maybe in `skimage.graph.cut`). What do you think about that @jni?

**Comment by alexdesiqueira** [comment]
> @alexdesiqueira @Borda the superpixel version exists in skimage.future.graph. We definitely need to pull that out of there...\

As per @jni's comment, I'm closing this PR. The plan is to bring the respective function in `future.graph` to `graph`.
Thank you everyone for your work on this one!

**Pull request closed without merging**
