### PR TITLE
segmentation.expand_labels sampling argument for anisotropic resolution

### PR DESCRIPTION
**Pull request by jouyun**
## Description
Adds additional option argument to segmentation.expand_labels function.  This allow for 
cases of expanding labels easily when the image stack is not isotropic in all dimensions, as 
is frequently the case for the z-dimension in most light microscopy applications.  Adds an
appropriate test.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Added optional sampling argument to segmentation.expand_labels

```release-note
...
```

### CODE REVIEW

**Comment by stefanv** [comment]
Apart from this keyword usually being named `spacing`, it seems very straightforward to pass it through to the underlying function. But I would like @jni to review, if he has time.

**Comment by jni** [comment]
Thanks @jouyun and sorry that this fell through the cracks! I agree with @stefanv, this is ready to go, with just:
- renaming `sampling` to `spacing` for consistency with other skimage functions.
- fixing merge conflicts.

Do you have time to do this? If you would like us to take those steps for you we will be happy to do so!

**Comment by jouyun** [comment]
I believe I have updated as you suggested.

Sean
________________________________

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
The failures are pooch download errors and can be ignored I think. imho this is ready to merge. Thanks @jouyun!

**Pull request merged**
