### PR TITLE
Specify the encoding of files opened in the setup phase

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

Help specify the correct encoding for non-standard platforms:
Helps #4705

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by sciunto** [comment]
If we can backport this to 0.17.2, that would be great (Cc @emmanuelle )

**Comment by hmaarrfk** [comment]
0.17.3 ;)

**Comment by emmanuelle** [comment]
Ah yes it missed the 0.17.2 train but there will probably be a 0.17.3 :-).

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.17.x

**Pull request merged**
