### PR TITLE
Fix docstring (missing minus sign) for `EuclideanTransform`.

### LINKED ISSUE #7380: A typo in source code comment and document
### Description:

Check the [doc](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.EuclideanTransform) and the [source code](https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/transform/_geometric.py#L1192).
For Eclidian Transform, the homogeneous transformation matrix should be like:

$$
\begin{bmatrix}
a_0&-b_0&a_1\\
b_0&a_0&b_1\\
0&0&1
\end{bmatrix}
$$

which equals to:

$$
\begin{bmatrix}
\cos\theta&-\sin\theta&t_x\\
\sin\theta&\cos\theta&t_y\\
0&0&1
\end{bmatrix}
$$

But now, in both of the source code comment and the document, it’s writen as this:

```
        [[a0  b0  a1]
         [b0  a0  b1]
         [0   0    1]]
```

Check the `__doc__`  in `Class SimilarityTransfrom`，it was written correctly:
```
        [[a0  -b0  a1]
         [b0  a0  b1]
         [0   0    1]]
```

I think maybe it’s a typo here. But it actually confused me for a minute :joy:

[First posted here](https://forum.image.sc/t/is-this-a-tiny-bug-in-source-code-comment-and-document-eclidian-transform-in-skimage-trasform-geometric/94605)

### Way to reproduce:

just found a little typo in code comment

### Version information:

```Shell
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]
Windows-11-10.0.22631-SP0
scikit-image version: 0.22.0
numpy version: 1.26.4
```

### PR DESCRIPTION
**Pull request by mkcor**
## Description

This is a tiny follow-up on https://github.com/scikit-image/scikit-image/pull/6840#issuecomment-1525688968.

Not sure about 5e8e1a84a7: I have right-aligned the matrix coefficients because I find it more readable, but I noticed that, in the docstring for `ProjectiveTransform`, they seem centred rather than right-aligned or left-aligned...

Closes #7380.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
Add missing minus sign in docstring of `skimage.transform.EuclideanTransform`.
```

### CODE REVIEW

**Review by lagru — APPROVED** [review]
Looks good. Happy with either way to format whitespace. :) Thanks Marianne.

**Comment by stefanv** [comment]
I think the `1` was wrong, and everything should be left-aligned, other than for signs.

**Comment by lagru** [comment]
The `1` as in the last element in the third row? If you look at the equation for rotation around the z-axis on [Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix#In_three_dimensions), it seems to be correct.

image

**Comment by mkcor** [comment]
The `1` is consistent with the plain equations (also in other docstrings for transforms of the same family).

I have reverted 5e8e1a84a75ae6a8e4dd456dbe31ca4ee4884ea7 where I had right-aligned two matrices. I'm not sure how  I should left-align
```py
        [[a0  -b0  a1]
         [b0  a0  b1]
         [0   0    1]]
```
though. Either
```py
        [[a0  -b0  a1]
         [b0  a0   b1]
         [0   0    1]]
```
where the matrix elements are left-aligned, period, or
```py
        [[a0  -b0  a1]
         [b0  a0   b1]
         [0   0    1 ]]
```
to preserve the array structure? Thanks.

**Comment by lagru** [comment]
I think Stéfan was suggesting something like this (aligned on letter / number, sign is ignored):
```
        [[a0 -b0  a1]
         [b0  a0  b1]
         [0   0   1 ]]
```

**Comment by mkcor** [comment]
@lagru should I label this PR 'quick win' or milestone 0.23?

**Comment by lagru** [comment]
"Quick win" would have been appropriate I think. But I'll just merge this now, as it has been open for some time with no open concerns. It's also minor and easy to revert.

**Comment by lagru** [comment]
This way it also goes into v0.23. @jarrodmillman, let me know if I should have postponed this until after the release and I'll do so in the future with similar cases.

**Pull request merged**
