### PR TITLE
Remove installation instructions for video packages

### PR DESCRIPTION
**Pull request by stefanv**
/cc @cdeil 
xref https://github.com/scikit-image/scikit-image/pull/3176

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by cdeil** [comment]
👍 to these changes.

One more small issue I noticed: there's a missing `https:` here and thus a broken link:

> The `Video` class in `PIMS <github.com/soft-matter/pims>`__ invokes PyAV and

http://scikit-image.org/docs/dev/user_guide/video.html#adding-random-access-to-pyav

**Comment by soupault** [comment]
Maybe a few words on the rationale of this change?

**Comment by stefanv** [comment]
The rationale is in the cross-linked issue, but basically the installation instructions were outdated and are no longer relevant.  Most of these packages can be installed either directly through pip or conda forge.

**Comment by sciunto** [comment]
Good to me as well. Thanks.

**Pull request merged**
