### PR TITLE
Backport PR #4236 on branch v0.16.x (Migrate to networkx 2.x)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #4236: Migrate to networkx 2.x

### CODE REVIEW

**Comment by NelleV** [comment]
I'd like to postpone this backport a bit so that I can finish the release cleanly.

**Comment by jni** [comment]
@NelleV no problem at all, merge this at your leisure! Or just let us know. =)

**Comment by jni** [comment]
Anyway is there any issue at all with merging to the branch now that the tag is done?

**Comment by NelleV** [comment]
We're good to go (I'm a bit surprised that you would backport such significant changes).

**Comment by jni** [comment]
Well, as @jarrodmillman said, if someone installs scikit-image 0.16.1 and NetworkX 2.4 together, it will break. I consider that a big problem!

**Pull request merged**
