### PR TITLE
Enable testing against nightly upstream wheels

### PR DESCRIPTION
**Pull request by lagru**
## Description

See https://github.com/scientific-python/upload-nightly-action#using-nightly-builds-in-ci

Somewhat related https://github.com/scikit-image/scikit-image/issues/6514.

cc @bsipocz, @jarrodmillman  

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
Looks all good, thanks for doing these updates.

Also, add a `development`, or the magic "fix" word that this closes #6956

**Comment by lagru** [comment]
> Also, add a development, or the magic "fix" word that this closes https://github.com/scikit-image/scikit-image/pull/6956

Not sure what you mean? "#6956" is this PR?

**Comment by lagru** [comment]
Also as pointed out to me by, this solution using `--extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple` isn't expected to include all nightly wheels right now. But it's expected upstream projects like NumPy will start providing wheels there. You can see under https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ which nightly wheels are already available...

**Comment by lagru** [comment]
One thing I'm not sure about is whether we want to test nightly wheels on every pull request. I don't want contributors to get confused and frustrated because they are assuming it's something they did. So we could turn this into [a regular actions that's only triggered for `main` like networkx did](https://github.com/networkx/networkx/pull/6705/files), but others pointed out that then there are no automatic notifications for everyone if there is a failure...

**Comment by lagru** [comment]
@jarrodmillman, this should be ready to merge now.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
