### PR TITLE
matplotlib: remove interpolation=nearest, none in our examples

### LINKED ISSUE #3998: SKIP: remove interpolation=nearest in our examples
## Description

Since 1.1.x, matplotlib set interpolation to nearest [by default](https://matplotlib.org/3.1.0/api/prev_api_changes/api_changes_1.1.x.html). We have plenty of examples in which the option is set to nearest (and a few to None).

I think there is room for simplifying our examples by removing these options. Any comment?

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Closes #3998

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Does this still output warnings?

**Comment by sciunto** [comment]
Warnings about what? I'm confused...

**Comment by hmaarrfk** [comment]
I think this was added because we changed what interpolation method we used by default.

If a user runs this with 0.16.dev, will they get many deprecation warnings?

**Comment by sciunto** [comment]
I'm still confused. Let me explain and see if it helps. Here we are talking about matplotlib. We have not decided which method to use by default (but mpl dev did). The removal of these option as no impact for users as mpl use nearest by default since a long time. they changed to this default value when they figured out that interpolating is not a good idea by default for people playing with images.

**Comment by hmaarrfk** [comment]
.... good double explaining something that never needed it in the first place.

Thanks for your patience!

**Pull request merged**
