### PR TITLE
Backport of #3238

### PR DESCRIPTION
**Pull request by jni**
## Description
See #3238 for details.

@soupault it was only four commits so I just cherry-picked them individually. I agree that merge commits are messy. =)

### CODE REVIEW

**Comment by jni** [comment]
@soupault oops! Fixed!

**Comment by hmaarrfk** [comment]
@jni I think this PR should be backported first. then rebase #3304 and the tests **should** pass.

**Comment by hmaarrfk** [comment]
Does github allow you to set rules for what you can merge? Seems like @stefanv has BDFL powers. Did he not extend those to you @jni?

**Comment by jni** [comment]
@hmaarrfk 

> Does github allow you to set rules for what you can merge? Seems like @stefanv has BDFL powers. Did he not extend those to you @jni?

We all have the same powers, but we endeavour to use them responsibly. =) By an unwritten agreement that needs to become written (I alluded to this in my roadmap proposal), we only merge after two reviews. But the backporting/LTS thing is new and we don't have a policy for these.

**Pull request merged**
