### PR TITLE
Backport PR #3477 on branch v0.14.x (Avoid travis failure regarding scikit.lookfor)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #3477: Avoid travis failure regarding scikit.lookfor

### CODE REVIEW

**Comment by jni** [comment]
For some reason this appears to have failed on Python 3.x?

**Comment by hmaarrfk** [comment]
I think you need a few more PRs: 
See current line
https://github.com/scikit-image/scikit-image/blob/master/requirements/build.txt#L1

**Comment by hmaarrfk** [comment]
Though i guess your rule does capture both of those :/

**Comment by hmaarrfk** [comment]
Cython version isn't being respected :/

https://travis-ci.org/scikit-image/scikit-image/jobs/453561833#L847

**Comment by sciunto** [comment]
I merge and backport another PR that should to the job.

**Comment by sciunto** [comment]
We  must merge this in v0.14.x #3227

**Pull request merged**
