### PR TITLE
Fix Travis docs push and add instructions

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
Ping @stefanv.

**Comment by stefanv** [comment]
Thanks!

**Comment by sciunto** [comment]
Does it mean that the doc is now refreshed after each merge in master?
Looks like favicon are still missing: https://linkchecker.sciunto.org/scikit-image.org-docs_dev
I didn't investigated more.

**Comment by blink1073** [comment]
@sciunto, it should, if all goes well in this [build](https://travis-ci.org/scikit-image/scikit-image/builds/80693231).

**Pull request merged**
