### PR TITLE
Bite the bullet: remove distutils and setup.py

### PR DESCRIPTION
**Pull request by stefanv**
Let's see how far we get!

### CODE REVIEW

**Comment by stefanv** [comment]
Too early :)

**Comment by stefanv** [comment]
Specifically, meson cannot build sdists (the way we like them, with compiled Cython files) the same way setuptools does. It instead takes a snapshot of the repo.

**Comment by stefanv** [comment]
Could build sdist using:

```
python -c "import setuptools; setuptools.setup()" sdist
```

with `pyproject.toml`:

```
[tool.setuptools.packages.find]
include = ["skimage*"]
```

But you'd need to specify the version in that setup call as well.

**Comment by eli-schwartz** [comment]
> Specifically, meson cannot build sdists (the way we like them, with compiled Cython files) the same way setuptools does. It instead takes a snapshot of the repo.

https://github.com/cython/cython/issues/5089#issuecomment-1408714455

:)

However, if you wish to do so anyway you'll want to:

- Run cython itself as a `meson.add_dist_script()` to add the .c files to the tarball.
- use a bit of if/else glue, check if `*.c` files exist in the source tree:
  - if they do, add those as extension module sources
  - if they don't, use `cython_gen.process()` instead

**Comment by stefanv** [comment]
:eyes: OK, I can go with that recommendation!

Still, I'd prefer not to package the whole git repo; there's a lot of CI cruft in there.

**Comment by eli-schwartz** [comment]
> Still, I'd prefer not to package the whole git repo; there's a lot of CI cruft in there.

That is a very valid point!

There are two general approaches to solving this:
- `meson.add_dist_script()` can be used to make *any* custom changes to the tarball, which includes deleting files or editing files in addition to running cython
- Meson uses `git archive` under the hood, so git's own support for `.gitattributes` and the `export-ignore` property can be used to ignore files when producing exported archives -- those will therefore not appear in the sdist either.

**Comment by stefanv** [comment]
Awesome, I'm going to try that; thanks!

**Comment by stefanv** [comment]
OK @jarrodmillman, this should be good to go now.

Please keep these commits separate, instead of squashing the PR.

**Comment by stefanv** [comment]
@jarrodmillman Scratch that; windows is now fine, but got some fixes on the Linux side still.

**Comment by stefanv** [comment]
@jarrodmillman I followed the new Cython guidance (see https://github.com/scikit-image/scikit-image/pull/6738#issuecomment-1423306354 above) and no longer add compiled Cython files to the sdist. This probably deserves a release note, what do you think?

**Comment by stefanv** [comment]
:heavy_check_mark: :sweat_smile:

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
