### PR TITLE
Corrected docstring formatting so that code block is displayed as code

### PR DESCRIPTION
**Pull request by emmanuelle**
Very minor change :-). I built the doc to verify it does what it should. See http://scikit-image.org/docs/stable/api/skimage.measure.html#profile-line to see the problematic formatting

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.14.x

**Comment by hmaarrfk** [comment]
@soupault here is the second test for meeseeksdev powers

**Comment by hmaarrfk** [comment]
Got it!

**Comment by JDWarner** [comment]
@meeseeksdev backport to v0.14.x

**Comment by jni** [comment]
Hmm, for some reason this was not picked up by the old contrib script. (The new one works only by date so it was picking up too much non-0.14 noise...) Will add to notes.

**Pull request merged**
