### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by ahojnnes**
Commit messages should explain individual fixes. I am little short of time and could not split into separate PRs.

### CODE REVIEW

**Comment by jni** [comment]
A multi-PR is fine, but Travis is deeply unhappy... =P

**Comment by ahojnnes** [comment]
Damn. I was hoping this goes through smoothly :-)

**Comment by ahojnnes** [comment]
This should fix it again.

**Comment by jni** [comment]
And so it does! Thanks @ahojnnes!

**Pull request merged**
