### PR TITLE
List only the two primary methods of installing skimage

### PR DESCRIPTION
**Pull request by stefanv**
If we consistently wanted to specify installation instructions for each distro / OS, the list will get very long.

### CODE REVIEW

**Review by mkcor — APPROVED** [review]
Good point!

**Review by jarrodmillman — APPROVED** [review]

**Comment by lagru** [comment]
```markdown
- **All platforms:** ``pip install scikit-image``
- **Conda:** ``conda install -c conda-forge scikit-image``
```
Clarifying question: is conda not available on all platforms as opposed to pip?

**Comment by stefanv** [comment]
All Pythons should have pip, but you can't conda in a traditional Python installation. Happy to update the wording, though, if you have a suggestion!

**Comment by lagru** [comment]
On some Linux distributions pip might not be available even though Python is. E.g. on Arch Linux, pip is not a dependency of the system Python and on my system it's not available unless I'm in a environment. 

Not a strong opinion, but I would suggest `**pip:**` as a less confusing variant.  Feel welcome to ping me if you want to update.

**Comment by stefanv** [comment]
See #6560

**Pull request merged**
