### PR TITLE
Some minor tweaks to CI

### PR DESCRIPTION
**Pull request by jni**
## Description

These are just minor follow-up tweaks on top of #5052:
- Circle-CI is just for doc builds. I think we should keep it on 3.8 until wheels for 3.9 are available for all our dependencies.
- ~~I think it's better to keep the `--retries` on pip installs on Azure, though happy to be overruled there! (?)~~ **Update:** undid this, see discussion below.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by terencehonles** [comment]
I followed up on your comment here https://github.com/scikit-image/scikit-image/pull/5052#discussion_r530510930, but the default retries is 5 and it's probably better to leave this the default unless there are problems with retrying that much and it really should be 3.

**Comment by hmaarrfk** [comment]
Do you want to rework the python 3.6 builds on Travis?

I thought we were going to drop 3.6. I would keep 1 token build for pypy support (maybe).

**Comment by jni** [comment]
@terencehonles sorry for jumping the gun! Is the 5 retries default new or did we just bungle that from the beginning??? 😂

@hmaarrfk Travis is getting jettisoned altogether... Do you mean to move some of the builds somewhere? @emmanuelle is doing that in #5074...

**Comment by terencehonles** [comment]
> @terencehonles sorry for jumping the gun! Is the 5 retries default new or did we just bungle that from the beginning??? 

Not sure on that, but it looks like it switched from 3 to 5 about 6 years ago :sweat_smile: 

https://github.com/pypa/pip/commit/15b2258769987870b02c5c1feea9f131b9f13b66

**Comment by jni** [comment]
Yikes! On our end it dates from #3072 but there wasn't any rationale or discussion. I'll revert! Thank you @terencehonles!

**Comment by hmaarrfk** [comment]
maybe it is time to retire appveyor too?

**Comment by hmaarrfk** [comment]
as for retry. The first pip that is installed was likely not up to date. I must have erroneously added the argument even to the updated pips,

**Review by alexdesiqueira — APPROVED** [review]

**Comment by alexdesiqueira** [comment]
Thank you @jni!

**Pull request merged**
