### PR TITLE
Add footprint_from_sequence to public API in skimage.morphology

### PR DESCRIPTION
**Pull request by lagru**
## Description

[`footprint_from_sequence` does not show up in our current API documentation](https://scikit-image.org/docs/dev/search.html?q=footprint_from_sequence&check_keywords=yes&area=default) but nevertheless seems to be part of our public API ([see this gallery example](https://scikit-image.org/docs/dev/auto_examples/numpy_operations/plot_footprint_decompositions.html))? I think this was simply forgotten in 852e9daccf6c394a96fd662ae1f1c5488f1b6596 (#5482).

Discovered while preparing the release notes for v0.20.

cc @grlee77

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by mkcor** [comment]
I agree that a small diff is always nicer (notably, it makes reviewing easier), but I don't think it's a relevant criterion ultimately (the real criterion being that the codebase be the way we want it to be). I think that alphabetical ordering in the __init__ file is good practice, so that's my only rationale.

**Comment by stefanv** [comment]
In the spirit of our contributor guide, I've gone ahead and alphabetized the imports to save @lagru the trouble.

**Comment by mkcor** [comment]
Thank you very much, @stefanv! Approving now.

**Review by mkcor — APPROVED** [review]

**Comment by stefanv** [comment]
@lagru Please go ahead and merge if happy with the patch I pushed.

**Comment by lagru** [comment]
Thanks to both of you. Though I'd like to state that I don't agree with your weighting of importance here. :wink:

> I agree that a small diff is always nicer [...], but I don't think it's a relevant criterion ultimately (the real criterion being that the codebase be the way we want it to be). I think that alphabetical ordering in the init file is good practice, so that's my only rationale.

Let's hope that at some point we have the tools and consensus to automate this kind of noise away.

**Comment by stefanv** [comment]
See https://github.com/scikit-image/scikit-image/pull/6563

**Pull request merged**
