### PR TITLE
threshold_otsu can't work with one color images

### LINKED ISSUE #1856: threshold_otsu raises exception when image is one color
Tested against current HEAD:

```pycon
>>> import numpy as np
>>> from skimage.filters import threshold_otsu
>>> threshold_otsu(np.array([1,2,3]))
1
>>> threshold_otsu(np.array([1,1,1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/skimage/filters/thresholding.py", line 140, in threshold_otsu
    idx = np.argmax(variance12)
  File "…/numpy/core/fromnumeric.py", line 968, in argmax
    return argmax(axis, out)
ValueError: attempt to get argmax of an empty sequence
```

### PR DESCRIPTION
**Pull request by OrkoHunter**
Fixes #1856

### CODE REVIEW

**Comment by jni** [comment]
@OrkoHunter Thanks! This new line needs to be tested! Use `np.testing.assert_raises`.

**Comment by OrkoHunter** [comment]
@jni Added the test.

**Comment by wolever** [comment]
What's the process for getting the documentation for `threshold_otsu` updated so it clearly describes this case?

**Comment by stefanv** [comment]
Just make a pull request to update the docstring in the source.

**Pull request merged**
