### PR TITLE
WIP: (2/4) n-Dimensional Geometric Transformations

### PR DESCRIPTION
**Pull request by kne42**
## Description
Enhances geometric transformation classes to work on points of any dimension.

## Checklist
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

## References
Dependent upon #2747.
Dependency for #2739.

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by stefanv** [comment]
We need reviewers for this issue please @scikit-image/core

**Comment by kne42** [comment]
@stefanv This PR is still a WIP. I will finish it once I fully adjust to my course load.

However, #2747 could use reviewing as this (and the other two parts) are dependent upon the function introduced in it.

**Comment by stefanv** [comment]
Yes, I think it's hard to evaluate that one in isolation, because it is really shaped by what happens in numbers 2, 3, and 4.

**Comment by ahojnnes** [comment]
@kne42 I appreciate the efforts, thanks! I looked at your changes and I don't know what the essential/fundamental matrix in a N-dimensional space should be. Maybe you can clarify what your intention is here. I think, it's not possible to make any transformation work in all dimensions. Also, it is not sufficient to make the documentation/constructors compatible but the transformation and estimation code would need a reimplementation too.

**Comment by kne42** [comment]
@ahojnnes I'll need to actually check out the math, but I believe that the way that `estimate` is currently implemented in the classes that I have enhanced would work for N-dimensional images.

As for your concerns regarding the proper functionality of fundamental and essential matrices in N-dimensional space, they are both transformation matrices and therefore have the shape (N+1, N+1). Similarly, the submatrix at [\:N+1, \:N+1] corresponds to the scaling and rotation components of the transformation matrix and the column at N+1 corresponds to the translation vector. You are able to use epipolar geometry to determine the fundamental and essential matrices in nD space because just as where with 2D images, more information about a 3D image can be extrapolated due to the differing viewpoints (this is the mathematical equivalency of depth) — N-dimensional images can be used to infer more details about the (N+1)-dimensional world that they are describing.

**Comment by kne42** [comment]
Closing, as no changes will take place aside from those necessary to get #2739 working.

**Pull request closed without merging**
