### PR TITLE
Added the Laplacian operator

### PR DESCRIPTION
**Pull request by glemaitre**
Hi,

Just added the Laplace operator to compute the approximation of 2nd-order derivative.

Since this is my first pull-request, I tried to follow the other syntax: I documented, test and add the to the __init__.py

Let me know if it is actually useful.

Cheers,

### CODE REVIEW

**Comment by jni** [comment]
@glemaitre Thanks for a very clean PR! Could I ask for a couple of changes from you?

1. There's actually no reason that the Laplace filter needs to be limited to 2D images. You can create an nD image kernel as follows:

```python
def laplace_kernel(dims):
    kern = np.ones((3,) * dims, float)
    kern[(1,) * dims] = - 3 ** dims + 1
    kern /= 3 ** dims
    return kern
```

Can you add this and remove the `assertnD` call?

2. The tests are a bit too trivial. I can do a lot of damage to the `laplace` function before the tests will pick it up! =) Could you write a test for e.g. detecting a vertical edge? You might get some use from `np.allclose` for detecting the correct magnitude of the edge.

Thank you again!

**Comment by glemaitre** [comment]
Ok I'm on it.

**Comment by glemaitre** [comment]
Hey,

I modified using a Laplacian kernel as you proposed. However, I reuse the implementation from `skimage.restoration.uft.laplacian()`.

I also did a less naive test for a 0-image with a 1-square inside it.

Cheers,

**Comment by jni** [comment]
Ha! I didn't even know that was there! =)

The Appveyor failure appears to be unrelated to this, so I'm merging! Thank you!

**Pull request merged**
