### PR TITLE
WIP: Change Cython language_level to 3.

### PR DESCRIPTION
**Pull request by stefanv**
Starts to address https://github.com/scikit-image/scikit-image/issues/3510

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](https://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by emmanuelle** [comment]
Maybe add in TODO.txt to monitor when Cython changes its default directive to Python3.

**Comment by hmaarrfk** [comment]
I think it neneds a rebase and a version bump for Cython.

**Comment by hmaarrfk** [comment]
The error is really not descriptive of the problem. Maybe somebody @cython can help us make sense of this?

```python
/home/mark2/miniconda3/envs/skdev/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
skimage/graph/__init__.py:1: in <module>
    from .spath import shortest_path
skimage/graph/spath.py:2: in <module>
    from . import _spath
skimage/graph/_spath.pyx:1: in init skimage.graph._spath
    # -*- python -*-
skimage/graph/_mcp.pyx:230: in init skimage.graph._mcp
    cdef class MCP:
E   AttributeError: type object 'skimage.graph._mcp.MCP' has no attribute '__reduce_cython__'

```

Note i had to change `_spath` with the following patch
```patch
diff --git a/skimage/graph/_spath.pyx b/skimage/graph/_spath.pyx
index 1624bc7d6..a261e4b7b 100644
--- a/skimage/graph/_spath.pyx
+++ b/skimage/graph/_spath.pyx
@@ -1,7 +1,7 @@
 # -*- python -*-
 
-import _mcp
-cimport _mcp
+from . import _mcp
+from . cimport _mcp
 from libc.math cimport fabs
```

**Comment by hmaarrfk** [comment]
@stefanv this needs a rebase and will work at least with cython = 

You also need this patch after the rebase:

```patch
diff --git a/skimage/draw/_draw.pyx b/skimage/draw/_draw.pyx
index 4acfccf37..7baa3f691 100644
--- a/skimage/draw/_draw.pyx
+++ b/skimage/draw/_draw.pyx
@@ -299,10 +299,10 @@ def _circle_perimeter(Py_ssize_t r_o, Py_ssize_t c_o, Py_ssize_t radius,
     cdef double dceil_prev = 0
 
     cdef char cmethod
-    if method == b'bresenham':
+    if method == 'bresenham':
         d = 3 - 2 * radius
         cmethod = b'b'
-    elif method == b'andres':
+    elif method == 'andres':
         d = radius - 1
         cmethod = b'a'
     else:
```

**Comment by hmaarrfk** [comment]
what happened to ctmf?

**Comment by hmaarrfk** [comment]
nevermind, I still get the same error.

**Comment by hmaarrfk** [comment]
Finally got it working. It seems we needed to use relative imports:
See
https://github.com/scikit-image/scikit-image/pull/3707/commits/1db0dcadacd3c476dcb8f854e89dcd6fa84fc745

**Comment by stefanv** [comment]
Superseded by #3707

**Pull request closed without merging**
