### PR TITLE
Update docstring slic superpixels

### PR DESCRIPTION
**Pull request by RonakSharma1**
Updated the image docstring to highlight the NaN issue

### CODE REVIEW

**Comment by jni** [comment]
@RonakSharma1 it looks like git inadvertently added a whole bunch of .DS_Store files. Could you please remove each of them with `git rm path/to/.DS_Store`, then commit and push again?

**Comment by RonakSharma1** [comment]
@jni Thanks for letting me know. I have removed the .DS_Store files now. Let me know if this problem still exists.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Thank you @RonakSharma1!

**Comment by RonakSharma1** [comment]
Thank you for my first contribution!

**Comment by stefanv** [comment]
Addresses https://github.com/scikit-image/scikit-image/issues/4883

**Pull request merged**
