### PR TITLE
[WIP] Drop python 3.6 from the build matrix

### PR DESCRIPTION
**Pull request by hmaarrfk**
## Description

This does the technical work to drop python 3.6 from the build matrix.
Follow recommendations from NEP29 proactively: https://numpy.org/neps/nep-0029-deprecation_policy.html

It is probably best to focus the discussion on the mailing list:

Mailing list discussion: https://mail.python.org/archives/list/scikit-image@python.org/thread/X5XBWFD2DYKXC2XYBCY6Z5D7FCHTMKEA/

NumPy mailing list discussion: https://mail.python.org/pipermail/numpy-discussion/2020-November/081127.html

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by soupault** [comment]
+1 if the numpy team falls back to NEP29 policy. Although, not going to lie, to me 3.6 sounds quite recent.

**Comment by hmaarrfk** [comment]
It seems that many of our minimum pins would need updating too because they don't exist as wheels for python 3.7.

This tool can help refresh dependencies for nep29 conformity
pypi.org/project/nep29

**Comment by emmanuelle** [comment]
I think you also need to modify the `.appveyor.yml`. Probably we want to merge this PR after the `0.18.x` branch is made?

**Comment by hmaarrfk** [comment]
image

Numpy just decided to drop Python 3.6. If this PR is ready in time approved and all, I wouldn't "wait" to merge it in.

**Comment by jni** [comment]
I agree with @hmaarrfk, now that NumPy is going to follow NEP-29 strictly also, I think we should just drop it — the drop date was June so we are well past it.

@hmaarrfk Do you need any help getting this to pass? Is this PR dependent on the other build matrix PRs in flight? I don't have a good overview right now.

**Comment by hmaarrfk** [comment]
I would like to help the pthon 3.8 pr get through, then do a straight version bump on all python versions with NEP29 updates.

I was holding off until the numpy decision went through

**Pull request closed without merging**
