### PR TITLE
Use math.prod instead of np.prod where possible

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This PR should be merged after #6056, which it is built on top of (`math.prod` does not exist in Python 3.7). Only commits starting from 13cda12 here are new.

One motivation is reducing overhead of NumPy calls to compute small products based on image shapes, etc which are only `ndim` in length. The overhead of np.prod is a few microseconds while for math.prod it is < 100 ns.

It will also generally be helpful in supporting other array backends to reduce usage of the NumPy API in places where it is not needed. For example, we would not want to replace `np->xp` here if using the `__array_namespace__` proposed for NumPy 1.22 as this would lead to use of `cupy.prod` when the input is a GPU array. That would have even larger overhead and would return a 0-dim float array on the GPU rather than the desired float value on the host. Use of `math.prod` ensures we get a float on the host.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Review by rfezzani — APPROVED** [review]

**Comment by jni** [comment]
@grlee77 the appveyor `--pre` fail (with numpy 1.22rc1) is mighty suspicious... (probably not related to the PR but thought I'd note it down...)

https://ci.appveyor.com/project/scikit-image/scikit-image/builds/41643832/job/b2p28dgo33fh8wt3?fullLog=true#L7640

**Comment by jni** [comment]
Note that there was a timing issue — the Linux `--pre` build didn't have 1.22rc1 yet!

https://github.com/scikit-image/scikit-image/runs/4303205297?check_suite_focus=true#step:4:51

So this might affect all our builds now...

**Comment by jni** [comment]
Ditto for Azure: https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=7138&view=logs&j=b083e468-b9e5-5594-1c70-563bdb1556ce&t=d8a92811-2237-50f3-d9ec-b995b6d901e1&l=54

**Comment by grlee77** [comment]
> @grlee77 the appveyor --pre fail (with numpy 1.22rc1) is mighty suspicious... 

Thanks, I will look into it. I also noticed some warnings about use of deprecated `np.int` in SIFT.

**Pull request merged**
