### PR TITLE
Drop support for Python 3.7 on main

### PR DESCRIPTION
**Pull request by grlee77**
## Description

In accordance with NEP-29, Python 3.7 support [can be dropped from main](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) (given that we will not make a non-0.19.x release before the end of the year). Some other projects like SciPy have already done so in their main branch.

This will allow us to reduce our CI test matrix sizes and take advantage of new features introduced in Python 3.8 (such as new typing functionality, `math.prod`, etc.)

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
should we also go ahead and remove the error message text about Python 2.7 support ("For Python 2.7, please install the 0.14.x Long Term Support release using:"... in setup.py)? I don't think we are still updating that branch at this point?

**Comment by grlee77** [comment]
apparently need to bumpy our NumPy requirement from 1.17.0 to 1.17.3 as the first version providing Python 3.8 wheels.

**Review by jni — APPROVED** [review]

**Comment by hmaarrfk** [comment]
I was going to say lets wait for numpy to drop it. But they did! Wow sticking to nep29!

**Comment by hmaarrfk** [comment]
https://github.com/numpy/numpy/blob/main/setup.py#L410

**Review by hmaarrfk — APPROVED** [review]

**Comment by hmaarrfk** [comment]
I put my finger on "Merge pull request" a few times. But I want this to linger here for a little longer tin case there are strong objects.

**Comment by grlee77** [comment]
closing this as @jni merged #6057 which included all of the commits here

**Pull request closed without merging**
