### PR TITLE
[WIP]- Change sphinx theme for docs

### PR DESCRIPTION
**Pull request by leej3**
In a discussion on the mailing list with @stefanv and @jni migrating to the pydata sphinx theme for the docs was mentioned. 

This would:
a) address an existing problem with no warning banner showing when users are accidentally accessing docs for old versions of the package
 b) Make use of some of the niceties of the pydata sphinx theme. This is a prototype for this migration to trigger discussion.

I have looked through other users to get a sense of how they have organized their site using this theme (these are listed [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/)).

Generally the logo in the web page title bar is used as an overview of the project. This usually contains some intro text and pretty pictures. Sometimes it provides a set links both internal and external to the website that help orient the would be user/contributor. This sometimes just reiterates the structure already defined by each tab in the title bar of the website and other times provides a different view into the website (typically more detailed and targeted than the title bar tabs can be). Here is a quick summary of the different sites to give a sense of the different organizations:

pydata sphinx theme docs:
+ Tabs: user guide, contributing, demo site, changelog, pandas docs 
+ Home page:  overview is simple description and links into some of the tabs

pandas:
+ Tabs: getting started, user guide, api reference, development, release notes 
+ Home page:  tabs repeated in overview page

numpy:
+ Tabs: user guide, api reference, development 
+ Home page:  overview page contains many different links, some unique, and other indexing into the tabs themselves or subsections within them

bokeh:
+ Tabs: version, first steps, user guid, gallery, reference, developers, releases, tutorial, community 
+ Home page:  overview largely describes the tabs

binder:
+ Tabs: tutorials, how-to guides, reference, about, contribute 
+ Home page:  overview page largely describes the tabs

scipy:
+ Tabs: getting started, user guide, api reference, development, release notes 
+ Home page: Concise... reiterates tabs, adds some basic info and links

networkX:
+ Tabs: install, tutorial, reference, releases, developer, gallery, guides
+ Home page: Provides various bits of information about the project similar to the `About` tab of other projects 

fairlearn:
+ Tabs: about us, quickstart, user guide, api reference, example notebooks, contributor guide, faq 
+ Home page:  a snazzy webpage with a general overview

Current sections on scikit-image website that are considered as tabs when switching to the pydata sphinx theme:

+ scikit-image: image processing in Python
+ API Reference for skimage x.x.x dev
+ Version 0.16 # links to api changes
+ Installing scikit-image
+ User guide
+ Glossary
+ Working with scikit-image source code
+ How to contribute to scikit-image
+ License
+ General examples
+ Release notes
+ Core developer guide
+ scikit image proposals
+ our mission
+ scikit-image code of conduct
Home page: links to many sections that do not map perfectly to the above sections

I propose mapping this structure to the following (and have provided a basic implementation of this in this PR):

+ Skimage homepage (as before and accessed via the logo)
+ `Overview` instead of being labelled  scikit-image: image processing in Python

+ `User guide` that contains
	+ Installing scikit-image
	+ User guide
	+ Examples
	+ Glossary
+ `Contribute`
	+ Working with scikit-image source code
    + How to contribute to scikit-image
	+ Core developer guide
+ `API` that contains
	+ API changes
	+ API Reference for skimage x.x.x dev
	+ scikit image proposals
+ `Changelog` which contains Release notes
+ `About` which contains
	+ License
	+ our mission
	+ scikit-image code of conduct

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
Wow, thanks @leej3! 

Here is a link to the CircleCI doc build output: https://2391-2014929-gh.circle-artifacts.com/0/doc/build/html/index.html

This looks like a new failure, but should be easy to fix:
https://github.com/scikit-image/scikit-image/pull/5489/checks?check_run_id=3143576662#step:5:2278

**Comment by grlee77** [comment]
The organization here seems reasonable to me. For some reason, I do not see the project logo at all when browsing the doc artifact. 

It looks like most content is there, but a couple of things like the pictures of the current core team and emeritus members and the "News" items are missing. Is there other pages you know of that are left out in this version?

**Comment by leej3** [comment]
> The organization here seems reasonable to me. For some reason, I do not see the project logo at all when browsing the doc artifact.

The project logo should probably appear at the top left where the text "skimage" currently sits. That must have been lost in translation.


> It looks like most content is there, but a couple of things like the pictures of the current core team and emeritus members and the "News" items are missing. Is there other pages you know of that are left out in this version?

Does Changelog contain the "News"? Also, I can't spot that or the picture on the current site (I am referring to the documentation, there is a component of the scikit-image website that is built elsewhere I believe). Can you send on a link? There shouldn't really be anything missing as files in doc/source raise an error if they are not included somewhere in the toctree. I can ask around for the gotchas in that statement though!

**Comment by grlee77** [comment]
It looks like the script for generating the HTML for the team list is in a different repository here:
https://github.com/scikit-image/scikit-image-web/blob/main/tools/team_list.py

I am actually not very familiar with how the website builds are configured currently. @jni or @stefanv should have a better idea about that.

**Comment by grlee77** [comment]
The NEWS items are in this file in that repo, here: https://github.com/scikit-image/scikit-image-web/blob/main/index.rst

**Comment by grlee77** [comment]
My other feedback at the moment would be that our nice examples **Gallery** is pretty hidden in the new design. I would prefer it to show up alongside the other items in the top bar (similar to how it is currently at https://scikit-image.org/).

We might also consider adding **Installation** up top as well. I seem to recall our web stats showing that was the most commonly visited page.

**Comment by grlee77** [comment]
Here is the site with our web stats: https://plausible.io/scikit-image.org

**Comment by stefanv** [comment]
This looks very nice already, thanks @leej3.  Agreed with @grlee77 on the gallery being more prominent.  I like the grouping you proposed.

**Comment by grlee77** [comment]
I'm not sure where is the best place to post this, but as it is related to the website I have put it here. 

I parsed the "Top Pages" data from https://plausible.io/scikit-image.org to get
an idea of what pages are being most commonly visited within 4 categories that I defined (API, User Guide, Example Gallery, Other).

The numbers here are the totals over the last 6 months and are in terms of number of visitors rather than page views. The totals have been combined across the dev, stable and release-specific docs.


**API pages**
<details>
<summary>API Details</summary>

```
skimage.measure.html: 60701
skimage.transform.html: 51716
skimage.filters.html: 42073
skimage.io.html: 41257
skimage.feature.html: 37808
skimage.morphology.html: 37099
skimage.segmentation.html: 33099
skimage.color.html: 22775
skimage.html: 21949
skimage.exposure.html: 19988
api.html: 19900
skimage.metrics.html: 19244
skimage.util.html: 15214
skimage.draw.html: 15105
skimage.data.html: 12939
skimage.restoration.html: 10423
skimage.filters.rank.html: 6099
skimage.registration.html: 4826
api_changes.html: 2303
skimage.future.graph.html: 1777
skimage.graph.html: 1371
skimage.future.html: 786
skimage.viewer.html: 730
skimage.viewer.plugins.html: 373
skimage.viewer.viewers.html: 282
skimage.viewer.canvastools.html: 267
skimage.viewer.widgets.html: 219
skimage.viewer.utils.html: 178
```

</details>

**User Guide pages**
<details>
<summary>User Guide Details</summary>

```
data_types.html: 20819
numpy_images.html: 18498
user_guide.html: 17500
getting_started.html: 11871
tutorial_segmentation.html: 10367
transforming_image_data.html: 6738
video.html: 4862
viewer.html: 3440
geometrical_transform.html: 3125
visualization.html: 2395
getting_help.html: 1320
tutorials.html: 1239
tutorial_parallelization.html: 1171
plugins.html: 1115
```

</details>

**Gallery Examples pages**
<details>
<summary>Examples Details</summary>

```
index.html: 43332
transform/plot_rescale.html: 29910
transform/plot_ssim.html: 18275
color_exposure/plot_rgb_to_gray.html: 15022
segmentation/plot_watershed.html: 14929
edges/plot_canny.html: 13030
edges/plot_skeleton.html: 12520
features_detection/plot_hog.html: 12324
segmentation/plot_regionprops.html: 12170
color_exposure/plot_equalize.html: 12021
features_detection/plot_glcm.html: 11829
segmentation/plot_label.html: 11449
segmentation/plot_thresholding.html: 10883
edges/plot_contours.html: 10047
features_detection/plot_blob.html: 9829
edges/plot_circular_elliptical_hough_transform.html: 9256
applications/plot_morphology.html: 8953
segmentation/plot_segmentations.html: 8819
edges/plot_line_hough_transform.html: 8624
edges/plot_active_contours.html: 8521
features_detection/plot_local_binary_pattern.html: 8492
segmentation/plot_peak_local_max.html: 8327
edges/plot_edge_filter.html: 7932
color_exposure/plot_histogram_matching.html: 7850
transform/plot_radon_transform.html: 7238
color_exposure/plot_rgb_to_hsv.html: 6815
filters/plot_denoise.html: 6776
applications/plot_thresholding.html: 5926
data/plot_scientific.html: 5757
filters/plot_entropy.html: 5512
features_detection/plot_gabor.html: 5506
features_detection/plot_template.html: 5421
edges/plot_marching_cubes.html: 5290
segmentation/plot_floodfill.html: 5249
segmentation/plot_multiotsu.html: 5137
applications/plot_3d_image_processing.html: 5033
color_exposure/plot_log_gamma.html: 5013
filters/plot_deconvolution.html: 4725
transform/plot_matching.html: 4513
color_exposure/plot_local_equalize.html: 4478
registration/plot_register_translation.html: 4240
edges/plot_convex_hull.html: 4206
filters/plot_nonlocal_means.html: 4178
segmentation/plot_morphsnakes.html: 4157
filters/plot_hysteresis.html: 3935
edges/plot_ridge_filter.html: 3914
filters/plot_denoise_wavelet.html: 3836
data/plot_specific.html: 3834
segmentation/plot_chan_vese.html: 3769
segmentation/plot_niblack_sauvola.html: 3711
numpy_operations/plot_structuring_elements.html: 3617
segmentation/plot_metrics.html: 3530
data/plot_general.html: 3431
filters/plot_unsharp_mask.html: 3407
color_exposure/plot_regional_maxima.html: 3317
segmentation/plot_trainable_segmentation.html: 3102
segmentation/plot_random_walker_segmentation.html: 3019
filters/plot_dog.html: 3014
features_detection/plot_holes_and_peaks.html: 3012
features_detection/plot_shape_index.html: 2977
color_exposure/plot_ihc_color_separation.html: 2933
registration/plot_register_rotation.html: 2924
filters/plot_rank_mean.html: 2910
features_detection/plot_orb.html: 2874
registration/plot_opticalflow.html: 2840
registration/plot_masked_register_translation.html: 2839
edges/plot_polygon.html: 2835
filters/plot_restoration.html: 2826
edges/plot_shapes.html: 2807
applications/plot_rank_filters.html: 2806
transform/plot_ransac.html: 2804
segmentation/plot_expand_labels.html: 2777
numpy_operations/plot_camera_numpy.html: 2735
applications/plot_human_mitosis.html: 2721
applications/plot_coins_segmentation.html: 2674
segmentation/plot_mask_slic.html: 2633
segmentation/plot_marked_watershed.html: 2620
filters/plot_inpaint.html: 2576
features_detection/plot_corner.html: 2541
filters/plot_phase_unwrap.html: 2463
applications/plot_image_comparison.html: 2368
filters/plot_tophat.html: 2298
segmentation/plot_ncut.html: 2247
segmentation/plot_rag_merge.html: 2218
segmentation/plot_rolling_ball.html: 2197
transform/plot_transform_types.html: 2187
color_exposure/plot_tinting_grayscale_images.html: 2140
numpy_operations/plot_view_as_blocks.html: 2117
color_exposure/plot_adapt_rgb.html: 2090
segmentation/plot_join_segmentations.html: 2062
transform/plot_fundamental_matrix.html: 2057
edges/plot_random_shapes.html: 1996
color_exposure/plot_adapt_hist_eq_3d.html: 1991
transform/plot_piecewise_affine.html: 1934
applications/plot_haar_extraction_selection_classification.html: 1808
segmentation/plot_hausdorff_distance.html: 1748
segmentation/plot_compact_watershed.html: 1715
applications/plot_face_detection.html: 1704
segmentation/plot_rag_boundary.html: 1660
features_detection/plot_daisy.html: 1563
filters/plot_window.html: 1528
transform/plot_pyramid.html: 1525
segmentation/plot_rag_mean_color.html: 1513
developers/plot_threshold_li.html: 1401
transform/plot_edge_modes.html: 1305
data/plot_3d.html: 1300
segmentation/plot_regionprops_table.html: 1264
features_detection/plot_windowed_histogram.html: 1222
transform/plot_swirl.html: 1150
segmentation/plot_extrema.html: 1143
segmentation/plot_rag_draw.html: 1086
developers/plot_max_tree.html: 1076
features_detection/plot_haar.html: 1028
features_detection/plot_brief.html: 1021
segmentation/plot_boundary_merge.html: 1019
filters/plot_attribute_operators.html: 952
features_detection/plot_multiblock_local_binary_pattern.html: 951
features_detection/plot_censure.html: 930
filters/plot_cycle_spinning.html: 912
transform/plot_geometric.html: 856
segmentation/plot_euler_number.html: 854
filters/plot_j_invariant_tutorial.html: 805
segmentation/plot_rag.html: 770
features_detection/plot_gabors_from_astronaut.html: 669
filters/plot_j_invariant.html: 635
segmentation/plot_perimeters.html: 484
applications/plot_3d_structure_tensor.html: 465
applications/plot_3d_interaction.html: 113
filters/plot_blur_effect.html: 38
```

</details>

**Other pages** (install, code of conduct, contributor guide, etc)
<details>
<summary>Other Pages Details</summary>

```
install.html: 104629
index.html: 56527
search.html: 29900
overview.html: 9653
glossary.html: 1726
genindex.html: 1613
release_notes.html: 913
license.html: 867
values.html: 783
contribute.html: 719
skips/index.html: 589
skips/1-governance.html: 318
skips/0-skip-process.html: 174
conduct/code_of_conduct.html: 133
skips/2-values.html: 81
core_developer.html: 77
gitwash/patching.html: 71
gitwash/index.html: 34
gitwash/git_install.html: 29
gitwash/following_latest.html: 16
gitwash/development_workflow.html: 12
gitwash/git_intro.html: 8
conduct/report_handling_manual.html: 8
gitwash/forking_hell.html: 7
gitwash/git_resources.html: 7
gitwash/set_up_fork.html: 5
gitwash/configure_git.html: 4
gitwash/git_development.html: 3
gitwash/maintainer_workflow.html: 3
```

</details>

**Comment by stefanv** [comment]
@leej3 Thank you for starting this effort. Our docs are now using the PyData Sphinx Theme.

**Pull request closed without merging**
