### PR TITLE
JupyterLite in documenation

### PR DESCRIPTION
**Pull request by DerThorsten**
## Description
This adds a jupyterlite shell to the documentation which can be tried out on the fly.

Locally this already works fine, maybe it will also work on the CI already.
 Atm I put the jupyterlite console at the very beginning of the documentation (probably should be in some subsection)

If you are interested in this I can polish this PR more!

A few thoughts:
 * we could also embed a "full" jupyterlite instead of just a shell (ie a thing with multiple cells)  (more infos here https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8)
 * we could reuse existing demo notebooks

try_me
code

### CODE REVIEW

**Comment by DerThorsten** [comment]
This might already work on the CI.

**Comment by lagru** [comment]
Thanks @DerThorsten! I'll try it out it the next few days. :)

**Comment by emmanuelle** [comment]
Thank you @DerThorsten ! I also need to read the PR in more details. Right now you can take a look at the built CI doc on  https://output.circle-artifacts.com/output/job/60034042-2f07-4163-96d7-57e0b56af094/artifacts/0/doc/build/html/index.html

Taking a look at the CI doc, it looks like the output is not displayed (see screenshot below), I guess this is not what is expected?

Screenshot from 2022-09-02 23-10-54

**Comment by mkcor** [comment]
Exciting! Thanks for your submission, @DerThorsten.

From the [Medium post](https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8) by @jtpio and @martinRenou:

> The NumPy project had already been using an interactive console on the [numpy.org](https://numpy.org/) documentation website.

I was curious of what happened with this interactive console, so here I am :slightly_smiling_face: 

> we could reuse existing demo notebooks

Oh, yes!

**Comment by DerThorsten** [comment]
> Thank you @DerThorsten ! I also need to read the PR in more details. Right now you can take a look at the built CI doc on https://output.circle-artifacts.com/output/job/60034042-2f07-4163-96d7-57e0b56af094/artifacts/0/doc/build/html/index.html

I can't load this at all from the circleci artifacts. The page is very slow and most downloads timeout so the repl does not event start this way.


> Taking a look at the CI doc, it looks like the output is not displayed (see screenshot below), I guess this is not what is expected?

This is not expected and I hope this is  just some issue when loading the page from the circleci artifacts

with my local build it looks like this:

skimage

**Comment by lagru** [comment]
Okay, I have several thoughts on this:

- I think there is value in providing a quick and low barrier way to explore and play around with scikit-image a little bit. But only if it does not significantly complicate our CI or maintenance burden. :wink: 
- From what I gathered during the conference, JupyterLite does not support downloading datasets via pooch because it's not allowed sockets? I think our gallery examples rely on that.
- I'm not that keen about adding this to our gallery as we already using MyBinder which has been low maintenance for scikit-image (correct me if I'm wrong).
- Emulating NumPy, I think a good place for this could be https://scikit-image.org rather than our Sphinx doc at https://scikit-image.org/docs/stable/.

Thinking about this, I'm really wondering if other projects already have statistics about user interaction with JupyterLite (e.g. NumPy's start page) and MyBinder.

**Comment by stefanv** [comment]
I think this is the kind of widget that works well on a project frontpage, like what NumPy does.

For our documentation, I suggest we work on using JupyterLite to make our gallery pages interactive, very much like we do with Binder.

**Comment by stefanv** [comment]
I'm going to close this in preference of future work done on Sphinx integrations with pyodide. See, e.g., https://blog.holoviz.org/panel_0.14.html#Sphinx-extension

Thank you for opening this investigation, @DerThorsten!

**Comment by lesteve** [comment]
FYI I have opened #6911 that uses sphinx-gallery JupyterLite integration to add a JupyterLite button to each example similarly to what was done in scikit-learn.

**Pull request closed without merging**
