### PR TITLE
Added chapter title formatting for numpy_images.rst

### PR DESCRIPTION
**Pull request by emmanuelle**
The layout of the "crash course on numpy images" chapter in http://scikit-image.org/docs/stable/user_guide.html, because the title of the chapter had the same formatting as its sections. I corrected this, so that section titles now appear nested below the title of the chapter.

### CODE REVIEW

**Comment by soupault** [comment]
@emmanuelle maybe it is worth also to refactor other `.rst`s in http://scikit-image.org/docs/stable/user_guide.html : I've discovered that many of them use inconsistent header formatting.
For example, https://raw.githubusercontent.com/scikit-image/scikit-image/master/doc/source/user_guide/getting_started.rst and https://raw.githubusercontent.com/scikit-image/scikit-image/master/doc/source/user_guide/data_types.rst.

**Comment by emmanuelle** [comment]
@soupault indeed the same formatting is not used in all files of the user guide, but I'm not sure we chose which convention should be used :-) -- maybe because it's not important for the way it's rendered. The important thing is to have a different formatting for the title than for the sections.

**Comment by soupault** [comment]
@emmanuelle Yes, I got it. :)
:+1: to merge this, in any case.

**Comment by sciunto** [comment]
Merged. Thanks @emmanuelle

**Pull request merged**
