### PR TITLE
Update Sphinx gallery

### PR DESCRIPTION
**Pull request by stefanv**
Updated from upstream; we should probably have a script to do this, or use submodules.

### CODE REVIEW

**Comment by soupault** [comment]
Does this fix https://github.com/scikit-image/scikit-image/issues/2410?

**Comment by sciunto** [comment]
I thought we said that we want to merge a released version.

**Comment by soupault** [comment]
@stefanv could you like to update the PR with v0.1.8? https://github.com/scikit-image/scikit-image/issues/2410#issuecomment-274520630

**Comment by jni** [comment]
@soupault, @sciunto did the Sphinx-gallery 0.1.8 update in #2474. I must admit I don't understand how the two PRs interact, but Travis is happy... =)

**Comment by sciunto** [comment]
This one should be closed, was partial.

**Pull request closed without merging**
