### PR TITLE
Remove pep8speaks config

### PR DESCRIPTION
**Pull request by jarrodmillman**
## Description

We will also need to disable pep8speaks access to the repo. Maybe here:
https://github.com/scikit-image/scikit-image/settings/installations

See #7171

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
...
```

### CODE REVIEW

**Review by mkcor — APPROVED** [review]
:sunglasses:

**Review by lagru — APPROVED** [review]
Less noise is :+1:

**Comment by lagru** [comment]
This PR is easily reverted and I don't anticipate that it's controversial. So I'll merge now. :)

**Comment by lagru** [comment]
I don't have permissions to remove the apps access to our repo. Perhaps this requires permissions on the org level.

**Comment by mkcor** [comment]
> I don't have permissions to remove the apps access to our repo. Perhaps this requires permissions on the org level.

The 'Configure' button is greyed out for me as well (for PEP8 Speaks, unlike for the other 4 GitHub apps).

**Pull request merged**
