### PR TITLE
Remove obsolete meson instructions

### PR DESCRIPTION
**Pull request by mkcor**
## Description

@soupault @jarrodmillman removing the `meson` files... as per https://github.com/scikit-image/scikit-image/pull/7160#issuecomment-1746058544?

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
...
```

### CODE REVIEW

**Comment by stefanv** [comment]
Only the MD file should go, the rest is needed for building.

**Comment by mkcor** [comment]
@stefanv oops! Re-added. Thanks.

**Review by lagru — APPROVED** [review]
Thanks for the cleanup.

**Comment by soupault** [comment]
Thank you @mkcor !

**Pull request merged**
