### PR TITLE
Simplify installation instructions

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by arve0** [comment]
> These instructions are insufficient.

"inappropriate", "too much" or "messy" is probably more descriptive.

**Comment by JDWarner** [comment]
The whole file needed an overhaul, @arve0. My changes were also insufficient.

**Comment by stefanv** [comment]
I'm a bit OCD when it comes to docs and simplicity, so please don't take it personally, and feel free to disagree with me at any time!  Also, I am *extremely* grateful for that PR, so I hope I didn't make you think otherwise.

**Comment by blink1073** [comment]
Sorry @stefanv, I merged #1545, not realizing this had not been merged.  You'll need a rebase.

**Comment by stefanv** [comment]
Done.

**Comment by JDWarner** [comment]
Nice overhaul of the installation instructions, @stefanv!

**Pull request merged**
