### PR TITLE
Improve documentation of bounding box

### PR DESCRIPTION
**Pull request by sdsingh**
## Description
Clarifies the format of the bounding box, in code. 

## References
Addresses issue: #1959

### CODE REVIEW

**Comment by jni** [comment]
Well, it looks like Sphinx isn't happy with this...

**Comment by jni** [comment]
Errr, maybe not related to this, master is also broken!
https://travis-ci.org/scikit-image/scikit-image/builds/119680755

Maybe Sphinx has been updated? =\

**Comment by sdsingh** [comment]
Sphinx has been updated, pushed a (hopeful) fix

**Comment by stefanv** [comment]
@sdsingh No need to close the PR.  You can push new changes to an existing branch, and the PR will be updated accordingly.

**Pull request closed without merging**
