### PR TITLE
Use lazy imports for matplotlib in skimage.io

### PR DESCRIPTION
**Pull request by samtygier**
## Description

Use lazy imports for matplotlib in skimage.io. This speeds up import for the common case of not using the matplotlib plugin and still gives a speed up when not all the matplotlib functionality is used. For a short script the speedup can be significant.

When using skimage.io the import of matplotlib takes a significant amount time, even in the case that it the matplotlib import is not used.

Using 
```
python -X importtime -m skimage.io 2> import_time_skimage_io.log
tuna import_time_skimage_io.log
```
Screenshot at 2022-09-28 15-33-11

Shows that 47% of the import time is importing matplotlib (~0.8 out of 1.6 seconds). (I have seen figures down to 37% depending on setup).

With some test scripts, run 10 times in a loop in bash

|Example|Before|After|
|---|---|---|
|import_skimg_io.py | 1.8082s | 0.9405s |
|imread_default.py | 4.9919s | 4.1473s |
|imread_mpl.py | 5.0551s | 4.6022s |

import_skimg_io.py
``` python
import skimage.io
```

imread_default.py
```python
import skimage.io
from skimage._shared.testing import fetch
for _ in range(100):
	img = skimage.io.imread(fetch("data/astronaut.png"))
print(img.shape)
```

imread_mpl.py
```python
import skimage.io
from skimage._shared.testing import fetch
for _ in range(100):
	img = skimage.io.imread(fetch("data/astronaut.png"), plugin="matplotlib")
print(img.shape)
```

Measurements on i5-8250U (restricted to 1GHz to avoid throttling), nvme SSD, on Fedora 36, python 3.10. 

Its not immediately clear how to make a benchmark that measures imports time, but I can look into it if required.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Review by lagru — COMMENTED** [review]
> With some test scripts, run 10 times in a loop in bash

Could you post those as well so I can reproduce?

> Its not immediately clear how to make a benchmark that measures imports time, but I can look into it if required.

See [Raw timing benchmarks](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#raw-timing-benchmarks).

**Comment by samtygier** [comment]
The times in the table are from doing
```time (for i in `seq 10`; do python import_skimg_io.py ; done)```
with each of the scripts.

I see there is already a benchmark for imports, so I'll add the module to the param list there ( https://github.com/scikit-image/scikit-image/blob/main/benchmarks/benchmark_import_time.py ).

**Comment by samtygier** [comment]
I have added `skimage.io` to the import time benchmark. I can see it in the output, but as far as I can understand asv I can't see a difference between my branch and main.

I have also tried converting to the timeraw method, which makes all the import tests faster (I assume because it skips starting a shell), but still I can't see a difference.

The timeraw method is cleaner and probably safer, so I could add a patch so switch the whole test to that. If it is not a problem that it changes existing times.

**Comment by lagru** [comment]
> The timeraw method is cleaner and probably safer, so I could add a patch so switch the whole test to that. If it is not a problem that it changes existing times.

I'd advocate that change as it's asv's recommended approach. :+1:

**Comment by lagru** [comment]
Hmm, the benchmark suite still doesn't seem to pick up a difference. Does it show locally for you @samtygier?

**Comment by samtygier** [comment]
No I've not seen a time difference for this patch with asv. Is it possible that asv already has matplotlib loaded into the interpreter? 

I do see the improvement when I actually run a script that imports `skimage.io`. I've see this on 2 computers and also in docker (to make sure I have clean environments). I can post the docker files if those are useful.

**Comment by samtygier** [comment]
I tried adding a timeraw test like this:

```python
    def timeraw_import_info(self):
        return """
        import sys
        with open("/tmp/timeraw_import_info", "w") as fh:
            for k,v in sys.modules.items():
                print(k,v, file=fh)
        """
```
In the output I see:
`mpl_toolkits <module 'mpl_toolkits' (<_frozen_importlib_external._NamespaceLoader object at 0x7f80d805feb0>)>`

**Comment by hmaarrfk** [comment]
When I was doing import time bechmarks, it is import that you do things like commands:

```
python -c "import XXXX"
```
within ASV, as in, start a new interpreter and whatnot.

**Comment by hmaarrfk** [comment]
to be honest, I am somewhat worried about you trying to help improve this module given that the loose consensus among scikit-image maintainers has been that `skimage.io` provides little improvement over `imageio`. Many of us would like to remove the module `skimage.io` as a whole, that said, it is quite hard.....

For reference if you use:
```
import skimage
import imageio.v3
```
in your code, you could get something more reasonable in terms of import times
image

https://github.com/imageio/imageio

It is not that I am trying to discourage you from contributing, but rather I do really understand your frustration. Using imageio gives you:

1. Faster import times today. (you don't have to wait for a new release of scikit-image)
2. Avoids churn here.
3. Ensures that you are using what some skimage maintainers think is best practice.

**Comment by samtygier** [comment]
> When I was doing import time bechmarks, it is import that you do things like commands

The docs suggest that `timeraw` should be good for imports. It also uses `subprocess.check_output` instead of `subprocess.run` so is more robust to errors.

> Many of us would like to remove the module skimage.io as a whole

Should there be a deprecation warning on import?

**Comment by hmaarrfk** [comment]
> Should there be a deprecation warning on import?

That's more of a discussion for 
https://github.com/scikit-image/scikit-image/issues/5036

**Comment by stefanv** [comment]
FWIW, I don't think we need benchmarks for changes as these.

Needs a rebase, then should be good to go.

**Comment by lagru** [comment]
@samtygier may I resolve the merge conflict for you or do you want to do it?

**Comment by samtygier** [comment]
> @samtygier may I resolve the merge conflict for you or do you want to do it?

Yes, please do.

**Comment by lagru** [comment]
Done. I opted to keep the original way of measuring import time to keep the other benchmarks consistent. Though I tend to agree that the `timeraw_import` way would be the better approach.

**Review by stefanv — APPROVED** [review]

**Comment by stefanv** [comment]
Since @lagru merged main and made changes, I see that as an approval. Merging.

**Pull request merged**
