### PR TITLE
Added explanation in the example of `segmentation/plot_label.py` to make the background transparent

### PR DESCRIPTION
**Pull request by lisabug**
## Description
Regarding issue #4091, I updated the example in gallery. 

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by lisabug** [comment]
failed in CI by the part installing imread 🤔

**Comment by sciunto** [comment]
Thanks for the patch @lisabug The failure seems to be unrelated to this PR. 

I think another important place to fix is around: https://github.com/scikit-image/scikit-image/blob/7a85970ed21d96366ddcb3136ad546c907436277/skimage/color/colorlabel.py#L91
where we must specify better the meaning of this parameter.

**Comment by lisabug** [comment]
@sciunto thanks for pointing out it. updated the docstring and added more explanation in the example.

**Comment by sciunto** [comment]
Great! I merge this one. Thanks.

**Pull request merged**
