### PR TITLE
WIP: Implement contour finding for binary images

### PR DESCRIPTION
**Pull request by evanlimanto**
Same functionality as in [openCV](http://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?.highlight=findcontours#findcontours).

### CODE REVIEW

**Comment by soupault** [comment]
@evanlimanto could you compare this with the current implementation (http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.find_contours)?

**Comment by soupault** [comment]
@evanlimanto any updates?

**Comment by emmanuelle** [comment]
Indeed we already have our own ``find_contour``, which implements the marching cubes algorithm. The algorithm of this PR is the one used in openCV. Do we need two algorithms for contour detection?

**Comment by stefanv** [comment]
This algorithm is useful because it detects *hierarchies* of contours in a binary image.  This PR may not be complete enough to use as is, but it is functionality we should eventually implement.

**Comment by stefanv** [comment]
Example usage: https://naturalhistorymuseum.github.io/inselect/pages/gallery.html

Code: https://github.com/NaturalHistoryMuseum/inselect/blob/7047bb1d03dd212b43e6563822849fce45e0c477/inselect/lib/segment.py#L468

**Pull request closed without merging**
