### PR TITLE
Use checkout action version 4

### PR DESCRIPTION
**Pull request by rettinghaus**
## Description

Tiny PR to update the used GH action.

### CODE REVIEW

**Review by soupault — APPROVED** [review]
Changelog is here - https://github.com/actions/checkout/releases .

**Comment by jarrodmillman** [comment]
Would you mind updating this everywhere:
```
.github/workflows/build_docs.yml:19:        uses: actions/checkout@v3
.github/workflows/tests.yml:76:        uses: actions/checkout@v3
.github/workflows/tests.yml:155:        uses: actions/checkout@v3
.github/workflows/wheels_recipe.yml:26:      - uses: actions/checkout@v3
.github/workflows/wheels_recipe.yml:60:      - uses: actions/checkout@v3
.github/workflows/wheels_recipe.yml:102:      - uses: actions/checkout@v3
.github/workflows/wheels_recipe.yml:179:      - uses: actions/checkout@v3
.github/workflows/benchmarks.yml:26:      - uses: actions/checkout@v3
.github/workflows/test_nightlies_on_main.yml:34:      - uses: actions/checkout@v3
.github/workflows/wheel_tests_and_release.yml:32:      - uses: actions/checkout@v3
````

**Comment by rettinghaus** [comment]
Done.

**Comment by rettinghaus** [comment]
Thanks for spotting!

**Review by jarrodmillman — APPROVED** [review]

**Review by stefanv — APPROVED** [review]

**Pull request merged**
