### PR TITLE
Remove temporary constraint <2.28 for imageio

### PR DESCRIPTION
**Pull request by lagru**
## Description

Should have been addressed by now in https://github.com/scikit-image/scikit-image/pull/6764. 

@jarrodmillman this is probably something we want in the release?! 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by lagru** [comment]
Feel free to ignore (we can always release a patch) or push to this branch (in case I'm not reacting fast enough about a red CI).

**Review by stefanv — APPROVED** [review]

**Comment by lagru** [comment]
Wait I'm really confused by my local test results despite https://github.com/scikit-image/scikit-image/pull/6934 not being merged. I'd have expected my local tests to fail a lot. Instead there is a new doctest failure that seems independent of imageio's version and the failures addressed in https://github.com/scikit-image/scikit-image/pull/6934 don't happen. :confused: 

I'll wait for the CI (maybe my setup is weird). Let's not make this block the release and remove it from the milestone for now. :see_no_evil:

**Comment by stefanv** [comment]
The issues with ImageIO were addressed via a slightly different mechanism in https://github.com/scikit-image/scikit-image/pull/6942 (I think you were away that day, so I couldn't coordinate with you, sorry for any confusion!).

**Review by jarrodmillman — APPROVED** [review]

**Comment by lagru** [comment]
> The issues with ImageIO were addressed via a slightly different mechanism in https://github.com/scikit-image/scikit-image/pull/6942 (I think you were away that day, so I couldn't coordinate with you, sorry for any confusion!).

Ah, that's reassuring. I was confused why this suddenly stopped being a problem. Thanks.

**Pull request merged**
