### PR TITLE
Fixing gallery examples.

### PR DESCRIPTION
**Pull request by alexandrejaguar**
Some gallery examples would work better with matplotlib 2.0.

## References
Related to #2486.

### CODE REVIEW

**Comment by sciunto** [comment]
@alexandrejaguar Could you post the figures please?

**Comment by alexandrejaguar** [comment]
@sciunto sure thing.

* Entropy:

entropy_fig1

entropy_fig2

* Regional maxima:

maxima_fig1

maxima_fig2


* Marching cubes:

marchingcubes_fig1

**Comment by soupault** [comment]
@alexandrejaguar thanks! `marching cubes` and `regional maxima` examples look great!

>what about using magma in the 3rd example? :) Please check this fix.

I actually like `viridis` more for the `entropy` plot. Is much easier to perceive the difference in that case.

**Comment by sciunto** [comment]
I'm +1 for viridis.

**Comment by alexandrejaguar** [comment]
@soupault @sciunto your call. The `viridis` version follows:

entropy_fig1_v2

**Pull request merged**
