### PR TITLE
Attempting to build documentation on circle-ci

### LINKED ISSUE #2269: Build the doc with CircleCI?
At the moment, when a change is made to the documentation, the persons who are reviewing the PR have to (or should :-)) fetch the corresponding branch and build the doc on their machine. We could maybe use CircleCI and configure it to build the doc, so that it would be possible to see the new doc online, without having to build it locally.

What do you think?

### PR DESCRIPTION
**Pull request by NelleV**
This is a tests to build on circle.yml

Fixes #2269

### CODE REVIEW

**Comment by stefanv** [comment]
Circle-CI built!

**Comment by stefanv** [comment]
@NelleV We now have our other build systems back to green; do you have time to finish this PR?

**Comment by stefanv** [comment]
I am pausing CircleCI for the time being, since it's turning all of our tests red.

**Comment by NelleV** [comment]
@stefanv I'll have more time as soon as I submit my review paper. Ping me next week?

**Comment by soupault** [comment]
Any updates on this PR?

**Comment by sciunto** [comment]
No update since the last release. Ok to postpone one more time? (Cc @emmanuelle ).

**Comment by emmanuelle** [comment]
@skimage/core should we try to revive this PR? Having doc artifacts on CircleCI is very convenient.

**Comment by emmanuelle** [comment]
I propose to close this one in favor of #4881. This PR does fancier things (I think it's based on the scikit-learn workflow) but #4881 works with a simple config file.

**Comment by NelleV** [comment]
Agreed!

**Comment by NelleV** [comment]
I closed without waiting :grimacing:

**Comment by emmanuelle** [comment]
wooshhhh... I love the sound of 3-year-old PRs when they get closed/merged :-).

**Pull request closed without merging**
