### PR TITLE
Do not use lena in test_brief.py

### LINKED ISSUE #1859: Tests in skimage/feature/tests/test_brief.py use 'lena'
To remove the lena image (#1855) some tests have to be rewritten to use a different image.
The following tests in ``skimage/feature/tests/test_brief.py`` use lena

* test_normal_mode
* test_uniform_mode

### PR DESCRIPTION
**Pull request by OrkoHunter**
Fix #1859 

I've used the grayscale coins image instead of lena.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@soupault Excited about `coveralls.io` result for this one ! (Did it stop running?)

**Comment by stefanv** [comment]
Another test that wasn't particularly good to begin with.  We have some room for future improvement in this department!

**Comment by soupault** [comment]
Seems like we are accumulating coverage decrease in imaginary units. Not good, not good... :)

**Comment by stefanv** [comment]
:)

**Comment by OrkoHunter** [comment]
@soupault Haha
@stefanv Thanks for merging those PRs ! :)

**Comment by stefanv** [comment]
Thank you for making them!
​

**Pull request merged**
