### PR TITLE
Let biomed example load image data with Pooch.

### PR DESCRIPTION
**Pull request by mkcor**
## Description

In this PR, we are making use of a recent (v0.17.1) feature, namely on-the-fly download of data with `pooch`.
It follows from the fact that we are [now](https://gitlab.com/scikit-image/data/-/merge_requests/2) hosting a copy of the CC0-licensed image at: https://gitlab.com/scikit-image/data

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
> We have a gitlab page as well?

Yes, that's a new thing based on the fact that gitlab is more generous with bandwidth than github. Might be premature optimisation but we were seeing so many sporadic CI failures with pooch downloads that I wondered whether we were hitting bandwidth limits. I do also like diversifying our tools base...

**Comment by jni** [comment]
Note that there is nothing compulsory about using gitlab vs another github.com/scikit-image/data repo vs really any other page on the web. Pooch only cares about stable URLs, which gitlab should be as good as github at providing.

**Comment by emmanuelle** [comment]
Thank you @mkcor ! Marianne was telling me that we lack documentation about using pooch (both for devs and users), which is true. For a future PR :-)... Merging this one now.

**Comment by hmaarrfk** [comment]
My goal is to help alleviate the installation guide first, then move on to the pooch guide.

I think we are doing good strides in the install guide

**Pull request merged**
