### PR TITLE
Fix matplotlib set_*lim API deprecations

### PR DESCRIPTION
**Pull request by sciunto**
## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](https://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This actually happened in matplotlib?

**Comment by sciunto** [comment]
Before, the API was repetitive, now it sounds stupid (IMO). :(

**Comment by stefanv** [comment]
Perhaps the most natural calling convention then becomes `set_*lim([None, L])`

**Comment by stefanv** [comment]
@soupault Was my suggestion not a good one? :)

**Comment by soupault** [comment]
@stefanv sorry, I didn't catch that you were suggesting to change the PR. Personally, I'm fine with the current implementation and don't really find `right`, `top`, etc stupid. But if you insist to revert the PR and switch to unnamed arguments, I would mind.

**Comment by stefanv** [comment]
On Wed, 28 Nov 2018 13:11:10 -0800, Egor Panfilov wrote:
> @stefanv sorry, I didn't catch that you were suggesting to change the
> PR. Personally, I'm fine with the current implementation and don't
> really find `right`, `top`, etc stupid. But if you insist to revert
> the PR and switch to unnamed arguments, I would mind.

No worries, I think this patch is fine.  The new API in Matplotlib is
frustrating, though.

**Pull request merged**
