### PR TITLE
mini-galleries for classes as well

### PR DESCRIPTION
**Pull request by emmanuelle**
I noticed that only functions had their mini-galleries, not classes. This PR corrects this.

### CODE REVIEW

**Comment by emmanuelle** [comment]
This one should be pretty easy to review I hope :-).

**Comment by jni** [comment]
@emmanuelle I assume you've tested this locally? I must admit I find *all* of that sphinx code impenetrable...

**Comment by emmanuelle** [comment]
Yes, I've tested locally. This code adds mini-galleries to the API reference of classes as well (before they were just generated for functions, I adapted the code used for functions to classes). See the screenshot below from my local build
image

**Comment by emmanuelle** [comment]
This correspond to this feature in sphinx-gallery: https://sphinx-gallery.github.io/stable/configuration.html#references-to-examples

**Comment by jni** [comment]
@emmanuelle :heart_eyes: 

Yes, this was a massive improvement in our API doc, great to bring it to classes also!

@scikit-image/core anyone up for pushing the green button? =)

**Pull request merged**
