### PR TITLE
Region boundary based RAGs

### PR DESCRIPTION
**Pull request by vighneshbirodkar**
figure_1

This implements a new kind of RAG which me and Juan were discussing sometime back.

Before I can implement any segmentation algorithms, I wanted some feedback,

The current code, though ND, is slow. The RAG construction takes around `6.5s`. I'm open to suggestions on how I can improve it, particularly if I can cythonize any part to speed it up. As a fallback, we can also consider a fast cython function for the 2D special case.

Also, please find the line profile here
https://gist.github.com/vighneshbirodkar/fd2547a8e169a7a7c35f

### CODE REVIEW

**Comment by vighneshbirodkar** [comment]
@jni Please have a look.

**Comment by jni** [comment]
@vighneshbirodkar very cool!!!

An efficient nd neighbours function is something I've been looking to implement for a very long time. (You can probably find some examples on the mailing list!) Other than your current connectivity definition being wrong [1], I think we can compute something in Cython to speed up the whole thing.

I'll try to find some time later today to try to come up with something. Have a look at my [old implementation in gala](https://github.com/janelia-flyem/gala/blob/master/gala/morpho.py#L546). It's not what we want, as it's for ravelled indices and won't work in discontiguous arrays, but it's got the right ideas in there.

[1] `sqrt(3)` ≈ 1.7 < 2, so by your definition a connectivity of 2 in 3D would in fact implement a connectivity of 3

**Comment by vighneshbirodkar** [comment]
Currently,  what's the fastest way to iterate over an ND array in Cython ? 

Also, will Cython utility functions that directly access the underlying C array be useful? Or is there something in Cython which already does that.

**Comment by jni** [comment]
@vighneshbirodkar you are in uncharted territory, at least by me. =) My first guess would be numpy.nditer. (which you showed me! =)

**Comment by vighneshbirodkar** [comment]
I was wondering if there was a way to do that without involving the python
overhead ?
@stefanv @bewithaman

**Comment by jni** [comment]
@vighneshbirodkar I may be way off, but I thought "cimport numpy as cnp" avoided Python overhead.

**Comment by vighneshbirodkar** [comment]
@jni but we are calling `np.nditer` and not `cnp.nditer`

**Comment by jni** [comment]
@vighneshbirodkar so, *can we* call cnp.nditer in a Cython function instead? I'm not sure, but I would try that next. (Sorry, didn't have time to try my hand at this today in the end...)

**Comment by vighneshbirodkar** [comment]
..... Long Pause......
......Drum Roll......
Unfortunately no, we can only use what is defined in the module [here](https://github.com/cython/cython/tree/master/Cython/Includes/numpy)

**Comment by stefanv** [comment]
@vighneshbirodkar No, that's not accurate.  We can call any part of the C API we like from Cython.  We may just have to write our own header.

I looked at the line profile.  What is the purpose of line 375?

**Comment by stefanv** [comment]
This page may be relevant: http://docs.scipy.org/doc/numpy-dev/reference/arrays.nditer.html

**Comment by vighneshbirodkar** [comment]
@stefanv , 375 converts to a tuple before indexing, otherwise, we will end up indexing with arrays.

**Comment by vighneshbirodkar** [comment]
@stefanv the `np.nditer` function still has a Python overhead. Is there a way to iterate over an ND array (an array whose dimensions are not known ahead of time), as fast as you would iterate over a memory-view for instance.

**Comment by stefanv** [comment]
The C-API it is, then.

**Comment by vighneshbirodkar** [comment]
@stefanv 
I was

**Comment by stefanv** [comment]
@vighneshbirodkar I'm not sure--I'd have to hear more about what you have in mind.

Another question: is accessing the Python iterator object prohibitively expensive, given that it can return chunks of the array?

**Comment by vighneshbirodkar** [comment]
@stefanv The problem in this PR is the use of `np.ndindex`. During each iteration I need one index, and I access 2 arrays based on that simultaneously. So my idea was to write cython routines to generate indices of N dimensions and then access arrays based on those indices.

**Comment by stefanv** [comment]
I understand.  And a person cannot simply initialize two array iterators?

**Comment by vighneshbirodkar** [comment]
@stefanv ,  He can, but that still does not solve the problem of efficiently accessing the neighborhood of a point. Could you look at this code and suggest how you would change it ?

Meanwhile, I have been trying this out
https://github.com/vighneshbirodkar/cy_iter

Once the neighborhood iterator (http://docs.scipy.org/doc/numpy/reference/c-api.array.html#neighborhood-iterator) is added, the module would be complete.

@jni, that would also solve your problem of accessing ND arrays and their ND neighborhood

**Comment by stefanv** [comment]
@vighneshbirodkar I am confused--we can already access the entire NumPy C API, which does allow us to use the neighborhood iterator?

**Comment by vighneshbirodkar** [comment]
@stefanv Yes, we can, but i think it would be good if they were exposed through Cython. Properly iterating over an array required some tricky pointer manipulation. Even though I have some experience in C, thr Cython syntax was tricky, specially getting the imports right.

All I plan to do is wrap the C code in Cython. If you think that is useful enough I can maybe place it in the `util` module. Otherwise,  I'll use it in isolation.

**Comment by JDWarner** [comment]
If it's faster - or even slightly slower but easier to use, making other functions more likely to use it and appreciate the gains - I say drop it in `util`.

**Comment by vighneshbirodkar** [comment]
@stefanv @jni Thoughts ?

**Comment by jni** [comment]
@vighneshbirodkar we all suffer from [this](https://xkcd.com/386/), so my silence can often be safely interpreted as agreement with the last thing that was said. =)

So, to reiterate, I agree with @JDWarner, this seems useful enough to go in `util`! (Which literally means "useful" in Spanish, come to think of it! =D)

**Comment by vighneshbirodkar** [comment]
@jni Nicely Put. :)

**Comment by vighneshbirodkar** [comment]
I'll create a new PR for that soon

**Comment by tacaswell** [comment]
@jni But that assumes you have had time to come back to _this_ place someone might be wrong.  The internet in a big place; rounds can take a while.

**Comment by jni** [comment]
@tacaswell hence my use of "often". =)

**Comment by vighneshbirodkar** [comment]
@jni I will resume this PR as soon as my exams get over this week. I was just wondering, if we could modify `find_boundaries` to give us an extra array which told us which 2 regions caused a boundary and each pixel, we could have a much faster implementation.

**Comment by jni** [comment]
@vighneshbirodkar no worries, thanks!

Regarding your `find_boundaries` comment, that assumes that you can generate that extra array in less time than you could here. I don't think that's the case. =)

**Comment by vighneshbirodkar** [comment]
@jni Just so that we are on the same page let's say
```
boundary[x] == True
```
then I am assuming we can get 2 arrays `B1` and `B2` such that
```
B1[x] # id of the first region
B2[x] # id of the second region
```
Can't we do some dilation/erosion sorcery to get these 2 arrays quickly ?

**Comment by jni** [comment]
@vighneshbirodkar possibly. Now that you mention it, this could work:

```python
eroded = erosion(labels)  # this is B1
dilated = dilation(labels)  # this is B2
boundaries = eroded != dilated
```

I didn't realise it could be so simple! Unless I'm missing something... This could even be used to build the graph directly!

```python
small_labels = eroded[boundaries]
large_labels = dilated[boundaries]
data = sobel[boundaries]
coo = sparse.coo_matrix((data, (small_labels, large_labels)))
g = coo.tocsr()
```

`g` will contain the total boundaries between each (i, j). Now if you just repeat with:

```python
# create a repeating array of [1., 1., ...] using stride tricks to save memory
from numpy.lib.stride_tricks import as_strided
counts = np.ones((1,), dtype=float)
counts = as_strided(counts, shape=small_labels.shape, strides=(0,))
# use COO matrix to count the ones at each location
count_g = sparse.coo_matrix((counts, (small_labels, large_labels))).tocsr()
g.data /= count_g.data
```

You will have the mean boundary graph. =O

Well, that was an exciting comment... =D

**Comment by vighneshbirodkar** [comment]
@jni WOW ! That might actually work. And if we can also write a helper method to give us the boundary between any 2 given regions, we should also be able to the hierarchical merging on this graph. Do you have spare time to submit the PR?  if not I can submit one later this week.

Also, lend me your `Numpy Wizardry` book for a week :smile:

**Comment by vighneshbirodkar** [comment]
@jni I am working on this now.

**Comment by vighneshbirodkar** [comment]
@jni I compared the example output before and after, there seems to be a change.
## Before
figure_2

## After
figure_1

Is this change significant ? Given that the 2 algorithms are completely different.

**Comment by jni** [comment]
@vighneshbirodkar I haven't looked at your code yet but the change does look significant to me. The edges on the top left and top right of the cup should have a high mean boundary probability, just like those around the rest of the cup, right? Are the superpixels the same? Can you post the raw picture and the superpixel map as well?

Looking at your code now, but I would look at those edges and why they are different.

**Comment by jni** [comment]
@vighneshbirodkar come to think of it, you've also changed the footprint, right??? That might be the reason. If your boundaries are too thin, you might now be capturing more irrelevant pixels.

**Comment by jni** [comment]
You might try `connectivity=1` to get a thinner boundary. I would favor that as the default.

Also, I know you're just playing for now, but before we get this merged you should keep both the total sum and the pixel count on the nodes so that you can merge regions.

**Comment by vighneshbirodkar** [comment]
@jni, where have I changed footprint ?

**Comment by jni** [comment]
@vighneshbirodkar I don't remember your old code but didn't you use your previous asymmetric footprint? ie

[[0, 0, 0],
 [0, 1, 1],
 [0, 1, 1]]

whereas now you are using np.ones((3, 3))

**Comment by vighneshbirodkar** [comment]
@jni See [old code](https://github.com/vighneshbirodkar/scikit-image/blob/4904111b5ec358a7543f5fa0463522b0ad6539b9/skimage/future/graph/rag.py)
Connectivity was being computed in a different way, but I think the neighbors were he same as they are now

**Comment by jni** [comment]
@vighneshbirodkar errr, no it wasn't:

```python
In [5]: nbr = list(np.ndindex(*[2] * 2))

In [6]: nbr
Out[6]: [(0, 0), (0, 1), (1, 0), (1, 1)]
```
That only looks forward, not back.

**Comment by jni** [comment]
You would suffer from the same bug that you would not find the edge (2, 3) in:

[[1, 2],
 [3, 4]]

**Comment by vighneshbirodkar** [comment]
@jni I think I have found the problem, although I have no idea how to solve this
http://cs.nyu.edu/~vnb222/share/boundary.ipynb

**Comment by jni** [comment]
@vighneshbirodkar sorry for the delay in answering, on holiday in Tasmania. =)

I don't really understand what you're trying to show with your example... That pixels that are part of more than one edge automatically get assigned to the one between the smallest and biggest label? Or...? And I don't see how this could be having a big effect on the results, since they are a small minority of pixels?

**Comment by vighneshbirodkar** [comment]
@jni I was trying to show that instead of detecting one pixel at the boundary, the code thinks the boundary is 2 pixels wide.

**Comment by jni** [comment]
@vighneshbirodkar this is inevitable and correct. imho finding edges should be rotation/mirror invariant. Why should the edge pixel be the one to the top-left instead of the bottom-right one? See the "mode" kwarg in [`find_boundaries`](http://scikit-image.org/docs/dev/api/skimage.segmentation.html#find-boundaries), in docstring and code, for more details.

**Comment by jni** [comment]
@vighneshbirodkar also, incidentally, this method doesn't have single-pixel precision. In the example I gave, [[1, 2], [3, 4]], using connectivity=2, *all* pixels will be part of the boundary of (1, 4), and that will be the only edge.

This is a pathological example, but is definitely worth keeping in mind (and documenting). The consequence is that it would only work when we expect the *majority* of boundary to lie on lines, rather than single points. I think it's a reasonable assumption.

**Comment by vighneshbirodkar** [comment]
@jni Then I don't know why there is the difference, even after I corrected the old function

**Comment by jni** [comment]
@vighneshbirodkar I've just today refined the formula for finding edges. See [here](https://github.com/jni/gala/blob/learn-zmq/gala/agglo2.py#L40). It might improve things here. Can you give it a shot?

**Comment by vighneshbirodkar** [comment]
@jni, where are we going to get the data from, i.e, in your last code you did `sobel[boundaries]`

**Comment by jni** [comment]
@vighneshbirodkar `sobel` is just an example. Any boundary detection filter would work. You did normalise by the boundary length, right?

In my linked application I only needed the adjacency relationships, not the boundary values, so I didn't compute the data. But the principle is the same. You just need to get all of the boundary values in the right order, ie:

```python
pixel_boundary_map = filters.sobel(image)
data = np.concatenate((pixel_boundary_map[boundaries0], pixel_boundary_map[boundaries1]))
```

**Comment by vighneshbirodkar** [comment]
@jni Here
figure_new2

**Comment by jni** [comment]
@vighneshbirodkar that's a bit better already! =) My advice would be to look at those specific superpixel pairs that are showing low values to try to determine why. Are their borders particularly small? Are they windy and missing the sobel edge? How different is the value (both the mean and the sum) between the manual iteration method and the new method?

**Comment by jni** [comment]
@vighneshbirodkar I just noticed that there's only two levels of intensity on the edge cmap. Maybe if you add more levels we'll notice that the difference is actually quite small? Thresholding often results in bad artifacts!

**Comment by vighneshbirodkar** [comment]
@jni Here are the comparisons with an actual colormap, I also drew on a completely black image so that differences are noticeable. Except a few edges, the plots are identical I think.
### Old
figure_old
### New
figure_new

I was wrongly under the impression that `ListedColormap` would interpolate in the range given, I think we should change our examples to not use it.

**Comment by jni** [comment]
@vighneshbirodkar you're after `LinearSegmentedColormap`. =) Having said that, I think a named colormap is a better idea!

The resulting plots look great though!!! Very exciting indeed! =D Wanna complete the PR? Might even make it into 0.12! =)

**Comment by vighneshbirodkar** [comment]
I can only work on this by the weekend.

**Comment by jni** [comment]
Haha it is funny that you think 0.12 might be out before the weekend. =P

**Comment by jni** [comment]
@vighneshbirodkar but don't you have the code on your branch without having pushed? If you push to here I *might* be able to contribute before then.

**Comment by vighneshbirodkar** [comment]
@jni have a look
figure_new

**Comment by vighneshbirodkar** [comment]
Updated plot with `jet`
figure_new

@jni, You have any preference for colormap ?

**Comment by JDWarner** [comment]
Anything other than `jet`! My vote would be for `viridis`, but any of the new matplotlib colormaps (e.g., `magma`) would do.

**Comment by vighneshbirodkar** [comment]
@JDWarner the newer colormaps only come with `matplotlib-1.5`

**Comment by JDWarner** [comment]
We ship viridis as of 0.12, for backwards compatibility:
`from skimage.util.colormap import viridis`

**Comment by vighneshbirodkar** [comment]
`viridis` does not look that good IMO
figure_new

**Comment by JDWarner** [comment]
If the nodes were a mid-gray tone, it might look a lot better. Seems that viridis isn't so much the issue but rather the nodes being disproportionately bright.

**Comment by vighneshbirodkar** [comment]
How about this ? If that's ok I'll change it
figure_new

**Comment by JDWarner** [comment]
I like that one, personally, though tastes may differ ;)

**Comment by jni** [comment]
@vighneshbirodkar oops, sorry for the mistakes!

Looks like typing `type(my_generator)` gives different output from different Python versions. Maybe just get rid of that line in the doctest?

**Comment by vighneshbirodkar** [comment]
@jni You think this is ready for merging ?

**Comment by jni** [comment]
@vighneshbirodkar yes, yes I do! =) I'm really happy with the way this turned out! =D

**Pull request merged**
