### PR TITLE
Remove skimage.test as it was never used.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Until  PR #3152 was merged, this function didn't actually work. Many of the build scripts just called `pytest` directly. The only one that I found that didn't call `pytest` directly was the`conda-forge` recipe,
which will be fixed when [thisPR](https://github.com/conda-forge/scikit-image-feedstock/pull/25)
is merged.

Previous comments from the omnibus PR #3147

@jni [mentionned](https://github.com/scikit-image/scikit-image/pull/3147#discussion_r193919183)
> I understand the sentiment, but I think we don't want to do this. The reason this exists is that we used to use nosetests and were bitten when it reached end-of-life. skimage.test allows us to keep the same testing syntax even if we decide to switch frameworks later on.

@jni [said](https://github.com/scikit-image/scikit-image/pull/3147#discussion_r193921324):
> also, "achieved". =P
> 
> I'm neither +1 or -1 on this btw. Running individual tests is more natural if we normalise with pytest. Just wanted to flag it since others (@soupault) have in the past preferred strongly hiding pytest (using skimage.testing.raises instead of pytest.raises, for example).

@hmaarrfk [replied]:
> @jni, I understand that the idea was to have the testing localized, but after having going through a few of the other build procedures, it seems that skimage.test was never used in the first in place.
>
> When I tried skimage.test myself a few months back, I thought I wasn't using the function correctly, but a recent PR showed me that it wasn't just me.
>
> I'm glad to go back to the old functionality, but I feel like the ship has sailed on that, even before my PR. I didn't have to change any of the other tests when I removed this function.

## Checklist
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
Thanks for the summary @hmaarrfk!

I believe @NelleV, @stefanv, and @soupault were the main architects of `skimage._shared.testing`, so I will let them comment. I myself am happy to go full pytest.

**Comment by hmaarrfk** [comment]
As an extra remark:

I understand that `skimage._shared.testing` served a purpose to ensure that future testing backends wouldn't require 100+ changes in the future.

This testing function does not serve that purpose though.
It only wraps one function, and the code for wrapping 1 line of code is quite literally 43 lines long.

The documentation either reads:
> To test `scikit-image` please run:
```python
import skimage; skimge.test()
```

or

> To test scikit-image, please run
```python
import pytest; pytest.main(['--pyargs', 'skimage'])
```

For developers, this adds yet an other layer of "just for scikit-image" that they must learn in order to jump on board.

**Comment by emmanuelle** [comment]
I'm also in favor of removing this code.

**Comment by emmanuelle** [comment]
Merging, thanks.

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.14.x

**Pull request merged**
