### PR TITLE
BF: Initialize firstbg to the numels so if no bg value found, second loop is not executed

### LINKED ISSUE #2398: skimage FTBFS on multiple architectures testsuite failures.
## Description
When building skimage on Debian autobuilders the test suite fails on several architectures.
In the [bug log](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840589#35) it is explained that when checking with gdb it is just by chance that the failure does not happen with amd64.  The problematic commit is d29831882daef9b7d7691becc3669349d642b547.  The variable firstbg is only initialized conditionally in the first loop. It depends on the array values and the and background value. Still it is used as the starting pointer on the second loop, even if uninitialized. At best the pointer point to the wrong address, at worst it generates an out of bound access causing the segmentation fault.

## Way to reproduce
See [bug log](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840589#35)

- [ ] Debian Linux 
- [ ] 0.12.3

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #2398 

If tests pass -- will cherry pick into debian branch patches and upload BF to Debian unless a fresh release is coming?

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks @yarikoptic. Since #2395 has been merged, would you mind rebasing on master so that we can check whether tests pass?

**Comment by sciunto** [comment]
@emmanuelle It seems it doesn't: https://github.com/scikit-image/scikit-image/issues/2398#issuecomment-266560766

**Comment by emmanuelle** [comment]
@matejak @stefanv could you please check what the initial value of ``firstbg`` should be?

**Comment by matejak** [comment]
Please take a look at PR #2381, it also fixes the issue + there are some more goodies in it.

**Comment by soupault** [comment]
Fixed via https://github.com/scikit-image/scikit-image/pull/2399 ( :thinking: ).

**Comment by matejak** [comment]
Is #2381 going to be merged as well?

**Comment by soupault** [comment]
@matejak I hope so.

**Pull request closed without merging**
