### PR TITLE
Added flip function

### PR DESCRIPTION
**Pull request by swiftdiaries**
## Description
Flip function ISSUE:2563

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new features are mentioned in `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
I appreciate you taking the initiative to contribute, but I don't see much point in re-implementing functionality that is already in numpy.  I think the numpy `flip` function has a preferable signature with `axis` being used to select the axis to flip (good for general n-dimensional data and not just 2D images).  Perhaps it may be worth just exposing numpy's `flip` function in the namespace of `skimage.transforms`?  At a minimum we could mention its existence in the transforms documentation so that users are aware of it.

Our current numpy version requirement is 1.11 and `flip` was only added in 1.12, but the function is simple if we wanted to just keep a local copy temporarily until our numpy dependency requirement reaches 1.12.  In numpy it is defined here:
https://github.com/numpy/numpy/blob/8ea619a8717d2c82d42e4662b2266121faba58e4/numpy/lib/function_base.py#L141

**Comment by swiftdiaries** [comment]
Yes, I believe that would be a better approach (using axis) to flip for
n-dimensional images. Exposing numpy's flip would be a better option than
basically re-implementing the feature using the same function with limited
functionality.

As the issue mentioned, I thought this would be convenient for newbie users
to get started off with. Maybe we could mention the availability of a more
advanced version of the flip function for now and just add the numpy
version once our requirement is updated.

**Comment by grlee77** [comment]
>>  and just add the numpy version once our requirement is updated.

not sure if there is a misunderstanding, but to be clear, if we were to copy the numpy `flip` routine into scikit-image it would work from older numpy versions as well.  The question is whether that is worth doing.

As far as documentation, I don't really see any section of the tutorial covering routines from `skimage.transform`.  If there were such a tutorial, I would say we could mention `flip` there.  As is, I think the transform routines are mainly documented in the autogenerated API docs (and via the examples).

**Comment by JDWarner** [comment]
@grlee77 is entirely correct - our general approach is not to reimplement functions which are provided by packages we depend upon.  There are exceptions to this rule, like the Gaussian filter which is a light wrapper around SciPy.NDImage.

This may not be ideal for discoverability in all cases, however, we are a toolkit which builds upon the shoulders of the core ecosystem.  The maintenance burden associated with even small wrappers also needs to be taken into consideration.

**Comment by stefanv** [comment]
I concur with the discussion above; I appreciate the effort, but this is out of scope for scikit-image.

**Pull request closed without merging**
