### PR TITLE
update setup.cfg field from license_file to license_files

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This PR fixes a warning about use of deprecated "license_file" that was seen on CI. This field has been replaced by `license_files` so that multiple files can potentially be listed.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by grlee77** [comment]
An upstream example of use with multiple separate LICENSE_* files is [in matplotlib](https://github.com/matplotlib/matplotlib/blob/4a5d09cba5f4a20e14553cebd8f70c1f34d20d35/setup.cfg#L5)

**Comment by grlee77** [comment]
Circle CI failure here should be resolved by #6528

**Comment by lagru** [comment]
For reference: [`license_file` was deprecated in setuptools v56.](https://setuptools.pypa.io/en/latest/history.html#id420)

**Comment by lagru** [comment]
I tested locally that the LICENSE.txt is included in both the sdist archive and wheel. This option seems only to affect the inclusion in the wheel? The file was included in the sdist archive regardless of the `license_files` option.

@grlee77 is it possible to look at the sdist archive and wheels for a commit? Do we include them as artifacts in our CI?

**Review by lagru — APPROVED** [review]

**Comment by grlee77** [comment]
> I tested locally that the LICENSE.txt is included in both the sdist archive and wheel. This option seems only to affect the inclusion in the wheel?

Thanks for double-checking. I think it should have been working the same both before and after this change? It is just that using `license_file` singular is deprecated so will likely quit working in the future.

> @grlee77 is it possible to look at the sdist archive and wheels for a commit? Do we include them as artifacts in our CI?

I don't think you can get the artifact for that currently, but we could perhaps store it if needed. Right now the wheels created during the "deploy" step after a version tag is uploaded do get stored as artifacts, but I don't think the source archive is included with that. We also test from the sdist in at least one test case, but haven't stored it as an artifact.

**Review by mkcor — APPROVED** [review]

**Pull request merged**
