### PR TITLE
Return empty array if hough_line_peaks detects nothing

### PR DESCRIPTION
**Pull request by seheatwole**
## Description
…w errors
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
Closes https://github.com/scikit-image/scikit-image/issues/2804

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by soupault** [comment]
@seheatwole good! Please, add also a test with the case from your issue to https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/tests/test_hough_transform.py . This way we'll be sure that this edge case will be handled properly in the future.

**Comment by seheatwole** [comment]
Sorry, I was swamped at work and couldn't get to this.  You are right, (h,
np.array([]), np.array([])) is more correct.

**Comment by thrdr** [comment]
I think there's a bug in this code.

The bug shows up in the case where  `_prominent_peaks()` detects peaks and the all peaks have angle 0. 

Those are valid results but the `a.any()` test evaluates to false for zero values. So the returned angle and distance values with get replaced with empty arrays.

**Comment by rfezzani** [comment]
Hello @thrdr and thank you for your interset in `skimage`. Can you open a new issue reporting this bug to track it? It would be great If you can come with a failing sample code demonstrating this bug :wink:

**Comment by pdinnen** [comment]
I've opened issue #6187 @rfezzani.

**Pull request merged**
