### PR TITLE
Only index tif and gif files in collection

### LINKED ISSUE #1447: ImageCollection loads images prematurely
``ImageCollection('*.jpg')`` loads all JPG images, even when conserve_memory is set to True.  What used to be an instantaneous operation is now very slow.

/cc @blink1073

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1447.

### CODE REVIEW

**Comment by blink1073** [comment]
@stefanv, all done!

**Comment by stefanv** [comment]
@blink1073 Is the indexing fast for both tif and gif files?

**Comment by blink1073** [comment]
Well, it could be if we play fast and loose.   Right now we read in the whole array when we index to make sure it is a valid file: https://github.com/scikit-image/scikit-image/blob/master/skimage/io/collection.py#L207.

**Comment by blink1073** [comment]
Well, that is for the gif files; tif files are indexed in the header, so that should be plenty fast.

**Comment by stefanv** [comment]
I think we should only index images of which we can inspect the headers, otherwise the slowdown will occur for those other types of files too.

**Comment by blink1073** [comment]
How does that look?  I don't have a directory with 1000 jpgs in it, but opening an image and seeking to 0 takes ~0.5ms on my machine, so theoretically 500ms for you.

**Comment by stefanv** [comment]
Excellent!  Thank you @blink1073

**Pull request merged**
