### PR TITLE
Merge pull request #3227 from hmaarrfk/travis_cleanup_pip (solve np.lookfor for v0.14.x)

### PR DESCRIPTION
**Pull request by sciunto**
Travis-CI: cleanup pip commands

## Description

See #3543

### CODE REVIEW

**Comment by sciunto** [comment]
ping @hmaarrfk Can you check this please? I had a hard time this git...

**Comment by sciunto** [comment]
The cython version looks correct now. But we are facing the same issues as in master for which I have no idea of the origin... We are in a warfare.

**Comment by sciunto** [comment]
warefare must be fixed by #3557

**Comment by hmaarrfk** [comment]
I think maybe you can rebase this now?

**Comment by sciunto** [comment]
oooppsss, i didn't want to push directly to the repo... :(  hopefully, it is ok.  My bad...

**Comment by jni** [comment]
Just looked at the commits, looks like you merged without review, which isn't a huge deal. =)

**Pull request closed without merging**
