### PR TITLE
Force imageio reader to return NumPy arrays

### PR DESCRIPTION
**Pull request by stefanv**
In newer versions of `imageio`, they now return an ndarray subclass with a `.meta` attribute.  We moved away from this kind of representation many years ago (yes, we used to have an Image object!), because these subclassed arrays do not survive computation through a typical pipeline.

### CODE REVIEW

**Comment by jni** [comment]
@stefanv btw do you know what *we* changed between 0.14 and 0.15 that meant that we used to return an array even with new imageio versions?

**Comment by jni** [comment]
@scikit-image/core This is probably a critical bug fix (see report in [zulip](https://skimage.zulipchat.com/#narrow/stream/175598-general/topic/type.20changes.20in.200.2E15.2E0/near/163042890), so please review ASAP!

**Comment by stefanv** [comment]
Can you think of a simpler wrapper that preserves the docstring?  I'd be happy to switch.

**Comment by hmaarrfk** [comment]
Basically, using wraps on a function definition is simpler.

**Comment by jni** [comment]
@stefanv, @hmaarrfk provided the full alternative implementation above. I'm inclined to agree with him that it's simpler and better *unless* we envision adding lots of plugins *and* that many will need the decorator. I hope we don't get there!

**Comment by stefanv** [comment]
That's fine with me; especially once you fix the capitalized R in return ;)  Go ahead and push to my branch.

**Comment by hmaarrfk** [comment]
Thanks for the input everybody. Merging.

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.15.x

**Comment by soupault** [comment]
@meeseeksdev backport to v0.15.x

**Comment by soupault** [comment]
@Carreau Asking for backporting twice is, probably, stupid, but you might be interested to take a look at the logs :).

**Comment by Carreau** [comment]
Sorry missed the notification. 
Feel free to email me next time.

**Pull request merged**
