### PR TITLE
Remove build_versions.py.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Functionality duplication of `pip --list`

This makes adding and removing dependencies a lot easier since we don't have to worry about updating this script.
`pip --list` is also much more complete.

Part of: Issue #3172

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by stefanv** [comment]
Except that build_versions limits the output only to packages of interest, which is useful:

```
$ ./tools/build_versions.py        
     numpy   1.15.0.dev0+c8c9f1e
     scipy   1.1.0
matplotlib   2.2.2
 PIL.Image   1.1.7
  networkx   2.1
    Cython   0.27.3
```

**Comment by hmaarrfk** [comment]
Ok.

**Comment by soupault** [comment]
What about making `build_versions.py` less hard-coded? I'd suggest to scan all the requirements files for the package names, and use those.

**Comment by hmaarrfk** [comment]
@soupault that would take more time. probably a good enhancement issue to create.

**Pull request closed without merging**
