### PR TITLE
Updated centroid to use coords - works in 3d

### PR DESCRIPTION
**Pull request by jmetz**
## Description
 Really quick pull request to add 3d `centroid` prop (#1489) by replacing dependency on `moments` with `coords`.

### CODE REVIEW

**Comment by ahojnnes** [comment]
What is the speed difference of the two approaches?

Thanks.

**Comment by jmetz** [comment]
@ahojnnes - I just did a really basic benchmark (using average of 3 calls - just using `time`, not `timeit` though) and I got: 
New version:
```
2d version...
  - generated 71838 regionprops
  - e.g. centroid 1: (0.0, 4.0)
2d time : 0.2234658400217692 [mean of 3]
3d version...
  - generated 88812 regionprops
  - e.g. centroid 1: (499.55023357940456, 499.4258386270655, 49.5034841007975)
3d time : 0.9921420415242513 [mean of 3]
```
Old version: 
```
2d version...
  - generated 72105 regionprops
  - e.g. centroid 1: (1.8571428571428572, 3.1428571428571428)
2d time : 0.22224958737691244 [mean of 3]
3d version...
  - generated 88240 regionprops
  (NO 3d centroid!)
3d time : 0.9933149814605713 [mean of 3]
```

i.e. no discernible time difference...

**Comment by jmetz** [comment]
I used random 2d & 3d images of dimensions `1000,1000` and `1000,1000,100` respectively, generated masks by thresholding at `0.8`, ran `label` and then timed the time taken to generate `regionprops` 3 times - so not a perfect timing as this times the whole `regionprops` call, but at least it's  clear that the `centroid` changing to using the `mean` of the `coords` is not causing a noticeable slowdown.

**Comment by ahojnnes** [comment]
Thanks Jeremy, LGTM!

**Comment by ahojnnes** [comment]
Actually, would you mind adding a test for 3D data?

**Comment by stefanv** [comment]
:+1: after addition of simple 3D test

**Comment by jmetz** [comment]
Added simple test - used `np.mean( SAMPLE_3D.nonzero(), axis=1)` to generate the test value. 

Admittedly this is a little circular given that this is almost exactly what `regionprops` does (now), but I think in this case it's probably ok - right?

**Comment by ahojnnes** [comment]
LGTM, thanks!

**Comment by jni** [comment]
Hi @ahojnnes @jmetz 

It seems to me that @jmetz measured the time taken by the regionprops call itself — which doesn't actually compute anything. It's only when you try to access the centroid property that anything gets called. ie don't measure:
```python
x = measure.regionprops(im)
```
but rather
```python
cs = [p.centroid for p in measure.regionprops(im)]
```

**Comment by ahojnnes** [comment]
@jni Thanks for following up. I guess, only @jmetz can clarify?

**Comment by jmetz** [comment]
@jni - You're partly right - I only used one call to `regionprops` in my benchmark. Below I compared 0, 1 and N calls to `regionprops` (where N is the number of regions). 
To summarize, the full list comprehension over the `regionprops.centroid` is : 

old 2d version: 4.416301170984904 s
new Nd version: 4.614382187525432 s

so about a 5% slowdown, though the variance is pretty high

**Old version**
```
2d version...no calls to centroid
  - generated 71964 regionprops
  - e.g. centroid 1: (0.0, 2.0)
2d time : 0.22329243024190268 [mean of 3]
2d version + 1 centroid call...
  - generated 71964 regionprops
  - e.g. centroid 1: (0.0, 2.0)
2d time : 0.1925503412882487 [mean of 3]
2d version + centroid calls...
  - generated 71964 regionprops
  - e.g. centroid 1: (0.0, 2.0)
2d time : 4.416301170984904 [mean of 3]
3d version... no calls to centroid
  - generated 89191 regionprops
  (NO 3d centroid!)
3d time : 1.1492459774017334 [mean of 3]
3d version + 1 centroid call...
  - generated 89191 regionprops
  (NO 3d centroid!)
3d time : 1.0912513732910156 [mean of 3]
3d version + centroid calls...
  - generated 89191 regionprops
  (NO 3d centroid!)
3d time : 1.094856897989909 [mean of 3]
```

**New version**
```
2d version...no calls to centroid
  - generated 72192 regionprops
  - e.g. centroid 1: (0.0, 1.0)
2d time : 0.2125371297200521 [mean of 3]
2d version + 1 centroid call...
  - generated 72192 regionprops
  - e.g. centroid 1: (0.0, 1.0)
2d time : 0.19180560111999512 [mean of 3]
2d version + centroid calls...
  - generated 72192 regionprops
  - e.g. centroid 1: (0.0, 1.0)
2d time : 4.614382187525432 [mean of 3]
3d version... no calls to centroid
  - generated 88453 regionprops
  - e.g. centroid 1: (499.49161639218704, 499.51328563370396, 49.504228479675184)
3d time : 1.046361764272054 [mean of 3]
3d version + 1 centroid call...
  - generated 88453 regionprops
  - e.g. centroid 1: (499.49161639218704, 499.51328563370396, 49.504228479675184)
3d time : 2.413388808568319 [mean of 3]
3d version + centroid calls...
  - generated 88453 regionprops
  - e.g. centroid 1: (499.49161639218704, 499.51328563370396, 49.504228479675184)
3d time : 8.428961435953775 [mean of 3]
```

**Comment by jni** [comment]
This makes more sense and is totally acceptable as a performance tradeoff to gain nD support! Thanks for following up @jmetz! =D

**Pull request merged**
