### PR TITLE
Update contributor's guide: all PRs must get two +1's by core team before merge

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jni** [comment]
LOL wtf Coveralls

**Comment by JDWarner** [comment]
My only concern here is that there are significant periods of time when many core devs are busy, and it seems like only one is operating. Needing to ping other devs, who are busy at the moment, isn't necessarily ideal. This could significantly slow down development and our ability to address bug fixes in a timely manner.

**Comment by jni** [comment]
@JDWarner Too bad this policy wasn't in place before the PR was merged! =P

**Comment by vighneshbirodkar** [comment]
@jni , beat me to it

**Comment by jni** [comment]
@JDWarner More seriously, I think having two :+1:s is not as onerous as you think. I think there's often a second core dev available for a quick check. In practice I think there will be one primary and one secondary reviewer, and the job of the secondary is not that onerous.

@vighneshbirodkar LOL!

**Comment by stefanv** [comment]
Good motivation to grow the core team!

**Comment by JDWarner** [comment]
True!

**Comment by soupault** [comment]
Well, as a new member of the team I'd like to express my opinion on the point. I could participate in larger number of PRs, but many of the project's conventions in terms of project vision and architecture aren't clear/documented.
How do you feel about better discussing/documenting project's policy and roadmap? As a quite good example I can refer to https://github.com/matplotlib/matplotlib/wiki and https://github.com/matplotlib/matplotlib/milestones .
Thanks!

**Comment by stefanv** [comment]
Thank you for sharing your perspective, Panfilov.  We can talk about the
two issues separately:

W.r.t. process, triaging tickets, setting milestones, etc.--the machanics
of managing software development--I agree that we can do better.  Your help
with labeling, e.g., is much appreciated.  I would like to learn what we
can do to make you a more effective contributor, so please share.

W.r.t. roadmaps and future vision: there are several ways of running a
project such as this one.  One approach is to have a grand vision, outline
it, work towards that vision, and deliver a masterpiece.  But since the
beginning we have chosen to take a much more organic approach to things:
initially, scratching our own itches, and later filling in gaps for our
users.  We do not have a large, consistent workforce: everyone here
volunteers their time, and I'd prefer for them to work as much as possible
on *their* ideals for the project.

Perhaps two points to consider: 1. I do talk to our users as often as I
can, and get feedback on how to improve the project.  This information
eventually makes its way into development.  I want to do better in this
regard by, e.g., linking a survey from the front-page; it's on my radar.
2. I have thought about ways in which we can give others in the
organization more opportunities for focused leadership.  Some of these
thoughts made their way into a governance proposal:
https://github.com/stefanv/skimage-org/blob/governance_proposal/governance.md
But these ideas are yet undebated, and since there are many ways to skin a
cat (see e.g.
https://github.com/numpy/numpy/blob/master/doc/source/dev/governance/governance.rst),
we have quite a bit of thinking/talking to do on the topic.

**Comment by soupault** [comment]
@stefanv I see, thanks very much for clarification and governance draft!
Really, a lot of things are to be discussed. Let's continue in more suitable place.

**Pull request merged**
