### PR TITLE
[MRG] Add deprecation path to skimage.transform.integrate API change

### PR DESCRIPTION
**Pull request by jni**
Addresses comments added by @ahojnnes to #953 after I merged.

### CODE REVIEW

**Comment by ahojnnes** [comment]
Great, thanks. LGTM.

**Comment by jni** [comment]
@ahojnnes I got carried away and made a couple of extra enhancements. =)

**Comment by jni** [comment]
This should be ready now, after a few fixes.

**Comment by stefanv** [comment]
I like it when you get carried away, Juan.

**Pull request merged**
