### PR TITLE
Remove legacy Travis-CI scripts and update contributor documentation accordingly

### PR DESCRIPTION
**Pull request by grlee77**
## Description

There were quite a few Travis scripts and mentions of Travis in the contributor documentation. This PR removes these. If we ever need any of this again in the future we can just retrieve it from the history.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by soupault — APPROVED** [review]
Thank you @grlee77 , the change looks good!

On a tangent, could you, please, point me to the PR[s] where GitHub Workflow is introduced? Seems that I have missed lots of changes to the CI...

**Comment by grlee77** [comment]
> On a tangent, could you, please, point me to the PR[s] where GitHub Workflow is introduced? Seems that I have missed lots of changes to the CI...

Emma ported the tests to GitHub Actions in late 2020 when TravisCI started restricting credits to a level that it became no longer feasible as a free option for our CI:
https://github.com/scikit-image/scikit-image/pull/5074

Juan got the wheel building set up using `cibuildwheel` around the same time:
https://github.com/scikit-image/scikit-image/pull/5080

**Review by mkcor — APPROVED** [review]
I seized the opportunity to improve the writing a little bit (but I broke the 79 char limit in some suggestions).

**Comment by mkcor** [comment]
@grlee77 are you okay with the minor edits I suggested? If so, I can take of including them and I'll merge right away.

**Comment by grlee77** [comment]
Yes, those all look good. Thanks!

**Pull request merged**
