### PR TITLE
Add microaneurysms() to gallery

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Add the image to our gallery http://scikit-image.org/docs/dev/auto_examples/data/plot_scientific.html#sphx-glr-auto-examples-data-plot-scientific-py

### CODE REVIEW

**Comment by sciunto** [comment]
@ThomasWalter Would you mind reviewing this please?

**Comment by soupault** [comment]
@sciunto could you, please, elaborate on the purpose of adding this image?

**Comment by sciunto** [comment]
all images must be shown in the gallery.

**Comment by soupault** [comment]
Oops, sorry, my bad, I thought you're adding new image. 🤦‍♂️

**Comment by ThomasWalter** [comment]
Sorry, I was too late for the review ... 👍

**Comment by stefanv** [comment]
Note, this image still does not have a license description.

**Pull request merged**
