### PR TITLE
FIX: Point Windows batch file at source subdir.

### PR DESCRIPTION
**Pull request by JDWarner**
Simple fix to address #1707.

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, the Makefile also runs three other targets for 'html', should we add those?

**Comment by JDWarner** [comment]
Seems reasonable, but I can't robustly test on Windows at the moment so I may have to defer that to a separate PR.

**Comment by blink1073** [comment]
Yeah, we should build the docs on Appveyor as well.

**Comment by blink1073** [comment]
Cheers!

**Pull request merged**
