### PR TITLE
Move from CITATION.bib to CITATION.cff

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by lagru** [comment]
Could you give some context here? Why .cff over .bib?

**Comment by stefanv** [comment]
Compare the citations boxes on https://github.com/scikit-image/scikit-learn and https://github.com/scikit-learn/scikit-learn.

**Review by hmaarrfk — APPROVED** [review]

**Comment by stefanv** [comment]
I should note that I don't know whether this is going to work until we merge it :) But I'll fix it if it breaks anything.

**Comment by stefanv** [comment]
Let's see.

**Comment by stefanv** [comment]
Looks like it's working!

image

**Pull request merged**
