### PR TITLE
Fix ORB test

### PR DESCRIPTION
**Pull request by stefanv**
In a previous PR, the scales were incorrectly copy-pasted.

### CODE REVIEW

**Comment by stefanv** [comment]
Once this is done, rebuild https://github.com/scikit-image/scikit-image/pull/1937

@scikit-image/core please review for 0.12.

**Comment by jni** [comment]
@stefanv, what am I looking at? how did the previous PR's tests pass?

**Comment by stefanv** [comment]
@jni You know how I have been ranting on and on on the mailing list about this for three weeks now?  *This* is the issue.

a) Our test suite had a bug that made a lot of tests pass *even though they were broken*
b) The PR in #1937 fixes that, but then breaks the test suite
c) Because of (a) a change by a new contributor slipped through where expected output was not updated.  This PR fixes that, thereby allowing us to fix the tests via (b).

**Comment by stefanv** [comment]
Of course, you really should first merge #1937 before this one, otherwise we'd never know if it is correct :D

**Comment by stefanv** [comment]
But maybe I broke something in #1937.  This is fun :)

**Comment by jni** [comment]
@stefanv fascinating indeed! I'll go ahead and merge this in the interest of expediency, despite the blatant violation of house rules. =P

**Comment by jni** [comment]
@stefanv I guess now you can rebase #1937 on this to test the fix?

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/1935 .

**Comment by stefanv** [comment]
Juan, you can just retrigger the build.

**Comment by jni** [comment]
@stefanv how so? iirc Travis tests the git tip, not whatever would result from a merge?

**Comment by stefanv** [comment]
No, it merges first.

**Comment by jni** [comment]
@stefanv fascinating indeed! can you point to docs on this???

**Comment by stefanv** [comment]
@jni Yes, I learnt that while deploying Drone!  See, e.g., https://travis-ci.org/scikit-image/scikit-image/jobs/114171890#L117

**Comment by jni** [comment]
@stefanv :+1:!!!

**Pull request merged**
