### PR TITLE
Prefer importing build_py and sdist from setuptools

### LINKED ISSUE #6006: installation issues with setuptools 58.5.x
## Description

I observed some failures on CI in a recent PR that appear to be related to use of setuptools >= 58.5.0. Example: https://github.com/scikit-image/scikit-image/runs/4104921276?check_suite_focus=true

I was able to reproduce the issue locally with 58.5.0, but it does not occur for 58.4.0. A temporary workaround would be to pin setuptools <58.5 on CI.

## Way to reproduce

build from source with setuptools >= 58.5

### PR DESCRIPTION
**Pull request by grlee77**
## Description

closes #6006 

This PR updates some imports to use setuptools own versions rather than the ones from distutils. This is needed for compatibility with recent setuptools (>58.5.0) which made this breaking change: https://github.com/pypa/setuptools/commit/2e66eb7147ae1e8a799b2276c7340f48f63a7220

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
Upstream issue: https://github.com/pypa/setuptools/issues/2849

**Comment by grlee77** [comment]
This may end up being resolved upstream in which case we can just disallow 58.5.0 and 58.5.1. We may still want to make this change, though?

**Comment by abravalheri** [comment]
> This may end up being resolved upstream in which case we can just disallow 58.5.0 and 58.5.1. We may still want to make this change, though?

The support for commands inheriting directly from `distutils` is considered deprecated by `setuptools` (and `distutils` itself will be removed from Python as per [PEP 632](https://www.python.org/dev/peps/pep-0632/)), so I think this is a positive change :)

**Comment by hmaarrfk** [comment]
do we need the try statement? i feel like with distutils being deprecated we should move away from it completely.

**Comment by grlee77** [comment]
Not sure. I hadn't checked if these are present in our oldest supported setuptools.

**Review by rfezzani — APPROVED** [review]
Thank you @grlee77

**Comment by grlee77** [comment]
> Do we need the try statement? i feel like with distutils being deprecated we should move away from it completely.

It works without the try/except for setuptools 0.45, so I have removed it. I'm not sure about how to best avoid importing the CompileError or SetupError classes from `distutils`. As far as I could tell those are not in the public API of setuptools (they are under `setuptools._distutils.errors`).

**Comment by abravalheri** [comment]
> I'm not sure about how to best avoid importing the CompileError or SetupError classes from `distutils`. As far as I could tell those are not in the public API of setuptools (they are under `setuptools._distutils.errors`).

Maybe the best is to open an issue to setuptools asking for suggestions. They might think the best is to expose these in the public API.

**Comment by grlee77** [comment]
> Maybe the best is to open an issue to setuptools asking for suggestions? They might think the best is to expose these in the public API.

Just found this issue that seems to cover it already: https://github.com/pypa/setuptools/issues/2698

**Comment by abravalheri** [comment]
Ok, it should be a matter of PR then. I am sure the folks in setuptools would find it reasonable, or at least provide a clear alternate path.

**Comment by grlee77** [comment]
Agreed. I will merge this as is today once the CI completes.

**Comment by abravalheri** [comment]
@grlee77, there you go https://github.com/pypa/setuptools/pull/2858.

It should be available soon in a release 😄

**Pull request merged**
