### PR TITLE
[WIP] Make dtype consistent in filters.rank fonctions

### LINKED ISSUE #1010: Increase coverage of skimage.filters.rank.*
This module has insufficient test coverage. Also, the tests should be restructured.

### LINKED ISSUE #3577: rank filter maximum incorrect doc of output dtype
## Description

The documentation of `skimage.filters.rank.maximum` says that the returned array has the same dtype as the input:

> Returns: | out : 2-D array (same dtype as input image)

However this is not the case for `bool`.

## Way to reproduce
```python
import numpy as np
from skimage.filters.rank import maximum

arr = np.random.randint(2, size=(10, 10)).astype(bool)
print(arr.dtype)
result = maximum((arr), selem=np.ones((3, 3)))
print(result.dtype)
```

Output:
> bool
> uint8

Tested on skimage `0.14.1`.

Related to #466, #1244, #1010

### PR DESCRIPTION
**Pull request by Henley13**
## Description
Boolean inputs return uint8 output with `filters.rank.maximum` or `filters.rank.mean`for example. We want to keep the input and output dtypes identical.

## Checklist
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Test for boolean inputs
- [ ] Test for `_handle_input` in filters/rank/generic.py
- [x] Be sure to (re)cast the output properly (after the cython computation ?)

## References
Closes  #3577
Closes #1010

## For reviewers
- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by soupault** [comment]
@Henley13 It would be nice also to have a test covering the modified piece of code (see the snippet in #3577 for inspiration :slightly_smiling_face:).

**Comment by Henley13** [comment]
> > file_to_check.py:48:-1357: W605 invalid escape sequence '-'

Does someone can find the typo in the code ?

**Comment by clementkng** [comment]
Hi @Henley13, I'm interested in trying to find the typo and help close the PR, but I'm just curious to see what you tried to clean the code style? Currently, I tried to pull your branch and rebase on master, but I have quite a few new test failures to wander through before I can start looking for any typos.

**Comment by sciunto** [comment]
I'm closing this as it is superseeded by #3981

**Pull request closed without merging**
