### PR TITLE
Update _canny.py

### PR DESCRIPTION
**Pull request by dallakyan**
Updated URL for William Green's Canny tutorial.

## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks!

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.14.x

**Comment by soupault** [comment]
@meeseeksdev backport to v0.14.x

**Comment by hmaarrfk** [comment]
@soupault thanks! I was trying it out since @stefanv had let me know that the bot was working on allowing people without commit privileges to send requests.
https://github.com/MeeseeksBox/MeeseeksDev/issues/26#issuecomment-406071790

I guess it is still in beta!

**Comment by soupault** [comment]
@hmaarrfk hmm... That's suspicious. Could you double check on a different PR?

**Pull request merged**
