### PR TITLE
Unify skeletonize and skeletonize 3D APIs

### PR DESCRIPTION
**Pull request by jni**
## Description

It's easy to detect whether an image is 2D or 3D, so we might as well offer a single API for both algorithms.

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
@stefanv

> should we aim to use the same algorithm for 2D & ND, or is there an advantage to Zhang for 2D?

I'm not sure. They give significantly different results at the edges of skeletons, see:

https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html

Certainly it would be a major change with deprecation cycles etc. I'd rather punt on this.

Latest commit *should* fix the test failure... :crossed_fingers:

**Comment by jni** [comment]
Ok *now* it should be fixed. Boolean logic is hard. =P

**Comment by jni** [comment]
Gaah, doc build failing again:

https://travis-ci.org/scikit-image/scikit-image/jobs/532589015#L4193-L4195

```
Warning, treated as error:
/home/travis/venv/lib/python3.7/site-packages/skimage/transform/_geometric.py:docstring of skimage.transform.FundamentalMatrixTransform:30:duplicate citation R573, other instance in /home/travis/build/scikit-image/scikit-image/doc/source/api/skimage.util.rst
Makefile:53: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/travis/build/scikit-image/scikit-image/doc'
Makefile:26: recipe for target 'html' failed
make: *** [html] Error 2
```

I'm going to delete the cache and try again, but other suggestions welcome. Either way, this does not appear to be a part of this PR...

**Comment by stefanv** [comment]
On Tue, 14 May 2019 17:39:44 -0700, Juan Nunez-Iglesias wrote:
> Certainly it would be a major change with deprecation cycles etc. I'd rather punt on this.

👍

**Comment by jni** [comment]
Deleting the cache worked! :tada:

**Pull request merged**
