### PR TITLE
Do not use lena in test_hog.py

### PR DESCRIPTION
**Pull request by OrkoHunter**
Address #1861 

As pointed by @ivoflipse, for `test_histogram_of_oriented_gradients_output_correctness` inside `test_hog.py`, we can use a different image for the test. I have used the astronaut image.

Description of the files added :

 * `astronaut_GRAY.npy` : This file was created by reading the `astronaut.png` with `as_grey=True` and then saving it with `numpy.save`
 * `astronaut_GRAY_hog.npy` : Saved after using `skimage.feature.hog()` on the grayscale astronaut image.

### CODE REVIEW

**Comment by JDWarner** [comment]
Instead of adding a grayscale version of the Astronaut, let's load it dynamically for this test from the data directory and apply skimage.color.rgb2gray. This will help keep the repository size down.

You will need to amend this commit; removing and re-committing will still add the file to the repository.

**Comment by OrkoHunter** [comment]
That sounds a better idea. Though, we'll have to keep one file for the correct_output, right? I made the changes.

**Comment by JDWarner** [comment]
Yes, we do need the reference. Just not the grayscale conversion.

**Comment by JDWarner** [comment]
I restarted the two failed builds, which seemed unrelated.

**Comment by OrkoHunter** [comment]
Coveralls seems to have hung up.

**Comment by OrkoHunter** [comment]
@JDWarner Ping.

**Comment by JDWarner** [comment]
Looks great - don't know what the issue is with Coveralls. I feel confident merging this.

**Comment by JDWarner** [comment]
Thanks, @OrkoHunter!

**Pull request merged**
