### PR TITLE
Fixes in novice module

### PR DESCRIPTION
**Pull request by david1koeller**
… for restore functionality.

### CODE REVIEW

**Comment by brianhelba** [comment]
Tests are failing.

Also, this should be split into separate commits for each distinct feature.

**Comment by david1koeller** [comment]
Pushed a new version to address @brianhelba comments.

**Comment by david1koeller** [comment]
Fixed tests.

**Comment by brianhelba** [comment]
LGTM.

AppVeyor build is passing. Travis building seems to be very backed up, so it may take a long time to complete.

**Comment by brianhelba** [comment]
@stefanv Ready for your review.

**Comment by stefanv** [comment]
Thanks very much @david1koeller and @brianhelba!

**Pull request merged**
