### PR TITLE
Bugfix separate stains log10

### LINKED ISSUE #2995: colorconv.separate_stains should use np.log10() instead of np.log()?
This method is used for stain deconvolution. It implements the method defined in this paper: http://www.math-info.univ-paris5.fr/~lomn/Data/2017/Color/Quantification_of_histochemical_staining.pdf
which is the original paper on color deconvolution. The algorithm is defined on page 6 of the paper:

ODC = -log10(IC/I0,C) = A*cC . 

Shouldn't line 1130: 
stains = np.dot(np.reshape(-np.log(rgb), (-1, 3)), conv_matrix)

really be:
stains = np.dot(np.reshape(-np.log10(rgb), (-1, 3)), conv_matrix)
?

Right now it uses ln instead of log10.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes #2995

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks @hmaarrfk , merging.

**Comment by hmaarrfk** [comment]
@scikit-image/core backport?

Though this one is a difference in the in/out functionality. So....

**Comment by stefanv** [comment]
This may be an unexpected change for a point version, so let's skip for now.

**Comment by hmaarrfk** [comment]
Agreed. I just wanted to flag a few backports before too many PRs got pulled in.

**Comment by stefanv** [comment]
Much appreciated!  I've backported most of the others.

**Pull request merged**
