### PR TITLE
Rename denoise nl means

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by emmanuelle** [comment]
This PR looks good to me. The ``copy_func`` utility function is nice. I was thinking that this function should be mentioned in release notes, but do we have a file to prepare notes for the next release?

**Comment by emmanuelle** [comment]
Also, github mentions some conflicts of the branch, but I don't know where they could come from...

**Comment by stefanv** [comment]
I thought of `copy_func` as a utility only, so I didn't add that to release notes.  I'll rebase the branch.

**Comment by stefanv** [comment]
Oh, but we do have release notes: `doc/release/release_dev.txt`.

**Comment by emmanuelle** [comment]
:+1: for merging, waiting for a second advice

**Comment by ahojnnes** [comment]
LGTM.

**Comment by emmanuelle** [comment]
Merged.

**Pull request merged**
