### PR TITLE
Add the ability to always warn for a given warning

### PR DESCRIPTION
**Pull request by blink1073**
Also, always warn for low_contrast io.

### CODE REVIEW

**Comment by stefanv** [comment]
Looks good--needs a test.

**Comment by blink1073** [comment]
This is good to go.  @stefanv I think we need to fix our "error" threshold in coveralls.

**Comment by blink1073** [comment]
Ping @stefanv, this is ready for merging.

**Comment by blink1073** [comment]
Closing as stale.

**Pull request closed without merging**
