### PR TITLE
Fix missing peaks in hough_line_peaks.

### PR DESCRIPTION
**Pull request by hohlraum**
Address Issue #1420.

### CODE REVIEW

**Comment by JDWarner** [comment]
I just restarted the Travis-CI build. The errors appeared to be due to Sphinx problems, which should now be resolved on master.

**Comment by JDWarner** [comment]
...and it passes! Are you happy with the state of this PR, @hohlraum?

**Comment by hohlraum** [comment]
No, not happy yet. There are several related problems and the PR in its current form fixes only a few of them. I'll work on it now.

**Comment by hohlraum** [comment]
I've hit a bit of a wall and would appreciate some input. The attached figure illustrates my thinking. It has four lines. The question is how to instruct ```hough_line_peak``` to interpret those lines. There are a few different options:

1) interpret each line separately. An ordered list of peaks then would return (3,2,4,1).

2) Interpret lines 1&2 as a single line. The list of peaks is now (1+2, 3, 4). This takes place during the filtering operation.

3)  Interpret all lines separately, but suppress peaks within 30px of a larger peak. Now the returned list is (3,4). This takes place in the neighbourhood suppression.

4) Interpret lines 1&2 as a single line and suppress peaks within 30px of a large one. This returns (1+2, 4).

Note that the filtering range is unrelated to the suppression neighbourhood. So this will require two new arguments to define the filtering range. 
The neighbourhood suppression is done, but I don't know how to perform the filtering to achieve schemes 2 and 4. The current scheme uses a local max filter. This effectively suppresses all minor peaks in a neighbourhood so the intensity from 1 does not contribute to that from 2. 

Any ideas? Is this at all useful? Am I wasting my time?

line_test

**Comment by JDWarner** [comment]
@hohlraum I apologize for letting this fall through the cracks. You bring up some great points for consideration.

My feeling is that our default behavior should be along the lines of case 1 - no filtering. Allow the user to filter if they choose to in an advanced workflow using `hough_line` and operating in the Hough accumulator space directly.

The problem with trying to merge lines, even close ones, is in the way the parameter space is normalized. We use a parameterization where one axis is angle, and the other is the shortest distance from the origin to any point on the line. In this parameter space, there is no easy or efficient way to identify similarly-sloped lines. Lines 1 and 2 look very different in r/theta space, because while theta is identical the r value is not. We have to use this space because it's bounded.

If we did choose to add this functionality, I would be fine with patching it in via keyword arguments as you suggest. Thus, if a solution presents itself in the future we have a path forward. Ergo, I recommend we move forward with this simpler PR as it's blocking a couple others and does fix a known problem. Thoughts?

**Comment by stefanv** [comment]
Thanks, Josh, that seems like a reasonable analysis to me.

**Comment by bennlich** [comment]
@hohlraum did you see Josh's reply? Sounds like this might be ready to merge.

**Comment by JDWarner** [comment]
As there have been no dissenting comments and this PR implements the suggested fix, I'm merging.

**Comment by bennlich** [comment]
@JDWarner Nice!

**Comment by stefanv** [comment]
@JDWarner @hohlraum Thanks for taking care of this!  I wonder if we shouldn't add a comment above the sort to explain why it is there.  Also, no test to check for regressions!  And an extra space after the ``=`` :)

**Pull request merged**
