### PR TITLE
Deprecate indices in peak_local_max

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

This PR proposes to deprecate the `indices` argument from `peak_local_max`. The `remove_arg` decorator is added for this purpose.

To motivate this change I would like to cite @stefanv's https://github.com/scikit-image/scikit-image/issues/3892#issuecomment-591819705, that BTW should be integrated in the contributions guide lines ;)

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by rfezzani** [comment]
The `remove_arg` decorator introduced in this PR will allow to easily remove the `coordinate` argument from `active_contour`.

**Comment by sciunto** [comment]
I agree with this change.

**Comment by rfezzani** [comment]
:tada: Thank you @sciunto ;)

**Comment by rfezzani** [comment]
:joy:, thank you @jni!

**Pull request merged**
