### PR TITLE
Add function alphanumeric_key in __all__ of io.collection.py

### LINKED ISSUE #4309: io documentation is incomplete
## Description

`skimage.io.collection.alphanumeric_key` is a useful function (my second addition to skimage! :smile:), but it is currently not documented (https://scikit-image.org/docs/dev/api/skimage.io.html), it is importable from `skimage.io.collection` instead of `skimage.io` (is this how we want it?), and cannot be found by `skimage.lookfor`.

## Way to reproduce
```python
import skimage
skimage.lookfor('alphanumeric_key')
from skimage.io.collection import alphanumeric_key  # works
```

### PR DESCRIPTION
**Pull request by sciunto**
## Description

Fixes #4309

Test:
```
In [3]: skimage.lookfor('alphanu' 
   ...: )                                                                                                                                                                                                                                    
Search results for 'alphanu'
----------------------------
skimage.io.alphanumeric_key
    Convert string to list of strings and ints that gives intuitive sorting.
skimage.io.ImageCollection
    Load and manage a collection of image files.

```


## Checklist

<!-- It's fine to submit PRs which are a work in progress! -->
<!-- But before they are merged, all PRs should provide: -->
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

<!-- For detailed information on these and other aspects see -->
<!-- the scikit-image contribution guidelines. -->
<!-- https://scikit-image.org/docs/dev/contribute.html -->

## For reviewers

<!-- Don't remove the checklist below. -->
- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by soupault** [comment]
Frankly speaking, I am not sure if this is a good addition to the public API, since the function is rather simple and cover quite specific naming case. Perhaps, we could have more core members to share their opinions.

**Comment by jni** [comment]
well, we wanted to use it in at least one other place, namely napari. I also don't think it warrants its own package or anything (hello left-pad), and it is complex enough that I don't want to reimplement it everywhere... But I agree that it's kinda weird to provide it. I just don't think there is a better option.

**Comment by hmaarrfk** [comment]
https://pypi.org/project/natsort/ ???

**Comment by jni** [comment]
@hmaarrfk that's pretty nice, thanks!

**Comment by sciunto** [comment]
Should I close this? Should we remove this function?

**Comment by jni** [comment]
I would not remove it for sure — no chance we want that dependency. The only question is whether we want it to be part of the public API. Of that I’m not sure. I suggest we wait for more devs to weigh in.

**Comment by sciunto** [comment]
I would be in favor to add the link to natsort in the dosctring as an indication.

**Comment by stefanv** [comment]
Err, woops, just left a comment on the wrong issue.  Let's try again :)

@jni I'd suggest renaming this function to better explain what it does, as well as moving it from io to util.

**Comment by lagru** [comment]
How about `as_alphanumeric_key` or `as_natural_sort_key`?

**Comment by emmanuelle** [comment]
This one is a bit tricky, maybe we should take the opportunity of a dev meeting to discuss the best name.

**Comment by emmanuelle** [comment]
As discussed in the Atlantic meeting Jan 31st, let's keep this function private and add an example with `natsort` in the documentation.

**Comment by jni** [comment]
Cool, sounds good to me.

**Pull request closed without merging**
