### PR TITLE
Change show_rag back to draw_rag

### PR DESCRIPTION
**Pull request by stefanv**
I suggest we revert the renaming of ``draw_rag``.

This commits also cleans up some leftovers from the `skimage.graph` init file.

/cc @jni @vighneshbirodkar

### CODE REVIEW

**Comment by ahojnnes** [comment]
LGTM, waiting for @jni  or @vighneshbirodkar to approve.

**Comment by vighneshbirodkar** [comment]
@stefanv My intention behind renaming this was that `draw_*` returns a modified image and `show_` would have some GUI side effect. Don't you think the `draw_rag` name is misleading ?

**Comment by stefanv** [comment]
Yes, I think the confusion goes back to matplotlib. They use plot to plot,
show to show, but imshow to plot as well. So, maybe it's fine, but when I
last read the docstring it still said "draw a region adjacency graph on an
image".

If that has changed, then the documentation should be updated.

Let's have @jni weigh in here on a good naming convention as well.

**Comment by jni** [comment]
@jni has no strong views on this matter. =P

**Comment by emmanuelle** [comment]
I kinda like the convention proposed by @vighneshbirodkar for show (some plotting) and draw (modified image). I would go for updating the docstring instead of reverting to the old name.

**Comment by ahojnnes** [comment]
+1 for @emmanuelle 's proposal

**Comment by jni** [comment]
@stefanv you have hereby been shot down. =P Closing to reduce clutter.

**Comment by stefanv** [comment]
Sorry, the docstring says the image is modified.

**Comment by stefanv** [comment]
I.e., let's fix the docstring if we want to close this issue.

**Comment by jni** [comment]
@stefanv what? This is a PR, not an issue! i.e. if you want the docstring changed you should change it and squash the commits! =)

**Comment by stefanv** [comment]
Err, yes, how unobservant of me.  OK, here you go:

https://github.com/scikit-image/scikit-image/issues/2162

**Pull request closed without merging**
