### PR TITLE
TEST: define seed in setup() / Fix random test failure

### LINKED ISSUE #2113: Seed not defined in test_rank causes tests to randomly fail
In `skimage/filters/rank/tests/test_rank.py`, many tests do not have a fixed seed, so they can fail  randomly (just happened to me).

TODO: Check if it could also happen elsewhere

### PR DESCRIPTION
**Pull request by sciunto**
Closes #2113

Hopefully, seeds are now properly defined. 

Note: For `test_all`, i'm puzzled by this random failure: https://travis-ci.org/sciunto/scikit-image/jobs/148856616 From my understanding, the seed is supposed to be defined initially... Any comment is welcome.

### CODE REVIEW

**Comment by sciunto** [comment]
Alright. After some tests, I discovered that np.random.seed() is not thread safe. Thus, the decorator @test_parallel can cause a test failure depending on the thread order.

I do not see the interest to make the test in parallel. as I said on gitter, to me, this decorator just repeats twice the test in parallel. What's the points? I don't know. Clearly, it's not for speed.

Anyway, I think this refactoring will solve the random failures (happened again after my previous push :) )

**Comment by jni** [comment]
@sciunto I think the idea is to make sure that the function being run is thread safe. Here's the PR that merged it. (Note that we both commented on it LOL.)

https://github.com/scikit-image/scikit-image/pull/1519

**Comment by sciunto** [comment]
I remember this PR, but not the decorator. 

If it's to check that the function is thread safe, humm, why not but i guess it will fail randomly, especially with nthread=2. @ahojnnes can probably give us the light and confirm your idea :)

**Comment by sciunto** [comment]
@stefanv gave me some lights. I added a comment in the docstring of the decorator.

I also reintegrated `@test_parallel` and used the setup function to generate the random image. I guess it's safe this way.

**Comment by sciunto** [comment]
@scikit-image/core Anyone to review this? Our test suite fails randomly and this PR must fix it :)

**Comment by stefanv** [comment]
This looks good to me.

**Comment by jni** [comment]
That was exhausting but very useful! Thanks @sciunto! =)

**Pull request merged**
