### PR TITLE
Fix crash on import if byte-compiled level 2

### PR DESCRIPTION
**Pull request by JGoutin**
## Description

Fix crash on import if byte-compiled level 2 (Python -OO command line argument)
## Checklist
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Gallery example in `./doc/examples` (new features only)
- [x] Unit tests
## References

No related issue.

### CODE REVIEW

**Comment by stefanv** [comment]
Is there any way to test for this so we don't break it again by accident?  Also, a comment around that code would be helpful---just looking at it, I don't think it's obvious why it has too look that way.

**Comment by stefanv** [comment]
Maybe modify Travis to execute this specific test under -O0?

**Comment by JGoutin** [comment]
I added a job with -OO to Travis.

**Comment by JGoutin** [comment]
The Travis job work as intended. There is one error related to `-OO` but in dask module  and not directly in scikit-image: 
```
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/venv/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/venv/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/venv/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/venv/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/travis/venv/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/scikit-image/scikit-image/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/home/travis/build/scikit-image/scikit-image/skimage/util/__init__.py", line 5, in <module>
    from .apply_parallel import apply_parallel
  File "/home/travis/build/scikit-image/scikit-image/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/home/travis/venv/lib/python3.5/site-packages/dask/array/__init__.py", line 27, in <module>
    from . import random, linalg, ghost, learn, fft
  File "/home/travis/venv/lib/python3.5/site-packages/dask/array/ghost.py", line 13, in <module>
    from . import chunk, wrap
  File "/home/travis/venv/lib/python3.5/site-packages/dask/array/wrap.py", line 74, in <module>
    ones = w(np.ones, dtype='f8')
  File "/home/travis/venv/lib/python3.5/site-packages/toolz/functoolz.py", line 281, in __call__
    return self._partial(*args, **kwargs)
  File "/home/travis/venv/lib/python3.5/site-packages/dask/array/wrap.py", line 66, in wrap
    """ % {'name': func.__name__} + func.__doc__
TypeError: Can't convert 'NoneType' object to str implicitly
```

Appveyor fail, but I'not sure this is because my changes.

**Comment by JGoutin** [comment]
No more errors from Dask, but new errors from Scikit-image.

**Comment by sciunto** [comment]
@JGoutin Don't worry about the test failure, it's related to #2227

**Comment by sciunto** [comment]
@JGoutin Would you mind to squash some commits, just to keep a few, please?

**Comment by JGoutin** [comment]
Added fix for a -oo related test fail, and squashed.

**Comment by sciunto** [comment]
Reopened to run the tests again.

**Comment by stefanv** [comment]
@sciunto Note that it is no longer necessary to close and re-open issues to rebuild.  Just go to the Travis CI output and click the button there.

**Comment by stefanv** [comment]
It looks like there's some more work to be done on the warning catcher.

**Comment by sciunto** [comment]
thanks @stefanv

**Comment by sciunto** [comment]
I beleive this issue is fixed in master. See #9373. Please reopen otherwise.

**Pull request closed without merging**
