### PR TITLE
Fix calculation of Z normal in marching cubes

### PR DESCRIPTION
**Pull request by praeclarum**
This seems to be a typo in the original code.

This is a fix for #6226

### CODE REVIEW

**Review by grlee77 — CHANGES_REQUESTED** [review]
Thanks @praeclarum, I suspect this is indeed correct but can you think of a small test case we could add that would fail prior to this change?

**Comment by praeclarum** [comment]
The difference should be apparent in all normals that use the v12 vertex. So any test data that invokes that cell vertex should change a bit. If there are any acceptance tests with generated models, they will change (sorry I don't know if you do this).

A proper test case would have to orient that vertex so its obvious normal has a substantial Z component. This comes up in meshes regularly (v12s are emitted in more than 6 of the decision cases), but I am not sure how to reverse engineer a minimal repro as I don't know the LUTs well enough.

All that's to say, I'm pretty sure it's right too :-), and it looks good on my sample meshes. A minimal test case could certainly prove its correctness but is a bit beyond my skill at the moment.

Anyway, `v12_zg` is not written to anywhere else but it is read. (The library is already putting random data in people's meshes.) So evidence mounts that this change is correct.

**Review by grlee77 — APPROVED** [review]
Okay, I do not know how to write a simple test for this offhand, but it does appear like a pretty clear copy/paste error in the original code so I will go ahead and approve.

**Comment by grlee77** [comment]
The Appveyor failure is unrelated and can be ignored here.

**Comment by grlee77** [comment]
@almarklein, as the contributor of this code to scikit-image, does this change look sensible to you? (If there is no further feedback I will go ahead and merge this fix in the next day or two)

**Comment by almarklein** [comment]
I think this change is correct. What I don't understand is how this error survived all this time. Wouldn't it raise an attribute error?

**Comment by grlee77** [comment]
> Wouldn't it raise an attribute error?

I don't think so as there is a `cdef double v12_z` near the top of the class. It is not initialized to a value, though, so it seems that it could hold anything when accessed later in `add_gradient`. It is somewhat surprising that this has not previously caused issues.

**Comment by almarklein** [comment]
> It is not initialized to a value, though, so it seems that it could hold anything when accessed later in `add_gradient`.

Fascinating! Anyway, I'm glad it's "finally" fixed 😛

**Comment by grlee77** [comment]
@meeseeksdev backport to v0.19.x

**Pull request merged**
