### PR TITLE
Remove redundant testing on Appveyor

### PR DESCRIPTION
**Pull request by grlee77**
## Description

Appveyor has started failing recently. ~I will try to trigger different builds and see if I can determine why.~

I did not determine why this was happening as the error log was not very helpful. Rather than spend more time trying to debug this, I have removed `.appveyor.yml` since we also have Windows testing on Azure as well .

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
You could also delete it

**Comment by hmaarrfk** [comment]
I mean remove Appveypr all together

**Comment by hmaarrfk** [comment]
Oh, we didn't setup windows on github actions. Got it.

**Comment by grlee77** [comment]
> Oh, we didn't setup windows on github actions. Got it.

Yes, but we still have Windows the tests on Azure, which have been working so these seem mostly redundant.

**Comment by hmaarrfk** [comment]
> Yes, but we still have Windows tests on Azure, which have been working so these seem mostly redundant.

My original objection to "removing appveyor" was that azure was relatively new, and I was unsure of its longevity.

I would support plainly removing it.

**Comment by grlee77** [comment]
Okay, as [discussed above](https://github.com/hmaarrfk), I have now updated to just remove the Appveyor file.

**Review by hmaarrfk — APPROVED** [review]

**Comment by grlee77** [comment]
@meeseeksdev backport to v0.19.x

**Pull request merged**
