### PR TITLE
labelling: Improved background-relatest tests

### PR DESCRIPTION
**Pull request by matejak**
## Description

The aim of this PR is to fix background-related code in the labelling functionality described in #2369 

## Checklist

- [x] Improve tests
- [x] Fix the issue
- [x] Improve the module code in a minor way

## References
If this is a bug-fix or enhancement, it closes issue #2369

### CODE REVIEW

**Comment by sciunto** [comment]
@matthew-brett Would you like to have a look at this patch? it seems that you spent some time on this already...

Thanks!

**Comment by sciunto** [comment]
@scikit-image/core Anyone to review this? I'm not familiar with this part.

**Comment by stefanv** [comment]
@jni @matejak I see we have merged the patch supplied by Debian; is that one sufficient, or are all these changes necessary?  See https://github.com/scikit-image/scikit-image/pull/2437

**Comment by matejak** [comment]
The two PRs are not in conflict, so both can be merged.
My PR alone fixes the issue + it improves the code and tests, so I suggest that you merge both.

**Comment by sciunto** [comment]
@stefanv Would you mind doing the second review please?

**Comment by jni** [comment]
@scikit-image/core we need a second review to get 0.13 out the door.

**Comment by stefanv** [comment]
Sorry for the delay in reviewing; thanks @matejak!

**Pull request merged**
