### PR TITLE
Bump min scipy version

### LINKED ISSUE #2250: filters.frangi fails with default parameters on Py3
When running the documentation example for the Frangi, fails because of default parameters to `frangi` **on Python 3**. Note this is fine on Python 2. 

```
Traceback (most recent call last):
  File "sktest.py", line 15, in <module>
    ax[1].imshow(frangi(image), cmap=plt.cm.gray)
  File "skimage/filters/_frangi.py", line 119, in frangi
    beta1, beta2)
  File "skimage/filters/_frangi.py", line 47, in _frangi_hessian_common_filter
    (Dxx, Dxy, Dyy) = hessian_matrix(image, sigma)
  File "skimage/feature/corner.py", line 154, in hessian_matrix
    mode=mode, cval=cval)
  File "/usr/lib/python3/dist-packages/scipy/ndimage/filters.py", line 292, in gaussian_filter
    sigmas = _ni_support._normalize_sequence(sigma, input.ndim)
  File "/usr/lib/python3/dist-packages/scipy/ndimage/_ni_support.py", line 63, in _normalize_sequence
    normalized = list(input)
TypeError: 'numpy.int64' object is not iterable
```
## Reproducing

Copy and run the official example: http://scikit-image.org/docs/dev/auto_examples/filters/plot_frangi.html

### PR DESCRIPTION
**Pull request by sciunto**
Closes #2250
- I update scipy to 0.17.0. I based by judgement on debian version of numpy and scipy in testing. Numpy corresponds already to our min requirement. I guess it doesn't hurt for scipy as well, as these versions have been released almost at the same time.
- I noticed that DEPENDS.txt had outdated requirements. Updated according to requirements.txt.

### CODE REVIEW

**Comment by JDWarner** [comment]
Do we now require this version? In other words, are we actively using features which were introduced in this version (or speed improvements)? Or are there compelling things we could be taking advantage of if we did?

If not, I am :-1:.

We bumped NumPy because of well justified demand for new kwargs which significantly improved performance. In summary, a minimum requirement should not be increased unless it is no longer sufficient.

**Comment by soupault** [comment]
I agree with Josh, `0.17` seems to be too recent. 
I bet we need to check the original issue against every version higher than `0.13` to know the minimal required one.

**Comment by sciunto** [comment]
OK, I let you go ahead guys.

**Comment by jni** [comment]
I'm not sure this is that clear cut. Although I totally get the argument that we shouldn't bump versions unnecessarily, this *does* fix a bug, *and*, realistically, how many users are going to have numpy 1.11 installed together with scipy 0.12, for example? Does that even work? It doesn't with conda:

```
 ~ $ conda create -n test-np-sp-version python=3.5 numpy=1.11 scipy=0.12
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 3.5*
  - scipy 0.12* -> numpy 1.5*|1.6*|1.7*
  - scipy 0.12* -> python 2.6*|2.7*|3.3*
Use "conda info <package>" to see the dependencies for each package.
```

In fact, I *do* have to go all the way to scipy 0.17 to install numpy 1.11 using conda, and this is true whether I use Continuum's default channel or the conda-forge channel.

I did manage to pip install scipy 0.12 in a numpy 1.11 environment, but then you get all kinds of warnings just doing the most minor things:

```python
>>> from scipy import sparse
>>> import numpy as np
>>> x = sparse.csr_matrix(np.diag(np.random.rand(500)))
/Users/nuneziglesiasj/anaconda/envs/test-np-sp-version/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
```

**Comment by jni** [comment]
(just reopening until we have a bit more discussion. We can close again if I am overwhelmed by a wave of negativity. =P)

**Comment by soupault** [comment]
@jni from my experience with `conda`, I'd say that it doesn't implement the "lower bound"-compatibility, rather convenient one. So, I'd not consider `conda`'s behaviour as a base for any inference.
I guess the best approach would be to dive into `frangi` code and find the feature, which isn't supported by the earlier versions of `scipy`, so to get the lowest required version number.

**Comment by soupault** [comment]
@sciunto I've dived a little deeper into the related issue, and now I'm :+1: on this PR (see https://github.com/scikit-image/scikit-image/issues/2250#issuecomment-242903581). Sorry for the inconvenience.

**Comment by sciunto** [comment]
So we converged on the same solution for different reasons... Nice :)

**Comment by sciunto** [comment]
I'm closing because it doesn't seems to be the right thing to do.

**Pull request merged**
