### PR TITLE
Resampling of nD arrays

### PR DESCRIPTION
**Pull request by ankit-maverick**
Current api :

``` py
In [1]: import numpy as np
In [2]: from skimage.transform._warps import downscale_local_means
In [3]: a = np.arange(16).reshape(4, 4)
In [4]: a
Out[4]: 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
In [5]: downscale_local_means(a, (2, 2))
Out[5]: 
array([[  2.5,   4.5],
       [ 10.5,  12.5]])
In [6]: 
In [6]: downscale_local_means(a, (2, 3))
Out[6]: 
array([[  3.        ,   1.66666667],
       [ 11.        ,   4.33333333]])
In [7]: from skimage.measure._sum_blocks import sum_blocks

In [8]: sum_blocks(a, (2, 2))
Out[8]: 
array([[10, 18],
       [42, 50]])
```

### CODE REVIEW

**Comment by forman** [comment]
Just stumbled over #492 where it seems I had very similar requirements as @cdeil and developed https://github.com/CAB-LAB/gridtools, which are now in operational use for the production of a climate data cube. I use Numba for performance reasons. I'm happy to contribute one or the other method.

**Comment by jni** [comment]
@forman Sorry what do you mean exactly? It seems from a quick reading that @cdeil's requirements were met by this PR?

**Comment by forman** [comment]
@jni oh, sorry, I wasn't clear at all. I just wanted to inform anyone interested about some additional downsampling methods I've implemented in `gridtools` which _may_ extend scikit-image capabilities.

**Comment by cdeil** [comment]
@forman - Thanks for pointing out https://github.com/CAB-LAB/gridtools

I see you've released it under the GPL license.

In case you're not aware: this means that many numerical Python people will not read or use or contribute to it. Numpy, Scipy, Numba, scikit-image, ... most numerical Python packages are under a liberal license like BSD or MIT.
I don't want to argue about licensing, but just in case you aren't opposed: please re-license to improve interop and re-use with similar numerical Python packages.

**Comment by forman** [comment]
@cdeil you are right, I'll put it under a more liberal license for the next release. Thanks!

**Comment by cdeil** [comment]
@forman - Thank you! 

In this case ... I'll install it and check it out now.

😄

**Comment by forman** [comment]
Done.

**Pull request merged**
