### PR TITLE
Update skimage mailing addresses

### PR DESCRIPTION
**Pull request by jarrodmillman**
Follow-up to #5951.

- [x] `skimage-core@python.org` ->  `skimage-core@discuss.scientific-python.org`
- [x]  `scikit-image@python.org` ->  `scikit@discuss.scientific-python.org`

### CODE REVIEW

**Review by grlee77 — APPROVED** [review]
Thanks!

**Review by stefanv — APPROVED** [review]

**Comment by stefanv** [comment]
I think for the discussion forum we want to encourage people to sign up on discuss, perhaps?

Thanks for the core list address update 👍

**Comment by jarrodmillman** [comment]
How would that work for something like:
```
skimage/util/setup.py:          maintainer_email='scikit-image@python.org',
```

Is `'scikit-image@python.org` still the preferred email address?

**Comment by stefanv** [comment]
I agree with you that there the email address would make more sense.

**Comment by jarrodmillman** [comment]
@stefanv Any preference for what name I choose:
- [ ] scikit-image@python.org -> scikit-image@discuss.scientific-python.org / skimage-contributor@discuss.scientific-python.org ?

**Comment by jarrodmillman** [comment]
Someone should double-check that I updated this correctly: a45f37f912755

Should I replace the mentions of `mailing list` with `discussion forum`?

**Comment by stefanv** [comment]
Death by a thousand small decision cuts :) skimage@ should be fine.

**Comment by alexdesiqueira** [comment]
Thank you @jarrodmillman!

**Pull request merged**
