### PR TITLE
Geometric mean

### PR DESCRIPTION
**Pull request by glemaitre**
Hi,

Add local geometric mean with proper associated test.
It is based on the log-average method.

Cheers,

### CODE REVIEW

**Comment by glemaitre** [comment]
Hi, I am using the function round() in the cython file. However, in Windows it seems that it failed to compile with the Visual Studio compiler:

`error LNK2019: unresolved external symbol _round referenced in function`

Any solution for that?

**Comment by vighneshbirodkar** [comment]
@glemaitre 
Use the in house round
https://github.com/scikit-image/scikit-image/blob/953fbfc539217ad4c92fcf14a9d6dfe1b4b1b793/skimage/feature/orb_cy.pyx#L14

**Comment by glemaitre** [comment]
Thanks

**Comment by ahojnnes** [comment]
@glemaitre Sorry for the late reply. This looks good to me. Would you have a reference for the method, that we can add to the doc string?

**Comment by glemaitre** [comment]
Hi,

The reference that could be included is the Digital Image Processing from Gonzalez and Wood.

Gonzalez, Rafael C. Digital image processing. Pearson Education, 2009.

**Comment by ahojnnes** [comment]
@glemaitre That would be great, would you please add that to your function, similar to https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/radon_transform.py#L282

Thanks.

**Comment by glemaitre** [comment]
Done.

**Comment by ahojnnes** [comment]
Could you please undo the merge? To preserve the history of all contributors, we have the policy to do a rebase as described here: https://github.com/scikit-image/scikit-image/blob/master/CONTRIBUTING.txt#L95

**Comment by glemaitre** [comment]
Sorry about that, I change it.

**Comment by ahojnnes** [comment]
Wonderful, thanks for your contribution!

**Pull request merged**
