### PR TITLE
subpixel shift registration addition

### PR DESCRIPTION
**Pull request by msarahan**
For the sake of keeping a more readily accessibly reference to this controversial addition, here's a PR.

Discussion has thus far been at:
https://groups.google.com/forum/#!topic/scikit-image/fDbdOgHgolI

This PR should not be merged until licensing issues discussed in that email thread have been addressed.

### CODE REVIEW

**Comment by stefanv** [comment]
```
*From:* Jim Fienup
*Subject:* FW: Open-source implementation of sub-pixel registration
*Date:* Wed 07 Jan 2015 11:25:47 AM PST

Attached are some comments on the Python implementation of our
registration algorithm by my student, Alex. I agree that it should allow
for either images or Fourier transforms to be input, and that images are
allowed to be complex-valued (important for coherent imaging such as for
medical ultrasound, synthetic-aperture radar, etc.), and that "phase
correlation" is not descriptive enough -- it is image registration by
cross-correlation.

I wish you success in getting this out to the Python community. Our group
(well, most of it) is transitioning from Matlab to Python.

Best regards,

James R. Fienup
Robert E. Hopkins Professor of Optics

---

On 1/7/15 11:07 AM, "Iacchetta, Alexander" wrote:

>Dr. Fienup,
>
>This scikit-image software mimics Manuel's Matlab code pretty well.  I
>mostly have suggestions that affect usage, but I also have a conceptual
>objection to the use of a filter function.  I tried to make my remarks as
>detailed as possible
>
>With regard to the filters, the intended usage is unclear and will likely
>decrease accuracy filtering the source image will change the magnitudes
>in the frequency domain.  Two identical images shifted by some amount
>will differ only in phase in the frequency domain, so a convolution with
>a filter function in the frequency domain on only one of the images could
>reduce accuracy.  Perhaps there is another reason why the filter function
>is included, but I suggest that all aspects of the filter function should
>be removed.  Another reason to remove the filter functions all together
>is that there is not enough control over the filters to have a broad use.
>
>If the filter functions are not removed, they will need a very minor
>modification.  The filters that are applied should be generated with
>"sym=False" to ensure that the DC pixel of the filter matches the DC
>pixel of the image (this has a very minor affect but shouldn't be
>ignored, see below).  The documentation should specify that filters are
>only used when image domain arrays are provided.
> --> line 101 of phase_correlate.py should be changed to "window =
>filter_function(axis_size, sym=False).reshape(filter_shape)" from "window
>= filter_function(axis_size).reshape(filter_shape)"
>
>Currently, the software makes assumptions about the domain of the images
>based on being real or complex arrays.  Whether or not the input arrays
>are in the image or frequency plane should be set by a flag, not with
>real/complex assumptions, so that complex images can also be registered.
>The error message that occurs when one input is real and one is complex
>should also be removed to allow for registering complex images (lines
>162-165).
>
>The name of the function could lead to some confusion, and should be more
>indicative of image registration.
>
>A final consideration is to use a Fourier filter to perform the shift
>operation if the example script plot_phase_correlate.py instead of spline
>interpolation.  For example:
>        def fourier_shift(image, shift):
>            rows =
>numpy.fft.ifftshift(np.arange(-numpy.floor(image.shape[0]/2),
>numpy.ceil(image.shape[0]/2)))
>            cols =
>numpy.fft.ifftshift(np.arange(-numpy.floor(image.shape[1]/2),
>numpy.ceil(image.shape[1]/2)))
>            cols, rows = numpy.meshgrid(cols, rows)
>            out = numpy.fft.ifft2(numpy.fft.fft2(image)*
>numpy.exp(1j*2*pi*(shift[0]*rows/image.shape[0]+shift[1]*cols/image.shape[
>1])))
>            return out
>
>Let me know if there are any questions.
>
>Alex

```

**Comment by stefanv** [comment]
@msarahan Above is some feedback from Prof. Fienup and his student Alex.  If you'd kindly have a look--I think we are close.  We'll need to prepare an email with feedback to the three reviewers (perhaps the easiest is if you leave a comment here, then I can forward it to them).  Thanks very much!

**Comment by msarahan** [comment]
1. Thanks for the feedback!
2. I really intended filter functions for use in the image domain/real-space (I'll add a comment in the docstring).  This is the only kind of input data I work with, so thanks for expanding my perspective.  Images that do not obey periodic boundary conditions are plagued with streaking in the FFT from image boundaries.  In practice, I've found that the filters (slightly) improve registration accuracy.  The difference is minor enough that I'd be happy to remove filters altogether - if any end-users want filtering, they can do it on input data prior to calling this function.
3. If filters stay in, how much more control would you want?  Perhaps one more argument, "filter_kw" as keyword arguments that would be passed to the filter function?
4. If filters stay in, I'm not certain I understand your modification.  I think you think that the filters are applied in Fourier space.  They're not - they're applied to one image before doing the FFTs.  Does your DC pixel alignment still apply?  I'm not sure I feel comfortable forcing a "sym=False" argument being passed to arbitrary functions.  It should hold for any of the scipy.signal functions, but my hope was to be general enough that someone could pass arbitrary window functions there (that may not have sym keyword arguments)
5. Based on earlier input from Manuel, the software no longer makes assumptions about image domain based on real/complex.  It now requires an additional argument, "space" that takes a string argument: "real" or "fourier"
6. The name of the function has been changed to "register_translation" - is this adequately specific?
7. I would like the scikit-image team to comment about a fourier shift function.  Specifically, is this useful enough to include generally as part of scikit-image?  I like just using scipy for the example code, because a function call is so simple and keeps the example clear.  I'm not attached to spline interpolation in any way, and would happily replace the scipy shift code with some equally simple function call (for example, if your fourier shift function were part of scikit-image.)

**Comment by JDWarner** [comment]
Regarding point 7: Prof. Fienup is correct, using the DFT shift property will yield the highest possible quality for subpixel translation. Spline interpolation along with most other interpolation methods impose a model and attempt to interpolate, while the DFT is pure.

IMO there is a place for this in the library, even though it's relatively simple to implement. The tricky bits are in handling the wraparound (for intermediate calculations wraparound is needed; for the final translation it would probably be best to fill with zeros). The likely locations for it would be in `skimage.transform`, `skimage.util`, or `skimage._shared` depending on if we want it to be public or private.

**Comment by stefanv** [comment]
Fourier shift may not be equally simple for all to implement.  As a tiny extra, let's just add it here.

**Comment by msarahan** [comment]
- Removed filter/window.
- Replaced scipy.ndimage.shift with Alex's fourier_shift function, which is defined in register_translation.py.  This is used in both plot_register_translation, and in the tests.
- Fixed a docstring that referenced the old behavior of determining the space from the input data's dtype

**Comment by stefanv** [comment]
When you're ready, let me know, then I'll ship off the comments and ask for a final review.

**Comment by msarahan** [comment]
Fixed one reference to "window" in docstring.  This should be ready to go.  Please ask for the final review.

**Comment by stefanv** [comment]
Feedback sent.

**Comment by stefanv** [comment]
I've pinged Prof. Fienup--let's hope we can include this in the release, which I hope to make no later than Sunday.

**Comment by stefanv** [comment]
Feedback from Prof. Fienup:

When comparing complex-valued images (which we often do for optical fields), the Python version does not always work, whereas the old Matlab version does work, as described in the emails below.

This might be due to what Alex mentions in his Feb. 18 email:

When the upsampling factor is greater than 1, Manuels routine finds an initial shift estimate using an upsampling factor of 2. The Python code uses an upsampling factor of 1 for all initial guesses. I tried modifying the Python code to find an estimate using an upsampling factor of 2, and that seemed to solve the problem for a range of piston values (-pi/2, pi/2).

So initially doing an FFT with 2x embedding in each dimension seems to be the safer thing to do, although it is more computationally expensive.

Best regards,
Jim Fienup


From: Alexander

I ran the current Python (without my modifications) and Manuel’s Matlab code for two cases of piston phase differences of 1 and 2 radians between the images, where I kept the translation the same for all cases and show the results for upsampling factors of 1, 10, and 100. The pasted the outputs below. The results for the case of 1 radian are nearly identical, except for the detected phase difference (particularly for upsampling factor of 1). For the case of 2, we have the same issue with the upsampling factor, and the Python routine is unable to determine the translation.

The 2 Python cases:

The 2 Matlab cases:

1)
Known pixel offset (y, x) and radians of piston phase:
(2.485, 7.739)
1
upsampling factor = 1
Detected pixel offset (y, x):
[ 2.  8.]
Detected Phase Difference:
-1.00000067017
Error:
0.0412438322752
upsampling factor = 10
Detected pixel offset (y, x):
[ 2.5  7.7]
Detected Phase Difference:
0.999999682717
Error:
0.00360550684785
upsampling factor = 100
Detected pixel offset (y, x):
[ 2.48  7.74]
Detected Phase Difference:
0.999999983341
Error:
0.000376259413504

1)
Known pixel offset (y, x) and radians of piston phase:
(2.485,7.739)
1
upsampling factor = 1
Detected pixel offset (y, x):
(2,8)
Detected Phase Difference:
1
Error:
0.041244
upsampling factor = 10
Detected pixel offset (y, x):
(2.5,7.7)
Detected Phase Difference:
1
Error:
0.0036055
upsampling factor = 100
Detected pixel offset (y, x):
(2.48,7.74)
Detected Phase Difference:
1
Error:
0.00037626


2)
Known pixel offset (y, x) and radians of piston phase:
(2.485, 7.739)
2
upsampling factor = 1
Detected pixel offset (y, x):
[ 212.  251.]
Detected Phase Difference:
-1.99999460631
Error:
0.680012748637
upsampling factor = 10
Detected pixel offset (y, x):
[ 211.8  251.2]
Detected Phase Difference:
1.99999380957
Error:
0.680014443706
upsampling factor = 100
Detected pixel offset (y, x):
[ 211.84  251.17]
Detected Phase Difference:
1.99999374432
Error:
0.680014433271

2)
Known pixel offset (y, x) and radians of piston phase:
(2.485,7.739)
2
upsampling factor = 1
Detected pixel offset (y, x):
(2,8)
Detected Phase Difference:
2
Error:
0.041244
upsampling factor = 10
Detected pixel offset (y, x):
(2.5,7.7)
Detected Phase Difference:
2
Error:
0.0036055
upsampling factor = 100
Detected pixel offset (y, x):
(2.48,7.74)
Detected Phase Difference:
2
Error:
0.00037626

**Comment by stefanv** [comment]
From Alexander:

I spent some more time today looking into the issue, and I've attached my modified Python routine. I added comments with my initials (ASI) wherever I made a change. After the modifications, I did not have to use an upsampling factor of 2 for an initial estimate for larger upsampling factors.

With these changes, Manuel's Matlab routine and the Python routine provide consistent results.

Thanks,
Alex

**Comment by stefanv** [comment]
See https://gist.github.com/stefanv/86a7a764ed9fcbf86e25

**Comment by msarahan** [comment]
Great!  Alex made some very nice improvements.  I'll merge his changes tonight and rebase.

**Comment by msarahan** [comment]
Would Alex mind sharing the test data that he has?  It would be good to
write tests to make sure that their data works the way they expect.
Assuming he's willing to share some data, where should it live?  With the
rest of the skimage data?

**Comment by msarahan** [comment]
One further question for Alex:  When finding the max pixel, Alex suggests
the following: "np.argmax does not use abs of input, but it should here"

Why should abs be used?  Doesn't that leave you open to returning
anti-correlated results?  Like with a checkerboard pattern with noise,
could you conceivably have a registration result with the "white" squares
on top of the "black" squares because of the absolute value?  Maybe this is
something about complex data that I'm not used to considering.

**Comment by JDWarner** [comment]
@msarahan I believe it's because `np.abs` finds the complex magnitude, while `np.argmax` only operates on the real portion. Thus, the "maxes" found aren't truly maximums.

I can't comment on the anti-correlation issues off the top of my head, but for complex input it is appropriate.

**Comment by msarahan** [comment]
Thanks @JDWarner - makes sense.  I think in practice, anticorrelation would only be an issue with data that was negative and positive (and somewhat periodic) - not common in my experience, since images generally represent counted phenomena.

**Comment by stefanv** [comment]
I mailed Alex about the data.

**Comment by stefanv** [comment]
@msarahan Thank you for diligently following this issue through to its conclusion.  I am going to merge the feature, and once we hear back from Alex we can add his test case as an additional PR.  Excellent work, thank you!  (May I ask you to also do a PR that adds your name to `CONTRIBUTORS.txt`?)

**Comment by stefanv** [comment]
Actually, if you don't mind, I've added you myself: https://github.com/scikit-image/scikit-image/commit/4cbd8fdf888cbefb3d76d875c727a08cf168c84e

**Comment by msarahan** [comment]
Thanks everyone for your patience!  Sorry I didn't squash at the end there - I thought I'd have one more chance and wanted to keep the changes easy to examine/discuss.

**Comment by keflavich** [comment]
This is a bit out of date now, but there is another implementation of nearly the same thing here:
http://image-registration.readthedocs.org/

**Pull request merged**
