### PR TITLE
bump min matplotlib version to 2.1.0 to follow edits in #3300

### PR DESCRIPTION
**Pull request by sciunto**
## Description

I merged too rapidly #3300 Matplotlib min version has to be increased.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Matplotlib 2.1.0 was released in Oct 2017. 

Is there maybe a better way to hide deprecation warnings in the docs?

**Comment by sciunto** [comment]
matplotlib 2.0.0 was released in Jan 2017. Is the 8 months difference significant?

**Comment by sciunto** [comment]
And our LTS will support matplotlib 2.0.0.

**Comment by hmaarrfk** [comment]
Not too sure. I like to live on the bleeding edge and others are more conservative than me.

Good to have both dates up there to let the others decide. 

Removing the matplotlib dependency is 2 PRs away.
Unfortunately, one of is a build matrix PR so that will take a while to review.

**Comment by hmaarrfk** [comment]
Maybe we need 2.1.1?

**Comment by stefanv** [comment]
What's going on with the Qt backend in the tests?

**Comment by jni** [comment]
Yes I think @hmaarrfk is right. @sciunto can you try pushing up to 2.1.1? I don't have the references off the top of my head but I remember having to wait for mpl to update their Qt backend links.

Regarding the min version bump, as @hmaarrfk says, we ultimately want to remove mpl from the computational core dependencies, so I don't mind having a recent requirement for this. It's ultimately going to be a docs requirement.

**Comment by sciunto** [comment]
Done

**Comment by jni** [comment]
:sob:

**Comment by sciunto** [comment]
@tacaswell I'm sorry to bother you. Dou you have any clue regarding the travis failure please?

**Comment by hmaarrfk** [comment]
maybe this? https://github.com/scikit-image/scikit-image/pull/3345/files

**Comment by hmaarrfk** [comment]
Since this is a .doc dependency. Does it make sense to leave the default requirements at 2.0.0 but add a line to the .doc dependency file?

**Comment by hmaarrfk** [comment]
Did you try restricting the version of pyqt for the minimum requirements test?

**Comment by hmaarrfk** [comment]
Man, you just got really unlucky with that last build
https://travis-ci.org/scikit-image/scikit-image/jobs/429581805#L4739

**Comment by hmaarrfk** [comment]
Interesting. It is like your scripts won't automatically close. Can you run the examples on your own computer to check that all the windows automatically close?

**Comment by sciunto** [comment]
I won't have time any time soon to do that on my machine... :(

**Comment by sonicgao** [comment]
matplotlib 3.0.0 has been released, depend on python >= 3.5
https://github.com/matplotlib/matplotlib/releases/tag/v3.0.0

how to default with LTS version?

**Comment by sciunto** [comment]
If someone wants to look at it... I'm sorry but I won't.

**Pull request closed without merging**
