### PR TITLE
DOC: test piwik with piwik.sciunto.org

### PR DESCRIPTION
**Pull request by sciunto**
@emmanuelle Let's give a try for #1649

### CODE REVIEW

**Comment by sciunto** [comment]
Travis failure for py3.5 does not make sense...

**Comment by sciunto** [comment]
@stefanv Do you know what's going on with travis? The failure looks random. (was only with py3.5)

**Comment by stefanv** [comment]
Yes, ignore that for now. Steven will fix it *cross fingers* :)

**Comment by emmanuelle** [comment]
@sciunto can you / did you try it on a mock website?

**Comment by sciunto** [comment]
@emmanuelle I did on my personal webpage

**Comment by sciunto** [comment]
Also, I think merging this PR will only integrate the code in the dev pages. But, still, it's a good start to check that it's correctly implemented. Once I'm check that, I can send credential  to the core dev and others (if they ask).

**Comment by emmanuelle** [comment]
Well, I think we should merge it then. Any other :+1: ?

**Comment by stefanv** [comment]
Yeah, let's give it a shot.

**Pull request merged**
