### PR TITLE
ENH: doc of ridge functions

### PR DESCRIPTION
**Pull request by sciunto**
## Description

This PR aims at improving the doc of #3515   as these functions are designed for processing on vessels, I changed the image for a crop of retina. I added see also sections as well.
Figure_1

Cc @DavidBreuer 

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by emmanuelle** [comment]
Thanks @sciunto ! The contrast of frangi is flattened because the higher values are at the border of the image, could you please increase the contrast (eg setting vmax) for this filter, since the result is quite good but it doesn't show here.

**Comment by emmanuelle** [comment]
We could also have more explanations about the differences between the different filters, but this can come in another PR because this PR is already an improvement.

**Comment by sciunto** [comment]
Do you think it is better to set a vmax for a particular case or crop all images of 4 pixels on each edge and add a note saying that Frangi leads to an edge effect removed in this example?

PS: I'm discovering these filters and I'm not familiar at all with these algorithms.

**Comment by jni** [comment]
I'm confused — doesn't matplotlib automatically stretch the contrast for each image?

**Comment by jni** [comment]
Oh, sorry, misread @emmanuelle's comment. Hmmm. I'm not sure what the best answer is here. @sciunto go with whatever you think is prettiest I reckon. =)

**Comment by emmanuelle** [comment]
@sciunto I would stretch the contrast for this particular case and explain in the text that Frangi filter does this special thing at the border (which will be visible because these pixels will be saturated). But I also leave it to your personal taste, the important thing is that this subplot is not pitch black and users think frangi is worthless.

**Comment by sciunto** [comment]
I forgot about this PR. I put a crop to improve the rendering. 
sphx_glr_plot_ridge_filter_001

**Comment by jni** [comment]
Looks great, thanks @sciunto!!!

**Pull request merged**
