### PR TITLE
Set -DNPY_NO_DEPRECATED_API=NPY_1_23_API_VERSION on build

### LINKED ISSUE #7347: Add `-DNPY_NO_DEPRECATED_API` flag to our meson configuration
From the comment in https://github.com/cython/cython/issues/2498#issuecomment-1992608347 and [`scipy/meson.build#L73-L77`](https://github.com/scipy/scipy/blob/33e93e04b0ca65b4938e685b28fda9846d68f657/scipy/meson.build#L73-L77) it seems like there's a flag to make sure we are not using deprecated C API features of NumPy. Seems like a good idea.

I'm not sure how to translate SciPy's configuration to our [skimage/meson.build](https://github.com/scikit-image/scikit-image/blob/main/skimage/meson.build) yet. So I'm opening this issue first. Does anyone have an idea?

### PR DESCRIPTION
**Pull request by stefanv**
Closes #7347

### CODE REVIEW

**Comment by stefanv** [comment]
@seberg How are we supposed to use this compiler flag, now that NumPy 2 produces backwards compatible builds?

**Review by lagru — APPROVED** [review]
I don't have a lot of insights into the configuration here but it seems to work. So I'm happy to try this out.

**Review by hmaarrfk — APPROVED** [review]

**Comment by stefanv** [comment]
Could NumPy make an official recommendation on how to use this, perhaps?

**Comment by hmaarrfk** [comment]
Thank you at @seberg we try to stay pretty close to SPEC0 and we set a lower bound of 1.23 at runtime so I think we are in the clear!!!

https://github.com/scikit-image/scikit-image/blob/a8f5c6fe05c3e89f02dc9dc688084cb852de678f/pyproject.toml#L29

**Comment by seberg** [comment]
Ah, wait I misread, because I didn't think about this switch in forever (rather the ABI version), but I think this is right then.
We have just not really used this mechanism to deprecate anything new (forcing/asking users to bump it) in a very long time, I think...

**Pull request merged**
