### PR TITLE
Only use retry_if_failed with recent pooch

### LINKED ISSUE #5146: Pooch Dependency Issue
The following merged PR added dependency to pooch 1.3.0 in data module:
https://github.com/scikit-image/scikit-image/pull/5105/files

The current implementation checks if pooch is installed by trying to import it:

https://github.com/scikit-image/scikit-image/blob/0862e5630a00c151566260f02d118f4ee46bb351/skimage/data/__init__.py#L114-L120

Then uses it as if it's v1.3.0:

https://github.com/scikit-image/scikit-image/blob/0862e5630a00c151566260f02d118f4ee46bb351/skimage/data/__init__.py#L149-L150

This raises error if an older version of pooch such as 1.2.0 is installed.

The code is always executed since data module is imported in skimage init:

https://github.com/scikit-image/scikit-image/blob/0862e5630a00c151566260f02d118f4ee46bb351/skimage/__init__.py#L135

So you get the error even if you don't use data, hence did not install the scikit-image[data] extra.

### PR DESCRIPTION
**Pull request by jni**
## Description

Fixes #5146

Would love to get this in ASAP and release 0.18.1.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Review by rfezzani — APPROVED** [review]
Thank you @jni!

**Comment by hmaarrfk** [comment]
Interesting that you want to entertain using pooch, even though it is a lower version.

**Review by hmaarrfk — APPROVED** [review]

**Comment by jni** [comment]
> Interesting that you want to entertain using pooch, even though it is a lower version.

Yeah, I started *not* doing that, but then I realised it was just as easy to do this — easier, in fact, because our error messages would have to be updated ("please install pooch" and users would see that it was already installed).

Errors are unrelated, so I'm merging. Thanks @rfezzani and @hmaarrfk for the review!

**Comment by hmaarrfk** [comment]
@meeseeksdev backport to v0.18.x

**Comment by jni** [comment]
LOL sorry, this actually needs a *forward port*. I made it against the v18 branch for expediency in the fixup release, which I'll make today.

**Pull request merged**
