### PR TITLE
Add explicit ordering of gallery sections

### LINKED ISSUE #3462: order the examples in our gallery
## Description

As suggested by @emmanuelle in #3388, it would be interesting to use the [ordering feature of sphinx-gallery](https://sphinx-gallery.readthedocs.io/en/stable/advanced_configuration.html?highlight=sorting#sub-gallery-order) a set a more logical order among sections and examples (eg operation on numpy arrays could come among the first ones).

### PR DESCRIPTION
**Pull request by PinkFloyded**
## Description
Add explicit ordering of gallery sections.

## References
Closes #3462 
Related discussion at: #3621 

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
Thanks @PinkFloyded!

**Comment by jni** [comment]
btw, what happens if a section is not mentioned in the `ExplicitOrder`? Does it not get served? If so, then we should have a reminder in the guide that new sections need to be added here.

**Comment by PinkFloyded** [comment]
If it is not mentioned in the `ExplicitOrder` then it doesn't build and throws an error:
```
ValueError: If you use an explicit folder ordering, you must specify all folders. Explicit order not found for ../examples/new_section
```
I'm not sure where this can be documented. Please let me know and I will add it in.

**Comment by jni** [comment]
Personally, I think that error message is explicit enough that we don't need to add a note, but for the record it would go in the [contributing guide](http://scikit-image.org/docs/dev/contribute.html), the source of which is [here](https://github.com/scikit-image/scikit-image/blob/master/CONTRIBUTING.txt). Looking it over, there isn't a natural place there (it does not explicitly state how to add examples to the gallery), so it would require extensive modifications.

**Pull request merged**
