### PR TITLE
Unpin scipy dependency

### PR DESCRIPTION
**Pull request by adamjstewart**
## Description

Re-enables the use of new scipy on old python. See https://github.com/scikit-image/scikit-image/pull/6567#issuecomment-1450878366 for context.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

@jarrodmillman @stefanv

### CODE REVIEW

**Review by stefanv — APPROVED** [review]

**Comment by stefanv** [comment]
Thanks @adamjstewart, your change looks correct to me.

**Comment by stefanv** [comment]
Note that we auto-generate our pyproject.toml file, so you need to modify  `tools/pyproject.toml.in` and run `tools/generate_pyproject.toml.py`.

**Comment by stefanv** [comment]
`pre-commit` should catch this, but I guess you don't have it enabled.

**Comment by adamjstewart** [comment]
`tools/pyproject.toml.in` does not include any mention of scipy...

**Comment by stefanv** [comment]
Right, sorry, that's why we generate the file, so there's one source of truth :sweat_smile: 

Edit `requirements/default.txt`.

**Comment by adamjstewart** [comment]
Hold on, let me just compile rust real quick...

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
> Hold on, let me just compile rust real quick...

:grimacing: Sorry, I can do the templating for you. I'm a bit shocked by the decision not to include a proper TOML writer in the standard library.  The Python core devs say they don't want to tie themselves up with API decisions, but it feels like a pretty major hole in functionality.

**Comment by adamjstewart** [comment]
There's tomli now, but my other deps don't yet support 3.11 so I'm stuck on 3.10.

**Comment by stefanv** [comment]
I tried a few, but could only find one that formatted it anywhere near like what a human would.

Thanks for this PR, @adamjstewart!

**Comment by adamjstewart** [comment]
The current milestone for this change is 0.21, but I wonder if it could make it into the 0.20.1 release instead. It looks like there are at least a couple repos blocked on adding Python 3.11 support.

**Comment by space-nuko** [comment]
@stefanv Please do, I encountered this issue 
https://github.com/gradio-app/gradio/pull/3487
https://github.com/gradio-app/gradio/actions/runs/4504131543/jobs/7928212303?pr=3487

**Comment by stefanv** [comment]
Thanks for letting us know @space-nuko

**Comment by adamjstewart** [comment]
Any updates on 0.21.1?

**Comment by stefanv** [comment]
Yes, we're releasing 0.22 next week.

**Comment by adamjstewart** [comment]
Does the release of 0.21rc0 also coincide with a release of 0.20.1? We can use an rc version in CI if needed, but a stable release would be even better.

**Comment by stefanv** [comment]
I don't think we'll be doing a 0.20.1; but we can check with release manager @jarrodmillman.

**Pull request merged**
