### PR TITLE
Fix for NumPy 1.26

### PR DESCRIPTION
**Pull request by jarrodmillman**
Follow up to #6970.

See
- https://github.com/scikit-image/scikit-image/pull/6970#issuecomment-1680647078
- https://github.com/scikit-image/scikit-image/pull/6970#issuecomment-1680721091

### CODE REVIEW

**Comment by lagru** [comment]
Is it possible that [`gufunc` (in this case `_umath_linalg.eigvalsh_lo`](https://github.com/numpy/numpy/blob/7bc18034031f32e5d03bb646c472dabd1623e9d5/numpy/linalg/linalg.py#L1181) or something in that machinery is not thread-safe? I am struggling to find a cause for this on our side. 

@seberg, I hope it's okay to ping you in the hope that you have some insight or know whom to ask about this. E.g. might https://github.com/numpy/numpy/commit/7508afd73161edeef7b3d158fa15d5bfe91b285a be responsible?

**Comment by lagru** [comment]
I'll try my luck with `git bisect` later. Perhaps I can identify a commit on our or NumPy's side. Otherwise I am out of ideas.

**Comment by lagru** [comment]
An even more minimal reproducing example:
```python
import numpy as np
from concurrent.futures import ThreadPoolExecutor

assert np.__version__ == '1.26.0b1'

rng = np.random.default_rng(32)
matrices = (
    rng.random((5, 10, 10, 3, 3)),
    rng.random((5, 10, 10, 3, 3)),
    # rng.random((5, 10, 10, 3, 3)),
)

with ThreadPoolExecutor(max_workers=None) as ex:
    list(ex.map(lambda m: np.linalg.eigvalsh(m), matrices,))
```
on the pre-build NumPy 1.26.0b1, I get one of these errors:
- ```
  free(): invalid pointer
  free(): invalid pointer
  
  Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
  ```
- ```
    File "/home/lg/.local/lib/venv/skimagedev/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 1181, in eigvalsh
    w = gufunc(a, signature=signature, extobj=extobj)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ValueError: On entry to DSYEVD parameter number 8 had an illegal value
  ```
- Sometimes it even passes! :see_no_evil: 

When building NumPy 1.26.0b1 from source with `python setup.py build_ext --inplace -j 4` it passes all the time. So `git bisect` is no use right now.

Maybe something todo with CBLAS etc.? Not sure how to read the output of `numpy.show_config()`.

**Comment by lagru** [comment]
Reported upstream in https://github.com/numpy/numpy/issues/24512.

**Comment by lagru** [comment]
Just noticed, the [failing test](https://github.com/scikit-image/scikit-image/actions/runs/5904811581/job/16017675397?pr=7101#step:5:530) in https://github.com/scikit-image/scikit-image/pull/7101/commits/eb97c5ebcdd5062575ed7a878af5829e776d19a2 is a different one
https://github.com/scikit-image/scikit-image/blob/79cb89d1ee4bb6ff46a53529a0e5a05e0348ff3b/skimage/future/tests/test_trainable_segmentation.py#L95

compared to the one mentioned in https://github.com/scikit-image/scikit-image/pull/6970#issuecomment-1680647078. But it's the same function `np.linalg.eigvalsh` that fails. Though I can't reproduce this failure locally. Only the [previous one](https://github.com/scikit-image/scikit-image/blob/161ee8bde3323261b5b5f14b9c9a978ec4f3f24a/skimage/feature/tests/test_basic_features.py#L41) fails for me locally.

**Comment by seberg** [comment]
> Is it possible that [gufunc (in this case _umath_linalg.eigvalsh_lo](https://github.com/numpy/numpy/blob/7bc18034031f32e5d03bb646c472dabd1623e9d5/numpy/linalg/linalg.py#L1181) or something in that machinery is not thread-safe? I am struggling to find a cause for this on our side.

Sorry, just on the process of coming back from vacation.  I am very sure that the lapack lite stuff is not threadsafe, but if you install wheels they shouldn't be using it, the `np.show_runtime()` would be useful.  You may be using it if you install NumPy yourself locally though.
(`show_runtime()` is often more helpful than `show_config()`)

Next, the warning state may be unsafe, but this doesn't seem the problem (fixed on NumPy `main` finally).  I am not aware there are other threading issues and I somewhat doubt it, but neither am I quite sure there are not.  (Or whether openblas might have issues.)

**Comment by seberg** [comment]
Ah, hand't seen the NumPy issue where some nice sleuthing found that it is indeed the lapack-lite being used (due to build problems) which were fixed.

**Comment by jarrodmillman** [comment]
https://pypi.org/project/numpy/1.26.0rc1/

**Review by lagru — APPROVED** [review]
:tada:

**Pull request merged**
