### PR TITLE
Add data files for new illuminants.

### PR DESCRIPTION
**Pull request by mkcor**
## Description

Following up with #5234 -- only adding the new data here. 

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by mkcor** [comment]
The current test fail is not specific to this PR.

@hmaarrfk @BierretA I have manually cherry-picked the new (non-duplicate) data files from #5234.

**Comment by mkcor** [comment]
@hmaarrfk please review/approve ;)

**Review by hmaarrfk — APPROVED** [review]
It seems that adding the files to the registry itself causes test to fail.

I noticed that the azure pipelines all build off the build wheels.

They will fail without a pull request like this.

**Comment by hmaarrfk** [comment]
I'm kinda ok with this, but I think that merging https://github.com/scikit-image/scikit-image/pull/5283 would have caused fewer failures.

I can't really inspect the azure failures, but in either case, it is clear that the build system has stopped that PR from going through.

I would be ok just merging the main PR as is.

**Comment by mkcor** [comment]
> It seems that adding the files to the registry itself causes test to fail.

Yes, because the files don't live in `main` yet! So, if we merge this PR first, then we can go on with the data registry update (via a PR which will pass CI).

**Comment by mkcor** [comment]
> I'm kinda ok with this, but I think that merging #5283 would have caused fewer failures.

@hmaarrfk "would cause" :wink: Let's fix the CI script first, of course!

**Comment by mkcor** [comment]
Let's move forward with this, now that #5283 is merged! /cc @grlee77 @jni

**Pull request merged**
