### PR TITLE
Update matplotlib minimum version

### PR DESCRIPTION
**Pull request by jarrodmillman**
## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I feel like you might as well go further:

```
$ pip install nep29
$ nep29 matplotlib
| version |    date    |
|:-------:|:----------:|
|  3.5.0  | 2021-11-16 |
|  3.4.0  | 2021-03-26 |
|  3.3.0  | 2020-07-16 |
```

**Comment by jarrodmillman** [comment]
I also updated the minimum supported version of pillow from 6.1.0 to 6.2.0, since matplotlib 3.3 requires pillow>=6.2.0. So w/out this change the tests of minimum required dependencies fails.

**Comment by hmaarrfk** [comment]
You can probably just run the nep29 tool for matplotlib too and update that. But this is ok with me.

**Review by stefanv — APPROVED** [review]

**Comment by hmaarrfk** [comment]
For reference:
```
$ nep29 pillow
| version |    date    |
|:-------:|:----------:|
|  9.1.0  | 2022-04-01 |
|  9.0.0  | 2022-01-02 |
|  8.4.0  | 2021-10-15 |
|  8.3.0  | 2021-07-01 |
|  8.2.0  | 2021-04-01 |
|  8.1.0  | 2021-01-02 |
|  8.0.0  | 2020-10-14 |
|  7.2.0  | 2020-06-30 |
```

**Comment by stefanv** [comment]
What does `nep29` do? I can't quite figure out from its GitHub README.

**Pull request merged**
