### PR TITLE
Sort naturally peaks coordinates of same amplitude in peak_local_max

### LINKED ISSUE #4580: corner_harris returns peaks in a non "natural" order when the peaks have the same amplitude
## Description

@emmanuelle [caught](https://github.com/scikit-image/scikit-image/pull/4218#issuecomment-612629627) a bug in `corner_peaks`: it returns the peaks coordinates in the wrong order when the peaks have the same amplitude.

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

Fixes #4580. This PR is the one line fix proposed [here](https://github.com/scikit-image/scikit-image/pull/4218#issuecomment-612641502).

## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by jni** [comment]
@rfezzani this is so hard to review! =P

Could you add a test for this, though? I can imagine an enterprising future me coming in, seeing that this line creates an "unnecessary" array copy, and reverting it.

**Comment by rfezzani** [comment]
> Could you add a test for this, though?

@jni, the test is already implemented as a doctest, should I also implement it with pytest?

**Comment by jni** [comment]
@rfezzani wait, I'm confused... If a doctest already covered this, how come the change got merged?

**Comment by rfezzani** [comment]
@jni I just fixed the [doctest](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/corner.py#L953) was implemented but with the wrong ordering :confused:, I just fixed now...

**Comment by jni** [comment]
@scikit-image/core this is ready now imho, just needs another approval! =) Thank you @rfezzani!

**Comment by sciunto** [comment]
Thanks !

**Comment by rfezzani** [comment]
Thank you @jni and @sciunto :tada:

**Pull request merged**
