### PR TITLE
Remove coverage table.  Add document with release notes and download instructions.

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by JDWarner** [comment]
Good riddance to the coverage table! I thought that was long gone.

**Comment by neothemachine** [comment]
I really don't understand your code. download.txt doesn't exist and _release_notes_for_docs.txt is some kind of template only?

**Comment by blink1073** [comment]
@stefanv, I agree with @neothemachine: where are `download.txt` and `_release_notes_for_docs.txt` being generated?

**Comment by JDWarner** [comment]
@blink1073 @neothemachine `_release_notes_for_docs.txt` is copied from `docs/release` by the new `release_notes` Makefile target in these lines:

```bash
release_notes:
	@echo "Copying release notes"
	@tail -n +4 `ls release/*.txt | sort -k 2 -t . -n | tail -n 1` > release/_release_notes_for_docs.txt
```

But I can't figure out `download.txt`.

**Comment by stefanv** [comment]
Sorry, looks like I forgot to commit that file.  Added it now.

**Comment by stefanv** [comment]
Nope, my mistake: I meant to remove download.txt entirely (which I did now)

**Comment by JDWarner** [comment]
Looks great now @stefanv!

**Pull request merged**
