### PR TITLE
Fix Hessian matrix eigvals

### PR DESCRIPTION
**Pull request by ahojnnes**

### CODE REVIEW

**Comment by ahojnnes** [comment]
Fixes issue https://github.com/scikit-image/scikit-image/issues/1389

**Comment by JDWarner** [comment]
Agreed this should be fixed for 0.11.

Not sure what went wrong with Travis - I can't find a failure under 3.3, is there a hard 10k line limit for build logs?

**Comment by blink1073** [comment]
@JDWarner, there is a button called "Download log" on the top right that will open a new page with the raw log:

```python

======================================================================
ERROR: skimage.io.tests.test_pil.test_all_mono
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scikit-image/scikit-image/skimage/io/tests/test_pil.py", line 176, in test_all_mono
    mono_check('pil', 'tiff')
  File "/home/travis/build/scikit-image/scikit-image/skimage/_shared/testing.py", line 169, in mono_check
    r4 = roundtrip(img4, plugin, fmt)
  File "/opt/python/3.3.5/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/home/travis/build/scikit-image/scikit-image/skimage/_shared/_warnings.py", line 112, in expected_warnings
    raise ValueError('Unexpected warning: %s' % str(warn.message))
ValueError: Unexpected warning: unclosed file <_io.BufferedReader name='/home/travis/build/scikit-image/scikit-image/skimage/data/multipage.tif'>
```

I saw this appear randomly earlier, and was cleared by a subsequent run, so I restarted the job.

**Comment by JDWarner** [comment]
@ahojnnes, @blink1073 - I'm surprised this fix didn't make the Hessian test suite throw a fit.

I don't want to delay 0.11 further. This fix is obvious, necessary, and blocking. Are you guys OK with merging this fix, then raising a separate issue to enhance the Hessian test suite (which wouldn't necessarily be a 0.11 milestone)?

**Comment by blink1073** [comment]
@jdwarner, agreed.

**Comment by ahojnnes** [comment]
I can work on this post 0.11, but right now I am too busy.

**Comment by ahojnnes** [comment]
See https://github.com/scikit-image/scikit-image/issues/1393

**Comment by JDWarner** [comment]
All right, I'm merging this fix. Thanks for the report, @gregosh!

**Comment by stefanv** [comment]
@ahojnnes I've tried to write a test for this, but I am confused.  First, what is this function computing?  Why does it return an entire array as an eigenvalue?

**Comment by stefanv** [comment]
No worries, figured it out.

**Comment by ahojnnes** [comment]
Feel free to write test cases anyway ;-)

**Comment by stefanv** [comment]
After testing this I am pretty sure that something is not quite right here.

**Comment by ahojnnes** [comment]
Please, add some example...

**Comment by stefanv** [comment]
If you look at H_xy, it always has extremely small values--is that the way
it should be?

**Comment by ahojnnes** [comment]
What happens if you change line 165 to `    kernel_xy /= kernel_xy.sum()`?

**Comment by ahojnnes** [comment]
(This is imo the bug, without actually testing it)

**Comment by JDWarner** [comment]
:+1: @ahojnnes, good catch.

**Comment by JDWarner** [comment]
@ahojnnes do you want to make a PR with that fix, or shall I?

**Comment by ahojnnes** [comment]
See https://github.com/scikit-image/scikit-image/pull/1394

**Pull request merged**
