### PR TITLE
DOC: make image smaller for better visu

### LINKED ISSUE #1922: DOC: Reduce size image in plot_inpaint
In reference to #1920 

* Reduce the size of the image in  doc/examples/filters/plot_inpaint.py to show more clearly the result of the algorithm.

### PR DESCRIPTION
**Pull request by sciunto**
Closes #1922

### CODE REVIEW

**Comment by soupault** [comment]
@sciunto may I ask you to attach image of the result to the PR, so everybody will be able to evaluate the changes easily? Thanks!

**Comment by soupault** [comment]
@sciunto thanks you so much! 
:+1:

**Comment by blink1073** [comment]
Thanks @sciunto!

**Pull request merged**
