### PR TITLE
WIP: remove local copy of sphinx gallery and use latest release

### LINKED ISSUE #2663: Install lastest sphinx-gallery instead of re-distributing a copy in our source tree
## Current behavior

We have a copy of sphinx-gallery in our source tree

## A better behavior

Download the latest version or use git submodule to be always uptodate.

## TODO

unpin sphinx < 1.6.1, ie revert #2662

### PR DESCRIPTION
**Pull request by grlee77**
## Description
Update to the latest sphinx-gallery as discussed in #2663 and #2661 

closes #2663

Currently this downloads the latest sphinx-gallery at documentation build time, but there was also discussion of maybe using `git submodule` instead.  Please provide guidance on which is the preferred approach.

I had to change one deprecated variable name in the configuration in `doc/source/conf.py` to get the build to complete with the newer revision. 

 `pip install sphinx-gallery` failed without including `pytest-runner` as well.

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.

### CODE REVIEW

**Comment by sciunto** [comment]
Many thanks @grlee77

**Comment by stefanv** [comment]
Hey, folks, we updated the sphinx gallery CSS a while ago to look less hideous.

See, e.g., the buttons at the bottom of:

http://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_ihc_color_separation.html#sphx-glr-auto-examples-color-exposure-plot-ihc-color-separation-py

vs

http://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_ihc_color_separation.html#sphx-glr-auto-examples-color-exposure-plot-ihc-color-separation-py

Would you mind restoring the style updates?

**Comment by stefanv** [comment]
@grlee77 @sciunto Please confirm that you've seen the above.

**Comment by grlee77** [comment]
> Please confirm that you've seen the above.

now I have :).  I will look into making the style fix.

**Comment by grlee77** [comment]
Does someone with more familiarity with sphinx / sphinx-gallery know how to specify overrides for the default `gallery.css`?  

Basically, our [previous local copy of gallery.css](https://github.com/scikit-image/scikit-image/blob/v0.13.x/doc/ext/sphinx_gallery/_static/gallery.css) had several minor changes relative to [the one packaged with scikit-gallery](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/_static/gallery.css).

cc @emmanuelle @RoseZhao as previous modifiers of `gallery.css`.  My apologies for inadvertently undoing these style changes when the local copy of sphinx-gallery was removed!

**Comment by stefanv** [comment]
Thanks for looking into it, @grlee77

**Comment by grlee77** [comment]
I have found two options so far, but I am not an expert on sphinx or CSS, so perhaps I am missing something.

1.)  reintroduce a local copy of sphinx gallery and then modify the local `gallery.css` as before.
 
2.)  A second workaround seems to be appending the following CSS code to the bottom of the existing [custom.css](https://github.com/scikit-image/scikit-image/blob/master/doc/source/themes/scikit-image/static/css/custom.css) file.  I had to add `!important` flags here CSS or these settings did not end up overriding the settings in sphinx-gallery's own `gallery.css`.  These settings all appear to be within a `sphx-glr` CSS namespace, so I don't think it causes any effects outside the gallery.  
```css

/*
Overrride some default settings in sphinx-gallery's gallery.css */
.sphx-glr-thumbcontainer {
  border: solid #d6d6d6 1px !important;
}

div.sphx-glr-download {
  width: auto !important;
}

div.sphx-glr-footer {
    text-align: left  !important;
}

div.sphx-glr-download a {
  background-color: #d9edf7 !important;
  border: 1px solid #bce8f1 !important;
  background-image: none !important;
}

div.sphx-glr-download code {
  color: #3a87ad !important;
}

div.sphx-glr-download a:hover {
  background-color: #d9edf7 !important;
}

p.sphx-glr-signature a.reference.external {
  display: none !important;
}
```

A drawback of the second approach is that it could break or need tweaking depending on the version of sphinx-gallery used to build the docs.  For example, I had to introduce the line below about `background-image: none` to get the blue background to show up in the buttons rather than an image gradient of yellows as used in current sphinx-gallery.

**Comment by stefanv** [comment]
The second approach looks good to me.

**Pull request merged**
