### PR TITLE
Add one-line docstring to `skimage.segmentation`

### PR DESCRIPTION
**Pull request by Br-Al**
## Description
Added a docstring to `skimage.segmentation`. This updates the issue #6761.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by Br-Al** [comment]
Hi @lagru, what do you think about this one?

**Comment by lagru** [comment]
See https://github.com/scikit-image/scikit-image/pull/6831#issuecomment-1473584972.

**Review by lagru — APPROVED** [review]

**Comment by lagru** [comment]
Thanks!

**Comment by lagru** [comment]
Hey, @Br-Al I took the liberty to tweak the one-liner a bit to make it more useful to readers. Hope that's okay. :)

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
