### PR TITLE
Ensure gallery pages are always generated

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jni** [comment]
Can't say that I understand what's wrong with it... Are we sure all the examples in the gallery run on things other than 2.7?

**Comment by blink1073** [comment]
It looks like a problem with our rackspace wheel server.

**Comment by stefanv** [comment]
I suspect this was due to dask.  They broke something in their latest release w.r.t toolz.  I think it's fixed here:

https://github.com/blaze/dask/commit/ffcd1216ade17e04dce10c453b686a251b5ae3d8

**Comment by blink1073** [comment]
Confirmed.  @mrocklin, would you mind cutting a 0.7.5?

**Comment by mrocklin** [comment]
Cut. https://pypi.python.org/pypi/dask/0.7.5

**Comment by mrocklin** [comment]
My apologies for the upset.

**Comment by stefanv** [comment]
No worries :)

**Comment by blink1073** [comment]
Thanks Matt.

**Pull request merged**
