### PR TITLE
Use context manager when possible

### PR DESCRIPTION
**Pull request by rfezzani**
## Description

Completes #6458 refactoring.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Review by lagru — COMMENTED** [review]
Thanks @rfezzani for completing this obvious improvement. May I suggest two more candidates:
- https://github.com/scikit-image/scikit-image/blob/main/doc/source/random_gallery.py#L52-L54
- https://github.com/scikit-image/scikit-image/blob/main/doc/tools/apigen.py#L182-L184

I don't think these are covered by #6458 which I don't want to hold up further.

Otherwise looks good! :+1:

**Review by lagru — APPROVED** [review]
Thanks for addressing my suggestions. Looks ready to merge in my opinion. But perhaps we should wait until #6458 is merged to avoid merge conflicts for that first-time contribution..

**Comment by rfezzani** [comment]
Thank you @lagru.

**Comment by soupault** [comment]
Fantastic, thank you @rfezzani !

**Comment by alexdesiqueira** [comment]
Thank you @rfezzani!

**Pull request merged**
