### PR TITLE
0.12.0 release

### PR DESCRIPTION
**Pull request by emmanuelle**
I tagged 0.12! docs have already been built. 

Should this PR be merged or should I just push to origin?

### CODE REVIEW

**Comment by emmanuelle** [comment]
I can't see the new tag in the "files changed" tab... Maybe it's because it's not a file, but I wonder if the tag will be included in the merge...

**Comment by stefanv** [comment]
Finally, we're here! You have to push tags with the git push --tags command.

**Comment by emmanuelle** [comment]
I did ``push --tags``. More precisely, I did 
``git push --tags emma 0.12.x``
with emma being my github repo. 

I can see the tag on my repo https://github.com/emmanuelle/scikits.image/releases

Anything else that I should do?

**Comment by emmanuelle** [comment]
I could also have pushed directly to origin master, instead of pushing to my github. Is this how you would do @stefanv ? 

If pushing to scikit-image is the right way to go, i ll do it tomorrow and close this PR. 

Sorry for the baby steps, let s say that I feel a bit shy about pushing directly to scikit-image

**Comment by emmanuelle** [comment]
I also pushed the 0.12.x to scikit-image/scikit-image, as advised by @jni on gitter. This PR could therefore be closed, but I wonder at which point the commits will be merged?

**Comment by stefanv** [comment]
Thanks, @emmanuelle for all your hard work, and @jni for providing a helping hand!

**Pull request merged**
