### PR TITLE
Added sections to gallery of examples

### PR DESCRIPTION
**Pull request by emmanuelle**
Addresses #1651.

The choice of how to cluster examples in sections was made using two tools
- my gut feeling about typical operations user would like to do
- and statistics of visits using the piwik logs set up by @sciunto. In particular, I built a graph of pages that were visited together, and tried to cluster this graph using spectral clustering. This process showed some tendencies consistent with the aforementioned gut feeling, with other interesting points (for pages that have few visits, they seem to be visited just after one of their neighbors in the gallery). 

I used a mixture of the tools, that is when I had some doubts about an example, I tried to put it in the same section as other pages that were visited together.

One consequence of this way of organizing examples is that it is more task-oriented than module-oriented. For example, thresholding operations are  in the same section as segmentation algorithms.

There might diverging opinions about how to organize examples, so I guess this PR is the place for discussions!

Also, I was wondering whether to rename folders as 00_color_exposure, 01_edges, etc., in order to control the order in which sections appear.

### CODE REVIEW

**Comment by blink1073** [comment]
Hi Emma, it is hard to get a feel for where things are, can you post a directory listing for each section?

**Comment by emmanuelle** [comment]
Sure

```
color_exposure:
plot_adapt_rgb.py             plot_log_gamma.py
plot_equalize.py              plot_regional_maxima.py
plot_ihc_color_separation.py  plot_tinting_grayscale_images.py
plot_local_equalize.py        README.txt

edges:
plot_canny.py                                plot_marching_cubes.py
plot_circular_elliptical_hough_transform.py  plot_medial_transform.py
plot_contours.py                             plot_polygon.py
plot_convex_hull.py                          plot_shapes.py
plot_edge_filter.py                          plot_skeleton.py
plot_line_hough_transform.py                 README.txt


features_detection:
plot_blob.py                   plot_hog.py
plot_brief.py                  plot_holes_and_peaks.py
plot_censure.py                plot_local_binary_pattern.py
plot_corner.py                 plot_multiblock_local_binary_pattern.py
plot_daisy.py                  plot_orb.py
plot_gabor.py                  plot_template.py
plot_gabors_from_astronaut.py  plot_windowed_histogram.py
plot_glcm.py                   README.txt

filters:
plot_denoise.py  plot_nonlocal_means.py  plot_rank_mean.py    README.txt
plot_entropy.py  plot_phase_unwrap.py    plot_restoration.py

numpy_operations:
plot_camera_numpy.py  plot_view_as_blocks.py  README.txt

segmentation:
plot_join_segmentations.py  plot_rag_merge.py
plot_label.py               plot_rag.py
plot_local_otsu.py          plot_random_walker_segmentation.py
plot_marked_watershed.py    plot_regionprops.py
plot_ncut.py                plot_segmentations.py
plot_otsu.py                plot_threshold_adaptive.py
plot_peak_local_max.py      plot_watershed.py
plot_rag_draw.py            README.txt
plot_rag_mean_color.py

transform:
plot_edge_modes.py        plot_radon_transform.py       plot_seam_carving.py
plot_matching.py          plot_ransac3D.py              plot_ssim.py
plot_piecewise_affine.py  plot_ransac.py                plot_swirl.py
plot_pyramid.py           plot_register_translation.py  README.txt

xx_applications:
plot_coins_segmentation.py  plot_morphology.py    plot_rank.py
plot_geometric.py           plot_rank_filters.py  README.txt

```

**Comment by emmanuelle** [comment]
if it helps
http://sd-27941.dedibox.fr/html/auto_examples/

**Comment by emmanuelle** [comment]
There are several errors because the path of images linked to in the user guide has changed. I will correct these errors after I get some feedback about the sections.

**Comment by blink1073** [comment]
Yes, the visual example was most helpful.  I have no complaints, nice work @emmanuelle!

**Comment by stefanv** [comment]
Shall we also make the gallery more compact, so that it is easier to take in?  I like, e.g., http://scikit-learn.org/stable/auto_examples/index.html

**Comment by stefanv** [comment]
Also, how cool that you analyzed the visit graph!

**Comment by emmanuelle** [comment]
OK, no more broken links any more. I rebased for cleaner logs. Hope this is good to go!

**Comment by blink1073** [comment]
LGTM, still WIP?

**Comment by emmanuelle** [comment]
@blink1073 not any more :-)

**Comment by blink1073** [comment]
Awesome, well done!

**Pull request merged**
